### ISSUE TITLE
cyrillic symbols dosn't support?

### ISSUE THREAD

**Issue by u-alexey** [bbernhard/signal-cli-rest-api#1]
Thanks for your solution integration signal to HA.
Everything works fine (but slow) except for the Cyrillic alphabet.
![photo_2020-01-16_12-02-27](https://user-images.githubusercontent.com/50143425/72509283-53a7ba00-3858-11ea-9b3b-9019fe87f5c7.jpg)

**Comment by bbernhard** [comment]
Thanks for the bug report! 

I think it should be fixed now...at least I wasn't able to reproduce it anymore after the bugfix. 

In case you want to give it a try, you can checkout the latest changes and build the new docker image with `docker-compose build`. 

(I'll update the image on dockerhub later today as well..so the new image should be available soon)

**Comment by bbernhard** [comment]
the images are now also updated on dockerhub

**Comment by u-alexey** [comment]
Thank you, Bernhard.  

![photo_2020-01-17_09-12-03](https://user-images.githubusercontent.com/50143425/72588468-7a71f900-3909-11ea-9c62-9b34110a23d0.jpg)
