### ISSUE TITLE
How to install on Debian

### ISSUE THREAD

**Issue by MatejKovacic** [bbernhard/signal-cli-rest-api#101]
I would like to install this on Debian machine, but standalone, not as Hassio plugin. Are there any instructions how to do this?

**Comment by bbernhard** [comment]
What do you mean by standalone? At the moment there's only the possibility to run it as docker container or Hassio addon (which is strictly speaking also a docker container). There's no debian package for it. You could of course compile the sources yourself and install the REST API natively, but this is quite a bit of work (you would need to setup java, compile the REST API sourcecode, compile signal-cli, etc)

**Comment by MatejKovacic** [comment]
I am not familiar with docker, so I would appreciate short guide how to install docker.

BTW, I also found this: https://pypi.org/project/signal-cli-rest-api/

**Comment by MatejKovacic** [comment]
Sorry, my suggestion is to publish this guide on README.md.

**Comment by bbernhard** [comment]
As already mentioned above, the steps are basically:

* Install docker + docker-compose: https://docs.docker.com/engine/install/debian/
* use the docker-compose.yml from the README.md
* run docker-compose pull + docker-compose up

The official docker documentation covers the installation of the docker daemon pretty well - so you basically just have to copy & paste some commands.

In case you want to improve the documentation - pull requests on that matter are highly appreciated!
