### ISSUE TITLE
Fails to Connect to :8080, even though it's listening

### ISSUE THREAD

**Issue by EJansenMSFT** [bbernhard/signal-cli-rest-api#102]
In my scenario, I'm on a Windows 10 machine where I've installed docker, downloaded the code, and ran the couple of lines to get the container up and running.  It was a pretty smooth process.  The container looks fine and says that it's running on port 8080:

![image](https://user-images.githubusercontent.com/72317762/110231039-45e14800-7ee3-11eb-8579-759ad6b44b47.png)

Once the container is started, I can see that 8080 is now listening on the host:

![image](https://user-images.githubusercontent.com/72317762/110231059-745f2300-7ee3-11eb-8c81-c003089d3a70.png)

But if I try to connect via browser it just fails:

![image](https://user-images.githubusercontent.com/72317762/110231102-ac666600-7ee3-11eb-8baa-a9787feabaf9.png)

It appears that until I can do that, I can't move forward to use any of the sample code for sending group messages.

Any ideas?

Thanks,
Eric

**Comment by EJansenMSFT** [comment]
Also, if I try the following command on the host I get the following error:

![image](https://user-images.githubusercontent.com/72317762/110231385-8772f280-7ee5-11eb-84e2-7cb7299c8111.png)

If I try it on the container cli, I get this error:

![image](https://user-images.githubusercontent.com/72317762/110231432-b25d4680-7ee5-11eb-811e-549f56be6cd3.png)

Thanks,
Eric

**Comment by bbernhard** [comment]
Please try with `http` instead of `https`. The REST API doesn't support SSL (in case you want SSL, you would need to put a reverse proxy like nginx in front of the docker container)

**Comment by EJansenMSFT** [comment]
Well this looks a bit better:

![image](https://user-images.githubusercontent.com/72317762/110231677-2a783c00-7ee7-11eb-925b-8b3ea96d05e7.png)

I tried http in the browser, but not with curl.  I just assumed that if it didn't work in the browser that it wouldn't work in the cli either.

Thanks!  I'll keep playing around with it.

Cheers,
Eric

**Comment by EJansenMSFT** [comment]
Hmm, what do I put for this:

![image](https://user-images.githubusercontent.com/72317762/110232231-9314e800-7eea-11eb-953e-7fb551b7511c.png)

Thanks,
Eric
