### ISSUE TITLE
/v1/groups/ with open invite: Field groupMasterKey_ for org.signal.storageservice.protos.groups.GroupInviteLink$GroupInviteLinkContentsV1 not foun

### ISSUE THREAD

**Issue by gf78** [bbernhard/signal-cli-rest-api#104]
{
error: "Exception in thread "main" java.lang.RuntimeException: Field groupMasterKey_ for org.signal.storageservice.protos.groups.GroupInviteLink$GroupInviteLinkContentsV1 not found. Known fields are [] at com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:608) at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:502) at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221) at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:85) at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71) at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93) at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107) at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170) at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:386) at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:394) at org.signal.storageservice.protos.groups.GroupInviteLink.setV1Contents(GroupInviteLink.java:402) at org.signal.storageservice.protos.groups.GroupInviteLink.access$900(GroupInviteLink.java:9) at org.signal.storageservice.protos.groups.GroupInviteLink$Builder.setV1Contents(GroupInviteLink.java:566) at org.asamk.signal.manager.groups.GroupInviteLinkUrl.createUrl(GroupInviteLinkUrl.java:101) at org.asamk.signal.manager.groups.GroupInviteLinkUrl.<init>(GroupInviteLinkUrl.java:96) at org.asamk.signal.manager.groups.GroupInviteLinkUrl.forGroup(GroupInviteLinkUrl.java:26) at org.asamk.signal.manager.storage.groups.GroupInfoV2.getGroupInviteLink(GroupInfoV2.java:62) at org.asamk.signal.commands.ListGroupsCommand.handleCommand(ListGroupsCommand.java:77) at org.asamk.signal.App.handleLocalCommand(App.java:211) at org.asamk.signal.App.init(App.java:169) at org.asamk.signal.Main.main(Main.java:43) "
}

**Comment by bbernhard** [comment]
Cannot reproduce anymore with the latest versions. Please re-open in case this issue still exists.
