### ISSUE TITLE
@EJansenMSFT Onboarding

### ISSUE THREAD

**Issue by bbernhard** [bbernhard/signal-cli-rest-api#106]
So i registered the new number just fine and I added the number as a contact to my phone, and invited the new number to join a group, but how can I programmatically accept the invite?  I guess the better question is how do I know what the group ID is?

_Originally posted by @EJansenMSFT in https://github.com/bbernhard/signal-cli-rest-api/issues/89#issuecomment-793054218_

**Comment by bbernhard** [comment]
@EJansenMSFT I've moved your issue here, in order to keep the captcha-thread clean.

Have a look at the API documentation here: https://bbernhard.github.io/signal-cli-rest-api/

I guess you are looking for the List Groups/Join Group endpoint?

**Comment by EJansenMSFT** [comment]
Apologies - should have started a new thread.

Yeah, I tried the curl command from that link for joining a group, but I'm not sure what to put for the group ID.

**Comment by bbernhard** [comment]
> Apologies - should have started a new thread.

No worries. Do you mind if I remove also your (and my) other non-captcha related comments from the captcha thread? Or would you like to save any of those?

> Yeah, I tried the curl command from that link for joining a group, but I'm not sure what to put for the group ID.

If you list the existing groups via `curl -X GET "https://127.0.0.1:8080/v1/groups/+12345678" -H  "accept: application/json"` it shows you a list of all the groups and the corresponding ids.

**Comment by EJansenMSFT** [comment]
> No worries. Do you mind if I remove also your (and my) other non-captcha related comments from the captcha thread? Or would you like to save any of those?

No, I think I've documented most everything through this journey so far :)

> If you list the existing groups via curl -X GET "https://127.0.0.1:8080/v1/groups/+12345678" -H "accept: application/json" it shows you a list of all the groups and the corresponding ids.

Hmm, I ran that, but it just returned []

I'll give it another go.

**Comment by EJansenMSFT** [comment]
> Hmm, I ran that, but it just returned []

Granted, this number has never had any association with signal and I've not created any groups.  I just sent an invite from a group that I created on my other phone.

**Comment by bbernhard** [comment]
Please try to do a receive with: `curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/receive/+12345678'`

**Comment by EJansenMSFT** [comment]
Ah ok that better, it produced some data, but probably not what I want:

[{"envelope":{"source":"+1.............","sourceDevice":1,"timestamp":1615234286936},"error":{"message":"org.whispersystems.libsignal.InvalidMessageException: Message from +1...............:1 failed to decrypt; sender ratchet public key 776f1fa0ada4e9f2a708925e44a121c300ea9ccc36fb2c message counter 0\nCandidate session 0 failed with 'invalid ciphertext message', had 0 receiver chains"}}]

**Comment by bbernhard** [comment]
I haven't seen this particular exception before, but I know that signal-cli sometimes has some issues with switching between a properly registered phone number and a linked phone number. As you've experienced with a linked phone number before, I would suggest that you remove every config and start from scratch. 

If you are using the same `docker-compose.yml` file as in the README.md you should have a `signal-cli-config` folder inside the same folder the `docker-compose.yml` resides. `cd` into that folder, remove all the contents, restart the docker container and register the number again. After that, call the `receive` endpoint. Add the number to the group, call the `receive` endpoint again and accept the invitation via the REST API.

**Comment by EJansenMSFT** [comment]
Awesome, that did it.

**Comment by EJansenMSFT** [comment]
Ok, so I connected to the groups endpoint again after doing a receive and see the following:

![image](https://user-images.githubusercontent.com/72317762/110398897-d08c8900-8042-11eb-9eba-f9b4d0c6078e.png)

I tried to Join the group using the value in the internal_id, but it doesn't work.  I'm assuming that's the correct value to input when using the following?:

curl -X POST "https://127.0.0.1:8080/v1/groups/<PhoneNumber>/<GroupID>/join" -H  "accept: application/json" -d ""

**Comment by EJansenMSFT** [comment]
Reading through the other threads, it appears that you address that error here:  

https://github.com/bbernhard/signal-cli-rest-api/issues/54

**Comment by EJansenMSFT** [comment]
> Ok, so I connected to the groups endpoint again after doing a receive and see the following:
> 
> ![image](https://user-images.githubusercontent.com/72317762/110400377-878a0400-8045-11eb-8c0f-a5b0b3b30808.png)
> 
> I tried to Join the group using the value in the internal_id, but it doesn't work. I'm assuming that's the correct value to input when using the following?:
> 
> curl -X POST "https://127.0.0.1:8080/v1/groups/ +123456789/ "LargeValueRepresentingGroupID" /join" -H "accept: application/json" -d ""
> 
> If I use the value in ID, after 'groups.' then it appears to get somewhere, but it failed with the following:
> 
> ![image](https://user-images.githubusercontent.com/72317762/110399969-c3709980-8044-11eb-83ad-c74f5d3f5acc.png)
> 
> I'm not sure if there's a different function for accepting an invitation vs doing a group join?
> 
> Thanks!

OK, so in playing around a bit I was able to accept the invitation by using the ID, but for whatever reason before, I just assumed that I would have omitted the group. prefix of the ID value, so I was just putting the long value without the group. prefix.  As soon as I tried it with the prefix, it worked and I was able to accept the invitation to the group that was sent.

**Comment by EJansenMSFT** [comment]
@bbernhard 

As I'm writing some of these PowerShell functions to put in an eventual module, I was wondering if you had an offline means of communications for some questions, since I'm new to both Signals and Github.

Example:  Do you know what Format the the timestamp is in, should I want to convert it into an easier to read format with Get-Date?

![image](https://user-images.githubusercontent.com/72317762/110576025-f93d7d00-812d-11eb-9436-588dea3a7ca4.png)

Thanks,
Eric

**Comment by EJansenMSFT** [comment]
Hmm, by chance do you know where the docker container / images live on a Windows box?  I rebooted, opened up the docker desktop, and I see the following:

![image](https://user-images.githubusercontent.com/72317762/112180311-d3a28000-8bd1-11eb-88f3-20b6542df158.png)

![image](https://user-images.githubusercontent.com/72317762/112180386-e6b55000-8bd1-11eb-8a2d-3378d91b4145.png)

I spose worst case, I just figure out how to deregister the phone number that I've been testing with and deploy a new container.

Thanks!

**Comment by bbernhard** [comment]
You could try to run `docker images` in a commandline prompt whether that lists any images (just to rule out that any UI displaying issues). I think per default docker containers aren't started when you reboot your machine. You have to add `restart: always` to the docker-compose.yml file. (see https://docs.docker.com/compose/compose-file/compose-file-v3/#restart). Otherwise you have to go to the folder where your `docker-compose.yml` lives and do a `docker-compose up`.

**Comment by EJansenMSFT** [comment]
It ended up being some issue with the docker service.  Going to settings in the desktop would hang, as would the flyout menu  when right clicking the icon on the task bar.  Also got some access denied issues, so I just rebooted again and all was well.

**Comment by EJansenMSFT** [comment]
OK, so I've written a PowerShell function for every API call that you have in your REST API documentation, the only one that I'm struggling a bit with (I'm no developer) is my 'Generate-SignalCaptcha' function.  

Right now, when the function runs, I just have it pop up and present the picture tiles to click on.  Ideally I'd wait for user input and then be able to parse the console data for the generate.html file for the _signalcaptcha://<large value>_ 

I was trying to automate it as much as I could so that the returned value of the _Generate-SignalCaptcha_ function, if the correct captcha tiles were chosen, could be used as input to the -Captcha parameter in my _Register-SignalDevice_ function. 

Any idea how to do that? :)
