### ISSUE TITLE
How to restrict access to a specific IP

### ISSUE THREAD

**Issue by MatejKovacic** [bbernhard/signal-cli-rest-api#108]
I have installed docker on a Debian Buster server. On this server I have `ufw` firewall, however docker does not respect that and makes `signal-cli-rest-api` accessible to everyone after I say `docker-compose up`.

Docker [documentation says](https://docs.docker.com/network/iptables/) that I can use the following `iptables` command:
`sudo iptables -I DOCKER-USER -i eth0_or_other_network_interface ! -s allowed_ip -j DROP`

Would be possible to add this functionality to the app (maybe in docker-compose, if possible)?

**Comment by bbernhard** [comment]
I think that's something that can't be generalized easily, as everybody has a different network infrastructure. e.g: I do have a border firewall in front of my whole network which blocks everything from outside, so I do not need that. 

In case you do need that, you could inherit from the `signal-cli-rest-api` docker image and add the iptables rules yourself. The HomeAssistant signal addon is also using inheritance to override some things from the base docker image. See here: https://github.com/haberda/hassio_addons/blob/master/signal/Dockerfile

**Comment by f45tb00t** [comment]
Hello @MatejKovacic,

actually I don't see here the need to open an issue for that. 

To be honest I guess Bernhard has other things to do, as to explain how a paket filter works. There are plenty of resources which explain your needs. 

So my truly recommendation is, to keep not related things which do not aim to this project out of this issue tracker. 

Can you close this? k. Thx :)

**Comment by n-stone** [comment]
It's a know Issue: https://github.com/docker/for-linux/issues/690

Here's a workaround to bind to a specific IP:
```
...
ports:
  - "192.168.1.100:8080:8080"
...
```
Official Documentation: https://docs.docker.com/compose/compose-file/compose-file-v2/#ports

Or look at this to ensure ufw and docker are working together:
https://p1ngouin.com/posts/how-to-manage-iptables-rules-with-ufw-and-docker

**Comment by CodeShellDev** [comment]
Hi, there I am the developer of [`secured-signal-api`](https://github.com/CODEShelldev/secured-signal-api) and I have recently released a new version (`v1.5.0`) containing **IP Filters**, which should fit your case.

It is a proxy for signal-cli-rest-api, that adds auth and many other QoL features,
if you want come try it out: [Github Repo](https://github.com/CODEShelldev/secured-signal-api)
