### ISSUE TITLE
License

### ISSUE THREAD

**Issue by holgersson32644** [bbernhard/signal-cli-rest-api#11]
Hi, your API looks quite cool and of course I think that you want to share your code, but as you state no license, technically no one is allowed to use it (without your explicit permission).

**So, I’m sorry to bother you with this legal stuff, but would you please add a license of your choice to your project?**

(Side note: It get's far more weird  for every user of go packages as everyone has to comply with *all* licenses of every used go dep as go links (mostly) statically..)

Thanks!

**Comment by bbernhard** [comment]
Hi,

many thanks for the info - I've added one :)

**Comment by holgersson32644** [comment]
Thank you! :)
