### ISSUE TITLE
Can you give me an example of sending an attachment?

### ISSUE THREAD

**Issue by MatejKovacic** [bbernhard/signal-cli-rest-api#111]
I am trying to send an attachment, lets call it cat.jpg.

I am using curl from command line. Here is what I do.
First I read a file in base64 encoding:

MYFILE=`base64 cat.jpg`

Then:
```
curl -X 'POST'   'http://xx.xx.xx.xx:8080/v2/send'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
  "base64_attachments": [
    "$MYFILE"
  ],
  "message": "This is my message...",
  "number": "+123456",
  "recipients": [
    "+1238765"
  ]
}'

```
And I got this error:
`{"error":"illegal base64 data at input byte 0"}`

**Comment by EJansenMSFT** [comment]
I'm working on the same issue right now.  Here's how I'm doing it via a PowerShell function:

![image](https://user-images.githubusercontent.com/72317762/111569989-3b903b00-877a-11eb-81d5-296d3134a892.png)

The issue that I'm having is that when the file is received it shows up like this:

![image](https://user-images.githubusercontent.com/72317762/111570052-5b276380-877a-11eb-8bbd-02b5a3b8e1ac.png)

**Comment by EJansenMSFT** [comment]
![image](https://user-images.githubusercontent.com/72317762/111675294-58b52000-87f3-11eb-8cd0-bc62d7e198d1.png)

This works better.

**Comment by MatejKovacic** [comment]
Can someone give an example for sending base64 attachment with Linux?

```
TMPFILE=`base64 -w 0 cat.jpg`

curl -X 'POST' \
   'http://xx.xx.xxx.xx:8080/v2/send' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d '{
   "base64_attachments": [
   "$TMPFILE"
   ],
   "message": "My message!",
   "number": "+3xxxxx",
   "recipients": [ 
     "+3yyyyy"
   ]
 }'
```

It returns an error:

`{"error":"illegal base64 data at input byte 0"}`

**Comment by bbernhard** [comment]
The problem is that you are using parameter expansion inside a string with single quotes, which doesn't work.

**Comment by MatejKovacic** [comment]
Sorry, I don't understand. If I use single qoute is the same:
```
curl -X 'POST'   'http://91.185.195.221:8080/v2/send'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
  "base64_attachments": [
  '$TMPFILE'
  ],
  "message": "To je sporočilo!",
  "number": "+38977645506",
  "recipients": [ 
    "+38640432656"
  ]
}'

```
Get the error: `{"error":"Couldn't process request - invalid request"}`

**Comment by bbernhard** [comment]
See [here](https://askubuntu.com/questions/1070864/how-to-set-variable-in-the-curl-command-in-bash)

So, basically:

```
#!/bin/bash

set -x

TMPFILE=`base64 -w 0 cat.jpg`

curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "base64_attachments": ["'"${TMPFILE}"'"], "number": "<number>", "recipients": ["<recipient>"]}' 'http://127.0.0.1:8080/v2/send'
```
