### ISSUE TITLE
Message History Feature

### ISSUE THREAD

**Issue by EJansenMSFT** [bbernhard/signal-cli-rest-api#114]
### Feature Request
I can receive messages just fine, but there's no history (that I'm aware of) when doing it programmatically.  Is the message history stored on the container / can it be accessed separately, or do I just need to write some code in my Receive-SignalMessage function to store the history somewhere else?

Thanks!

**Comment by bbernhard** [comment]
At the moment there's no such thing, but I think it also shouldn't be too hard to add that functionality. For me the biggest question in that regard is which storage should be used. The easiest would probably be to dump the whole JSON in a file and call it a day. But I am pretty sure at some point, when the file gets bigger and bigger, reading the file will be pretty slow. So, to work around that, it's probably better to put the data in a database. Then, the next question is: Is it worth it to parse the JSON payload into a relational database schema, or is it sufficient to just write the JSON to the database? The former sounds more clean to me, but I am a bit afraid that at some point signal-cli will change the format of the payload and the data cannot be mapped to the database table anymore. At this point then database schema migrations are needed which makes the whole thing unnecessarily complicated. 

Okay, that was a pretty complicated way of saying: At the moment there isn't such a thing, but it would be kinda cool to have that. ;-)

Maybe I'll hack something together on a weekend and release that as experimental feature.

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.

**Comment by julienrbrt** [comment]
Hi! Since last year this is something possible: https://signal.org/blog/a-synchronized-start-for-linked-devices/
