### ISSUE TITLE
Migrating Containers with Signal Device configurations between Windows hosts.

### ISSUE THREAD

**Issue by EJansenMSFT** [bbernhard/signal-cli-rest-api#118]
I've spent a few hours trying to get this to work and ~~I've only had some success~~.  (**_After about 8 hours of messing with everything, I figured everything out, but still had some questions below_**). In short, I was trying to move the Signal Container off of my Windows 10 laptop onto a Physical Windows 2019 Server.  On the server, I did the following:

Side Note: This is just my pasting of notes after researching / experimenting, to show how I did what.

Installed Docker on the 2019 Server:

	• Install Hyper-V and Containers Windows Features
	• Enabled the Windows Subsystem for Linux.
		○ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
	        ○ Reboot
	• Download and Install Docker. 
            ○ Reboot

NOTE:  The Windows 10 machine is using WSL2, where the Server 2019 build isn't new enough to support it, so it's on the original version of the Windows Subsystem for Linux.

Migrated the Container from the Win10 box to the Server:

![image](https://user-images.githubusercontent.com/72317762/112244851-3cb3e300-8c26-11eb-9bab-2abc6c5006d6.png)

![image](https://user-images.githubusercontent.com/72317762/112243752-7be13480-8c24-11eb-92b6-a8672cb8fc13.png)

The container starts up, ~~but in this case, port 8080 isn't listening on the host~~ **_(posted what I did to figure this out in a follow on comment below)_**, and I don't think any of the configuration data in regards to the registered device moved with the machine.  When I installed the Signal API initially a few weeks ago, I copied it to c:\SignalAPI and then followed your instructions just running **docker-compose pull** and **docker-compose up**.  The device data / configuration appears to be stored there.  I say that because when I run **docker container inspect 'Container _ID_'** on the Win10 machine, I see the following:

![image](https://user-images.githubusercontent.com/72317762/112244322-7f28f000-8c25-11eb-818f-2cef1100d62a.png)

But on the new container, I see this instead (Though on the Server, possibly because it doesn't have WSL2, I had to run **docker container inspect 'Container _NAME_'**):

![image](https://user-images.githubusercontent.com/72317762/112244430-b13a5200-8c25-11eb-83ef-a1bec2371412.png)

~~Same thing in regards to the networking:~~

~~Win10:~~

![image](https://user-images.githubusercontent.com/72317762/112244522-d62ec500-8c25-11eb-85e3-73c6fccdb36c.png)

~~Server 2019:~~

![image](https://user-images.githubusercontent.com/72317762/112244688-f494c080-8c25-11eb-9c41-bba9037199f7.png)

I'm close, but not quite there.  I figure if I can get the port listening and config imported, then I think all will be good.  Any ideas? 

Thanks in advance for any guidance.

**Comment by EJansenMSFT** [comment]
**_Update, hours later._**  In case this can help someone else, I'll keep the details in here, since this has all been a big learning curve for me, not knowing Signal, Docker, or much about *nix.

Anyhow, I figured out the networking part.  Essentially saw that in the default configuration there was created what appears to be the equivalent of a virtual switch in HyperV or ESX, called **signalapi_default**, after finding this command:

![image](https://user-images.githubusercontent.com/72317762/112253548-4d1f8a00-8c35-11eb-89f1-085c817d1e8a.png)

I just played around a bit until I figured out how to do create that on the docker implementation on the target server, and came up with the following:

![image](https://user-images.githubusercontent.com/72317762/112253700-97087000-8c35-11eb-897f-f87e5a4231b1.png)

Then, I figured that I'd need to attach the container to the network, just like I'd connect a VM to a virtual switch, and ran this:

![image](https://user-images.githubusercontent.com/72317762/112253877-e64ea080-8c35-11eb-850e-1c7719b91c36.png)

Made some progress, but that didn't solve the port mapping issue, as seen here:

![image](https://user-images.githubusercontent.com/72317762/112253925-ff575180-8c35-11eb-8c0a-1a710e2497df.png)

I later discovered how to do the port mapping and it appears that it has to be done when creating the container, so I just deleted the one that I started with, and created another one from the imported image, like so:

![image](https://user-images.githubusercontent.com/72317762/112253985-2746b500-8c36-11eb-8773-68b015a5c9ca.png)

And now, _finally_, I can see that the port is listening on the host / 2019 Server:

![image](https://user-images.githubusercontent.com/72317762/112254198-93291d80-8c36-11eb-8f95-c7385d72972d.png)

Now I just need to figure out how to import the configuration data for the registered signal device.....

**Comment by EJansenMSFT** [comment]
_**Update again, hours later...after hours later.**_

So it appears that the magic happens here:

![image](https://user-images.githubusercontent.com/72317762/112265245-90cfbf00-8c48-11eb-9a3b-cc49e6e61d7f.png)

So all I had to run after exporting the image, copying it over, and then importing it, was **_docker-compose up_**, from within the C:\SignalAPI folder, where the docker-compose.yml file was (as seen in the screenshot)?

Lets say that I wanted to map that volume via the means that I 'discovered' earlier:

![image](https://user-images.githubusercontent.com/72317762/112265857-91b52080-8c49-11eb-8c07-01a3dfe99d0e.png)

What would I add to that command?  I was playing with the -v and --mount, but wasn't having much success.

Thanks!

**Comment by bbernhard** [comment]
Sorry for the late reply!

> So all I had to run after exporting the image, copying it over, and then importing it

There's no need to actually export the image, copy it over and import it again on the new host. I mean, you could do that of course, but that's unnecessarily complicated. A docker image doesn't contain any user specific data. So, when you want to move your docker container to a new host, you can pull the existing image from dockerhub. All the user/container specific data is passed into the docker container when the docker daemon starts the container.

There are two different ways to store data. Either via bind mounts or via docker volumes (you can read more about the two different mount modes [here](https://docs.docker.com/storage/bind-mounts/)). The `docker-compose.yml` example in the `README.md` uses the bind mount. This line `- "./signal-cli-config:/home/.local/share/signal-cli"` here mounts the `signal-cli-config` folder (which will be created in the same directory as the `docker-compose.yml` resides) into the container at the location `/home/.local/share/signal-cli"` (this is the location where the daemon inside the docker container looks for the file). 

So, if you want to move the container to a different host all you need to do is:

* copy the `docker-compose.yml` file and the `signal-cli-config` to your new host
* run `docker-compose pull` and `docker-compose up`
* remove the docker container from your old instance (otherwise two systems are fighting for the same signal number)

The above only works for bind mounts. In case you are using docker volumes it's a bit more complicated.

**Comment by EJansenMSFT** [comment]
> There's no need to actually export the image, copy it over and import it again on the new host. I mean, you could do that of course, but that's unnecessarily complicated. A docker image doesn't contain any user specific data. So, when you want to move your docker container to a new host, you can pull the existing image from dockerhub. All the user/container specific data is passed into the docker container when the docker daemon starts the container.

I eventually figured that out the hard way. :)  All part of the learning process though.

Yeah, I found deploying a new container and simply copying the data in the signal-cli-config folder to the new container was all that was required, and it didn't even require a container reboot, so that was awesome.

Right now, I have a separate container with NGINX in front of it, so it's all SSL traffic now to the host.  Just playing with some other options in regards to authentication to prevent unauthorized people on the network from being able to send commands to the host.  For now, firewall rules work just fine.

Thanks for all of your help thus far!

**Comment by bbernhard** [comment]
Glad to hear that you got it working!

Regarding Nginx: Very cool! 

I don't know if you have time/interest, but I would really love to see some documentation in that regard. This questions comes up every now and then in the github issues, but I haven't had time to set up a reverse proxy myself to document the necessary steps. So, if you want to create a pull request with some documentation - I would highly appreciate that!

Of course, I also totally understand if you don't have enough time to do so (writing documentation is always a pretty resource intensive task).

**Comment by EJansenMSFT** [comment]
I turned this into a bit of a small project and there's a couple of other guys testing reading through the code and looking at your Rest API and my PS module.  One of those guys did the NGINX part, but said he'd document the reverse proxy stuff and post when he can.

**Comment by bbernhard** [comment]
> I turned this into a bit of a small project and there's a couple of other guys testing / reading through the code and looking at your Rest API and my PS module. One of those guys did the NGINX part, but said he'd document the reverse proxy stuff and post when he can.

Awesome! Many thanks!

**Comment by bbernhard** [comment]
It looks like this issue is resolved, so I'll close it now. In case there are still some open questions, please either create a new issue or respond here and I'll re-open the issue again.
