### ISSUE TITLE
`/v1/receive/{number}` with timeout does not work as expected and can lose messages

### ISSUE THREAD

**Issue by rca** [bbernhard/signal-cli-rest-api#120]
Hello, this is an awesome project!  Really excited to put it to use.  I believe I found a problem with receiving messages, especially when the request is made with a large timeout.

```
http://localhost:8080/v1/receive/{number}?timeout=30
```

When a message is sent during a long timeout and the API request is canceled, any messages that came in will be lost, which is not good.

Also, I was under the impression that the timeout would work different than it does.  I would have expected it to return right after it receives a message rather than aggregating messages and returning after the timeout expires.  My mentality was similar to "long polling" back when websockets weren't yet a thing, it would hold the request open until there was something to return and do so immediately.

Thank you.

**Comment by bbernhard** [comment]
Sorry for the late reply. 

Unfortunately there is probably not much I can do. The REST API is just a small wrapper around signal-cli (which itself is a Java application). If you are running the docker container on small devices like the Raspberry Pi the Java startup time is significant and is (at least partly) the reason why the receive is so slow. If you are running the docker container on a x86-64 system you could use the experimental native mode (see the Readme). But it's still experimental and has some limitations.

The timeout parameter just allows to specify the time to wait until the request is aborted. Per default every API call will be aborted if it takes longer than 60 secs. By setting the timeout parameter you can extend that time.

**Comment by bbernhard** [comment]
In case you want to receive messages immediately, please use the `json-rpc` mode (which implements the `receive` as websocket endpoint)
