### ISSUE TITLE
Native mode - Listing or sending to groups doesnt work

### ISSUE THREAD

**Issue by xatr0z** [bbernhard/signal-cli-rest-api#122]
Hi,
Just tried out native mode and the speed difference is noticable (3 seconds instead of 5 seconds). However groups don't seem to work on my end,

When sending a message with the API (tried combinations of SECRETSECRET/SECRET=, without =, without /SECRET, prepending with group):
```
root@home:~# curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+31612312312", "recipients": ["SECRETSECRET/SECRET="]}' 'http://127.0.0.1:8080/v2/send'
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}
```

Even listing the groupID with the API doesn't work:
```
curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/groups/+31612312312'
{"error":"Exception in thread \"main\" java.lang.AssertionError: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.commands.ListGroupsCommand$JsonGroup and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])\n\tat org.asamk.signal.JsonWriter.write(JsonWriter.java:35)\n\tat org.asamk.signal.commands.ListGroupsCommand.handleCommand(ListGroupsCommand.java:91)\n\tat org.asamk.signal.App.handleLocalCommand(App.java:204)\n\tat org.asamk.signal.App.init(App.java:164)\n\tat org.asamk.signal.Main.main(Main.java:49)\nCaused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.asamk.signal.commands.ListGroupsCommand$JsonGroup and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])\n\tat com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)\n\tat com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)\n\tat com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)\n\tat com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)\n\tat com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)\n\tat com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)\n\tat com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)\n\tat com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)\n\tat com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)\n\tat com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)\n\tat com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3202)\n\tat org.asamk.signal.JsonWriter.write(JsonWriter.java:32)\n\t... 4 more\n"}r
```

The groupID is correct as I obtained this from withing the docker container:
```
signal-api@home:/$ signal-cli-native listGroup
Id: SECRETSECRET/SECRET= Name: My Name  Active: true Blocked: false
```

Sending messages to groups works as well:
```
signal-api@home:/$ signal-cli-native send -m bla -g SECRETSECRET/SECRET=
```

Am i forgetting something or is this a bug in the new native image?

**Comment by bbernhard** [comment]
Thanks for also trying with `signal-cli` directly, that always makes it a bit easier to narrow done the problem!

In case you are interested in finding out the actual command that's executed by the REST API wrapper, you can enable the debug mode. Unfortunately that's not yet documented anywhere, but I've briefly described it here: https://github.com/bbernhard/signal-cli-rest-api/issues/112#issuecomment-803444934

Regarding your problem:

I think that's a problem in the upstream (signal-cli) repository. This here works with the native image:

`signal-cli-native --config /home/.local/share/signal-cli -u <number> listGroups`

But this here doesn't:

`signal-cli-native --config /home/.local/share/signal-cli --output json -u <number> listGroups -d`

The last command is the one that's used by the REST API wrapper. Unfortunately there isn't much I can do until this issue is fixed upstream.

**Comment by xatr0z** [comment]
Thanks for your quick reply! 
I understand now that it's caused by a missing json serializer. It looks like it's already reported upstream https://github.com/AsamK/signal-cli/issues/572  and a fix is on the way https://github.com/AsamK/signal-cli/pull/576 . I'll check if it fixes my problem sometime soon.
