### ISSUE TITLE
Using GraalVM switch triggers unable to parse entity error

### ISSUE THREAD

**Issue by ict-one-nl** [bbernhard/signal-cli-rest-api#128]
Using the latest stable, suddenly I wasn't able to send messages to one telephone number anymore. The second worked fine, error:

```
root@neo-server:/opt/signal-rest-api# curl -X POST -H "Content-Type: application/json" -d '{"message": "<message>", "number": "+31619111111", "recipients": ["+316221111111"]}' 'http://192.168.2.35:18080/v2/send'
{"error":"Failed to send message: Unable to parse entity\n"}
```

removed the native flag, restarted the container and the problem disappeared. Runs on latest debian stable host (Intel NUC)

**Comment by bbernhard** [comment]
Intel NUC is x86-64, right? 

@filipre recently fixed some things regarding the native mode (see [here](https://github.com/bbernhard/signal-cli-rest-api/issues/103#issuecomment-828742759)). As there's no new `signal-cli` release yet, I haven't updated the `latest` tag on dockerhub. But there's a test image available, which contains the changeset. In case you want to give that one a try, you can use this docker image here: `bbernhard/signal-cli-rest-api:0.62-dev` 

edit: In case it's just one number that doesn't work anymore, you could also try to call the `receive` API endpoint. (i.e `curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/receive/<your signal number>'`). Calling `receive` often fixes some strange errors (signal-cli` also recommends to run the `receive` on a regular basis)

**Comment by ict-one-nl** [comment]
Will try this weekend, thanks! 

I don't have control over the call to signal-rest-cli, it's HomeAssistant that does that for me in this case.

**Comment by ict-one-nl** [comment]
First results are encouraging. Will monitor it in "production" use.

**Comment by bbernhard** [comment]
btw: I've just pushed a new image with the `latest` tag a few minutes ago. So, the `dev` image shouldn't be necessary anymore.

**Comment by ict-one-nl** [comment]
So far so good, upgraded to latest. Thanks!
