### ISSUE TITLE
Include my small shell client

### ISSUE THREAD

**Issue by florian-h05** [bbernhard/signal-cli-rest-api#130]
### Feature Request

Could you maybe include my very small shell client for the REST API in your documentation?

This [script at gist.github.com](https://gist.github.com/florian-h05/26be2140e9907884218b4e3144c2f2ab) can send messages, list & and trust identities.

I use it to send Signal messages from my Raspberry Pis and I run your Docker container on my NAS.

**Comment by bbernhard** [comment]
Many thanks, I've added it to the README.

In case I've missed something or you would like to change something, feel free to create a PR!

**Comment by florian-h05** [comment]
Okay, thank you very much.
I close the issue now.
