### ISSUE TITLE
Set file names of attachments

### ISSUE THREAD

**Issue by webzit** [bbernhard/signal-cli-rest-api#136]
### Feature Request

`TMPFILE="$(base64 cat.jpg)" && echo '{"message": "Hello CAT!", "base64_attachments": ["'"$TMPFILE"'"], "number": "+0000000000", "recipients": ["+0000000000"]}' | curl -X POST -H "Content-Type: application/json" -d @- 'http://127.0.0.1:8080/v2/send'`

Sending attachments works fine as long as "github.com/h2non/filetype" detects the file type. Unfortunately, some PDFs are not recognized.

It would be an improvement if we could set the file name ourselves.
e.g.

`TMPFILE="$(base64 cute_cat.pdf)" && echo '{"message": "Hello CAT!", "base64_attachments": [["'"$TMPFILE"'", "cute_cat.pdf"]], "number": "+0000000000", "recipients": ["+0000000000"]}' | curl -X POST -H "Content-Type: application/json" -d @- 'http://127.0.0.1:8080/v2/send'`

**Comment by bbernhard** [comment]
Do you maybe have a example PDF that gets wrongly detected? In case you can't share the PDF, could maybe run `file --mime-type your_pdf_file.pdf` on the commandline to check whether `file` correctly detects the MIME type. 

We could of course also add the possibility to manually set the filename/file extension via REST, but even when doing so, I would really be interested in improving the MIME type detection too. In case it's a valid PDF, it should also be detected as one :)

**Comment by webzit** [comment]
"_application/octet-stream; charset=binary_" .... but I just noticed that they are corrupted pdfs which I can't open either.

Adding the ability to set the file name/extension manually via REST would still be a good idea, as for example the file name "_Invoice-02_2021.pdf_" does give the recipient more info about the content than "_b38c61fa-3b95-4157-90e0-3601acb76301.pdf_" 👍

**Comment by bbernhard** [comment]
Totally agreed, that would definitely be a nice improvement! I'll schedule this is a feature improvements (with a slightly lower priority than if it would be a bug). In case you stumble across a file where the mime type isn't correctly detected, please let me know. This would require a more urgent fix.

**Comment by webzit** [comment]
The mime type is not recognized correctly for .txt / .log files. Perhaps we could change in the meantime the file extension ".unknown" to ".txt" as it is not easy to open unknown file extensions with iPhones.

Background: I would like to have important linux logfiles sent to me regularly with signal using cronjob :) As a workaround until now I compress the files before sending (.zip).

**Comment by bbernhard** [comment]
I've just kicked off a new build: https://github.com/bbernhard/signal-cli-rest-api/actions/runs/876386223

If the build runs through, there should be a new dev image available with the tag `bbernhard/signal-cli-rest-api:0.66-dev`. I did some testing with txt files, images and pdf files and so far everything seems to work fine. In case you want to give it a try, the image should be available on dockerhub in ~1.5hrs.

**Comment by webzit** [comment]
It works wonderfully! 
Small note: It seems that the new library adds the point itself. e.g. 4ebf5a6a-5a4c-421f-a17a-fc50672e7519..txt -> **..**

Is it only possible to send one file?

```
echo '{"message": "test with two txt files attached", "base64_attachments": ["SGFsbG8gbGllYmVyIGJiZXJuaGFyZCEgIzEK", "SGFsbG8gbGllYmVyIGJiZXJuaGFyZCEgIzIK"], "number": "+**********", "recipients": [""+**********"]}' | curl -X POST -H "Content-Type: application/json" -d @- http://127.0.0.1:8080/v2/send
```

**Comment by bbernhard** [comment]
> Small note: It seems that the new library adds the point itself. e.g. 4ebf5a6a-5a4c-421f-a17a-fc50672e7519..txt -> ..

Many thanks for the info, completely missed that!

> Is it only possible to send one file?

I've played a bit around with it and I think that's actually a limitation of the Signal Messenger. Sending multiple images works. It even works when changing the file extension of a txt file to `.jpg` (the images obviously can't be displayed in the Signal app, but at least I was able to send them).  

I tried to send multiple txt files via the Signal Messenger app on my android phone to another Signal user, but wasn't able to do so (I could only send on text file at a time). So I guess this is maybe not supported by Signal app/protocol?

**Comment by webzit** [comment]
The app gives me the following error message: 
Thus not a bug from signal-cli but a "feature" :)

> <img width="556" alt="Bildschirmfoto 2021-06-21 um 21 16 53" src="https://user-images.githubusercontent.com/79612125/122815765-30e3c580-d2d6-11eb-86b3-761dc305d706.png">

**Comment by bbernhard** [comment]
Closing, as it should be fixed already :)

**Comment by ShepelE** [comment]
Hello [bbernhard](https://github.com/bbernhard)! Thank you for this API. But I have to ask you if filename feature was implemented. Was it?
