### ISSUE TITLE
Code Change

### ISSUE THREAD

**Issue by fieldofsheep** [bbernhard/signal-cli-rest-api#139]
Hi Folks,

I have created a branch but I cannot push to your repo for a PR can you give me permissions.

I have implemented the 'updateContact' functionality where you can set message expiration.

**Comment by bbernhard** [comment]
There shouldn't be any permissions needed for creating a PR. Are you sure you are pushing the changes to your own? Pushing directly to this repo won't work. Have a look here: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by bbernhard** [comment]
Please re-open in case it's still an issue for you.
