### ISSUE TITLE
New docker container broke my setup: (no Creators, like default construct, exist)

### ISSUE THREAD

**Issue by f45tb00t** [bbernhard/signal-cli-rest-api#140]
Hello @bbernhard,

unfortunately I pulled the new container you provided. After that I cannot send any messages anymore. I tried now to downgrade, but as the older one has no tag, I have no clue how to do that. :(

Error: 

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "TEST", "number": "+49xxxxxxx", "recipients": ["+49xxxxx"]}' 'http://127.0.0.1:8080/v2/send'
{"error":"Error loading state file for user +49xxxx: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)\n at [Source: UNKNOWN; line: -1, column: -1] (IllegalArgumentException)\n"}
```
Can you tell me please how I can downgrade?
docker image ls -a bbernhard/signal-cli-rest-api
REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE
bbernhard/signal-cli-rest-api   latest    a6f9d535c445   12 days ago    459MB
bbernhard/signal-cli-rest-api   <none>    4ffcf870a49a   2 months ago   433MB

Since its missing the tag, I have no idea how I could change my compose file to get it running again.

**Comment by bbernhard** [comment]
In case you have the image still locally, it should be possible to obtain the sha256 hash from the image.

see https://stackoverflow.com/questions/32046334/where-can-i-find-the-sha256-code-of-a-docker-image

Once you have that you could append that to the image name. i.e `bbernhard/signal-cli-rest-api@sha256:...`

I'll try to add some additional info to the next docker images to make it possible to identify the tag more easily.

**Comment by f45tb00t** [comment]
Thanks a lot! :) 

It works again! Do you know what caused the issue that you can track it down?

**Comment by bbernhard** [comment]
It looks like the same issue @haberda also ran into. See https://github.com/bbernhard/signal-cli-rest-api/issues/134 for details.

In case it's the same for you and all the suggestions I've posted there doesn't work for you either, I am afraid there's not much I can do. @haberda created an issue in the upstream repository. see: https://github.com/AsamK/signal-cli/issues/634

**Comment by f45tb00t** [comment]
I don't think this is related tbh. Because I did not change anything, beside that I did "docker-compose pull" My old version was replaced with your new version and the issue came up. 

So I did not add any new one to the group. Me and the bot are the only ones in that group. So by now I changed latest entry to image: bbernhard/signal-cli-rest-api@sha256:4db672bc4539b188a3e3446109cf8074c06b095ebc441fc69a87cb27b859cea9
did a pull again and it worked.

**Comment by bbernhard** [comment]
> I don't think this is related tbh. Because I did not change anything, beside that I did "docker-compose pull" My old version was replaced with your new version and the issue came up.
> 
> So I did not add any new one to the group. Me and the bot are the only ones in that group. So by now I changed latest entry to image: bbernhard/signal-cli-rest-api@sha256:4db672bc4539b188a3e3446109cf8074c06b095ebc441fc69a87cb27b859cea9
> did a pull again and it worked.

I think @haberda did the same as you and just updated the docker image. In the linked ticket there are actually two different issues discussed. The issue with the group from the original author and the one from @haberda. Originally we thought that those issues might be related, but it turned out that the root cause is different.

**Comment by haberda** [comment]
Yes, I simply updated the image. It seems that signal-cli deprecated support for older statefiles, or at least that is my interpretation. To get it to work again I completely deleted all of the persistent storage and registered my number again.

Notably it did not work if I simply registered again without deleting the files first.

**Comment by f45tb00t** [comment]
Hi,

even when I pinned the working restored version the issue came back. Now I've updated the the most recent version, removed the config and re-register everything. It's working again.
