### ISSUE TITLE
Authentication for REST API

### ISSUE THREAD

**Issue by stefanstranger** [bbernhard/signal-cli-rest-api#142]
I've the Signal CLI REST API running in an Azure Web for Containers. Now I want to add some authentication on top of the REST API.

I enabled Easy Authentication for the Web App (Signal CLI REST API) as documented [here](https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service).

After implementing I get redirected to the provided Identity provider (Microsoft) but the callback fails with the following error.

![image](https://user-images.githubusercontent.com/2125385/121506189-cb452e80-c9e3-11eb-9466-1d481d8d77ec.png)

Does the Signal CLI REST API docker container responds differently when some header information is being returned by the Authentication provider?

Regards,
Stefan Stranger

**Comment by bbernhard** [comment]
Do you maybe see somewhere (e.g in the Azure log or the container log) what the actual HTTP request looks like that's hitting the container? I just tried to add some arbitrary headers to the curl commands, but couldn't see any issues there.

**Comment by stefanstranger** [comment]
Hi Bernard,

How can I enable more logging for the docker container?

**Comment by bbernhard** [comment]
Per default you should already see some output in the container log file.

e.g that's my output when starting the container with `docker-compose up` and sending a message with `curl`:


```
Starting signal-cli-rest-api_signal-cli-rest-api_1 ... done
Attaching to signal-cli-rest-api_signal-cli-rest-api_1
signal-cli-rest-api_1  | + set -e
signal-cli-rest-api_1  | + [ -z /home/.local/share/signal-cli ]
signal-cli-rest-api_1  | + chown 1000:1000 -R /home/.local/share/signal-cli
signal-cli-rest-api_1  | + cat
signal-cli-rest-api_1  | + cap_prefix=-cap_
signal-cli-rest-api_1  | + cat /proc/sys/kernel/cap_last_cap
signal-cli-rest-api_1  | + seq -s ,-cap_ 0 37
signal-cli-rest-api_1  | + caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37
signal-cli-rest-api_1  | + exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
signal-cli-rest-api_1  | time="2021-06-10T15:46:06Z" level=info msg="Started Signal Messenger REST API"
signal-cli-rest-api_1  | [GIN] 2021/06/10 - 15:47:13 | 201 |  4.409665287s |      172.19.0.1 | POST     "/v2/send"
```

Especially the last line is interesting here, as we can see the HTTP endpoint that was called (`/v2/send`) and the HTTP status code (`201`). Granted, that's not much debugging output and probably won't help us much in case the problem is caused by some specific HTTP headers, but it would already be interesting to see whether the correct HTTP endpoint is called.

**Comment by stefanstranger** [comment]
OK. Let my further investigate. I'll keep you posted.

Thanks for all the help.

**Comment by stefanstranger** [comment]
Hi Bernard,

I got everything working! I created a blog post with all my learning called "[Running Signal Messenger REST API in Azure Web App for Containers](https://stefanstranger.github.io/2021/06/01/RunningSignalRESTAPIinAppService/)" 

Thanks for all your help.

Stefan

**Comment by bbernhard** [comment]
Hi Stefan,

awesome blog post! Do you mind if I add a link to your blog post to the `README.md`?

**Comment by stefanstranger** [comment]
Hi Bernhard,

No problem, please link to the blog post in your README. It was my pleasure doing cool stuff with your solution.

Stefan

**Comment by bbernhard** [comment]
> Hi Bernhard,
> 
> No problem, please link to the blog post in your README. It was my pleasure doing cool stuff with your solution.
> 
> Stefan

Hi Stefan,

many thanks! I've added a link to the README :) 

Have a nice day,
Bernhard
