### ISSUE TITLE
On v2/send got 201 but recipients never receive messages

### ISSUE THREAD

**Issue by QuentinDubes** [bbernhard/signal-cli-rest-api#144]
### The problem

Hello,

I'm using the latest release 0.40.

My workflow is quite simple: use a Signal number in server to send some app notifications through Signal. In other words, we want to send messages to users (these users are registered on Signal).

The package is working fine locally: register, verify, send, receive, everything is working as excepted, recipients receive messages.
On my AWS server, the same workflow work fine (got no errors), but messages were never received by recipients.

So, on the server, I succeed to register and verify phone numbers. But when I run /v2/send, I get 201 and recipients won't receive any messages.
I get into issues, I see many times that running /v1/receive/+33xxxxx would make it work. I did it, got an empty array, with code 200. But recipients still don't receive the messages sent after that.

I feel like Signal need verification, so I tried /v1/identities/{number}/trust/{numberToTrust} with recipient on numberToTrust, but recipients still don't receive messages from server.

I found a solution, but it's absolutely not fitting my workflow because we have more than 1000 users, and they won't make it. The solution is to ask each user to send a message to the server. Once the server receive a message from a user, the user receive all messages sent from the server. 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

**Comment by bbernhard** [comment]
I've just released a new dev version for testing. see: https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.41-pre
This version updates `signal-cli` and `libsignal-client` to the latest version. Could you please try that one and check whether that fixes anything.

Apart from that I've added some documentation [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) which describes how to debug problems with the docker container. Would be great if you could give that a try.

**Comment by QuentinDubes** [comment]
Hello, thank you for all details about logs and verbose. 

I'm now sure that `signal-cli-rest-api` **is working in fine my case**, and my issue come from elsewhere. I need to dig deeper.

So I've opened an issue on `signal-cli` package [here](https://github.com/AsamK/signal-cli/issues/650).

**Comment by hannes2323** [comment]
Hi,

I have a similar problem with not receiving messages from signal. I guess the messages are not getting send out:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 136, in async_send_message
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 83, in send_message
    raise exc
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 79, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

Any ideas?

Thanks in advance!
