### ISSUE TITLE
Unable to send message

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#146]
### The problem

We have registered a signal bot using an Indian number using "/register" signal api.

We are able to send and receive messages to Indian numbers (+91) from the registered signal bot via APIs.

While we try to send messages to countries other than India, say Malaysian and Singapore number via API we are getting following error message
"{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}"

Can you please check and let us know what could be the issue here?

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by jyothisjose** [comment]
Can you please let us know the issue regarding  this?

**Comment by bbernhard** [comment]
Please make sure to run the latest version and then check this page [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) to verify whether it's an issue with the REST API wrapper or signal-cli
