### ISSUE TITLE
Unable to send group messages 

### ISSUE THREAD

**Issue by mightym** [bbernhard/signal-cli-rest-api#147]
### The problem

I'm using the latest docker image and I realized that I'm not able to send messages to groups. 
```
data = { "number": "+49XXXXXXXXXXX", "message":"test", "recipients":["signal_id_string"] }
r = requests.post("http://signal-cli-rest-api:8080/v2/send", json=data)
```
gives me:

`{"error":"WARN Manager - Failed to retrieve profile, ignoring: [404] Not found\\nWARN Manager - Failed to retrieve profile, ignoring: [404] Not found\\nFailed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found\\n"}'`

- sending to a single phone number works
- retrieving groups works
- receiving messages of that group works

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you tried setting your profile? See here: https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/TROUBLESHOOTING.md

**Comment by mightym** [comment]
I've set my profile. I need to check if it maybe has something to do with a linked devices. I remember last time I used the group messaging with signal cli 0.8.4 and there it worked.

**Comment by bbernhard** [comment]
I've never linked any devices, but I've heard from other people that signal-cli behaves a bit strangely when you first register a dedicated phone number, but then switch to linking the device instead. If you've done that, try to remove the complete config from the filesystem and start from scratch by linking the device.

**Comment by jernejml** [comment]
Same issue for me. @mightym Did you resolve it?

**Comment by jernejml** [comment]
@bbernhard @mightym 
I've figured it out. Few months ago signal protocol upgraded groups to v2. 
- I've called GET /v1/groups API, which did not return all my groups, but only v1 signal groups. 
- since i've had same or very similar (not exactly sure) human readable label for the v1 and v2 group, i've actually sent my messages to v1 group (which i already left/quit on my phone)
- after calling GET /v1/receive, GET/v1/groups then returned ALL groups (v1 and v2) and then i noticed mistake

After sending message to the v2 group, we've received notification

**Comment by bruno00o** [comment]
any updates on this issue? I've update my profile, but I can't send messages to a group too. I've tried in both normal and JSON-RPC modes.

**Comment by eikel** [comment]
Thanks for you comment, @jernejml! I had the same problem and used the old group id. It has been printed when creating the group. I saw that retrieving the groups with GET `/v1/groups/<number>` returns two ids (I created some random ones below):
```json
[
  {
    "name": "<name>",
    "id": "group.eebieph9xair2eiqu7iejaekaiy0dahh9ahthutho2IbeeCh1eexoo7Laek8=",
    "internal_id": "saequiebeeghoh2GeiW0iewee5aechio0Baed5oimeec=",
    "members": [
      "<member1>",
      "<member2>"
    ],
    "blocked": false,
    "pending_invites": [],
    "pending_requests": [],
    "invite_link": ""
  }
]
```
So `internal_id` was the wrong one I have used before. After switching to `id`, sending works now. :tada:

**Comment by soleous** [comment]
I am receiving messages that I am trying to respond to and the received message only has an internal_id.  I can do a call and some logic to get the correct ID, but I find this behaviour odd.  Is there something I can get to get the ID in received messages?

**Comment by LotusMoves** [comment]
just found this bug looking for a nice solution

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
