### ISSUE TITLE
Pass more parameters in create group API

### ISSUE THREAD

**Issue by jeffreyjam** [bbernhard/signal-cli-rest-api#148]
### Feature Request
Hello and thanks for your work maintaining this repo. Currently the create group API (POST /v1/groups/{number}) accepts the parameters `name` and `members`, then passes them to the [updateGroup](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#updategroup) CLI command.

It would be very useful to me to pass the additional parameters: -d DESCRIPTION, --link LINK_STATE, --set-permission-edit-details PERMISSION. 

Would it be possible to add those as optional parameters to the REST endpoint and then pass them to the CLI command?

**Comment by bbernhard** [comment]
Should be added. If you want to give it a try upfront, then I could push a `dev` image to dockerhub. Otherwise it will be in the next release :)

**Comment by jeffreyjam** [comment]
Thank you so much 🙏. Fastest action from a maintainer I've seen. If it's not too much trouble to push that `dev` image I'd appreciate that.

**Comment by bbernhard** [comment]
No problem, here you go: `bbernhard/signal-cli-rest-api:0.71-dev`

The API documentation can be found here: https://bbernhard.github.io/signal-cli-rest-api/#/Groups/post_v1_groups__number_

Please let me know in case you experience any problems.

**Comment by jeffreyjam** [comment]
Many thanks again. Closing this out.
