### ISSUE TITLE
Docker build failed issue

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#149]
### The problem

On building docker we are getting following error message.

> Task :assembleNativeImage
[signal-cli:131] classlist: 8,829.90 ms, 0.96 GB
[signal-cli:131] (cap): 1,242.53 ms, 0.96 GB
WARNING: Could not resolve jnr.enxio.channels.Native$LibC$jnr$ffi$1 for reflection configuration. Reason: java.lang.ClassNotFoundException: jnr.enxio.channels.Native$LibC$jnr$ffi$1.
WARNING: Could not resolve jnr.unixsocket.Native$LibC$jnr$ffi$0 for reflection configuration. Reason: java.lang.ClassNotFoundException: jnr.unixsocket.Native$LibC$jnr$ffi$0.
[signal-cli:131] setup: 4,262.54 ms, 0.96 GB
[signal-cli:131] (clinit): 1,671.75 ms, 3.08 GB
[signal-cli:131] (typeflow): 81,345.31 ms, 3.08 GB
[signal-cli:131] (objects): 61,171.46 ms, 3.08 GB
[signal-cli:131] (features): 4,459.02 ms, 3.08 GB
[signal-cli:131] analysis: 151,025.65 ms, 3.08 GB
[signal-cli:131] universe: 4,511.27 ms, 3.08 GB
[91mError: Image build request failed with exit status 137
[0m
> Task :assembleNativeImage FAILED
9 actionable tasks: 1 executed, 8 up-to-date
[91m
[0m[91mFAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assembleNativeImage'.
> Process 'command '/tmp/graalvm-ce-java11-21.0.0/bin/native-image'' finished with non-zero exit value 137

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 25s
[0mThe command '/bin/sh -c if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "x86_64" ]; then cd /tmp && tar xvf gvm.tar.gz && export GRAALVM_HOME=/tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION} && cd /tmp/signal-cli-${SIGNAL_CLI_VERSION} && chmod +x /tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin/gu && /tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin/gu install native-image && ./gradlew assembleNativeImage; elif [ "$(uname -m)" = "armv7l" ]; then echo "GRAALVM doesn't support 32bit" && echo "Creating temporary file, otherwise the below copy doesn't work for armv7" && mkdir -p /tmp/signal-cli-${SIGNAL_CLI_VERSION}/build/native-image && touch /tmp/signal-cli-${SIGNAL_CLI_VERSION}/build/native-image/signal-cli; else echo "Unknown architecture"; fi;' returned a non-zero code: 1

**_We are facing issue on executing following commands_**

```docker
RUN if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "x86_64" ]; then \
		cd /tmp && tar xvf gvm.tar.gz \
		&& export GRAALVM_HOME=/tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION} \
		&& cd /tmp/signal-cli-${SIGNAL_CLI_VERSION} \
		&& chmod +x /tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin/gu \ 
		&& /tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin/gu install native-image \
		&& ./gradlew assembleNativeImage; \
    elif [ "$(uname -m)" = "armv7l" ]; then \
		echo "GRAALVM doesn't support 32bit" \
		&& echo "Creating temporary file, otherwise the below copy doesn't work for armv7" \
		&& mkdir -p /tmp/signal-cli-${SIGNAL_CLI_VERSION}/build/native-image \
		&& touch /tmp/signal-cli-${SIGNAL_CLI_VERSION}/build/native-image/signal-cli; \ 
    else \
		echo "Unknown architecture"; \
    fi;
```

Can you please help us to solve the issue

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by jyothisjose** [comment]
Can you please let us know the issue regarding this?

**Comment by jyothisjose** [comment]
Can you please let us know the issue regarding this?

**Comment by bbernhard** [comment]
Please post the commands you are using to build the docker image. 

Are you trying to build the latest version? On which host system and for which target platforms are you trying ro build the docker image? Are you sure that it's not a problem on your build system? (e.g running out of RAM). Is there a particular reason why you want to build the image from scratch instead of using the image from dockerhub?

**Comment by jyothisjose** [comment]
> Please post the commands you are using to build the docker image.
> 
> Are you trying to build the latest version? On which host system and for which target platforms are you trying ro build the docker image? Are you sure that it's not a problem on your build system? (e.g running out of RAM). Is there a particular reason why you want to build the image from scratch instead of using the image from dockerhub?

Are you trying to build the latest version? 
	Yes.

On which host system and for which target platforms are you trying ro build the docker image? 

	We are using jenkins(running as a docker container on AWS server) to build the image.

Are you sure that it's not a problem on your build system? (e.g running out of RAM). Is there a particular reason why you want to build the image from scratch instead of using the image from dockerhub?

	We are using dbus, that's why we customize the docker image.

**Comment by bbernhard** [comment]
If you've customized the image then I most probably cannot help you. You can open source your changes and maybe the community is able to figure out what's wrong with your docker image, but without the sourcecode I don't think there's any chance.

**Comment by jyothisjose** [comment]
> If you've customized the image then I most probably cannot help you. You can open source your changes and maybe the community is able to figure out what's wrong with your docker image, but without the sourcecode I don't think there's any chance.

We have edited the following files.
1. entrypoint.sh, added dbus command and we are running a demon.
2. Dockerfile, we have commented entrypoint and added dbus commands.
3. Finally we have edited src/api/api.go line number 181. We have replaced the original line 'cmd := []string{"--config", signalCliConfig, "-u", number, "send"}' to cmd := []string{"--config", signalCliConfig, "--dbus", "send"}


Can you please check attached entrypoint.sh and Dockerfile.

**Comment by jyothisjose** [comment]
If you've customized the image then I most probably cannot help you. You can open source your changes and maybe the community is able to figure out what's wrong with your docker image, but without the sourcecode I don't think there's any chance.

We have edited the following files.

entrypoint.sh, added dbus command and we are running a demon.
Dockerfile, we have commented entrypoint and added dbus commands.
Finally we have edited src/api/api.go line number 181. We have replaced the original line 'cmd := []string{"--config", signalCliConfig, "-u", number, "send"}' to cmd := []string{"--config", signalCliConfig, "--dbus", "send"}
Can you please check attached entrypoint.sh and Dockerfile as text file type.

[DockerfileAsTextFormat.txt](https://github.com/bbernhard/signal-cli-rest-api/files/6935837/DockerfileAsTextFormat.txt)

**Comment by bbernhard** [comment]
I can't support custom images, please use the offical image.
