### ISSUE TITLE
Cannot send attachments

### ISSUE THREAD

**Issue by sirjeannot** [bbernhard/signal-cli-rest-api#15]
Hello,

since last commit 10 hours ago, I can't attach base64 documents.
URL has been updated to v2, but the message is sent without attachment. At this point I haven't changed anything else.

Then I noticed the json field name for attachment now is set to plural:
`"base64_attachments": ["<base64 encoded attachment>"]`

However adding this 's' throws the following error.
`{"error":"Couldn't process request - invalid request"}`

anything I'm not doing right?

**Comment by bbernhard** [comment]
Hi,

that's strange. Could you please send me an example REST API call which fails for you. That would help a lot with troubleshooting :)

**Comment by sirjeannot** [comment]
My bad, I did't see the attachments field is now a list. I just added the brackets and all is fine.
Sorry for not seeing this.

(and also thanks a lot for this tool!)

**Comment by bbernhard** [comment]
no worries - glad that it's working now :)
