### ISSUE TITLE
Is there a way to run the API smoothly on a raspberry pi?

### ISSUE THREAD

**Issue by Dattito** [bbernhard/signal-cli-rest-api#152]
In the moment, sending a message with the signal-cli-rest-api takes up to 40 seconds in a docker container on my raspberry pi 4. Any suggestions how to make executing a command quicker? E.g. is there a way to build a native binary for arm 32-bit?

**Comment by bbernhard** [comment]
Unfortunately GraalVM doesn't support armv7. But you could install 64bit Raspbian on your Pi.

**Comment by jyothisjose** [comment]
@bbernhard can you please check this issue also https://github.com/bbernhard/signal-cli-rest-api/issues/149 and please update us
