### ISSUE TITLE
native=1 doesn't work on latest version of docker and 41

### ISSUE THREAD

**Issue by diazzaid** [bbernhard/signal-cli-rest-api#153]
### The problem

i have tried both version of docker 41 and latest not support native=1, high cpu when sending message and sending time so long about 6 seconds or more. different from docker 40 version by using native=1 faster message delivery and not high cpu.

and how to manually update libsignal-client without updating docker image

thanks

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
The root cause could be the same as https://github.com/bbernhard/signal-cli-rest-api/issues/145. In the linked ticket the issue seems to be introduced with the new libsignal-client. 

> and how to manually update libsignal-client without updating docker image
To which version of libsignal-client do you want to update? Updating libsignal-client without updating the docker image is not really possible, as it's part of the image.

**Comment by diazzaid** [comment]
> Akar penyebabnya bisa sama dengan #145 . Dalam tiket tertaut, masalahnya tampaknya diperkenalkan dengan libsignal-client baru.
> 
> > dan bagaimana cara memperbarui libsignal-client secara manual tanpa memperbarui gambar buruh pelabuhan 
> > Ke versi libsignal-client mana yang ingin Anda perbarui? Memperbarui libsignal-client tanpa memperbarui gambar buruh pelabuhan sebenarnya tidak mungkin, karena itu adalah bagian dari gambar.

ok thanks

**Comment by diazzaid** [comment]
> The root cause could be the same as #145. In the linked ticket the issue seems to be introduced with the new libsignal-client.
> 
> > and how to manually update libsignal-client without updating docker image
> > To which version of libsignal-client do you want to update? Updating libsignal-client without updating the docker image is not really possible, as it's part of the image.

is there a tutorial to update libsignal-client directly on the container ?

**Comment by diazzaid** [comment]
> The root cause could be the same as #145. In the linked ticket the issue seems to be introduced with the new libsignal-client.
> 
> > and how to manually update libsignal-client without updating docker image
> > To which version of libsignal-client do you want to update? Updating libsignal-client without updating the docker image is not really possible, as it's part of the image.

oh sorry i mean how to update libsignal-client directly on cli container

**Comment by bbernhard** [comment]
libsignal-client is a library written in Rust, that unfortunately isn't available in the distribution's package manager. So, when you want to update libsignal-client from within the docker container, you have to install the Rust toolchain in the docker container, or cross compile the library on your host system. And even when you manage to update libsignal-client, it will be overwritten again as soon as you restart the docker container (as its not part of the image). So, the easiest way is to update libsignal-client in the Dockerfile and rebuild the complete image.

**Comment by diazzaid** [comment]
> libsignal-client is a library written in Rust, that unfortunately isn't available in the distribution's package manager. So, when you want to update libsignal-client from within the docker container, you have to install the Rust toolchain in the docker container, or cross compile the library on your host system. And even when you manage to update libsignal-client, it will be overwritten again as soon as you restart the docker container (as its not part of the image). So, the easiest way is to update libsignal-client in the Dockerfile and rebuild the complete image.

ok bro thanks,, it's a hard job hehe..
