### ISSUE TITLE
automatically re-send the previously message has 400 error code

### ISSUE THREAD

**Issue by Cempakers87** [bbernhard/signal-cli-rest-api#156]
### The problem

Hai @bbernhard, I have an issue regarding /send endpoint. 
In my code, I have condition that must re-trying N times to send if message has failed sent at first attempt.
Let say I have setup N=3. It will retrying 3 times until success.
Yesterday, I found that re-trying code executed and has some log like below
![image](https://user-images.githubusercontent.com/20413727/130564939-cdf9f424-6e46-48e5-8698-c8b1f22054f8.png)
In your opinion, does this project execute auto resend after it reach 400? Because really strange in my apps, it finally sent 4 times successfully although have 400 status code previously and doesn't have any 201 status.
Please help. Sorry my bad english.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

other

**Comment by bbernhard** [comment]
Not sure if I understood you correctly, but there is no built in retry. So, if you want to have a retry you have to implement that yourself. :)
