### ISSUE TITLE
signal-cli-rest-api seems to have problems with \n 

### ISSUE THREAD

**Issue by gadric** [bbernhard/signal-cli-rest-api#157]
### The problem

I am using signal-cli-rest-api for quite some time and it works with Home Assistant quite good. 

However, I am trying for a couple of months to redirect some alerts from monit to signal (for example: if users logging via SSH). 

in such a case, I am always getting the following error: 

```
time="2021-08-29T12:23:01Z" level=error msg="invalid character '\\n' in string literal"
[GIN] 2021/08/29 - 12:23:01 | 400 |      65.111µs |   192.168.44.12 | POST     "/v2/send"
[GIN] 2021/08/29 - 12:23:06 | 400 |  4.820241672s |   192.168.44.12 | POST     "/v2/send"
```

anyone has an idea how to address this problem? 

The following message should be sent: 

```
content match:
Aug 29 14:22:46 _<namereplaced>_ sshd[11496]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

I have already tested if I change the line to: 
`
content match: Aug 29 14:22:46 styx sshd[11496]: pam_unix(sshd:session): session opened for user root by (uid=0)
`
it works. 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
That's strange. I just tried it via curl and it works for me:

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "content match:\nAug 29 14:22:46 _<namereplaced>_ sshd[11496]: pam_unix(sshd:session): session opened for user root by (uid=0)", "number": "<my signal number>", "recipients": ["<recipient>"]}' 'http://127.0.0.1:8080/v2/send'
```
Does the above curl request work for you too?

**Comment by gadric** [comment]
Yes, 

this curl works for me. 

I have tried a couple of things now, and it always give the same error message. Is there a way from signal-cli-rest-api to show where expect the \n cause problem? 

The funny thing is that I have redirected the Messages to files and than use `cat` to show to content of the files to send them. This works. But direct from the message variable, even though I searched and replace all newlines, causes the error.

**Comment by bbernhard** [comment]
> Is there a way from signal-cli-rest-api to show where expect the \n cause problem?

With the image you are using, there isn't any. But I've pushed a new docker image to dockerhub that logs the complete JSON payload to stdout. Maybe this helps finding the root cause. The docker image tag is: `bbernhard/signal-cli-rest-api:0.74-gadric-dev`

**Comment by gadric** [comment]
I will have a look today and come back

**Comment by gadric** [comment]
quick question to to be sure, I guess if I use the following command, the complete JSON payload should be in a file right (with &> outputfile at the end of the command)?

`curl -X POST -H "Content-Type: application/json" -d '{"message": "content match:\nAug 29 14:22:46 _<namereplaced>_ sshd[11496]: pam_unix(sshd:session): session opened for user root by (uid=0)", "number": "<my signal number>", "recipients": ["<recipient>"]}' 'http://127.0.0.1:8080/v2/send &> outputfile'
`

**Comment by bbernhard** [comment]
It's only logged and not returned in the request's response. So, you have to look in the container log file

**Comment by gadric** [comment]
This version was the key to identify the error. 

I got it working now. The following message worked: 

```
time="2021-08-30T14:39:40Z" level=info msg="{\"message\": \"The system monitoring needs your attention.\\n\\nHost:        <hostname>\\nDate:        Mon, 30 Aug 2021 16:39:40\\nService:     ssh_logins\\nEvent:       Content match\\nDescription: content match:\\nAug 30 16:39:30 <hostname> sshd[18617]: pam_unix(sshd:session): session opened for user <username> by (uid=xxx)\\n\\n\\nThis triggered the monitoring system to: alert\\n\\n—\\nYou have received this notification because you have enabled the system monitoring on this host.\\nTo change your notification preferences, please go to the 'System | Notification' or 'System | Monitoring' page in the web interface.\", \"number\": \"+xxxxxxxxxx\", \"recipients\": [\"+yyyyyyyyyyyyyyyyyyyyy\"]}"
````

The error was related to `\\n`. I dont know why, but it seems that I needed the `\\` instead of only 1 \ to get the new lines. 

I dont not why, but running the same command with `\n` directly in the shell works. But if I try to use the messages from monit, I need to use `sed` to replace them with `\\n`

Does it make sense to have this incoporated into the software itself? LIke if you have multiple lines, signal-cli-rest-api will replace them with `\n` or `\\n`
