### ISSUE TITLE
IllegalArgumentException after update to latest

### ISSUE THREAD

**Issue by georf** [bbernhard/signal-cli-rest-api#159]
Currently I used the version 0.37. After update to a later version I get the following error, when I try to send a message:

```
Error loading state file for user +43XXXXX: Cannot construct instance of `org.asamk.signal.manager.storage.protocol.LegacyJsonSignalProtocolStore` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator) at [Source: UNKNOWN; line: -1, column: -1] (IllegalArgumentException) 
```

Is there a way to update the cli-config data file? Or did I something wrong?

**Comment by bbernhard** [comment]
Have you tried doing a `receive` via the REST API?

I also recommend configuring a Auto Receive Schedule (see https://github.com/bbernhard/signal-cli-rest-api#auto-receive-schedule for details).

If that doesn't have fix the issue, I would recommend to remove the whole signal-cli config data folder and start from scratch by re-registering your device. (I've seen some rare signal-cli issues where the automatic config file migration didn't work. In that case only a complete re-registering of the device worked for me)

**Comment by georf** [comment]
Thanks for your response.

I never did a receive before. So now I removed the data folder and started again. It is working now. I added the auto-receive option and hope that all will be fine in future. Thank you!
