### ISSUE TITLE
Binary for usage without Docker?

### ISSUE THREAD

**Issue by Larx** [bbernhard/signal-cli-rest-api#16]
Do you plan to provide a binary for usage without docker? Preferably with a configurable path to the config directory? I tried to compile myself, but always end up with
```
# command-line-arguments
./main.go:64:10: assignment mismatch: 2 variables but 1 values

```

I'm a bit reluctant to set up docker and pull an 1,3 GB image only for this usecase (wrapper of a Signal API wrapper ;-), as I prefer the "classical" way of installing programs, especially on low-end devices. (Moreover, for me the docker container always exits with "0" doing nothing, and I'm not very good in debugging docker problems...)

Thanks for your work!

**Comment by bbernhard** [comment]
A binary is not a problem, the only thing that you need to be aware of, is that you not only need the `signal-cli-rest-api` version, but also [signal-cli](https://github.com/AsamK/signal-cli) itself (which is a java application). In the past, I've had quite a few problems with java on musl based systems, that's why I've created the docker image. (That's btw. also the reason why the docker image is rather large. I am pretty sure I could trim it down further, but as I need a glibc based OS, using a small alpine image as base is unfortunately not possible). That being said, I guess I could also provide binaries. Is there a particular architecture you would need to binaries for?

**Comment by Larx** [comment]
Thanks for the reply! I have signal-cli already running on my Raspbian RPi4 without any problem. But yes, I forgot about Java, that explains the size of the docker image.
I guess the Raspbian architecture would be 'armhf'? I tried to compile it myself (never had any contact with Go before, just tried the Dockerfile), but only got the error above.

**Comment by bbernhard** [comment]
I think I had some changes locally which I forgot to push - sorry for that. Would be great if you could give it another try :)

**Comment by Larx** [comment]
Thanks. I'll try with the docker image first.

However, I don't quite understand your docker-compose.yml (I am no specialist in docker, however). If I use this file, the container always exits with a "0". I have to map 8080 to another port on my machine, as 8080 is already occupied. 

Using the standard bridged networking, everything seems to work.

Reading the docker docks I get the impression that mapping of ports is not possible when using host networking mode (https://docs.docker.com/network/host/). So maybe this ports-line is simply discarded and it is not possible to change the port with the setup you propose?

**Comment by bbernhard** [comment]
Oh, good catch! I'll change that in the documentation - many thanks for the info :)

**Comment by Larx** [comment]
Would be great to be able to use host networking and a custom port, however. Reading the docs I get the impression that for Linux host networking is the preferred option performance-wise.

**Comment by bbernhard** [comment]
> Would be great to be able to use host networking and a custom port, however. Reading the docs I get the impression that for Linux host networking is the preferred option performance-wise.

I could have a look to see if it's somehow possible, but I _think_ the performance difference is probably neglectable (at least for our usecase). Unfortunately, sending a signal message takes quite a bit of time. I haven't measured it yet, but I guess most of the time is probably spent on starting up the Java VM. :/ If there's demand for that, I guess I could have a look at `signal-cli`'s DBus implementation, that should be a lot faster.

**Comment by Larx** [comment]
You're right, we're not talking about a webserver here ;-). 
So with a running docker image I'm content for now (however, I'd still prefer a single native binary, but as long as it works).
