### ISSUE TITLE
Implement "sendTyping"

### ISSUE THREAD

**Issue by filipre** [bbernhard/signal-cli-rest-api#166]
### Feature Request
[signal-cli](https://github.com/AsamK/signal-cli/wiki/Feature-Matrix) can send (start, stop) a typing indicator by calling "sendTyping". For bot development, it would be very useful to support it because some commands require some time to respond and you can indicate that the bot is doing something.

Best!
René

**Comment by bbernhard** [comment]
I think that information is already returned - at least in JSON-RPC mode.


e.g:

```
< {"envelope":{"source":"+43xxxxx","sourceNumber":"+43xxxxxx","sourceUuid":"6ebd3d4c-304a-455d-92c4-xxxxxxxx","sourceName":"test","sourceDevice":1,"timestamp":1634571611509,"typingMessage":{"action":"STARTED","timestamp":1634571611509}}}
< {"envelope":{"source":"+43xxxxxxxx","sourceNumber":"+43xxxxxxxx","sourceUuid":"6ebd3d4c-304a-455d-92c4-xxxxxxxxxxx,"sourceName":"test","sourceDevice":1,"timestamp":1634571615062,"typingMessage":{"action":"STOPPED","timestamp":1634571615062}}}
```

At the moment, the information is returned in the `receive` endpoint. I guess we could think about moving that information to a dedicated websocket endpoint, but not sure if that makes sense?

**Comment by filipre** [comment]
Works great, thanks! Typing indicator showed up for other people. I will close the issue once the feature is released.
