### ISSUE TITLE
Hassio addon

### ISSUE THREAD

**Issue by haberda** [bbernhard/signal-cli-rest-api#17]
I'd like to make this into a hassio addon. I have made a few addons in the past by dissecting docker images. The only thing holding me back is where the config files are stored in the image. Is there a way to reroute the default location inside the container to /share?

After creating /share/signal-cli folder I tried:
ENTRYPOINT ["main --signal-cli-config /share/signal-cli"]

But I get an error that the location does not exist. Maybe a permissions issue? But they seem right.

I also tried symlinking, I get no error but the folder in the container is empty.

Anyway, thanks for the awesome work!

**Comment by bbernhard** [comment]
Hi,

I haven't tried it yet, but I think you need to pass the parameters to the entrypoint in its exec form:

```ENTRYPOINT ["main", "-signal-cli-config", "/share/signal-cli/"]```

**Comment by haberda** [comment]
Oh, that makes some sense. Also, I got simlinking to work and that's how I'm using it right now.

https://github.com/haberda/hassio_addons/tree/master/signal

I think it should work for everyone. Works on my machine anyway. Thanks!

**Comment by bbernhard** [comment]
> Oh, that makes some sense. Also, I got simlinking to work and that's how I'm using it right now.
> 
> https://github.com/haberda/hassio_addons/tree/master/signal
> 
> I think it should work for everyone. Works on my machine anyway. Thanks!

Very cool :muscle: 

Many thanks for sharing!

**Comment by aladin2000** [comment]
> > Oh, that makes some sense. Also, I got simlinking to work and that's how I'm using it right now.
> > https://github.com/haberda/hassio_addons/tree/master/signal
> > I think it should work for everyone. Works on my machine anyway. Thanks!
> 
> Very cool 💪
> 
> Many thanks for sharing!


Link is not available ( 404 error)
