### ISSUE TITLE
Messages send to groups only appear to one member

### ISSUE THREAD

**Issue by HrGaertner** [bbernhard/signal-cli-rest-api#173]
Hello,
i am trying to make a rss bot with this nice project and send the retrieved messages and pictures to a group.
This works quite fine except that only I am seeing the messages (I do not no if this matters I am the creator and only admin currently)

It is a v2 group. I told some people to write to the bot in hope that it would work as soon as they hat contact to the bot. That did not work

I do not know if this has something to do with this project, but i never heard of this problem.

Does somebody has a idea what is happening and how i could correct it? Thanks a lot!

**Comment by HrGaertner** [comment]
I already do the automatic receiving... I did not use json-rpc because i thought there must be some reason why it is not "normal" although it is slower... But that should not change the behaviour of the seeing/not seeing of messages in a group or?

**Comment by bbernhard** [comment]
Have you tried calling the `receive` endpoint manually after everybody joined the group? Afaik `receive` does some sort of synching, so maybe your signal instance is not aware that the group already consists of members.

**Comment by HrGaertner** [comment]
Ok, that did the trick. I am sorry for opening this issue. It makes totally sense since the signal instance has to encrypt the message to each participant differently.

Thanks a lot!
