### ISSUE TITLE
/v1/groups/{number}/{groupid}/block endpoint does not do anything (JSON-RPC)

### ISSUE THREAD

**Issue by thielenf** [bbernhard/signal-cli-rest-api#177]
### The problem

This is the debug log:
```
time="2021-11-01T19:24:49+01:00" level=debug msg="full command: {\"jsonrpc\":\"2.0\",\"method\":\"updateGroup\",\"id\":\"983f3b8b-13f0-48f7-a771-8db6329922f6\",\"params\":{\"groupId\":\"<id>\"}}"
[GIN] 2021/11/01 - 19:24:49 | 204 |    4.440421ms |  192.168.X.Y | POST     "/v1/groups/+49<number>/group.<id>/block"
```

This looks like an updateGroup call without any meaningful parameters, and indeed the group is not blocked afterwards:
```
  {
    "name": "Testgruppe X",
    "id": "group.<id>",
    "internal_id": "<id>",
    "members": [
      "+49<number 1>",
      "+49<number 2>"
    ],
    "blocked": false,
    "pending_invites": [],
    "pending_requests": [],
    "invite_link": ""
  },
```

To my understanding, [this](https://github.com/AsamK/signal-cli/blob/master/run_tests.sh#L106) is what the command should look like. I tried to test this, but signal-cli told me "This command doesn't work on linked devices." so it looks like I can't verify on my host.

Writing this out made me notice that the command was never gonna work via the API in the first place (as it is a linked device). However, the debug log still looks wrong.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

armv7

**Comment by bbernhard** [comment]
Many thanks for the bug report, should be fixed now :)

**Comment by bbernhard** [comment]
should be fixed with the latest released version
