### ISSUE TITLE
Retrieving groups produces "json: cannot unmarshal object into Go struct field SignalCliGroupEntry.pendingMembers of type string" error

### ISSUE THREAD

**Issue by kalbfuss** [bbernhard/signal-cli-rest-api#178]
### The problem

I have registered a fresh Signal account on an Android tablet and linked the signal-cli-rest-api docker cointainer via the /v1/qrcodelink afterwards. Receiving messages works. Sending messages to phone numbers and groups works (as long as I know the group id). 

Retrieving groups via the following command produces an error:
$ curl -X GET -H "Content-Type: application/json" 'http://localhost:8080/v1/groups/<phone number>'
{"error":"json: cannot unmarshal object into Go struct field SignalCliGroupEntry.pendingMembers of type string"}

Means I am unable to retrieve ids of those groups, which I joined via the Android device. 
I have tested with latest, latest-dev and version 0.52. Same result with all images.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by kalbfuss** [comment]
Tested with version 0.42. There it seems to work.

**Comment by skulumani** [comment]
@kalbfuss I'm receiving this message as well. Do you mean with version 0.52 you don't see it?

**Comment by bbernhard** [comment]
Downgrading to an older version is something that I wouldn't recommend. Unfortunately, I can't reproduce the issue. If you want to help troubleshooting the problem, please have a look here: https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md. Please post the obfuscated(!) output of signal-cli here (or create a new issue for that).

**Comment by skulumani** [comment]
Thanks! Will collect more information and create another issue

**Comment by kalbfuss** [comment]
> @kalbfuss I'm receiving this message as well. Do you mean with version 0.52 you don't see it?
No. Version 0.52 still produces the error. Version 0.42 seemed to work fine. What I did as a workaround is to downgrade temporarily to 0.42, retrieve the group IDs I was interested in, and reverted back to latest afterwards.
