### ISSUE TITLE
Issues on armv7 systems

### ISSUE THREAD

**Issue by bbernhard** [bbernhard/signal-cli-rest-api#181]
### The problem

signal-cli-rest-api    | + service supervisor start
signal-cli-rest-api    | Fatal Python error: pyinit_main: can't initialize time
signal-cli-rest-api    | Python runtime state: core initialized
signal-cli-rest-api    | PermissionError: [Errno 1] Operation not permitted

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

armv7

**Comment by bbernhard** [comment]
fixed by upgrading host system to debian buster and installing the right libseccomp2 version (https://packages.debian.org/buster-backports/libseccomp2)

**Comment by copart** [comment]
> fixed by upgrading host system to debian buster and installing the right libseccomp2 version (https://packages.debian.org/buster-backports/libseccomp2)

What do you mean by "the right version"

is using 

```apt-get install libseccomp2```

get you the wrong version?

**Comment by copart** [comment]
nevermind, found it:

for another finding their way here:
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/

Basically
```
# Get signing keys to verify the new packages, otherwise they will not install
rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138

# Add the Buster backport repository to apt sources.list
rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

rpi ~$ sudo apt update
rpi ~$ sudo apt install libseccomp2 -t buster-backports
```
