### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by stack74** [bbernhard/signal-cli-rest-api#183]
### The problem

I have 2 signal numbers running with jsonrpc in a single container. After sending / receiving messages this happens very often:

I am not a go expert, but it looks like we might need the following:
https://medium.com/swlh/handle-concurrency-in-gorilla-web-sockets-ade4d06acd9c
```
signal-cli-rest-api-jsonrpc_1  | panic: concurrent write to websocket connection
signal-cli-rest-api-jsonrpc_1  |
signal-cli-rest-api-jsonrpc_1  | goroutine 57 [running]:
signal-cli-rest-api-jsonrpc_1  | github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000505740, 0x1, {0x18cc058, 0xc0005882a0, 0xc000588358})
signal-cli-rest-api-jsonrpc_1  |        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x52b
signal-cli-rest-api-jsonrpc_1  | github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0000e8420, 0x0, {0x18cc058, 0x0, 0x0})
signal-cli-rest-api-jsonrpc_1  |        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:763 +0x13c
signal-cli-rest-api-jsonrpc_1  | github.com/bbernhard/signal-cli-rest-api/api.wsPing(0x0)
signal-cli-rest-api-jsonrpc_1  |        /tmp/signal-cli-rest-api-src/api/api.go:332 +0x65
signal-cli-rest-api-jsonrpc_1  | created by github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive
signal-cli-rest-api-jsonrpc_1  |        /tmp/signal-cli-rest-api-src/api/api.go:360 +0x1d1
signalclirestapijsonrpc_signal-cli-rest-api-jsonrpc_1 exited with code 2
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Thanks for creating an issue for that - that definitely looks like a bug. I haven't tested the JSON-RPC mode with multiple numbers yet, but I'll try to find an additional number I can use to reproduce the issue.

**Comment by stack74** [comment]
As I removed the `go wsPing` line, the error didnt occur anymore. Seems like a problem with the ping causing the panic

**Comment by bbernhard** [comment]
couldn't reproduce anymore.
