### ISSUE TITLE
Cannot receive Messages

### ISSUE THREAD

**Issue by bruno00o** [bbernhard/signal-cli-rest-api#184]
### The problem

Hi, first of all, thanks for your amazing work ! I used to use signal-cli on my raspberry 3 pi but sending messages was starting to take too long. I'm an absolute beginner with docker but I managed to install the signal-cli-rest-api with docker-compose and now I'm able to send messages in less than a second !

**Problem :** I cannot receive messages

Here is the error : 
`Bad Request
{"error":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}`

So, I wanted to know if there is a solution to my problem.
Thanks!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

armv7

**Comment by bbernhard** [comment]
In JSON-RPC mode, it's not possible to receive messages via the `GET` request. Instead you need to establish a websocket connection. This can e.g be done with [wscat](https://github.com/websockets/wscat) like this: `wscat -c 127.0.0.1:8080/v1/receive/<your registered signal number> --show-ping-pong --slash`

**Comment by bruno00o** [comment]
Thanks! It worked!
