### ISSUE TITLE
OTP verification issue on registering phone number

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#188]
### The problem

We created a signal docker to register a new phone number

After creating the docker we are able to send OTP for the phone number, using
curl -X POST -H "Content-Type: application/json" --data '{"captcha": "CAPTCHA"}' 'DOCKER_URL/v1/register/+PHONE_NUMBER' -u AUTH_KEY:AUTH_SECRET

While verifying the OTP using curl -X POST -H "Content-Type: application/json" 'DOCKER_URL/v1/register/+PHONE_NUMBER/verify/OTP' -u AUTH_KEY:AUTH_SECRET, we are getting following error in the API

{"error":"Verify error: Authorization failed!\n"}, {"error":"Authorization failed, was the number registered elsewhere?\n"}

Can you please help us to solve the issue

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
you can try to the delete the `signal-cli` config from the filesystem and start over.

**Comment by jyothisjose** [comment]
We are running it is on aws eks setup. Can you please let uk know how to delete signal-cli

**Comment by jyothisjose** [comment]
@bbernhard Can you please let us know how to delete signal-cli, we are using aws eks setup

**Comment by bbernhard** [comment]
you need to remove the folder from the filesystem that you've mounted in the `docker-compose.yml` file.

**Comment by jyothisjose** [comment]
@bbernhard we are getting same error {"error":"Verify error: Authorization failed!\n"}, {"error":"Authorization failed, was the number registered elsewhere?\n"} after removing the filesystem

**Comment by jyothisjose** [comment]
@bbernhard 
We have tried signal-cli from inside the docker container, the result is still authorization failed.
The command we tried is
**signal-cli -u PHONE_NUMBER_WITH_COUNTRY_CODE verify OTP**
The result we got is
**Verify error: Authorization failed!**

**Comment by bbernhard** [comment]
As you haven't checked the checkbox: Are you using the latest version?
