### ISSUE TITLE
Link device API fails to link the device

### ISSUE THREAD

**Issue by Shreyas-R** [bbernhard/signal-cli-rest-api#190]
When I tried to link my existing number to the signal cli running in a docker container using link device API, every-time after the QR scan, signal android app gave "No device found" or "Network error" toast and was failing to link the number. After searching through the internet I found similar issue reported here within another issue mentioned in below link:
https://github.com/bbernhard/signal-cli-rest-api/issues/95#issuecomment-780006579

Since only workaround was given there which takes a while to search and apply, I'm raising this issue here again so it gets fixed and gets the link device API working.

**Comment by Shreyas-R** [comment]
I have consolidated the workaround below for anyone stuck with same issue. Thanks to the original workaround given [here](https://github.com/bbernhard/signal-cli-rest-api/issues/95#issuecomment-780084593).

Inside docker container:
1. Access docker signal-cli-rest-api container through a terminal console with root privileges
2. Run `apt update` followed by `apt install qrencode` commands in the console
3. Run `su signal-api` command
4. Run following command and wait for it to complete,
`signal-cli --config /home/.local/share/signal-cli link -n <device_name> | xargs -l qrencode -o /tmp/qrcode.png --level=H -v 10 & while [ ! -f /tmp/qrcode.png ]; do sleep 1; done;`

Without closing the terminal console inside the docker container, follow further steps below,

Inside host machine (Outside docker container):
1. Open a terminal with root privileges and run the following command,
`sudo docker cp <container_id>:/tmp/qrcode.png /home/<user_name>/Desktop/qrcode.png`
2. Open the newly created qrcode.png file in your desktop with any image viewer app in GUI and scan through Signal app.

NOTE: Make sure you scan the newly created QR code before 
> Link request error: Connection closed!
status shows up inside the terminal console that you are running inside docker container.

**Comment by bbernhard** [comment]
should be fixed with the next version
