### ISSUE TITLE
Captcha registration without result or answer.

### ISSUE THREAD

**Issue by maxkr2** [bbernhard/signal-cli-rest-api#191]
Hi,
I am running HA on a Raspberry with Signal Messenger AddOn in Version 0.54.1 but I am not able to register a landline number with captcha on command line via:
curl -X POST -H "Content-Type: application/json" --data '{"captcha":"**[captcha-string]**", "use_voice": false}' 'http://127.0.0.1:8080/v1/register/[number]'

**[captcha-string]** is generated from another client and the result is pasted into the SSH-console on my Raspberry.
It takes a while an comand prompt is available but without any reply.

If I try to create a group with:
curl -X POST -H "Content-Type: application/json" -d '{"name": "[group name]"...

I get an error message, that number is not registered.
{"error":"User **[number]** is not registered.\n"}

Hope you can help.

Regards,
Max

**Comment by bbernhard** [comment]
Registering a number is a two step process. If you register with a mobile number you will receive a SMS for verification. For landline numbers you probably need to set `"use_voice": true`, which results in a phone call where you get the verification code. Aftee that, you need to complete the registration with the `verify` REST API endpoint.

**Comment by maxkr2** [comment]
Thank you bbernhard,
I had to use `"use_voice": true` in my first registering attempt and than was asked for captcha (I answered again with `"use_voice": true`) and it worked now as expected: Got a phone call with verfication number that I verfied successfully.
