### ISSUE TITLE
problem running the latest container with json-rpc mode in aws ubuntu 20.4

### ISSUE THREAD

**Issue by KY-7** [bbernhard/signal-cli-rest-api#193]
### The problem

Hi,

I'm having a problem when trying the latest release on an aws ubuntu 20.04 and mode set to json-rpc.
Please note that it works well when mode is set to normal or native.

Did I miss any specific setting when mode is json-rpc please?

The container exits immediately with following error:
------------------------------------------------------------------------------------------------------------------------------------------------
+ set -e
+ [ -z /home/.local/share/signal-cli ]
+ chown 1000:1000 -R /home/.local/share/signal-cli
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 37
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37
+ [ json-rpc = json-rpc ]
+ /usr/bin/jsonrpc2-helper
time="2022-01-08T14:56:40Z" level=fatal msg="Couldn't read contents of /home/.local/share/signal-cli/data. Is your phone number properly registered? Please be aware that registering a phone number only works in normal/native mode and is currently not supported in json-rpc mode!"
------------------------------------------------------------------------------------------------------------------------------------------------

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you registered your number with the `register` and `verify` endpoint before switching to the `json-rpc` mode?

**Comment by KY-7** [comment]
As suggested, registering a phone number with native or normal mode then switching to json-rpc did it.
Now, the container seems to be working. Thanks!

**Comment by alastairayliffe** [comment]
Hey @KY-7, did you have any trouble receiving a txt message to register the number (prior to moving to JSON-RPC Mode)? I'm trying to register/verify and as you did above, but am unable to get the SMS message through... see #278 

Thanks,
