### ISSUE TITLE
/tmp cleanup

### ISSUE THREAD

**Issue by sirjeannot** [bbernhard/signal-cli-rest-api#195]
Hello,

after sustained usage to send notifications with images, I ended up noticing the /tmp directory is filled with .so files, which are former attachments sent through signal-cli.
Would it be possible to include some way to clean this up, even through the API? there is no shell in the container so I have to manually clean the /tmp directory in /var/lib/docker/overlay2/<overlay_hash>/merged/tmp.

As usual, thanks for this tool.
ps: I'm using an old version of signal-cli-rest-api (0.8.1) as it just won't run with any newer version (takes more than a minutes to startup)
Thanks!

**Comment by bbernhard** [comment]
I vaguely remember that there was an issue a while ago similar to this one. So, maybe its already fixed in the new versions.

> ps: I'm using an old version of signal-cli-rest-api (0.8.1) as it just won't run with any newer version (takes more than a minutes to startup)

Which architecture does your host system have? Have you tried the `json-rpc` mode?

**Comment by sirjeannot** [comment]
armv7l :)
I'll check it out the json-rpc build, thank you. :)
