### ISSUE TITLE
changing mode without restarting the docker container

### ISSUE THREAD

**Issue by KY-7** [bbernhard/signal-cli-rest-api#196]
Hello,

Using json-rpc mode requires that the account was already registered. 
However, the registration can only be done when the container's mode set to native or normal.

That means a docker restart is required in order to reset the mode to json-rpc unless I missed something.

This unfortunately makes it harder to do everything automatically via REST API calls without manual intervention.

Is there a way to avoid the restart please?

**Comment by KY-7** [comment]
Thanks for the reply!
Actually the idea is take advantage of the json-rpc mode since it allows listening for messages sent to the registered account.
Could you confirm please the following: could we register several accounts using the same container 
and if so, does all registrations require native/normal mode or only the first one?

**Comment by bbernhard** [comment]
Currently `signal-cli` doesn't support `register` and `verify` with the `json-rpc` mode (see https://github.com/AsamK/signal-cli/wiki/Feature-Matrix) - so all the accounts need to be registered with normal/native mode first.

In theory multiple accounts within the same docker container should be possible. Unfortunately, there still seems to be a bug (see https://github.com/bbernhard/signal-cli-rest-api/issues/183). It's on my todo list to look into that, but I haven't found time to do so.
