### ISSUE TITLE
First messages get lost when receiving via WebSocket

### ISSUE THREAD

**Issue by SamuelBlickle** [bbernhard/signal-cli-rest-api#198]
### The problem

Hi everyone!

As I am unsure if the following behavior is a problem specific to the signal-cli api or not, please feel free to close this issue if my question is not related to this project.

I set up the signal-cli in a Docker Container and enabled json-rpc mode. Sending messages works like a charm, receiving messages does also work fine, at least to some degree.
I noticed a kind of strange behavior that I can not explain to myself. Therefore I would be happy if someone could have a look at the following description of my problem:

I wrote a simple Python program, that utilizes the WebSocket-client library to establish a connection to the receive endpoint and prints all incoming messages. However, the exact code of it seems to be irrelevant, as the same thing occurs when I establish a connection via wscat.
When I start my receiving ws client, it misses the first x messages that are being sent to the signal-cli. All messages after the xth message get delivered without any problem.
Here's how the number x of messages that get lost is determined: When I start my client, receive some messages, stop my client, and then start it up again, x is 1. Therefore I need to send 1 message to the signal-cli that gets lost, then I can continue to receive everything that is incoming as it should be. However, if I do not send a message to the signal-cli in this case and instead stop and restart my ws client again, x is equal to 2 now. The number of lost messages increases for every time a receiving client gets started and stopped, when no message gets sent to the cli while the client is running. 

It seems to be the case, that somehow all established connections of a WebSocket client get "stacked" inside the signal-cli API and for every incoming message, one of these (dead) connections gets removed from the stack, until finally the current (valid) ws client connection is on top and gets the messages delivered.

Is somebody able to make any sense of this kind of behavior? I'd be very grateful if someone could explain to me what's going on here and maybe how to avoid this problem.

Thank you very much! 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Unfortunately I can't reproduce the issue. 

This is what I did:

* started docker container in `json-rpc` mode
* connect with `wscat` to the receive endpoint
* send message from my smartphone to my registered signal-cli number
* stop `wscat` 
* connect again with `wscat` to the receive endpoint
* send another message from my smartphone to my registered signal-cli number

But no matter how often I disconnect/connect, `wscat`, I am not losing any messages.

Are you doing something different?

btw: you could also try this image here: `bbernhard/signal-cli-rest-api:0.88-dev`. It contains a bunch of fixes and updates signal-cli to v0.10.0

**Comment by SamuelBlickle** [comment]
Hi @bbernhard thanks for your quick reply!
Unfortunately the  0.88-dev has the same problem for me.

I do run the cli-api behind a Caddy 2 reverse-proxy, but there isn't anything sketchy going on. Just plain reverse-proxying...

I just found this error message, being emitted when a message gets lost:
```level=error msg="Couldn't write message: websocket: close sent"```

**Comment by bbernhard** [comment]
Could you please try `bbernhard/signal-cli-rest-api:0.89-dev`

**Comment by SamuelBlickle** [comment]
`signal-cli-rest-api:0.89-dev` works like a charm!
Thank you so much for the quick fix.
