### ISSUE TITLE
exited with code 0

### ISSUE THREAD

**Issue by nagyrobi** [bbernhard/signal-cli-rest-api#2]
Hi! Please help...
All I get is `signal_messenger_signal-cli-rest-api_1 exited with code 0` immediately after starting with `docker-compose up`. 
Can you please help me in determining what's going wromng?

**Comment by bbernhard** [comment]
I would need a few more informations in order to help you:

* Did you build the docker image manually or have you pulled the image from dockerhub?
* What 's the host systems architecture? (x86-64, i386,..?)
* Could you maybe share the content of your `docker-compose.yml` file?
* Which host port are you using? 8080? Please check that the port is still available and not taken by another service.

**Comment by lach1** [comment]
I had the same error. I had no problem anymore, when I removed following line from docker-compose.yml:

`network_mode: "host"`

Why is host network mode needed actually?

**Comment by bbernhard** [comment]
Do you have a service running on your host system which occupies port 8080? That would explain why the docker container fails to start. 


You don't necessarily need the `network_mode: "host"` setting in your `docker-compose.yml` file. However, personally, I find it convenient to map the internal docker container's REST API listening port to some port on the host system. This makes it way easier to access the REST API from within your LAN via cURL. But docker also offers other network modes (see https://docs.docker.com/network/ for details). It mainly depends on your (network) infrastructure and your docker knowledge.

**Comment by nagyrobi** [comment]
I had the same issue, on the same machine I have a different service occupying port 8080. I tried changing port numbers without success. I worked around by creating a fresh new VM just for this.
However I'd love to know how to move the port from 8080 to something different like 8081.

**Comment by bbernhard** [comment]
just change it like that in the `docker-compose.yml`:

```
ports:
      - "8081:8080" #map host port 8081 to docker port 8080
```

(don't forget to change the port also in your HomeAssistant's `configuration.yaml` to `8081`)

**Comment by nagyrobi** [comment]
I did try to change to "8081:8080" but it didn't work for some reason. That was an old 16.04 Ubuntu anyway, it's still in use for something else, I don't mind running a new VM for this atm.

**Comment by joekerna** [comment]
I ran into the same issue. Port 8080 is occupied and I tried to change it to 8081 as well.
When running `docker-compose up` I get the following:

```
Recreating signal-cli-rest-api_signal-cli-rest-api_1 ... done
Attaching to signal-cli-rest-api_signal-cli-rest-api_1
signal-cli-rest-api_1  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
signal-cli-rest-api_1  | 
signal-cli-rest-api_1  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
signal-cli-rest-api_1  |  - using env:	export GIN_MODE=release
signal-cli-rest-api_1  |  - using code:	gin.SetMode(gin.ReleaseMode)
signal-cli-rest-api_1  | 
signal-cli-rest-api_1  | time="2020-09-21T18:09:31Z" level=info msg="Started Signal Messenger REST API"
signal-cli-rest-api_1  | [GIN-debug] GET    /v1/about                 --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).About-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] POST   /v1/register/:number      --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).RegisterNumber-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] POST   /v1/register/:number/verify/:token --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).VerifyRegisteredNumber-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] POST   /v1/send                  --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).Send-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] GET    /v1/receive/:number       --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).Receive-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] POST   /v1/groups/:number        --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).CreateGroup-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] GET    /v1/groups/:number        --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).GetGroups-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] DELETE /v1/groups/:number/:groupid --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).DeleteGroup-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] GET    /v1/qrcodelink            --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).GetQrCodeLink-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] POST   /v2/send                  --> github.com/bbernhard/signal-cli-rest-api/api.(*Api).SendV2-fm (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (3 handlers)
signal-cli-rest-api_1  | [GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
signal-cli-rest-api_1  | [GIN-debug] Listening and serving HTTP on :8080
signal-cli-rest-api_1  | [GIN-debug] [ERROR] listen tcp :8080: bind: address already in use
signal-cli-rest-api_signal-cli-rest-api_1 exited with code 0
```

Shoudn't it listen to port 8081?
My `docker-compose.yml` is

```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    restart: always
    ports:
       - "8081:8080" # map docker port 8080 to host port 8081.
    network_mode: "host"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" # map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
```

**Comment by bbernhard** [comment]
Unfortunately, it's not possible to use `network_mode: "host"` with port mapping. see: https://docs.docker.com/network/host/

Please try without that, if you want to use port mapping. (I'll also update the example, as it's a bit misleading that way :). And in most cases the host network mode shouldn't be needed anyway.)

**Comment by joekerna** [comment]
Thanks, that is working!
I don't know what `network_mode: "host"` does so I didn't want to touch it at first.
