### ISSUE TITLE
Native Mode causes 'RuntimeException: Field storyContext_ for org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage not found'

### ISSUE THREAD

**Issue by bentolor** [bbernhard/signal-cli-rest-api#201]
### The problem

Thanks for this helpful container for Homeassistant Signal Integration!

To circumvent high latency for sending messages, I tried to use native mode. I stumbled over two issues

## Issue 1: Documentation
The README is talking about modes, but I found nowhere a clue what the default behavior is nor on how to understand which mode is active or how to control the mode.

Eventually I started to search the repo for `/usr/bin/signal-cli-native` and reading the Go code to understand how it is working. 

A note hinting that you need to set/pass a `MODE` on container creation as well as a hint on startup on the current mode (`Started Signal Messenger REST API is working in XXX mode`) would be great.

## Issue 2: Native mode not working

Setting `MODE=native` leads to a non-working installation returning:

{"error":"java.lang.RuntimeException: Field storyContext_ for org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage not found. Known fields are [private int org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.bitField0_, private java.lang.String org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.body_, private com.google.protobuf.Internal$ProtobufList org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.attachments_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$GroupContext org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.group_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$GroupContextV2 org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.groupV2_, private int org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.flags_, private int org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.expireTimer_, private com.google.protobuf.ByteString org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.profileKey_, private long org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.timestamp_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage$Quote org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.quote_, private com.google.protobuf.Internal$ProtobufList org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.contact_, private com.google.protobuf.Internal$ProtobufList org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.preview_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage$Sticker org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.sticker_, private int org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.requiredProtocolVersion_, private boolean org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.isViewOnce_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage$Reaction org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.reaction_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage$Delete org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.delete_, private com.google.protobuf.Internal$ProtobufList org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.bodyRanges_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage$GroupCallUpdate org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.groupCallUpdate_, private org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage$Payment org.whispersystems.signalservice.internal.push.SignalServiceProtos$DataMessage.payment_]\n\tat com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:608)\n\tat com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:502)\n\tat com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221)\n\tat com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)\n\tat com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)\n\tat com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)\n\tat com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)\n\tat com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:171)\n\tat com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:391)\n\tat com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:399)\n\tat org.whispersystems.signalservice.internal.push.SignalServiceProtos$Content$Builder.setDataMessage(SignalServiceProtos.java:1998)\n\tat org.whispersystems.signalservice.api.SignalServiceMessageSender.createMessageContent(SignalServiceMessageSender.java:996)\n\tat org.whispersystems.signalservice.api.SignalServiceMessageSender.sendDataMessage(SignalServiceMessageSender.java:341)\n\tat org.asamk.signal.manager.helper.SendHelper.lambda$sendMessage$12(SendHelper.java:466)\n\tat org.asamk.signal.manager.helper.SendHelper.handleSendMessage(SendHelper.java:479)\n\tat org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:465)\n\tat org.asamk.signal.manager.helper.SendHelper.sendMessage(SendHelper.java:77)\n\tat org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:407)\n\tat org.asamk.signal.manager.ManagerImpl.sendMessage(ManagerImpl.java:508)\n\tat org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:149)\n\tat org.asamk.signal.App.handleLocalCommand(App.java:289)\n\tat org.asamk.signal.App.init(App.java:208)\n\tat org.asamk.signal.Main.main(Main.java:53)\n"}⏎                   

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Regarding the error: I _think_ that should be fixed with the latest signal-cli version. The latest signal-cli-rest-api image still uses signal-cli 0.10.0, so I'll later bump the version and release a new image for testing.

Regarding the documentation issue: That's something where I would really appreciate PRs. As a developer it's not always obvious which parts are poorly documented and need improvement. So any PR is highly appreciated!

Regarding the log line: That's a good idea, I'll add that 👍

**Comment by bentolor** [comment]
Thanks. Fair enough. Created #204

Actually, the error is not fixed in `signal-cli` version 10.2. I already built the latest version locally: I share my configuration files with a local `signal-cli` install and was running into an `Database has been updated by a newer signal-cli version` error. Therefore I'm already using builds of the current versions locally.

**Comment by bbernhard** [comment]
Have you tried signal-cli v0.10.3 also? (haven't looked through the changelog yet, so not not sure if anything in that regard was fixed with 0.10.3)

You could enable the [Debug Mode](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) which prints out the exact `signal-cli` command that was used. This gives you the possibility to connect to the running docker container and invoke `signal-cli` yourself (without the API layer inbetween). But I am pretty sure that it's an upstream issue, so there's probably not much I can do. 

Have you considered using the JSON-RPC mode instead? It's even faster than the native mode  :)
