### ISSUE TITLE
capture problem?

### ISSUE THREAD

**Issue by hs6666** [bbernhard/signal-cli-rest-api#202]
### The problem

hi, just a newbie to programming, just trying to set this up for notifications for my uptime-kuma app

docker container is up and running and i get the capture message after trying to run the curl command

in firefox browser i open up developer console and goto https://signalcaptchas.org/registration/generate.html

i complete the capture that comes up, but notihng shows in in "inspector tab" or console tab" matching the token i need to paste into the new curl command

instead i get a popup asking which app i want to open link in, with the option showing for the signal app installed, which just opens up the signal app?

just wondering were i'm going wrong?

Thanks

Harry
 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you tried a different browser? (e.g Chrome) With Firefox some users reported that they had problems too. You might also try opening the URL in a private tab.

**Comment by RaxCore** [comment]
After answering the captcha you should find a log like this in the console tab while your browserwindow remains blank:

"signalcaptcha://03AGdBq25W9XOz7P3oh0sfAvspLTIVA4ZFc5gRa1T9Z-OgvRNguvVnCn5WILRifwfHZOYkiFUVhg7KSrPrnoUQHKve6cpU_vihrFWg4Uv77w7dtyYItdhPwtddya03fSi3uaboY7HhuKPKDxMPNyswGtIW7vJA_BuQMRhr5RQGj16K9aqKrYI9lav0RR8Mw1yJbHzUldnTIytrjn7D92iLWBb_BBpbNoDhhW0qzIPHZLzTIE1XgaKC0arcNjJzmEVBrnQZEORPuQfbs49oCB_eeXBzbB-pFTnn9HD-4N-A0lW1KpHUpqgFt_G2haIfweko9jbYNDepEKJFNXSg-3l6zgeLPKCEE-Uq3NnYNJAJ4ViNkC9Rf2xxO8PrR9E6oxFqUJHTQge8vzeJmfdZVD5Ic-sIvbnopH18nYrpeJdBKMljiVF0iEHn8oa12oRPC8g4H7VjcDISsq0zZYA1xD-76E_25TSTbzZJOlm_Rn0hPF18a4bP9qKk5kDqz6Ac-gjQ0Iim3hd3tqebK5UdZZMIdqKlJHL-Uo_DcA"

<img width="406" alt="2022-02-05 20_39_03-Mozilla Firefox" src="https://user-images.githubusercontent.com/96478711/152656395-79996947-92ff-49d0-aa97-6245091b45d4.png">

(tested with firefox 96.0.3/64bit)

**Comment by RaxCore** [comment]
Let me help you further with my final command line. Have a look at the beginning as the captcha code starts **behind** _"signalcaptcha://"_

curl -X POST -H "Content-Type: application/json" -d '{"captcha":"03AGdBq25W9XOz7P3oh0sfAvspLTIVA4ZFc5gRa1T9Z-OgvRNguvVnCn5WILRifwfHZOYkiFUVhg7KSrPrnoUQHKve6cpU_vihrFWg4Uv77w7dtyYItdhPwtddya03fSi3uaboY7HhuKPKDxMPNyswGtIW7vJA_BuQMRhr5RQGj16K9aqKrYI9lav0RR8Mw1yJbHzUldnTIytrjn7D92iLWBb_BBpbNoDhhW0qzIPHZLzTIE1XgaKC0arcNjJzmEVBrnQZEORPuQfbs49oCB_eeXBzbB-pFTnn9HD-4N-A0lW1KpHUpqgFt_G2haIfweko9jbYNDepEKJFNXSg-3l6zgeLPKCEE-Uq3NnYNJAJ4ViNkC9Rf2xxO8PrR9E6oxFqUJHTQge8vzeJmfdZVD5Ic-sIvbnopH18nYrpeJdBKMljiVF0iEHn8oa12oRPC8g4H7VjcDISsq0zZYA1xD-76E_25TSTbzZJOlm_Rn0hPF18a4bP9qKk5kDqz6Ac-gjQ0Iim3hd3tqebK5UdZZMIdqKlJHL-Uo_DcA", "use_voice": true}' 'http://{my_ip-address}:8080/v1/register/+{my_phone number}'

**Comment by hs6666** [comment]
hi, as advised i used chrome browser, but noticed that i am getting the following error when loading the captcha page ....

![Capture](https://user-images.githubusercontent.com/28625894/152672960-c7ef869e-fdca-4620-b68d-53d6a68bcbd7.JPG)

seems to give an ssl error?

thanks

**Comment by asad-awadia** [comment]
@RaxCore I am not seeing the captcha token in the dev console either - checked on botj firefox and chrome

**Comment by asad-awadia** [comment]
I just get the "open in application" window since I have signal installed on my laptop

**Comment by asad-awadia** [comment]
@hs6666 rename this to captcha problem not capture

**Comment by dashdrum** [comment]
I'm seeing the same issue.  
After uninstalling the Signal app and trying the registration/generate link in a Chrome incognito window, I see a "Failed to launch" error complaining that "the scheme has no registered handler" which included a short key value.
Next, I saved the error message in the console to a .log file (by right-clicking on the error)
Open this file in a text editor to see the FULL captcha key after 'signalcaptcha://'
Paste just the key (not the trailing apostrophe) into the captcha curl command and send it.
It worked!!

Note that you have to be quick, the key expires after just a short time.  Took me two tries to make it work.

Another note: I don't know if it is required to delete the Signal app first, just what I did.

**Comment by dashdrum** [comment]
Of course, after all of what I documented above, the API is telling me my number is not registered, so I don't know...

**Comment by Issr4k** [comment]
This worked for me. My captcha was like this: 'signal-hcaptcha.502b.........'
And i was a little confused if 'signal-hcaptcha' should stand there at the start too.
But yes... as @dashdrum said: everything after 'signalcaptcha://' has to be send.

Thx!!!
