### ISSUE TITLE
Changing / Adding group members

### ISSUE THREAD

**Issue by ronaldt80** [bbernhard/signal-cli-rest-api#210]
### The problem

I have created groups through the signal api with multiple members. I am able to leave and then rejoin this group myself (eg. the number associated with the API); I'm currently unable to add/remove members and or change group settings for groups created through the API. Looking at the upstream this should be feasible; any tips?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
Could you please temporarily switch back to the `normal` mode and check whether it works there (just to see if it is related to the json-rpc mode or an issue in general)

**Comment by ronaldt80** [comment]
Which API command should I give?

**Comment by bbernhard** [comment]
Sorry, my mistake. I could have sworn that we already have an endpoint to update existing groups. But looks like it's still missing. But it shouldn't be hard too hard to add it - I'll have a look

**Comment by ronaldt80** [comment]
@bbernhard let me know if there is anything I can test. Would not know where to start on a PR but testing I can do.

**Comment by bbernhard** [comment]
> @bbernhard let me know if there is anything I can test. Would not know where to start on a PR but testing I can do.

Thanks :+1: 

I just implemented the functionality. I'll do some alpha testing in the next days and then release an image for testing.
