### ISSUE TITLE
Link device API successful but device not added to 'Liked devices' list.

### ISSUE THREAD

**Issue by Yersi88** [bbernhard/signal-cli-rest-api#213]
### The problem

I generated QR code with this command: http://192.168.100.156:8080/v1/qrcodelink?device_name=homeass
Scanned it with the app.
Got message: Device approved!
However, the device does not show up in the 'linked devices' section of the mobile app.
And when I try to send notification with HA addon, nothing happens.

What could I do to fix this ?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by Yersi88** [comment]
I did: curl -X POST -H "Content-Type: application/json" -d '{"logging": {"level": "debug"}}' 'http://127.0.0.1:8080/v1/configuration'

And then tried to link with QR code again:
```
+ set -e
+ [ -z /data ]
+ chown 1000:1000 -R /data
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ [ normal = json-rpc ]
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/data
time="2022-02-11T18:58:28Z" level=info msg="Started Signal Messenger REST API"
[GIN] 2022/02/11 - 19:02:01 | 204 |    1.513736ms | 192.168.100.117 | POST     "/v1/configuration"
time="2022-02-11T19:02:18Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
time="2022-02-11T19:02:18Z" level=debug msg="*) docker exec -it b356cfb27b974e2a0bc78c701b903344b0580a2bc16f6a40356ed599aebbd608 /bin/bash"
time="2022-02-11T19:02:18Z" level=debug msg="*) su signal-api"
time="2022-02-11T19:02:18Z" level=debug msg="*) signal-cli --config /data link -n homeass"
```

app says device approved but not in the list in phone app.

**Comment by jarrah31** [comment]
Hello @bbernhard, I'm a new user to your project and I appear to have the same problem on my first attempt to register signal-cli... 

When I scan the code and press "Link New Device", the Signal app doesn't give me any messages and just returns to the "Linked Devices" page. No new device appears. If I attempt to scan the same code again, it says "Linking Device Failed, Invalid response from service", so I presume the first scan worked ok.

Device: iPhone 12 Pro
iOS: 15.1.1
Signal App version: 5.30.0.11
signal-cli-rest-api version: 0.56

Docker compose config:
```
  signal:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal
    hostname: signal
    restart: unless-stopped 
    environment:
      - MODE=native
      - SIGNAL_CLI_UID=$PUID
      - SIGNAL_CLI_GID=$PGID
    ports:
      - "$SIGNAL_PORT:8080" #9015
    volumes:
      - $DOCKERDIR/signal:/home/.local/share/signal-cli
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
```
$ cat accounts.json
{
  "accounts" : [ ]
}
```
I've enabled debug mode but as with Yersi88, no more messages appear after scanning the code:
```
today at 20:59:15time="2022-03-01T20:59:15Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
today at 20:59:15time="2022-03-01T20:59:15Z" level=debug msg="*) docker exec -it d9ae71e4056b2682763a1ae29c04a0561f9128d41018c50e2c242e4c472867c3 /bin/bash"
today at 20:59:15time="2022-03-01T20:59:15Z" level=debug msg="*) su signal-api"
today at 20:59:15time="2022-03-01T20:59:15Z" level=debug msg="*) signal-cli-native --config /home/.local/share/signal-cli link -n signal-api"
today at 20:59:15[GIN] 2022/03/01 - 20:59:15 | 200 |  501.325444ms | 192.168.1.165 | GET      "/v1/qrcodelink?device_name=signal-api"
```
What would normally happen after scanning the code? Does the web page refresh or offer any response that the secondary device is now registered?

Thanks.

**Comment by jarrah31** [comment]
Just to add an update, I've been able to successfully register signal-cli via my work's Android phone which has a different number to my iphone. It could be either an iPhone issue or something related to the number/account on there.

I'll be happy to try any debug methods on my iphone to see what the issue might be.

**Comment by Yersi88** [comment]
I was unable to link on a phone with new phone number but linking as successful on my regular phone where I use signal for a long time. No idea what the issue is here, both phones are running same versions of android. Maybe just newly registered numbers are having problems?

**Comment by jarrah31** [comment]
Certainly worth comparing notes as mine was the opposite, my work Android phone was a new Signal registration as of last night which worked linking the device, whereas I've had Signal on the iPhone for a while now.

I'll try wife's iPhone this evening - that will be a new Signal registration too.

**Comment by jarrah31** [comment]
hmm so it's not working on the wife's iPhone either... :(

**Comment by jarrah31** [comment]
Interesting - this gave me an error message.

signal-api@signal:/$ signal-cli --config /home/.local/share/signal-cli link -n signal-api

I copied the resulting sgnl://linkdevice?uuid=blahblah URL to my iphone which opened Signal and asked if I wanted to link the device. When I did so it then gave the following error:

Link request error: Failed to decrypt public key

I'll follow this up on signal-cli github as it's clearly not a rest api fault. :)

**Comment by jarrah31** [comment]
Here we go, known problem and a fix due to be released soon.
https://github.com/AsamK/signal-cli/issues/897

**Comment by bbernhard** [comment]
> @bbernhard should this error message have appeared in the docker logs or was I originally looking in the wrong place?

That's strange - that error should be logged to the docker log file as well. Maybe there's something wrong with the QR code link generation. :thinking: 

If you have a minute to spare, it would be great, if you could try to manually create the QR code with `qrencode` inside the docker container. (see https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning) for details) Then, copy the generated QR code to the host system and scan it with your phone. Would be interesting whether you see the error message that way. If so, then the QR code generation in the REST API wrapper is probably not working properly :/

**Comment by jarrah31** [comment]
Yes happy to help troubleshoot. 
Ok, so I managed to generate a QR code within the docker container by first installing qrencode (as root; apt update && apt install qrencode), and then running the command below, but I'm not sure what you mean by the next steps.

As seen below, the command outputs the QR code to CLI (which is neat, I wasn't expecting that!). I can then scan this on my phone and the error message appears after QR code on the CLI.
```
signal-api@signal:/$ signal-cli --config /home/.local/share/signal-cli link -n signal-api | tee >(xargs -L 1 qrencode -t utf8)
sgnl://linkdevice?uuid=randomLetters
█████████████████████████████████████████████
█████████████████████████████████████████████
████ ▄▄▄▄▄ ██▀▀▄▄ ▀█▄▄██▄▀▄██ ▀█ █ ▄▄▄▄▄ ████
removed
████▄▄▄▄▄▄▄█▄█▄▄▄███▄▄█▄▄██▄▄███▄███▄▄██▄████
█████████████████████████████████████████████
█████████████████████████████████████████████
Link request error: Failed to decrypt public key
signal-api@signal:/$ echo $?
0
```

**Comment by jarrah31** [comment]
Good news! The latest version 0.10.4.1 now works!

signal-api@signal:/tmp/signal-cli-0.10.4.1/bin$ ./signal-cli --config /home/.local/share/signal-cli link -n signal-api | tee >(xargs -L 1 qrencode -t utf8)
sgnl://linkdevice?uuid=xxxxxxxxxx
█████████████████████████████████████████████
█████████████████████████████████████████████
████ ▄▄▄▄▄ █   █▄█▄█ █▀ █ █▄█  █▄█ ▄▄▄▄▄ ████
Removed
████▄▄▄▄▄▄▄█▄█▄███▄█▄▄█▄██▄███▄▄████▄█▄▄▄████
█████████████████████████████████████████████
█████████████████████████████████████████████
INFO  ProvisioningManagerImpl - Received link information from +12345678, linking in progress ...
Associated with: +12345678
█████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ ██ ▄ ▄█ ▄▄▄▄▄ ████
Removed
████▄▄▄▄▄▄▄█▄▄█▄███▄███▄█████
█████████████████████████████
█████████████████████████████
signal-api@signal:/tmp/signal-cli-0.10.4.1/bin$

**Comment by bbernhard** [comment]
Many thanks for the info!

I have to admit, that I've never linked a device (the `qrcodelink` endpoint was actually implemented by someone else), so I was also a bit surprised to see that `qrencode` outputs the QR code on the command line, wasn't expecting that either.

I just checked the REST API wrapper sourcecode and it seems that we are not waiting until `signal-cli` has linked the device. Not sure if `signal-cli` changed its behavior there or if we did it wrong in the first place. But nevertheless, that's definitely something that should be fixed in the REST API. I'll try to have a look at it in the next days.

For everyone else that's affected by that issue: The easiest way to work around that issue is to do it like @jarrah31 did and connect to the running docker container and run the `signal-cli` command directly. I'll release a new image in the next days which contains `signal-cli v0.10.4.1`. Thanks to @jarrah31 for tracking down the issue!

**Comment by jarrah31** [comment]
Thank @bbernhard!
Regarding logging the error messages in docker logs, at the moment I'm trying to figure out why I can't receive a list of groups from signal, so I enabled debug mode and then ran the cli command manually. It gave an error message as seen below, but this didn't appear in the logs either, so the work you plan on doing over the next few days would benefit this too.

Rest API response:
```
curl -X GET -H "Content-Type: application/json" 'http://192.168.199.34:8080/v1/groups/+12345678'
[]%
```
CLI response:
```
signal-api@signal:/$ signal-cli-native --config /home/.local/share/signal-cli --output json -a +12345678 listGroups -d
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
[]
```
The above INFO message doesn't appear in docker logs:
```
today at 19:35:20[GIN] 2022/03/03 - 19:35:20 | 204 |     183.431µs | 192.168.199.165 | POST     "/v1/configuration"
today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="*) docker exec -it de3d7f166134f57732f1d8b314702165bf2602b1 /bin/bash"
today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="*) su signal-api"
today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="*) signal-cli-native --config /home/.local/share/signal-cli --output json -a +12345678 listGroups -d"
today at 19:35:51[GIN] 2022/03/03 - 19:35:51 | 200 |  1.465159276s | 192.168.199.165 | GET      "/v1/groups/+12345678"
```

**Comment by bbernhard** [comment]
> Thank @bbernhard! Regarding logging the error messages in docker logs, at the moment I'm trying to figure out why I can't receive a list of groups from signal, so I enabled debug mode and then ran the cli command manually. It gave an error message as seen below, but this didn't appear in the logs either, so the work you plan on doing over the next few days would benefit this too.
> 
> Rest API response:
> 
> ```
> curl -X GET -H "Content-Type: application/json" 'http://192.168.199.34:8080/v1/groups/+12345678'
> []%
> ```
> 
> CLI response:
> 
> ```
> signal-api@signal:/$ signal-cli-native --config /home/.local/share/signal-cli --output json -a +12345678 listGroups -d
> INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
> []
> ```
> 
> The above INFO message doesn't appear in docker logs:
> 
> ```
> today at 19:35:20[GIN] 2022/03/03 - 19:35:20 | 204 |     183.431µs | 192.168.199.165 | POST     "/v1/configuration"
> today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
> today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="*) docker exec -it de3d7f166134f57732f1d8b314702165bf2602b1 /bin/bash"
> today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="*) su signal-api"
> today at 19:35:49time="2022-03-03T19:35:49Z" level=debug msg="*) signal-cli-native --config /home/.local/share/signal-cli --output json -a +12345678 listGroups -d"
> today at 19:35:51[GIN] 2022/03/03 - 19:35:51 | 200 |  1.465159276s | 192.168.199.165 | GET      "/v1/groups/+12345678"
> ```

Yeah, that's a limitation of the normal mode. After you've registered the number/linked the device I strongly suggest to switch to the `json-rpc` mode (see https://github.com/bbernhard/signal-cli-rest-api#execution-modes for details). It works much faster and doesn't require you to call the `receive` periodically.

**Comment by jarrah31** [comment]
That's a really useful tip, I'll swap to that now. Thanks!

**Comment by jarrah31** [comment]
Just tried swapping to json-rpc but it gave the following error:

{"error":"Number not registered with JSON-RPC"}%

Went back to native and it worked.

**Comment by bbernhard** [comment]
> Just tried swapping to json-rpc but it gave the following error:
> 
> {"error":"Number not registered with JSON-RPC"}%
> 
> Went back to native and it worked.

Do you something like this in the docker logs when using the `json-rpc` mode?

```
signal-cli-rest-api-signal-cli-rest-api-1  | + set -e
signal-cli-rest-api-signal-cli-rest-api-1  | + [ -z /home/.local/share/signal-cli ]
signal-cli-rest-api-signal-cli-rest-api-1  | + chown 1000:1000 -R /home/.local/share/signal-cli
signal-cli-rest-api-signal-cli-rest-api-1  | + cat
signal-cli-rest-api-signal-cli-rest-api-1  | + cap_prefix=-cap_
signal-cli-rest-api-signal-cli-rest-api-1  | + cat /proc/sys/kernel/cap_last_cap
signal-cli-rest-api-signal-cli-rest-api-1  | + seq -s ,-cap_ 0 37
signal-cli-rest-api-signal-cli-rest-api-1  | + caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37
signal-cli-rest-api-signal-cli-rest-api-1  | + [ json-rpc = json-rpc ]
signal-cli-rest-api-signal-cli-rest-api-1  | + /usr/bin/jsonrpc2-helper
signal-cli-rest-api-signal-cli-rest-api-1  | time="2022-03-03T20:23:00Z" level=info msg="Found number +xxxxxx and added it to jsonrpc2.yml"
signal-cli-rest-api-signal-cli-rest-api-1  | + service supervisor start
```
Especially this line here:
> "Found number <+ your number> and added it to jsonrpc2.yml"

edit: Oh wait, I've never tried the json-rpc mode with a linked device. So maybe that's why it is not working :/

**Comment by jarrah31** [comment]
Seen your edit, but will paste below what the logs show when I try json-rpc. (thanks for your help btw)
```
today at 20:29:26+ set -e
today at 20:29:26+ [ -z /home/.local/share/signal-cli ]
today at 20:29:26+ usermod -u 1000 signal-api
today at 20:29:26usermod: no changes
today at 20:29:26+ groupmod -g 998 signal-api
today at 20:29:26+ chown 1000:998 -R /home/.local/share/signal-cli
today at 20:29:26+ cat
today at 20:29:26+ cap_prefix=-cap_
today at 20:29:26+ cat /proc/sys/kernel/cap_last_cap
today at 20:29:26+ seq -s ,-cap_ 0 40
today at 20:29:26+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
today at 20:29:26+ [ json-rpc = json-rpc ]
today at 20:29:26+ /usr/bin/jsonrpc2-helper
today at 20:29:26+ service supervisor start
today at 20:29:27Starting supervisor: supervisord.
today at 20:29:27+ supervisorctl start all
today at 20:29:28+ exec setpriv --reuid=1000 --regid=998 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
today at 20:29:28time="2022-03-03T20:29:28Z" level=info msg="Started Signal Messenger REST API"
today at 20:29:59[GIN] 2022/03/03 - 20:29:59 | 204 |     300.586µs | 192.168.199.105 | POST     "/v1/configuration"
today at 20:30:09[GIN] 2022/03/03 - 20:30:09 | 400 |     172.809µs | 192.168.199.105 | POST     "/v2/send"
```

**Comment by bbernhard** [comment]
> Seen your edit, but will paste below what the logs show when I try json-rpc. (thanks for your help btw)
> 
> ```
> today at 20:29:26+ set -e
> today at 20:29:26+ [ -z /home/.local/share/signal-cli ]
> today at 20:29:26+ usermod -u 1000 signal-api
> today at 20:29:26usermod: no changes
> today at 20:29:26+ groupmod -g 998 signal-api
> today at 20:29:26+ chown 1000:998 -R /home/.local/share/signal-cli
> today at 20:29:26+ cat
> today at 20:29:26+ cap_prefix=-cap_
> today at 20:29:26+ cat /proc/sys/kernel/cap_last_cap
> today at 20:29:26+ seq -s ,-cap_ 0 40
> today at 20:29:26+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
> today at 20:29:26+ [ json-rpc = json-rpc ]
> today at 20:29:26+ /usr/bin/jsonrpc2-helper
> today at 20:29:26+ service supervisor start
> today at 20:29:27Starting supervisor: supervisord.
> today at 20:29:27+ supervisorctl start all
> today at 20:29:28+ exec setpriv --reuid=1000 --regid=998 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
> today at 20:29:28time="2022-03-03T20:29:28Z" level=info msg="Started Signal Messenger REST API"
> today at 20:29:59[GIN] 2022/03/03 - 20:29:59 | 204 |     300.586µs | 192.168.199.105 | POST     "/v1/configuration"
> today at 20:30:09[GIN] 2022/03/03 - 20:30:09 | 400 |     172.809µs | 192.168.199.105 | POST     "/v2/send"
> ```

Looks like the json-rpc mode isn't working for linked devices :/ I guess signal-cli stores linked devices somehow differently on the filesystem. When the REST API wrapper starts in json-rpc mode, it traverses the signal-cli config directory and looks for all registered numbers. But as the linked devices are stored differently, it can't find any registered number. Could you do me a favour and create a new issue for that please. That would be great, thanks!

**Comment by jarrah31** [comment]
Thanks, will do.

**Comment by hofslu** [comment]
Hey guys, first of all, thank you for developing 🙏
As I had quite a pain setting it up (im very new to docker and programming in general) I thougt I may share for others who may are stranded as well.

I still had the issues that on trying to link devices I got: success and rerouting without adding the device, Networkerror.

What made it work for me after some failed attempts:
`cd $HOME/.local/share/`
`rm -r signal-cli`'<-- crucial'
`docker ps`
`docker exec -it <ContainerID> /bin/bash`
`apt update && apt install qrencode`
`su signal-api`
`signal-cli --config /home/.local/share/signal-cli link -n signal-api`
ctrl + C
`signal-cli --config /home/.local/share/signal-cli link -n signal-api | tee >(xargs -L 1 qrencode -t utf8)`
scanning the QRCode
