### ISSUE TITLE
Register a number

### ISSUE THREAD

**Issue by asad-awadia** [bbernhard/signal-cli-rest-api#214]
### The problem

How long does a number stay registered? Do I have to keep re-registering it?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
You only have to register it once.

**Comment by asad-awadia** [comment]
@bbernhard what does register mean? Like register a new account with signal? Or grab the keys?

**Comment by bbernhard** [comment]
Register a new account with signal (similar to this: https://support.signal.org/hc/en-us/articles/360007318691-Register-a-phone-number)

**Comment by asad-awadia** [comment]
what If I already have an account?

**Comment by bbernhard** [comment]
you either need a dedicated phone number (mobile number, landline number, etc) or you can link the docker container to an existing account.

**Comment by asad-awadia** [comment]
ok 👍
