### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by asad-awadia** [bbernhard/signal-cli-rest-api#215]
### The problem

What are the rate limits for sending messages?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
There's no built in rate limiting. The number of messages you can send is mainly determined by the mode (normal mode is the slowest whereas json-rpc mode is the fastest). I don't know if the Signal Server has any rate limiting built in.

**Comment by asad-awadia** [comment]
> I don't know if the Signal Server has any rate limiting built in.

Yeah this is what I was referring to - how to not get blocked by signal

**Comment by baseljd** [comment]
I'm getting the rate limit from Signal as follows:

`Failed to send message: [413] Rate limit exceeded: 413 (RateLimitException)
`
Has anyone been able to figure out the limits set from Signal for sending messages?

**Comment by alexw1982** [comment]
no - same issue here with a German number
