### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by ankitnetsol** [bbernhard/signal-cli-rest-api#217]
Hello,

 I am using this API to successfully register my phone numbers but I am not getting any response only getting a 201 status code. Register phone number API not getting any error but when I am using verify token API at that time getting error **Authorization failed**. Where can  I get a token that will pass into verify token?

Anyone, please give me a solution to this problem.

Thanks.

**Comment by bbernhard** [comment]
The verify token is only valid for a relatively short time. Are you sure that you verify the registration in a timely manner?

**Comment by dashdrum** [comment]
My verify token seems to be coming back with a space and line feed in the middle.  How would I enter something like this into the URL?  I've tried using a hyphen, as well as no space or character at all in the middle
![Screen Shot 2022-02-27 at 6 45 30 PM](https://user-images.githubusercontent.com/2257852/155905171-416726f9-b3bc-4a2f-af4b-0cd66cfa32ee.png)
.

**Comment by TinySpins** [comment]
Hi, 

I also ran into this issue today.
I fixed it by verifying using just the first six numbers of the verification code, so for your case just use: 149153

**Comment by dashdrum** [comment]
Thanks, Tiny.
