### ISSUE TITLE
Updating avatar

### ISSUE THREAD

**Issue by superzappa** [bbernhard/signal-cli-rest-api#218]
Hello,

I like this addon very much, but can´t get one thing to work. I want to set my personal avatar with the command for updating profiles.
Can anybody tell me what ist expected as "string"? I tried a path/filename to a .gif on my RaspberryPi in the size of 50x50 and had to learn, that I have to encode it in Base64. I did this using an online-tool, but this doesn´t work, too, but with no error. I found no tips how I can get it to work.

This is what I mean: 
"base64_avatar": "string"

Thank you in advance!
Dirk

**Comment by bbernhard** [comment]
should be fixed with the next release :)

**Comment by superzappa** [comment]
That´s fine, thank you! :)

**Comment by superzappa** [comment]
Thank you. :-) As a Home Assistant-user I now have to wait for the updated add-on.
Kind regards!

**Comment by superzappa** [comment]
Has worked now, thank you! :-)
