### ISSUE TITLE
`"use_voice": true` with fresh landline number requires captcha. Please help. 

### ISSUE THREAD

**Issue by prankousky** [bbernhard/signal-cli-rest-api#219]
Hi everybody,

I was having trouble linking an existing mobile phone number via `curl`, so I decided to use a landline instead. I tried this command: `curl -X POST -H "Content-Type: application/json" --data '{"use_voice": true}' 'http://<url>:<port>/v1/register/+49<my_number>'`.

This generated the following output:

```
curl -X POST -H "Content-Type: application/json" --data '{"use_voice": true}' 'http://...../v1/register/+49.....'
{"error":"Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"}%
```

Please tell me if this is wrong, but from what I can tell, you can online generate a captcha **after**

1. registering your number with the app (I use android)
2. then linking the signal app on a computer (because you cannot use developer tools on mobile to find the `signalcaptcha://`
3. finally register with captcha

However, I thought trying to **register** a **new** number meant that it had not previously been connected to any phone/pc. How can I receive a captcha for an account that does not yet exist?

I cannot say for sure, but I strongly believe that there cannot be a signal account linked to this landline number. I registered it from a SIP provider a long time ago, so it has been my number and nobody else should have been able to connect it. 

Thank you in advance for your help :)

**Comment by bbernhard** [comment]
The easiest thing is to open the captcha page in a private tab on your PC, complete the captcha request and use the token (obtained from the developer console) in the `register` request. There is no need to link anything.

**Comment by prankousky** [comment]
Thank you. I feel stupid! I assumed because that captcha page wants to interact with the signal app on my pc (trying to open it), I had to have the account I am trying to register linked to it O.O 

Since that is not the case, everything works perfectly fine now :)
