### ISSUE TITLE
Error: Verification failed! This number is locked with a pin

### ISSUE THREAD

**Issue by guitarflipper** [bbernhard/signal-cli-rest-api#22]
I have a PIN in use for my Signal account. When I run the curl commands to apply the verification code, I get the following:

{"error":"Verification failed! This number is locked with a pin. Hours remaining until reset: 150\nUse '--pin PIN_CODE' to specify the registration lock PIN\n"}

What is the syntax I need when running the following that results in the error?
curl -X POST -H "Content-Type: application/json" 'http://192.168.x.y:1234/v1/register/+1816xxxyyyy/verify/123-123'

**Comment by bbernhard** [comment]
Unfortunately this isn't yet exposed via the REST API. If you would like then I can quickly add that functionality. The problem is, that I can't test it right now, because I do not have a device with a pin code set. But if you want to give it a try, I can upload a test version for you.

**Comment by guitarflipper** [comment]
Thanks for replying so quickly. When you say you don't have a device with a pin code do you mean a pin code for the device or pin for the Signal app (Android)?

FYI: In my case, I have a pin set in the Signal app but I also have "PIN reminders" (occasional reminders to enter the pin). Also, "Registration Lock" which adds "extra security by requiring me to enter my PIN to register my phone number with Signal again."

I'm willing to try the test code. I'm using Home assistant on a RPI 3B+, (HassOS 4.11).

**Comment by bbernhard** [comment]
Ok, I've uploaded a new docker image to dockerhub. You can pull it with `docker pull bbernhard/signal-cli-rest-api:latest-dev`. 

With that image you should (hopefully) be able to verify your device with: 

```curl -X POST -H "Content-Type: application/json" --data '{"pin": "your registration pin"}' 'http://192.168.x.y:1234/v1/register/+1816xxxyyyy/verify/123-123'```

(you might need to request a new token via the `register` endpoint first, as your old token is probably already expired)

The `pin` should be the one you set with the [registration lock](https://support.signal.org/hc/en-us/articles/360007059792-Signal-PINs#manage_registration_lock)

**Comment by Gill-Bates** [comment]
@bbernhard You can test it with this fake SIM: https://receive-smss.com/sms/4915207829731/

**Comment by Colgaton** [comment]
`curl -X POST -H "Content-Type: application/json" --data '{"pin": "your registration lock pin"}' 'http://192.168.x.y:1234/v1/register/+1816xxxyyyy/verify/123-123'`

^^ This worked for me in the latest version.
