### ISSUE TITLE
json-rpc mode doesn't work with existing linked devices

### ISSUE THREAD

**Issue by jarrah31** [bbernhard/signal-cli-rest-api#224]
### The problem

I created a linked device using native mode, but when I swapped to json-rpc mode and tried to send a message, I received the following error:

`{"error":"Number not registered with JSON-RPC"}%`

The docker logs show the following when starting up in json-rpc mode:
```
today at 20:29:26+ set -e
today at 20:29:26+ [ -z /home/.local/share/signal-cli ]
today at 20:29:26+ usermod -u 1000 signal-api
today at 20:29:26usermod: no changes
today at 20:29:26+ groupmod -g 998 signal-api
today at 20:29:26+ chown 1000:998 -R /home/.local/share/signal-cli
today at 20:29:26+ cat
today at 20:29:26+ cap_prefix=-cap_
today at 20:29:26+ cat /proc/sys/kernel/cap_last_cap
today at 20:29:26+ seq -s ,-cap_ 0 40
today at 20:29:26+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
today at 20:29:26+ [ json-rpc = json-rpc ]
today at 20:29:26+ /usr/bin/jsonrpc2-helper
today at 20:29:26+ service supervisor start
today at 20:29:27Starting supervisor: supervisord.
today at 20:29:27+ supervisorctl start all
today at 20:29:28+ exec setpriv --reuid=1000 --regid=998 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
today at 20:29:28time="2022-03-03T20:29:28Z" level=info msg="Started Signal Messenger REST API"
today at 20:29:59[GIN] 2022/03/03 - 20:29:59 | 204 |     300.586µs | 192.168.199.105 | POST     "/v1/configuration"
today at 20:30:09[GIN] 2022/03/03 - 20:30:09 | 400 |     172.809µs | 192.168.199.105 | POST     "/v2/send"
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Should be fixed.

If you want to give it a try, you can use the following docker image for testing: `bbernhard/signal-cli-rest-api:0.100-dev`

**Changelog:**
* json-rpc mode should be fixed for linked devices
* per default the container ip is now used in the interactive swagger documentation as ip. If you want to use a different ip, you can override it in the `docker-compose.yml` file by setting the `SWAGGER_IP` env variable appropriately. 
* updated signal-cli to version 0.10.4-1

**Comment by jarrah31** [comment]
Thank you very much @bbernhard, I can confirm json-rpc mode now works with an existing linked account, and it is noticeably faster than native mode!

**Comment by jarrah31** [comment]
Just a quick heads-up, I tried to issue the receive command (to obtain a new group ID I'd created on the phone), but it gave the following error:
```
➜  ~ curl -X GET -H "Content-Type: application/json" 'http://192.168.199.34:8080/v1/receive/+123456789'
Bad Request
{"error":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}%
```
Going back to Native mode didn't give me an error:
```
➜  ~ curl -X GET -H "Content-Type: application/json" 'http://192.168.199.34:8080/v1/receive/+123456789'
[]%
```

**Comment by bbernhard** [comment]
That's intended (although I am not sure whether it is documented in the swagger API). In json-rpc mode you need to establish a websocket connection (e.g with a websocket client like `wscat`) in order to receive messages. See https://github.com/bbernhard/signal-cli-rest-api/discussions/160 for details.

**Comment by Larx** [comment]
Is this supposed to be fixed? I still get this error in json-rpc mode (using both latest and latest-dev tags).

**Comment by Larx** [comment]
```
Mär 14 21:17:08 server conmon[28193]: time="2022-03-14T21:17:08+01:00" level=info msg="Started Signal Messenger REST API"
Mär 14 21:17:15 server conmon[28193]: time="2022-03-14T21:17:15+01:00" level=error msg="Couldn't read data for number +xxxxxx: EOF. Is the number properly registered?"
```
with latest and latest-dev:
```
$ curl -X GET "http://server:8090/v1/about" -H "accept: application/json" 
{"versions":["v1","v2"],"build":2,"mode":"json-rpc","version":"0.101"
$ curl -X GET "http://server:8090/v1/about" -H "accept: application/json" 
{"versions":["v1","v2"],"build":2,"mode":"normal","version":"0.57"}
```

**Comment by bbernhard** [comment]
> I at least don't get error https://github.com/bbernhard/signal-cli-rest-api/issues/229...

Does the normal mode also work for you again?

Regarding the issue: Are you sure, that the signal-cli instance is still linked to your device? (In the past I've experienced some issues after a signal-cli update once, where for some reason the signal-cli config was messed up and not working properly. In that case I had to remove the signal-cli-config directory and register/link from scratch. 

Another thing you could try:

* get the container id with `docker ps`
* connect to the running container with `docker exec -it <container id> /bin/bash`
Inside the docker container run:
* `supervisorctl stop all`
* check with `ps -ax | grep signal` whether there is still a java process running. If so, kill it with `kill -9 <pid>`
* switch to signal-api user with `su signal-api`
* run `signal-cli --output=json -u <your registered/linked signal number> --config /home/.local/share/signal-cli/ jsonRpc`

If you get `INFO  SignalAccount - Config file is in use by another instance, waiting…` then there's still a Java process running that you need to kill first.

Do you see any errors? If you send a Signal message to that number you should see something pop up on the console.

**Comment by Larx** [comment]
Thanks for the quick replies!

> > I at least don't get error #229...
> Does the normal mode also work for you again?

That was a misconception of me :-/. I get #229 only if I try to send in normal mode. In json-rpc mode I cannot even send, as the number is not registered. So maybe the problem would also occur then.
 
> Regarding the issue: Are you sure, that the signal-cli instance is still linked to your device? (In the past I've experienced some issues after a signal-cli update once, where for some reason the signal-cli config was messed up and not working properly. In that case I had to remove the signal-cli-config directory and register/link from scratch.

Maybe I have to try that. I'd hoped to avoid that...

> Another thing you could try:
> * get the container id with `docker ps
> * connect to the running container with `docker exec -it <container id> /bin/bash`
>   Inside the docker container run:
> * `supervisorctl stop all`
```
root@e8c366c8dabf:/# supervisorctl stop all
unix:///var/run/supervisor.sock no such file
```
> * check with `ps -ax | grep signal` whether there is still a java process running. If so, kill it with `kill -9 <pid>`
```
root@e8c366c8dabf:/# ps -ax | grep signal
    1 ?        Ssl    0:
root@e8c366c8dabf:/# kill -9 1
root@e8c366c8dabf:/# ps -ax | grep signal
    1 ?        Ssl    0:02 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
  142 pts/0    S+     0:00 grep --color=auto signal
```
I have problems stopping signal-cli ...

**Comment by bbernhard** [comment]
> root@e8c366c8dabf:/# supervisorctl stop all
> unix:///var/run/supervisor.sock no such file

Looks like it isn't running in the first place. 

Please connect again to the running docker container and check in the folder `/var/log/signal-cli-json-rpc-1` whether there are any error logs.

**Comment by Larx** [comment]
> > root@e8c366c8dabf:/# supervisorctl stop all
> > unix:///var/run/supervisor.sock no such file
> 
> Looks like it isn't running in the first place.
> 
> Please connect again to the running docker container and check in the folder `/var/log/signal-cli-json-rpc-1` whether there are any error logs.

The named folder does not even exist. The container starts without any error, but seemingly only the rest interface is running, not signal-cli. Output of "top" within the container:
```
  1 signal-+  20   0  871236  31316  17572 S   0.7   0.8   0:00.21 signal-cli-rest                                                              
   24 root      20   0    7328   2688   2348 S   0.0   0.1   0:00.23 bash                                                                         
   36 root      20   0    9184   2492   2120 R   0.0   0.1   0:00.01 top  
```
But maybe this is not related with the original bug.

**Comment by Larx** [comment]
bootstrap.log contains a few errors, however:
[bootstrap.log](https://github.com/bbernhard/signal-cli-rest-api/files/8329535/bootstrap.log)
