### ISSUE TITLE
Problem with sending attachments

### ISSUE THREAD

**Issue by schorsch13** [bbernhard/signal-cli-rest-api#227]
As stated in the docs I tried to send a base64 encoded attachment:

```bash
meme="$(base64 meme.jpeg)"        
curl -globoff -X POST -H \"Content-Type:\ application/json\" -d \'{\"message\":\ \"Test\ image\", \"base64_attachments\":\ [\"\'\"${meme}\"\'\"],\ \"number\":\ \"$number\",\ \"recipients\":\ [\"$i\"]}\' \'http://127.0.0.1:8080/v2/send\'
```

But when running the script I always get the following error:

```
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
```

**Comment by schorsch13** [comment]
I also tried to remove all new lines of the base64 encoded image with:

```bash
meme="$(base64 meme.jpeg | tr -d '\n')" 
```

**Comment by vloschiavo** [comment]
I had a similar problem.  I found the answer here: https://askubuntu.com/a/650412

"Bash doesn't expand in single quotes. (Exit the opening quote before doing command substitution then open a quote again.)

So, for your example, try this, I've removed the \ escapes and closed the opening quote before the base64 attachment, and re-opened after.  

Note: In my application, I also had to prevent base64 from word-wrapping the lines; this removes the newlines every 76 characters in the variable $meme.

```
meme="$(base64 -w0 meme.jpeg)"
curl -X POST -H "Content-Type: application/json" -d '{"message": "Test image", "base64_attachments": ["'"${meme}"'"], "number": "+19166267556", "recipients": ["+15752084623"]}' 'http://192.168.1.65:8080/v2/send'
```

**Comment by vloschiavo** [comment]
If your attachment is "large" then curl may throw an error "Argument list too long".  To solve for this you must pass the -d parameter from STDIN via -d @- 

I ran into this just now too but found the solution [here](https://unix.stackexchange.com/questions/174350/curl-argument-list-too-long#comment1035571_174355): 


```
meme="$(base64 -w0 meme.jpeg)"
echo {"message": "Test image", "base64_attachments": ["'"${meme}"'"], "number": "+19166267556", "recipients": ["+15752084623"]} | curl -X POST -H "Content-Type: application/json" -d @- 'http://192.168.1.65:8080/v2/send'
```
