### ISSUE TITLE
Sending messages from Home-Assistant fails (64/32bit confusion?!)

### ISSUE THREAD

**Issue by Larx** [bbernhard/signal-cli-rest-api#229]
### The problem

When trying to send Signal messages from an Home-Assistant automation, the following error occurs:

`Maintainance: Update-Hinweis Nextcloud Apps: Error executing script. Unexpected error for call_service at pos 1: OpenJDK Server VM warning: You have loaded library /tmp/sqlite-3.36.0.3-af792558-7a7f-403e-8424-4aded1a0617b-libsqlitejdbc.so which might have disabled stack guard. The VM will try to fix the stack guard now. It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'. Failed to load native library:sqlite-3.36.0.3-af792558-7a7f-403e-8424-4aded1a0617b-libsqlitejdbc.so. osinfo: Linux/aarch64 java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.36.0.3-af792558-7a7f-403e-8424-4aded1a0617b-libsqlitejdbc.so: /tmp/sqlite-3.36.0.3-af792558-7a7f-403e-8424-4aded1a0617b-libsqlitejdbc.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform) ERROR HikariPool - HikariPool-1 - Exception during pool initialization. java.sql.SQLException: Error opening connection at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:244) at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) at org.sqlite.JDBC.createConnection(JDBC.java:115) at org.sqlite.JDBC.connect(JDBC.java:90) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) at org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:94) at org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32) at org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:23) at org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$17(SignalAccount.java:986) at org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1268) at org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:984) at org.asamk.signal.manager.storage.SignalAccount.initDatabase(SignalAccount.java:257) at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:88) at org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:64) at org.asamk.signal.App.loadManager(App.java:337) at org.asamk.signal.App.handleLocalCommand(App.java:272) at org.asamk.signal.App.init(App.java:213) at org.asamk.signal.Main.main(Main.java:58) Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/org/sqlite/native/Linux/aarch64:/usr/java/packages/lib:/lib:/usr/lib] at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:389) at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68) at org.sqlite.core.NativeDB.load(NativeDB.java:63) at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:240) ... 25 common frames omitted Error loading state file for user +xxxxxxx: Failed to initialize pool: Error opening connection (PoolInitializationException)`

The text hints at some arm64/arm32 problem which I don't understand. I use the container on Raspbian 32bit with the following systemd unit for podman:

`[Unit]
Description=Podman container: signal-cli-rest-api.service
Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
ExecStartPre=/bin/rm -f %t/container-signal-cli_rest-api.pid %t/container-signal-cli-rest-api.ctr-id
ExecStart=/usr/bin/podman run -d \
	--conmon-pidfile %t/container-signal-cli-rest-api.pid --cidfile %t/container-signal-cli-rest-api.ctr-id \
	--cgroups=no-conmon \
	--label "io.containers.autoupdate=image" \
	--replace --rm \
	--log-driver=journald \
	--name signal-cli-rest-api \
	-p 8090:8080 \
	-v /etc/localtime:/etc/localtime:ro \
	-v /srv/signal-cli:/home/.local/share/signal-cli \
	-v /etc/timezone:/etc/timezone:ro \
	--env PORT=8080 \
	--env MODE=normal \
	docker.io/bbernhard/signal-cli-rest-api:latest
ExecStop=/usr/bin/podman stop \
	--ignore \
	--cidfile %t/container-signal-cli-rest-api.ctr-id \
	-t 10
ExecStopPost=/usr/bin/podman rm \
	--ignore \
	-f \
	--cidfile %t/container-signal-cli-rest-api.ctr-id
PIDFile=%t/container-signal-cli_rest-api.pid
Type=forking

[Install]
WantedBy=multi-user.target`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

armv7

### Additional information

I'm using podman, not docker. I did not try sending from outside Home-Assistant.

**Comment by Larx** [comment]
Additional info, maybe related: I run raspbian 32bit, but with a 64bit kernel.

**Comment by bbernhard** [comment]
> Additional info, maybe related: I run raspbian 32bit, but with a 64bit kernel

Yeah, I think that could be the reason. Unfortunately I do not have any experience with a 32bit userspace and a 64bit kernel. As there is also virtualization (in your case podman) involved, I guess it could be quite tricky to find the root cause for your issue. One thing you could try is, to temporarily switch to docker to see if that changes anything (to rule out that it's something related to podman).

**Comment by Larx** [comment]
I switched back to using a 32bit kernel and signal-cli works again. Obviously some change (precompiled binaries?!) in signal-cli-rest-api somehow broke the docker image on a 64bit kernel with 32bit userspace.
