### ISSUE TITLE
Swagger incorrect?

### ISSUE THREAD

**Issue by bri-b-dev** [bbernhard/signal-cli-rest-api#23]
Hi,

it seems the send-endpoints are not correct:

/v1/send/{number}
/v2/send/{number}

`sendV1.POST("", api.Send)`
`sendV2.POST("", api.SendV2)`

Wouldn't that be 
`sendV1.POST(":number", api.Send)`
`sendV2.POST(":number", api.SendV2)`
if the swagger were right?

Regards

**Comment by bbernhard** [comment]
Good catch! Many thanks for raising the issue :)

Should be fixed now. (You might need to clear your browser cache to see the changes)

**Comment by bri-b-dev** [comment]
Wow, quick work :-)
Actually, shouldn't that be
`/v1/send`
`/v2/send`

rather than
`/v1/send/`
`/v2/send/`

**Comment by bbernhard** [comment]
really hoped that I could fix that before you would notice. But looks like you won the race ;-)

Should be fixed. Thanks again! :)

**Comment by bbernhard** [comment]
btw: I also added the "old documentation" again (see [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/EXAMPLES.md)). I removed it in favor of the swagger documentation, but I guess it might be a good idea to provide both. Although I really like the swagger documentation, in it's current state it's still a bit "rough". But I'll try to improve it a bit in the next days.
