### ISSUE TITLE
Manage group administrators

### ISSUE THREAD

**Issue by daniel-lerch** [bbernhard/signal-cli-rest-api#232]
## Feature Request

Thanks to the great work around #210 _signal-cli-rest-api_ will be able to manage group members with the next release 🥳 

The next step would be to show, add and remove group administrators.

#### `GET /v1/groups/{number}`
For each group include an array of admins:
```json
{
  "admins": [
    "string"
  ],
  "blocked": true,
  "id": "string",
  "internal_id": "string",
  "invite_link": "string",
  "members": [
    "string"
  ],
  "name": "string",
  "pending_invites": [
    "string"
  ],
  "pending_requests": [
    "string"
  ]
}
```

#### `GET /v1/groups/{number}/{groupid}`
Include an array of admins similar like shown above.

#### `POST /v1/groups/{number}/{groupid}/admins`
Similar endpoint like for adding group members.
```json
{
  "admins": [
    "string"
  ]
}
```

#### `DELETE /v1/groups/{number}/{groupid}/admins`
Similar endpoint like for removing group members.
```json
{
  "admins": [
    "string"
  ]
}
```

As of my applications, adding a new field to a JSON object would be a non-breaking change.

**Comment by bbernhard** [comment]
Should be implemented. In case you want to give it a try, here's a test version: `bbernhard/signal-cli-rest-api:0.103-dev`

**Comment by daniel-lerch** [comment]
Thank you very much for implementing these new endpoints. @Beniox has tried them out and confirmed they are working.

To complete this feature request it would be great if you could also update the two mentioned `GET` endpoints or tell me whether you want to update the v1 endpoint or create a new v2 endpoint. Then I would work on a pull request.

**Comment by bbernhard** [comment]
Sorry, completely forgot about that. But it should be now available for testing in: `bbernhard/signal-cli-rest-api:0.104-dev`

**Comment by daniel-lerch** [comment]
Thanks again for this great work!
