### ISSUE TITLE
Setting name, avatar doesn't update name

### ISSUE THREAD

**Issue by benjy3gg** [bbernhard/signal-cli-rest-api#236]
### The problem

I'm in rpc-json mode and want to change the username my contacts are seeing.
When i send a put request to the endpoint, i get 204 back and after about 1 minute, the avatar is update, but i still only see the phone number as the "username" in signal messenger on my phone.

Is this an issue with this client or is there something i'm doing wrong?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
I _think_ this should be fixed now. Please give this docker test image a try: `bbernhard/signal-cli-rest-api:0.105-dev`

**Comment by benjy3gg** [comment]
Perfect, that fixed it.
Avatar + name are nearly instantly update now.
When will the fix be integrated in a non-dev version?

**Comment by bbernhard** [comment]
Usually I wait until I've collected more bugfixes and features and release them in bulk. But if you need that functionality urgent, I guess I can also release it sooner.

**Comment by benjy3gg** [comment]
depends on you. wanna use it in production, but i can also just switch to the non-dev version later, when you release it.

**Comment by bbernhard** [comment]
should be now in the latest production version.

**Comment by maartenhendrix** [comment]
it is not working for me in 0.59

**Comment by BeckWS** [comment]
this is not working in the latest version

**Comment by bbernhard** [comment]
Please create a new issue in that case
