### ISSUE TITLE
Please provide a simple function to trust devices

### ISSUE THREAD

**Issue by Larx** [bbernhard/signal-cli-rest-api#237]
Subject says it all: I ran into the issue that signal-cli won't send any longer to some devices. Only digging in the logs gave me the hint that somehow signal-cli does no longer send to untrusted devices (why?). Now I have the hassle to enter the security number for all those devices in long curl calls.

I appreciate Signal for all its security and privacy features, but I also appreciate that the security number stuff is completely optional on "conventional" devices. I don't really understand why signal-cli seems to enforce the validation, that's overkill IMHO.

The command line client at least offers an option to trust a device without entering the security number. Can this feature made accessible via the api, too?

**Comment by bbernhard** [comment]
Which `signal-cli` command do you mean exactly? We currently have this `[/v1/identities/{number}/trust/{numberToTrust}](https://bbernhard.github.io/signal-cli-rest-api/#/Identities/put_v1_identities__number__trust__numberToTrust_)` endpoint for trusting identities. 

`signal-cli` also seems to have the possibility to set the trust level globally:

```
--trust-new-identities TRUST-MODE

    Choose when to trust new identities:

        on-first-use (default): Trust the first seen identity key from new users, changed keys must be verified manually

        always: Trust any new identity key without verification

        never: Don’t trust any unknown identity key, every key must be verified manually
```

It's not exposed via REST API, but you could set it on commandline.

**Comment by Larx** [comment]
I didn't know about the above command line switch. But I guess I understand my problem now: The affected phones were trusted "on-first-use", but after a re-install of Signal on the respective device the trust got lost. 

Is there an option to set this command line switch for your Docker container?

```
-a, --trust-all-known-keys
Trust all known keys of this user, only use this for testing.

-v VERIFIED_SAFETY_NUMBER, --verified-safety-number VERIFIED_SAFETY_NUMBER
Specify the safety number of the key, only use this option if you have verified the safety number. Can be either the plain text numbers shown in the app or the bytes from the QR-code, encoded as base64.
```

IMHO the "-a" variant is missing from the api. I don't really see any real-world security problem for most usecases here, and it saves you from manually typing in the huge security number...

**Comment by bbernhard** [comment]
Should be implemented now. Unfortunately I can't test it right now, because all my devices are in a trusted state. In case you want to give it a try, here's a test image: `bbernhard/signal-cli-rest-api:0.106-dev`

**Comment by Larx** [comment]
Thanks! I already trusted all my numbers with manually entering the keys (brrrrrrrr) but I'll use the switch next time and will reopen if it doesn't work
