### ISSUE TITLE
Is there any way to register user with json-rpc mode ?

### ISSUE THREAD

**Issue by Tzanou123** [bbernhard/signal-cli-rest-api#239]
### The problem

Hello,

I was trying to start the server with json-rpc for use the endpoint `/v1/receive/number` with a websocket but i get this below message : 

```
time="2022-04-14T15:31:36Z" level=fatal msg="Couldn't read contents of /home/.local/share/signal-cli/data. Is your 
phone number properly registered? Please be aware that registering a phone number only works in normal/native
mode and is currently not supported in json-rpc mode!"
```

It's annoying because in my use case i want my server to be multi user and i cant let the user register with normal mode and then switch to json-rpc mode since i want it all process doing automatically !

So can i let the user register to the json-rpc mode directly ? or maybe this feature is planned to be added in a close future ?

Or there is any way to launch the endpoint `/v1/receive/number` in normal mode and establish a websocket here to be able to nitify the user a new message was incoming in his signal ?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
As far as I know, [signal-cli](https://github.com/AsamK/signal-cli) currently only allows to register a number in normal/native mode. If signal-cli supports registering a number in json-rpc mode, it can also be exposed via REST API here.

**Comment by bbernhard** [comment]
will be implemented with the next version
