### ISSUE TITLE
Ability to use systemd-service / experimental dbus-interface

### ISSUE THREAD

**Issue by Larx** [bbernhard/signal-cli-rest-api#24]
If you're using signal-cli not only for HomeAssistant, but also for registering other numbers for "stand-alone desktop instances", it might make sense to have signal-cli running as a systemd-service.
https://github.com/AsamK/signal-cli/wiki/DBus-service
E.g. this makes it possible to synchronize contacts with the coupled instance, and, according to some web pages, is "useful to keep the keys in sync".
Is this possible with the dockerized image, too?

**Comment by bbernhard** [comment]
In theory I think it should be possible - at least I can't think of any reason why the DBUS interface wouldn't work inside a docker container. Of course, at the moment the DBUS interface is not yet implemented - so that's something that needs to be done first.

Is there a particular use case you are interested in that requires the DBUS interface? The reason why I am asking is, that it requires quite a bit of rework to add the DBUS interface into the existing code - which I am not sure I have enough time to do right now. So I am wondering if there's maybe another way to accomplish what you are after (which requires less change in the code base)? According to the signal-cli documentation there's a `updateContact` API call - would it help tp expose that one via the REST API, so that you could call it periodically in your application?

**Comment by Larx** [comment]
It is, for sure, a niche use case.

I want to implement a solution like this:
https://ctrl.alt.coop/en/post/signal-without-a-smartphone/

I want to use Signal for users who don't use a smartphone (yes, there are such people), but can use a classic computer, be it with Signal Desktop or by a bridge to conventional mail.

The tutorial on this page implements the signal-cli daemon to keep the keys in sync with the desktop app. I cannot judge how necessary this is.
But moreover, the daemon gives the possibiliy to store/edit/manage contacts centrally in signal-cli's config file which seems a rather interesting option.

So, to be sure, I can implement the smartphone-less Signal also with your docker image. But it's difficult to use other features of signal-cli like sync of contacts and keys, or to adapt existing scripts to bridge from signal to mail or other services etc.

I also don't know what the desktop app does if it is not able to connect to it's smartphone master instance for a longer period, which is basically what the current way of doing things implies?!

**Comment by bbernhard** [comment]
I see. I just checked signal-cli's sourcecode and if I understood it correctly all that it's done in daemon mode is to periodically call the `receive` command. So I _think_ it might not be necessary to implement the DBUS interface just for that. 

So I think it should be sufficient if you periodically (e.g. via cronjob or something similar) call the `receive` endpoint (https://bbernhard.github.io/signal-cli-rest-api/#/Messages/get_v1_receive__number_), which should keep the keys in sync. 

What's currently missing is the `addDevice` command - that one is not yet exposed via REST. But I could quickly add that one if you would like to give that a try.

**Comment by Larx** [comment]
Thanks for looking into that. That helps, as it means could indeed simply call the receive command from your docker image periodically.

However I had the impression that in Signal Desktop the desktop instance has to initiate the sync, as this is menu option of its own. How can it be sure that the daemon is up and running in this moment?

Concerning the adddevice option, yes this would be nice. It works with running signal cli from a shell within the docker container, too, but the rest api would be more elegant 😃.

**Comment by bbernhard** [comment]
> However I had the impression that in Signal Desktop the desktop instance has to initiate the sync, as this is menu option of its own. How can it be sure that the daemon is up and running in this moment?

If I understood you correctly, then you would like to sync the contacts from the signal-cli to the Signal desktop application and not the other way round, right? (at least that's how I understood the blog post you mentioned above). In that case I guess you probably need to use the `sendContacts` (see [here](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc)), which informs all linked devices that there's something to sync. The `sendContacts' command is not yet implemented via the signal-cli-rest-api, but can be easily added.

btw: The `receive` command does not only receive messages, but also receives contacts and groups. See [here](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning))

> After linking was successful, you need to execute the receive command to get the list of contacts and groups from the main device.

**Comment by Larx** [comment]
OK, I guess I'll have to play around a bit with that information ;-) ...

**Comment by bbernhard** [comment]
I've looked into the DBUS implementation and unfortunately it's not that straightforward as I wished it to be. The main problem is, that signal-cli only exposes a small subset of functions via the DBUS (see https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/Signal.java). So, the following functionality is currently missing:

* register phone number
* verify phone number
* delete a group
* link device via QR code

So, if we switch to DBUS, we lose quite a lot of existing functionality :/. Unfortunately it's also not possible to mix DBUS and non-DBUS calls. If one tries to do that, the following error appears: "Config file is in use by another instance, waiting…"

So I am not sure how to proceed here. Any suggestions are really appreciated.

**Comment by Larx** [comment]
Thanks for looking into that. However, though I reported the problem, I am not too much into coding :-/, so not the slightest idea...

**Comment by soleous** [comment]
Hi Guys,

Did anything come from this?  I am looking for a webhook or WS style means to receive message as they come in.  I only appear to be able to do this via a timed pull using the receive function.

Thanks,

**Comment by bbernhard** [comment]
There's now the `json-rpc` mode, which implements the `receive` as websocket endpoint.
