### ISSUE TITLE
Unable to deregister flawed phone number, high CPU likely result

### ISSUE THREAD

**Issue by EDelsman** [bbernhard/signal-cli-rest-api#242]
### The problem

I noticed a constant 26%CPU of the Signal Messenger Addon in Homey using json-rpc, and traced the most likely cause to a failed attempt to register a phone number that was missing the area code. The log is riddled with messages: "Couldn't read data for number +\<badphonenumber\>: EOF. Is the number properly registered?"

To fix it I tried to deregister the bad phone number by calling the rest api. But I cannot, because that results in an error: user +\<badphonenumber\> is not registered.

If I switch to normal or native mode the high load isn't there, but I want to use the faster json-rpc. 
That also produces errors: "AUTO_RECEIVE_SCHEDULE: Couldn't call receive for number +<badphonenumber>: {User +\<badphonenumber\> is not registered.\n}"

How can I remove the bad number (leaving the working registration intact), and hopefully return to a low, acceptable CPU usage?

Platform is an RPI4, running version 0.59.0 of the addon, using json-rpc mode and running on HA version 2022.5.3

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
Please have a look in the `signal-cli-config` directory on your host system. If you use the example `docker-compose.yml`, the `signal-cli-config` directory should be in the same folder as the `docker-compose.yml` file. Inside the `signal-cli-config` directory there is a `data` folder which contains a separate file for each registered number. Please remove the corresponding file and try again. 

In case that doesn't work, you could also try to remove everything inside the `signal-cli-config` directory and start from scratch by registering your number.

**Comment by EDelsman** [comment]
Can I get to that on HAOS?

**Comment by bbernhard** [comment]
> Can I get to that on HAOS?

Unfortunately, I have no experience with HAOS. But according to [this](https://developers.home-assistant.io/docs/operating-system/debugging/) it should be possible to connect via SSH.

**Comment by EDelsman** [comment]
I tried that once to no avail,  ut I also do not want to do anything that would lead to an unsupported config.

Also any ID why this seems to lead to 26% CPU (basically taking one whole core)? It shouldn't be that a phone number that isn't fully registered takes up so many resources. I could not complete the steps (obviously) but this state is in itself not unusual, as it is a multi step process to get a phone number fully operational.

If errors occur,  there should be at least a wait time before the API should try again.

**Comment by bbernhard** [comment]
The REST API process communicates with the `signal-cli` binary via a local socket. As the number isn't properly registered, `signal-cli` can't start in json-rpc mode and therefore the REST API can't connect to the socket. As this is a error condition which shouldn't happen during normal operation, it is immediately tried to (re-)connect to the socket. I guess that leads to the high CPU load.

I think the best would be to get rid of the faulty number. Either via SSH or maybe I can also add some REST API functionality in the next release.

**Comment by bbernhard** [comment]
I'll try to add some API calls to the next version. :+1:

**Comment by EDelsman** [comment]
Hi, I just unregistered the bad phone number with the new option to delete data and turned on json-rpc again. The errors are gone, and so is the high CPU. Tank you very very much!
