### ISSUE TITLE
Xml Files as Attachments?

### ISSUE THREAD

**Issue by UliEi** [bbernhard/signal-cli-rest-api#244]
### Feature Request

Is there a way to send an xml file together with its file name as an attachment via the Signal Rest Api? The app I am working on currently reads the xml file as a byte stream which gets converted to a base_64 string;  that in turn gets added to a message as attachment. What the Signal client receives is a .txt file with a randomized file name. Having read issue 136 (closed), is this a limitation of the implicit Mime type detection, or am I missing something?

In any event, the Rest Api has turned out to be very helpful, thx for your effort !

**Comment by bbernhard** [comment]
I guess that could indeed be related to the automatic mime type detection. Do you use the latest docker image?

I just tried with an simple xml file, but unfortunately I couldn't reproduce the issue. The file name of the attachment changes (the API wrapper generates a UUID as filename; that's just an implementation detail which could be changed if needed), but the extension is correct (i.e `.xml`). 

Do you have a sample xml file to reproduce the issue?

Anyway, I guess it might make sense to extend the API with an optional parameter to manually set the mime type/extension.

**Comment by UliEi** [comment]
Thx for your quick response. The docker image I have been using  is v 0.59 which is the latest I am aware of.

It occcurs to me that I should habe been more specific when posting my question. I am trying to send gpx files via Signal, which are xml files indeed, but need to have a .gpx file extension in order to be properly recognized by consuming clients. The example file I used for testing purposes is attached for reference. ---  I just noticed that GitHub does not support the .gpx file type as such. I attached a file renamed to example.txt, pls change the extension to .gpx before playing around with it. Sorry for the inconvenience. ---

[example.txt](https://github.com/bbernhard/signal-cli-rest-api/files/8808993/example.txt)

I believe that sending .gpx files in general is supported by Signal itself. For example, outdoor navigation apps like Locus Maps are able to send .gpx files as attachments via the "Share" functionality. These attachments, when received by by the Signal Rest Api, have a dataMessage property within the message envelope like the one below:

"dataMessage": {
            "timestamp": 1652866315920,
            "message": null,
            "expiresInSeconds": 0,
            "viewOnce": false,
            "attachments": [
               {
                  "contentType": "application/gpx+xml",
                  "filename": "Valtournenche_Mountainbiken.gpx",
                  "id": "69P8lCcx_O4_3mHvgqPd",
                  "size": 778530
               }
            ]
      }

To retrieve the attachment, appropriately handle and delete it afterwards is not at all an issue.

Admittedly, the issue may be a little off the trodden path, but I do appreciate your interest in it.

**Comment by UliEi** [comment]
I forgot last night to test if the file attached above is recognized as xml when sending it via the Api (after having changed the extension from .gpx to .xml). The Signal client still receives it as <UUID>.txt file

**Comment by bbernhard** [comment]
Could you please try this file:
[example2.txt](https://github.com/bbernhard/signal-cli-rest-api/files/8826534/example2.txt)

The sha256sum of the file is: `f3721a413b4b2ee0d37dd2e81520609fe4d68efafce7d4119ee2638c71ad0a3a`

The file should be identical to the one you posted before (`example.txt`), except that I've removed a BOM character from the beginning of your file. It seems that the golang mime detection library can't handle files with the BOM properly and falls back to txt as mime type.

**Comment by UliEi** [comment]
Thanks a lot for your effort, removing the BOM character does the trick. The file with no BOM gets received (and recognized) as a gpx file.

If you found the time to allow for specifying an attachments's file name , it would be greatly appreciated.

Thanks again for your guidance and support, I learned a few things on the way

**Comment by bbernhard** [comment]
Thanks! I am glad that it works now :)

> If you found the time to allow for specifying an attachments's file name , it would be greatly appreciated.

I've created a separate ticket for that :+1: 
https://github.com/bbernhard/signal-cli-rest-api/issues/246

**Comment by bbernhard** [comment]
@UliEi In case you are still looking for that functionality, I have good news for you. @zeetabit has implemented that (see https://github.com/bbernhard/signal-cli-rest-api/pull/260). If you want to help testing that feature, please let me know :)

**Comment by UliEi** [comment]
@bbernhard, sorry for the late reply and thanks for the good news. I would be excited to to help you testing the newly added feature. Unfortunately, for personal reasons, I only will be able to do so in a few weeks from. Thanks again for your (and @zeetabit's) efforts!

**Comment by UliEi** [comment]
@bbernhard, I do apologize for the late reply, I got stuck in a maze of issues (all unrelated to this topic).  Yes, I am still interested in testing the new feature., and again, sorry for the delay

**Comment by UliEi** [comment]
I just noticed that the swagger documentation covers the newly added feature. If formatted correctly (no blanks tolerated in the members of the base64_attachment array), it works great, this is exactly what I was looking for!

Thx a lot for providing that feature, and again sorry for the delay

**Comment by StanisGit** [comment]
> The file should be identical to the one you posted before (`example.txt`), except that I've removed a BOM character from the beginning of your file. It seems that the golang mime detection library can't handle files with the BOM properly and falls back to txt as mime type.

I tried this file and was able to get it in the signal client. I received a file with a different name and extension (.gpx):

`TMPFILE="$(base64 SignalsPictures/example.txt)" && echo '{"message": "Test message", "base64_attachments": ["'"$TMPFILE"'"], "number": "+123456789012", "recipients": ["group.e...0="]}' | curl -X POST -H "Content-Type: application/json" -d @- 'http://localhost:8080/v2/send'`
