### ISSUE TITLE
Upgrade to signal cli 0.10.7

### ISSUE THREAD

**Issue by timappelmansvlaanderen** [bbernhard/signal-cli-rest-api#247]
### Feature Request
Is it possible to upgrade the docker to Signal CLI release 0.10.7 to support the latest features?

**Comment by timappelmansvlaanderen** [comment]
Can this also be released? thanks a lot!

**Comment by bbernhard** [comment]
I haven't tested it yet, so there's no official release. But you can use this test image: `bbernhard/signal-cli-rest-api:0.109-dev`

**Comment by bbernhard** [comment]
is released
