### ISSUE TITLE
Receive endpoint not working ?

### ISSUE THREAD

**Issue by UliEi** [bbernhard/signal-cli-rest-api#249]
### The problem

Hi,

is there an issue with the messages receive endpoint? In response to the curl request

curl -X GET -H "Content-Type: application/json" 'http://localhost:8080/v1/receive/+49abcd'

I get the error message

{"error":"java.lang.NoClassDefFoundError: Lorg/signal/libsignal/protocol/NoSessionException;\n\tat com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:346)\n\tat org.signal.libsignal.internal.Native.GroupCipher_DecryptMessage(Native.java)\n\tat org.signal.libsignal.protocol.groups.GroupCipher.decrypt(GroupCipher.java:71)\n\tat org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:215)\n\tat org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:176)\n\tat org.whispersystems.signalservice.api.crypto.SignalSealedSessionCipher.decrypt(SignalSealedSessionCipher.java:57)\n\tat org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:212)\n\tat org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:158)\n\tat org.asamk.signal.manager.helper.IncomingMessageHandler.handleRetryEnvelope(IncomingMessageHandler.java:88)\n\tat org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessage(ReceiveHelper.java:251)\n\tat org.asamk.signal.manager.helper.ReceiveHelper.retryFailedReceivedMessages(ReceiveHelper.java:233)\n\tat org.asamk.signal.manager.helper.ReceiveHelper.receiveMessagesInternal(ReceiveHelper.java:130)\n\tat org.asamk.signal.manager.helper.ReceiveHelper.receiveMessages(ReceiveHelper.java:106)\n\tat org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:857)\n\tat org.asamk.signal.manager.ManagerImpl.receiveMessages(ManagerImpl.java:840)\n\tat org.asamk.signal.commands.ReceiveCommand.handleCommand(ReceiveCommand.java:62)\n\tat org.asamk.signal.App.handleLocalCommand(App.java:273)\n\tat org.asamk.signal.App.init(App.java:213)\n\tat org.asamk.signal.Main.main(Main.java:58)\n"}

Restarting the docker container did not help, sending messages w and w no attachments from the registered account works just fine (The account is a member of a group, is this issue perhaps related to https://github.com/AsamK/signal-cli/issues/290 ?).

In order to allow users to upload certain files to a web app and then see the result in a timely manner, I have been running a cron job that looks for new messages every minute. Does that approach "overstress" either the underlying cli or the Signal service itself, and ultimately results in a block?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
> In order to allow users to upload certain files to a web app and then see the result in a timely manner, I have been running a cron job that looks for new messages every minute. Does that approach "overstress" either the underlying cli or the Signal service itself, and ultimately results in a block?

I don't think so. That should work, although it is pretty inefficient. In that case it is better to switch to the `json-rpc` mode, which uses a websocket connection for the receive endpoint.

Was it working before or does it behave like that since you registered the number? In case the issue appeared at some point, you could try to start from scratch by removing the `signal-cli-config` directory from the filesystem and re-register the number.

**Comment by UliEi** [comment]
Thanks a lot for your help. 

Receiving messages did work in the first place, but stopped working at some point; I have no clue what the root cause was. After having started a new container (w the account number still registered), receiving messages now does work again.

As to switching to json-rpc mode, I need to familiarize myself with how to work with WebSockets from within an ASP.Net Core application. Things take a new turn every day ...

**Comment by UliEi** [comment]
After having played around a little, fetching messages from a container in json-rpc mode now works like a charm with a noticeable gain in speed. Your comments in https://github.com/bbernhard/signal-cli-rest-api/discussions/160 turned out to be helpful in the process.

Thanks again for great tool and your advice.

**Comment by bbernhard** [comment]
Sorry for the late reply. I am glad that it is working now :)
