### ISSUE TITLE
Home Assistant Add-on does not start

### ISSUE THREAD

**Issue by abaskin** [bbernhard/signal-cli-rest-api#25]
I am attempting to run the Home Assistant Add-on using the Add-on Store. The Add-on appears to install correctly, but when it is started the log produces the following error:

[FATAL tini (7)] exec main failed: No such file or directory

and is does not start.

I am running Home Assistant 0.113.3

**Comment by bbernhard** [comment]
This should be fixed by this pull request here: https://github.com/haberda/hassio_addons/issues/2
