### ISSUE TITLE
Error while adding members to a group

### ISSUE THREAD

**Issue by IvanHaentjensANB** [bbernhard/signal-cli-rest-api#250]
### The problem

When executing the add member API in postman, I receive this error:

"error": "WARN  AccountHelper - Messages have been last received 16 days ago. The Signal protocol expects that incoming messages are regularly received.\nFailed to send message: StatusCode: 400 (GroupPatchNotAcceptedException)\n"

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

other

**Comment by bbernhard** [comment]
When you are in `normal`/`native` mode you need to manually call the `receive` endpoint regularily. Please try to call the `receive` API endpoint first and then try again.

**Comment by IvanHaentjensANB** [comment]
Thanks Bernhard. First error is gone now.
Still have this one when trying to add members though:
"error": "Failed to send message: StatusCode: 400 (GroupPatchNotAcceptedException)\n"

**Comment by bbernhard** [comment]
Does that error happen always? I mean, if you create a new group via the REST API endpoint without any members, do you still get the error? Do you get the error only when you add a particular member to a group or does the error occur for every member you want to add?

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
