### ISSUE TITLE
Hide Phone number

### ISSUE THREAD

**Issue by Gottarocket** [bbernhard/signal-cli-rest-api#251]
I understand that its easy to fetch and send response to signal application by posting calls from JSON but if there was a option to hide it on the server it would be good. I am not familiar with it so please treat this as a question . I run this on VPS along with uptime kuma so that there wont be issue if my local system goes down. But storing it in plain text doesn't sit right with me . Maybe I am paranoid but would like to know if there is any way to store it as secret as in docker or hash the phonenumber once the setup is done.

**Comment by bbernhard** [comment]
This is just a wrapper around [signal-cli](https://github.com/AsamK/signal-cli) - all the heavy lifting is done by signal-cli. Unfortunately, I do not know the internals of the Signal protocol in detail, but I _think_ the phone number is used as identifier in the Signal network. So, hashing the number might not be possible. But please create a issue in the signal-cli repository if you want to be sure :)
