### ISSUE TITLE
Couldn't send message to golang channel, as there's no receiver

### ISSUE THREAD

**Issue by asad-awadia** [bbernhard/signal-cli-rest-api#255]
### The problem

getting this when sending a message via v2/send using json-rpc mode?

```
Couldn't send message to golang channel, as there's no receiver
```

@bbernhard 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by asad-awadia** [comment]
getting 400 on sending a message?

 no logs why

**Comment by bbernhard** [comment]
Can you please connect to the docker container with:

`docker exec -it <container id> /bin/bash`

and have a look inside the `/var/log/signal-cli-json-rpc` folder. Do you see any errors there?

Does the `native`/`normal` mode work?

**Comment by asad-awadia** [comment]
@bbernhard 
```
WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 100 ms
```

just lots of these


craziest part is that for 1 number messages don't go at all

and for 1 type of number only some messages go

but for my number all messages go

**Comment by asad-awadia** [comment]
starting working on its own - closing issue
