### ISSUE TITLE
CAPTCHA proof required when sending to new phone number

### ISSUE THREAD

**Issue by Emi94** [bbernhard/signal-cli-rest-api#258]
### The problem

After successfully sending messages to 2 new phone numbers on the 3rd new phone number I get:
> {"error":"WARN  SendHelper - Failed to send message due to IO exception: Unable to parse entity\nFailed to send message\n"}

But sending to the first 2 numbers still works

After entering the container and running `signal-cli --verbose -u +40712345678 send -m "test message" +40712345678` to send a message to the 3rd number that fails I get:

> Failed to send (some) messages:
> +40712345678: CAPTCHA proof required for sending to "+40712345678", available options "RECAPTCHA, PUSH_CHALLENGE" with challenge token "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", or wait "86400" seconds.
> To get the captcha token, go to https://signalcaptchas.org/challenge/generate.html
> Check the developer tools (F12) console for a failed redirect to signalcaptcha://
> Everything after signalcaptcha:// is the captcha token.
> Use the following command to submit the captcha token:
> signal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN

After this I ran `signal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha signal-recaptcha-v2.6L....` and I'm able to send messages to other 2 new numbers but on the 3rd I get the above error again.

Any idea how to send messages to more new phone numbers without having to manually solve the captcha multiple times?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

### Additional information

To send messages I've linked the docker container through the QR code, rather then register the phone number as a new account

**Comment by bbernhard** [comment]
I think you might be running into this issue: https://github.com/AsamK/signal-cli/issues/965

**Comment by Emi94** [comment]
I've read that issue before as well. But I'm using the lastest signal-cli-rest-api which has signal-cli 0.10.8. Signal-cli 0.10.9 is now the lastest version, maybe an upgrade is required?

And about receiving messages, I've ran the docker container with -e 'AUTO_RECEIVE_SCHEDULE=0 22 * * *' as recommended if I'm not periodically reading them, but can't find any cron set in the container. Is this option not working or have I not set it correctly?

**Comment by bbernhard** [comment]
Here's a docker test image with the latest signal-cli version: `bbernhard/signal-cli-rest-api:0.111-dev`

**Comment by Emi94** [comment]
I've tested with `json-rpc` before, but I couldn't send messages at all and gave up on that mode. Don't remember the exact error.

But now I have tested `bbernhard/signal-cli-rest-api:0.111-dev` with `json-rpc` and I was able to send messages to 5 different people without any problem. I'll leave it be for a day or two and see if I'm still able to send messages as I've also had problems by letting the server sit for a night and then refuse to send in the morning.

**Comment by Emi94** [comment]
@bbernhard do you have a plan to release `0.111-dev` as a stable version? So far my tests with `0.111-dev` and `json-rpc` mode have worked fine.

**Comment by bbernhard** [comment]
just pushed the stable tag to dockerhub.

**Comment by Emi94** [comment]
@bbernhard I installed the latest version, but it is using signal-cli 0.10.7, which is even older.

Is this intentional?

**Comment by Emi94** [comment]
It works nicely now in production, so I'm closing the issue. Thanks for the help.
