### ISSUE TITLE
Register with captcha by CLI isn't working

### ISSUE THREAD

**Issue by AlimFreight** [bbernhard/signal-cli-rest-api#259]
I am trying to register a number following the guide :

> When you try to register a number, if you receive a response like {"error":"Captcha required for verification (null)\n"} then Signal is requiring a captcha. To register the number you must do the following:
> 
> Go to https://signalcaptchas.org/registration/generate.html
> Open the developer console
> Find the line that looks like this: Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol. Copy the captcha value
> Use it to make the registration call like this:
> curl -X POST -H "Content-Type: application/json" -d '{"captcha":"captcha value"}'

But firstly I can't find "Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol" any more but find 

this <input type="hidden" id="recaptcha-token" value=here........">

When I use this captcha  I have received this error {"error":"Failed to register: [400] Response: {\"code\":400,\"message\":\"too few parts\"}\n"}%  

Any suggestion on this issue?   

So I put docker container on my VPS and got captcha from my https://my-server/v1/qrcodelink?device_name=signal-api
but when I try to link my number I am getting either “No device found” or "Network error"  Sometimes I got "Device activated successfully"  but it does't appear in Linked devices list.

**Comment by bbernhard** [comment]
> But firstly I can't find "Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol" 

Which browser do you use? Just tried with Firefox and it works for me like that.

**Comment by AlimFreight** [comment]
I am using chrome, but I don't think it depends on browser maybe  I so dumb , I simply chose Inspect element and then console opens but I can't find that line. I tried Firefox but couldn't find it either .
![image](https://user-images.githubusercontent.com/54543689/180555417-d52a9905-1874-4733-9c53-4821036c54bd.png)

**Comment by AlimFreight** [comment]
> > But firstly I can't find "Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol"
> 
> Which browser do you use? Just tried with Firefox and it works for me like that.

But could you please tell me what is going on which second approach where I am scanning Captcha and the getting these errors ?

**Comment by bbernhard** [comment]
In Firefox you should be able to Captcha in the Web Developer Console (More Tools -> Web Developer Console).

After you've opened, just complete the captcha challenge. Aftwards you should see the captcha appear in the console.

**Comment by AlimFreight** [comment]
> In Firefox you should be able to Captcha in the Web Developer Console (More Tools -> Web Developer Console). > > After you've opened it, just complete the captcha challenge. Aftwards you should see the captcha appear in the console.

Thank you for advice. I finally was able to register number. It didn't work for some reason on my Mac until I switched to Linux :).

But I'm still trying to link my already registered number to signal_api. Every time I try I am getting "Phone Approved" but it's doesn't appears in Linked devices section. Does it depends on phone model? Or any other reason why this could happen?

**Comment by bbernhard** [comment]
> It is definitely depends on phone, I was able to link it on Google Pixel. But I need to link number which is connected to One Plus phone :(

That's strange. I have a One Plus 5t here and it works fine. Also I can't think of any reason why it would be device specific. :thinking: 

I guess you use a different phone number on the Google Pixel, right? Or did you use the same phone number as with the One Plus?

**Comment by AlimFreight** [comment]
> That's strange. I have a One Plus 5t here and it works fine. Also I can't think of any reason why it would be device specific. 🤔 I guess you use a different phone number on the Google Pixel, right? Or did you use the same phone number as with the  One Plus?


 Yes it's different phone number, but how its related to linking process? I am changing number in a 'link request' accordingly.

**Comment by AlimFreight** [comment]
> > It is definitely depends on phone, I was able to link it on Google Pixel. But I need to link number which is connected to One Plus phone :(
> 
> That's strange. I have a One Plus 5t here and it works fine. Also I can't think of any reason why it would be device specific. 🤔
> 
> I guess you use a different phone number on the Google Pixel, right? Or did you use the same phone number as with the One Plus?

Here is a log after I kind of linked number on OnePlus 8T Android 12 
```
+ [ json-rpc = json-rpc ]
+ /usr/bin/jsonrpc2-helper
time="2022-07-28T14:36:25Z" level=info msg="Found number +1(GooglePixelNumber) and added it to jsonrpc2.yml"
time="2022-07-28T14:36:25Z" level=info msg="Found number +1(OnePlusNumber) and added it to jsonrpc2.yml"
+ service supervisor start
time="2022-07-28T14:36:26Z" level=error msg="Couldn't read data for number +1(OnePlusNumber): EOF. Is the number properly registered?"

```
Number that was registered by GooglePixel works properly.

**Comment by bbernhard** [comment]
Could you please:

* connect to the running docker container with `docker exec -it <container id> /bin/bash`
* check the `/var/log/signal-cli-json-rpc` folder inside the docker container whether the error log contains any errors

Does it work if you temporarily switch from the json-rpc mode to the normal/native mode?

**Comment by fnordson** [comment]
> > But firstly I can't find "Prevented navigation to “signalcaptcha://{captcha value}” due to an unknown protocol"
> 
> Which browser do you use? Just tried with Firefox and it works for me like that.

Hi.
I'm using Firefox for that but as soon as I've solved the captcha a popup comes up asking me to chose an application to open the "signalcaptcha link". 
![signal1](https://user-images.githubusercontent.com/5624605/194701253-8b56745c-8c9e-4c4f-bd37-c0ce7eb25a58.png)

There is nothing in the console. 
If I hit "open", I can see the link in the title of an error msg but can't get to it: 

![signal2](https://user-images.githubusercontent.com/5624605/194701275-e40f9f5b-af68-4dad-b4a5-610a48951f8e.png)

**Comment by zikeji** [comment]
You can get the link from the network tab. Just make sure you open dev tools before finishing the captcha.

**Comment by sh00t2kill** [comment]
I had the same problem, using chrome.
Tried in edge and it "just worked"
