### ISSUE TITLE
Growing container size due to missing cleanup for /tmp/*.{jpg,mp4} files 

### ISSUE THREAD

**Issue by bentolor** [bbernhard/signal-cli-rest-api#26]
Thanks for providing this great glueing service, @bbernhard ! I [recently praised it in my stream ;-)](https://twitter.com/bentolor/status/1291370025014702081)

I stumbled over a minor issue/annoyance:  A `sudo docker container ls -s` reveals the following:

```
58f27f04c663        bbernhard/signal-cli-rest-api            "signal-cli-rest-api"    7 days ago          Up 7 days           0.0.0.0:9922->8080/tcp                           signal-api                                   118MB (virtual 2.04GB)
```

On inspecting with `container diff` reports the following situation:

```
$ sudo docker container diff signal-api
C /tmp
A /tmp/10096571-0b51-41ac-84cc-44bd77a6fc4e.mp4
A /tmp/193791b7-a84c-4458-823d-6120b33c6b56.jpg
…
A /tmp/c37bebc6-c6a8-40b6-92c4-c770a97bdfeb.jpg
A /tmp/dfbea440-7709-4600-9065-7ce02fe76ba7.jpg
C /tmp/hsperfdata_root
D /tmp/hsperfdata_root/57
A /tmp/2c1f1207-e9ca-47c7-b1c3-3a7dc064b792.jpg
…
```

A container restart does not clean them up. 

After inspecting the code it seems there is also some sort of cleanup logic. Not sure where the fallthrough is lying: [func cleanupTmpFiles()](https://github.com/bbernhard/signal-cli-rest-api/blob/3b6957299209f14e2023268219e41fc32d5ec184/src/api/api.go#L84)

For me it seems that nearly _no_ cleanup happened at all, because the file list more or less matches all media files I yet sent via the API?!

**Comment by bbernhard** [comment]
Many thanks for your bug report...and also for the kind words on Twitter - very much appreciated! :)

I _think_ I've an idea why this is happening. I am testing the fix now :)

**Comment by bbernhard** [comment]
Ok, looks good. I am currently building the images for dockerhub. I'll let you know as soon as they are up :)

**Comment by bentolor** [comment]
Awesome! Thanks for you lightning fast fix!

**Comment by bbernhard** [comment]
No problem! :)

The images on dockerhub should now be updated.
