### ISSUE TITLE
unable to integrate signal rest api docker with HAss

### ISSUE THREAD

**Issue by esatravi** [bbernhard/signal-cli-rest-api#263]
### The problem

My setup is the following - HAss running on one Raspberry Pi 4, and the docker with the  signal_rest_api on another raspberry. Both rpi4 are on separate VLANs but can see each other, ping each other and ssh each other. 

Also, when 'curl ...' command is executed in the rpi4 with the signal-rest-api docker the message get through to whatever phone number I configured. 
The same is true when executing 'curl' command in the Hass ssh-terminal addon - the message gets send and received. 

The problem is that I wasn't able to configure the configuration.yaml in HAss so that  an automation workflow triggers signal message notification to my phone. And it's strange as the configuration seems very simple:

notify:
  - name: signal
    platform: signal_messenger
    url: "http://127.0.0.1:8080" # the URL where the Signal Messenger REST API is listening 
    number: "YOUR_PHONE_NUMBER" # the sender number
    recipients: # one or more recipients
      - "RECIPIENT1"

That's it. For some strange reasons I still can't trigger the message directly from the HAss automation. 

Does anyone have suggestions of where the problem could be? 
Than you.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you tried sending a notification in the Home Assistant developer tools? Do you see any error messages in the Home Assistant log?

**Comment by esatravi** [comment]
Thank you for such quick reply. I've actually logged in to close this issue. The problem was that I had to restart HAss in order for the new configuration to kick-in. All is working again by the books.
