### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by rajil** [bbernhard/signal-cli-rest-api#266]
### The problem

I linked the device succesfully using the QRcode. However sending a message doesnt work,

```
$ curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send'      -d '{"message": "Test via Signal API!", "number": "+Redacted", "recipients": [ "+Redacted" ]}' 
$: command not found
```
Any idea why it is returning `command not found`?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Please try with signal-cli directly (see https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and post the obfuscated output here

**Comment by bbernhard** [comment]
> Failed to send message due to untrusted identities

Looks like the recipients identity changed recently. Please use the [trust](https://bbernhard.github.io/signal-cli-rest-api/#/Identities/put_v1_identities__number__trust__numberToTrust_) endpoint to trust the new identity.

**Comment by rajil** [comment]
I am trying to send a message to myself i.e. send and receiver are the same number. How can i trust my own number?

**Comment by rajil** [comment]
Never mind, the endpoint worked after i set my  'verified_safety_number' obtained from the configuration.
