### ISSUE TITLE
Unable to send message to the group

### ISSUE THREAD

**Issue by bboybboy** [bbernhard/signal-cli-rest-api#267]
### The problem

Hi team!

I'm trying to send a message to the group. 

So I ran docker with `signal-cli` 
Register my acc on -  `http://localhost:8080/v1/qrcodelink?device_name=signal-api`
Send a `receive` request to be able to get a group id.

But when I'm trying to send a message to the group with body
`
{
    "message": "Blah Blah",
    "number": "+*******",
    "recipients":
    [
        "group.UkFCVitIRXdYSm5rQnRSTDZCbWEvVzlIZkIrWjU5WCtuRGNsV2dZTUZlOD0="
    ]
}
`

POST to http://localhost:8081/v2/send

I got an error - **400 Bad Request: "{"error":"Invalid account (phone number), make sure you include the country code.\n"}"**

BUILD_VERSION 0.61

Is it possible to fix it somehow?

Thanks in advance

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
> BUILD_VERSION 0.61

Do you get the same error with the latest (`0.62`) version?

> I got an error - 400 Bad Request: "{"error":"Invalid account (phone number), make sure you include the country code.\n"}"

Have you included the country code, as the error message states?
