### ISSUE TITLE
A little security advise

### ISSUE THREAD

**Issue by devrob20** [bbernhard/signal-cli-rest-api#268]
dont expose ports in production env, 

this a huge security risk. the problem is signal needs to link a phone number as sender. it would be much more secure when you could link your group as sender. but even then it can pull (receive) all messages. this makes me wonder how secure these cli tools are, thats why you wont see whatsapp support as they share this same design flaw in security. 

**once setup, is there a way to set a password or key for receive ? so it only acts as a sender ? and the owner of the phonenumber get a request to approve ?**

if you need signal-cli withs apps like uptime in docker, attach it to the uptime network of your docker app and use localhost.  both of these examples dont have a dedicated network so you need to "docker create network" or just a gui like portainer and place the signal-cli into that.

if you need root access, exec into the container and run the code command line, exposing the api is bad idea, even over the cluster or your local lan, it exposes all the data from that signal phone number like all the contacts and chat logs in plaintext.

**Comment by kolpav** [comment]
Nothing is preventing you from configuring the container however you want no? Also there is no mention of production in project description then there is link to how to run in in azure which includes Authentication so enough resources to get you going.

> once setup, is there a way to set a password or key for receive ? so it only acts as a sender ? and the owner of the phonenumber get a request to approve?

I would argue this is up to you to build and out of scope of this project it just exposes signal apis

**Comment by bbernhard** [comment]
As @kolpav already mentioned it's up to you to configure your setup the way you want. e.g you can put the REST API wrapper behind a reverse proxy to add SSL and authentication.

**Comment by CodeShellDev** [comment]
Hey there if @devrob20 you are looking for auth and restricting access to specific endpoints for specific numbers
maybe try out this proxy I made: [Github Repo](https://github.com/CODESHELldev/secured-signal-api). It doesn't handle Certs, but implements all kinds of access control features for reducing permission and attack surface.

Hope this helps!
