### ISSUE TITLE
Messages are not receiving on the webhook

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#270]
### The problem

We have registered a signal bot using an Indian number using "/register" signal api.
For some users the messages are not receiving on the webhook and getting following error message.

_The user’s key is untrusted, either the user has reinstalled Signal or a third party sent this message.|
Use 'signal-cli -u +919606xxxxx listIdentities -n 116e0b06-7f93-4bd1-xxxxxxxxx', verify the key and run 'signal-cli -u +919606xxxxx trust -v "FINGER_PRINT" 116e0b06-7f93-4bd1-xxxxxxxxx' to mark it as trusted
If you don't care about security, use 'signal-cli -u +91960xxxxxxxxx trust -a 116e0b06-7f93-4bd1-8096-xxxxxxxxx' to trust it without verification_

Can you please check and let us know what could be the issue here?

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
As the error message states, the user's key has changed. You need to invoke the `trust` endpoint (see the swagger documentation for details) and confirm the new key.

**Comment by jyothisjose** [comment]
> As the error message states, the user's key has changed. You need to invoke the `trust` endpoint (see the swagger documentation for details) and confirm the new key.

We have called the following curl command to get "safety_number" to provide in "v1/identities/+REGISTERED_PHONE_NUMBER/trust/+NUMBER_TO_TRUST" api as "verified_safety_number"

curl -X 'GET' \
'API_URL/v1/identities/+REGISTERED_PHONE_NUMBER' \
-H 'accept: application/json'

But we are getting 504 Gateway Time-out error.

Can you please guide us to solve this issue

**Comment by jyothisjose** [comment]
Do you have any update on this issue

**Comment by bbernhard** [comment]
Do you still get the Gateway Timeout error? Are you sure that the number is properly registered? Do other endpoints (like the `receive` endpoint) work or do you also get errors?

**Comment by jyothisjose** [comment]
> to get "safety_number"

**Comment by jyothisjose** [comment]
> Do you still get the Gateway Timeout error? Are you sure that the number is properly registered? Do other endpoints (like the `receive` endpoint) work or do you also get errors? Are you using the latest version?

Receive functionality is working fine. But we are still getting "Gateway Timeout" error for the API to get "safety_number".

**Comment by jyothisjose** [comment]
> > Do you still get the Gateway Timeout error? Are you sure that the number is properly registered? Do other endpoints (like the `receive` endpoint) work or do you also get errors? Are you using the latest version?
> 
> Receive functionality is working fine. But we are still getting "Gateway Timeout" error for the API to get "safety_number".

Do you have any update on this issue
