### ISSUE TITLE
Other person in the Group does not receive messages sent using CLI REST API

### ISSUE THREAD

**Issue by ghnp5** [bbernhard/signal-cli-rest-api#275]
### The problem

I'm sending a request to:

`http://signal-cli-rest-api:8080/v2/send`

With the following content:

```
{
"message": "This message.",
"number": +XYZ<my_number>,
"recipients": [ "group.xyzxyzxyzxyz.....=" ],
}
```

This group has myself and someone else in it.

I have Signal synchronizing between my mobile device and desktop device.

Any messages I send **manually** (using the Signal Desktop app) in that group, **the other person receives** without any problem.

However, the messages that send **through the CLI REST API don't seem to be reaching the other person** (both their devices), but I see them in the group on both my devices.

Do you know why isn't the other person receiving any messages sent using the CLI REST API?
Is it because I'm not running the "Receive API"? Not sure if it makes sense, because the problem is on the other person's devices not receiving the message, but I receive on my devices...

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
In `normal`/`native` mode it is required to periodically call the `receive` endpoint. If you don't want to do that, I'd suggest to use the `json-rpc` mode (which is my recommendation anyways).

**Comment by ghnp5** [comment]
@bbernhard 

> periodically call the receive endpoint.

Thanks. I invoked "receive", but seems none of the previous messages delivered to the other person

However,

> I'd suggest to use the json-rpc mode

I switched to "json-rpc" mode, and seems new messages are delivering the other person!

Thank you very much! :-)
