### ISSUE TITLE
Q: expected to be soon EOL?

### ISSUE THREAD

**Issue by marcelstoer** [bbernhard/signal-cli-rest-api#277]
This project depends on https://github.com/AsamK/signal-cli which in turn depends on https://github.com/signalapp/libsignal-protocol-java which...is EOL (the repo is read-only).

Hence, can we expect that this project too will sooner or later become EOL?

Or, are there plans to rebase onto https://github.com/signalapp/libsignal?

**Comment by AsamK** [comment]
signal-cli uses https://github.com/Turasa/libsignal-service-java which is still maintained. And which internally uses libsignal-client already instead of libsignal-protocol-java.

**Comment by marcelstoer** [comment]
@AsamK thanks, all good. I just read your project's README again and realized where I had missed the mention of the Turasa/libsignal-service-java project.
