### ISSUE TITLE
Not receiving verification code via txt or call

### ISSUE THREAD

**Issue by alastairayliffe** [bbernhard/signal-cli-rest-api#278]
### The problem

Firstly, thank you! Signal-cli-rest-api is awesome!!!!

I'm trying to register a number so I can switch to mode json-rpc. I'm running the docker on AWS.

I've followed you guidelines requesting a verification code first via txt message (I tried this twice) and then via a phone call (tried this once)..

e.g.
```
curl -X POST -H 
"Content-Type: application/json" 
'xxxURLxxx/v1/register/+447984855358' 
```

then 

```
curl -X POST -H 
"Content-Type: application/json" 
--data '{"use_voice": true}' 
'xxxURLxxx/v1/register/+447984855358'
```

They both run fine within the docker (without error). See below -

`[GIN] 2022/09/10 - 06:43:43 | 201 | 8.105674763s | 10.0.2.108 | POST "/v1/register/+447984855358"`

But I don't receive a verification code via SMS when sending via signal-cli-rest-api... I just installed signal and received their own verification code via SMS (when installing). I went through signal's trouble shooting for receiving a code and this didn't help...

Any help appreciated!!

Thanks,

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Could you please enable the debug mode (see https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and execute the signal-cli command directly. Does it work that way?

**Comment by alastairayliffe** [comment]
Hey @bbernhard,

Thanks for the quick response.

I ran the command and couldn't see an error... But, think I've figured it out :)... I was 'linking' the device to a mobile, prior to registering it. I believe the messages won't send if you'd already linked the device?...

Anyhow its sorted (I unlinked the device and started receiving the messages). Thanks again for your help...

**Comment by bbernhard** [comment]
Great! Glad it works now :)

**Comment by alastairayliffe** [comment]
All good, thanks
