### ISSUE TITLE
Support for native deployments (no docker)

### ISSUE THREAD

**Issue by oddlama** [bbernhard/signal-cli-rest-api#283]
### Feature Request
Thanks for the great project! One thing that I'm dearly missing is the ability to deploy this on bare-metal, without relying on docker. The problem is that in certain situations, docker might not be a viable option to deploy a project. We for example are using an extremely strict nftables firewall, for which docker has no compatibility (and docker will likely still take some years to catch up).

For the time being, I used the attached script to extract the latest version of this rest api from your docker image, and deployed that manually instead, but going forward I'd love to see an officially supported way to do native deploys. I'm sure this would be greatly appreciated by many folks that have similar issues or are working with resource-constrained systems. I'd be glad if you would consider it.

### Temporary native-deploy script

```bash
#!/bin/bash

# WARNING: This script requires a user 'signal-cli' with /var/lib/signal-cli as the home directory.
# Afterwards yo

set -uo pipefail
function die() { echo "error: $*" >&2; exit 1; }
function try() { "$@" || die "Command failed: $*"; }

TMP="$(mktemp -d)" || die "Could not create tmpdir"
trap 'rm -rf -- "$TMP"' EXIT

try cd "$TMP"
try wget https://raw.githubusercontent.com/moby/moby/master/contrib/download-frozen-image-v2.sh
try chmod +x download-frozen-image-v2.sh
try ./download-frozen-image-v2.sh container bbernhard/signal-cli-rest-api:latest

for i in $(jq -r ".[0].Layers[]" container/manifest.json); do
        echo "Processing layer $i"
        layer="container/$i"
        contents="$(tar tvf "$layer")"
        if signal_cli="$(grep -o " opt/signal-cli-[^/]*/$" <<< "$contents")"; then
                try tar xvf "$layer" "${signal_cli:1}"
        fi
        if grep -q " usr/bin/signal-cli-rest-api" <<< "$contents"; then
                try tar xvf "$layer" usr/bin/signal-cli-rest-api
        fi
done

[[ -e /var/lib/signal-cli/signal-cli ]] && try rm -rf /var/lib/signal-cli/signal-cli
try cp -vr opt/signal-cli-* /var/lib/signal-cli/signal-cli
try cp -vr usr/bin/signal-cli-rest-api /var/lib/signal-cli/signal-cli/bin

try ln -s /var/lib/signal-cli/signal-cli/bin/signal-cli /usr/bin/
try ln -s /var/lib/signal-cli/signal-cli/bin/signal-cli-native /usr/bin/
try ln -s /var/lib/signal-cli/signal-cli/bin/signal-cli-rest-api /usr/bin/
```

### Systemd service file `signal-cli-rest-api.service`

```systemd.service
[Unit]
Description=signal-cli REST API
Documentation=https://github.com/bbernhard/signal-cli-rest-api
After=network.target

[Service]
Environment=MODE=native
Environment=GIN_MODE=release
Environment=PORT=8080
Type=simple
User=signal-cli
Group=signal-cli
WorkingDirectory=/var/lib/signal-cli
ExecStart=/var/lib/signal-cli/signal-cli/bin/signal-cli-rest-api -signal-cli-config=/var/lib/signal-cli/data
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

(Release version environment variable is currently missing, but seems to be unproblematic)

**Comment by fow0ryl** [comment]
Would like to have a native deployment on Debian and Arch too.

**Comment by bbernhard** [comment]
I can definitely see that something like that makes sense and would be great to have. Unfortunately, I do not have enough time to create/maintain something like that right now. In case someone wants to work on that (or create a package for a linux distribution), I'll try to assist as much as possible in case any questions arise.

**Comment by oddlama** [comment]
No worries, I can totally understand that. The part that is missing to make that possible on most distributions are released binaries. It's unmaintainable if each distribution needs a copy of you build workflow, that has to be updated in case you change something.

The best thing that I can think of right now would be to create a github action workflow that automatically builds and publishes the required artifacts when you make a release. Those could then be used to create the docker container instead of the other way around. Unfortunately I'm currently also not able to implement this, but this should be an easy first issue for someone familiar with github actions.
