### ISSUE TITLE
Deprecated version exception, prevents receiving messages

### ISSUE THREAD

**Issue by etlweather** [bbernhard/signal-cli-rest-api#286]
### The problem

On receiving, getting status 400 error, deprecated version. This just started a few minutes ago. Also mentioned in a comment in issue #243 (https://github.com/bbernhard/signal-cli-rest-api/issues/243#issuecomment-1268971240)

Seems like this would be fixed by updating to latest `signal-cli`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

amd64

**Comment by zagl** [comment]
I get the same error. I also tried the latest version of signal-cli (v0.11.1) and even there I get StatusCode 499.

**Comment by dmlitvinov** [comment]
We have the same problem, problems started 20-30 minutes ago

**Comment by etlweather** [comment]
> I get the same error. I also tried the latest version of signal-cli (v0.11.1) and even there I get StatusCode 499.

@zagl Maybe you could open an issue then on `signal-cli` project with all details you have.

**Comment by etlweather** [comment]
Someone just did - https://github.com/AsamK/signal-cli/issues/1022

**Comment by aneisch** [comment]
I'm wondering if this is actually due to the version of libsignal-client used in the build of this container. Looks like `master` is using [LIBSIGNAL_CLIENT_VERSION=0.17.0](https://github.com/bbernhard/signal-cli-rest-api/blob/master/Dockerfile#L2) from May 13, 2022. Latest is [v0.20.0](https://github.com/signalapp/libsignal/releases/tag/v0.20.0)

**Comment by etlweather** [comment]
For a quick and dirty fix, see https://github.com/AsamK/signal-cli/issues/1022#issuecomment-1269169653

**Comment by etlweather** [comment]
This project will need to be updated with the latest `signal-cli` once my pull request is merged in.

**Comment by rfrederick** [comment]
I've had the same issue since around the same timestamp. Currently the only piece of routine functionality that's working for me is sending to groups.

**Comment by aneisch** [comment]
> For a quick and dirty fix, see [AsamK/signal-cli#1022 (comment)](https://github.com/AsamK/signal-cli/issues/1022#issuecomment-1269169653)

Thank you!

Pertaining specifically to this project here's the workaround:

Get a shell in your signal-rest-api container (you'll need the container name):
`docker exec -it signal_rest_API_container_name /bin/bash`

Apply the fix by pasting the following in the container's shell:
```
apt update && apt install -y zip unzip && \
cd /opt/signal-cli-0.10.9/lib/ && \
mkdir tmp && \
cd tmp/ && \
unzip ../signal-cli-0.10.9.jar && \
sed -i 's/Signal-Android\/5.22.3/Signal-Android\/5.51.7/g' org/asamk/signal/BaseConfig.class && \
zip -r ../signal-cli-0.10.9.jar org/ META-INF/ && \
cd .. && \
rm -rf tmp/ $$ \
exit
```

Now restart the container:
`docker restart signal_rest_API_container_name`

**Comment by etlweather** [comment]
@bbernhard We should be able to have an updated build of `signal-cli` soon - my pull request with the fix was merged. In the mean time, I hacked the `signal-cli-rest-api` Docker image on my machine with the latest (modified) version of `signal-cli` and the latest `libsignal-client` and it is working well. 

Would be awesome if you could publish a build with the latest once it is available.

**Comment by bbernhard** [comment]
Here's a test version `bbernhard/signal-cli-rest-api:0.112-dev` with the workaround applied. It should work on all architectures, except arm64 in native mode. It still uses signal-cli v0.10.9, as there are some problems with building the newer libsignal-client version for armv7.

**Comment by UliEi** [comment]
I am having similar issues regarding the 499 error, unfortunately, I am not sure when they started. 

Updating the docker container to version 0.112-dev did not help, as I now get the error ->level=error msg="Couldn't read data for number +49*******: EOF. Is the number properly registered?" <- when I tried to run the updated container. The number is registered, sending and receiving messages works fine from a cell phone. The accounts.json file reads

cat $HOME/.local/share/signal-cli/data/accounts.json
{
  "accounts" : [ {
    "path" : "6 digits",
    "environment" : null,
    "number" : "+49*******",
    "uuid" : "numerous digits"
  } ],
  "version" : 2
}

Killing and re-establishing the Signal account (admittely an act of desperation) did not help either. Am I making a stupid mistake, or is there still an issue?

Thx for your help    Uli

**Comment by UliEi** [comment]
Another attempt to start from scratch, using v 0.112-dev, worked out fine. I have no clue why it did not work in the first place
