### ISSUE TITLE
error: Failed to register: StatusCode 499

### ISSUE THREAD

**Issue by prankousky** [bbernhard/signal-cli-rest-api#287]
### The problem

Hi everybody,

suddenly, my docker instance did not work any longer. So I tried to set up again by

1. deleting everything in the local folder mapped to `/home/.local/share/signal-cli`
2. pulling the latest docker image
3. stopping and deleting the current version
4. starting the new instance

When I run `curl -X POST -H 'Content-Type: application/json' --data '{"use_voice": true}' 'http://<ip>:<port>/v1/register/<landline-number>`, I get `{"error": "Failed to register: StatusCode 499\n"}%`.

I tried all these modes in my `docker-compose`:

* `MODE=native`
* `MODE=normal`
* `MODE=json-rpc`

After running the command above (countless times, different configurations), I noticed that there was this `jsonrpc2.yml`

```yml
config:
  "+49<landline>":
    tcp_port: 6000
    fifo_pathname: /tmp/sigsocket0
```

There is a `data/accounts.json` as well

```
   1   │ {
   2   │   "accounts" : [ {
   3 ~ │     "path" : "732553",
   4 ~ │     "environment" : "LIVE",
   5   │     "number" : "+<landline_00>",
   6 ~ │     "uuid" : null
   7 ~ │   }, {
   8 ~ │     "path" : "694261",
   9 ~ │     "environment" : "LIVE",
  10 ~ │     "number" : "+<landline_01>",
  11 ~ │     "uuid" : null
  12 ~ │   } ],
  13 ~ │   "version" : 2
  14   │ }
```

I tried two different landline numbers; one that I had previously (successfully) connected to `signal-cli`, and another that had never been used for signal all together.

I tried to provide an additional `"captcha": "<captcha>"` value via `curl` (even though, unlike last time I did this, I had **not** been prompted to do so), but it did not work, either.

What can I do to fix this? I can currently not receive any signal messages sent by Home Assistant.

Thank you in advance for your help :)

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by kkoouu** [comment]
I'm getting the same StatusCode while trying to send message using an already registered number:
{"error":"Error while checking account +420608XXXXXX: StatusCode: 499\n"}

This started occuring yesterday ( Oct 5 ) sometimes between 6PM - 9PM GMT

**Comment by tchoffmann** [comment]
We got the same problems starting yesterday in the evening at 22:20 CEST (which was 5.10. 20:20 GMT). Know this quite exact because of our graylog-based log monitoring. 
We have this issue with version 0.57 but I also tested locally with latest docker image 0.62 and problem is the same. Would be great to get help/feedback soon if possible.

**Comment by abezruchenkov** [comment]
The same problem!

**Comment by Cadsters** [comment]
Theres a temp fix look [here](https://github.com/bbernhard/signal-cli-rest-api/issues/286#issuecomment-1269838852)

**Comment by tischenkoa** [comment]
> same error - stopped working yesterday evening & now registering new number also seems to throw this issue

https://github.com/bbernhard/signal-cli-rest-api/issues/286

**Comment by tchoffmann** [comment]
Thanks a lot from our side as well - fix is working fine.
