### ISSUE TITLE
/v1/qrcodelink?device_name=Name returns 404

### ISSUE THREAD

**Issue by MiKuBB** [bbernhard/signal-cli-rest-api#288]
### The problem

calling "curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://192.168.26.7:8080/v1/qrcodelink?device_name=HomeAssistant'" return 404 not found.

here are the logs from contianer.
signal-cli-rest-api    | [GIN] 2022/10/07 - 08:17:01 | 404 |       1.212µs |      10.8.2.110 | POST     "/v1/qrcodelink?device_name=HomeAssistant"
signal-cli-rest-api    | [GIN] 2022/10/07 - 08:17:03 | 404 |       1.188µs |      10.8.2.110 | POST     "/v1/qrcodelink?device_name=HomeAssistant"

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

I tryed also normal and native mode.

**Comment by bbernhard** [comment]
Could you please give this [pre-release](https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.64-pre) a try.
