### ISSUE TITLE
"Invalid username (phone number), make sure you include the country code."

### ISSUE THREAD

**Issue by greyivy** [bbernhard/signal-cli-rest-api#29]
After registering my number and trying to send a message, I get this:
Invalid username (phone number), make sure you include the country code. 

I received the registration code just fine. The number is prefixed with a +1.

**Comment by bbernhard** [comment]
If I understood correctly, you are saying the number is successfully registered, but afterwards you can't send a message? How do you send the message? 

Can you please try to send a message via cURL? 

e.g: 

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "<your number registered with the signal service>", "recipients": ["<recipient number>"]}' 'http://127.0.0.1:8080/v2/send'
```

**Comment by greyivy** [comment]
Sorry for the late update. It started working as intended shortly after I posted this issue without any change on my end. Not sure what the issue was but everything is functional now. Thanks!
