### ISSUE TITLE
Error loading state file for user +49XXXXXXXXXX: Config file was created by a more recent version! (IOException)

### ISSUE THREAD

**Issue by OSMmapper** [bbernhard/signal-cli-rest-api#293]
### The problem

Hello,

I have a problem with sending/receiving messages with the latest version (0.63).
signal-cli is updated to the latest version (0.11.3) and sending/receiving via the console works fine.

When I want to send a message I get the following error:
"{"error":"Error loading state file for user +49XXXXXXXXXX: Config file was created by a more recent version! (IOException)\n"}"

Does anyone have an idea what this could be, or how I can fix this problem?

Thx a lot...

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Please give this [pre-release](https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.64-pre) a try

**Comment by kroerig** [comment]
Hello,

I got the same error and tried with the pre-release. But I still get this error. My Signal-CLI Version is 0.11.6

**Comment by bbernhard** [comment]
> Hello,
> 
> I got the same error and tried with the pre-release. But I still get this error. My Signal-CLI Version is 0.11.6

Please try to remove the signal-cli config folder from the filesystem and start from scratch by registering the phone number again.
