### ISSUE TITLE
High CPU usage in json-rpc mode

### ISSUE THREAD

**Issue by mericon** [bbernhard/signal-cli-rest-api#295]
### The problem

When i use the Docker in MODE=json-rpc i have 100% CPU usage at one core of my i7 10700K ...

![image](https://user-images.githubusercontent.com/1723113/196032237-ba96e2d9-3343-49fd-bf7d-e8b1b0fd1c26.png)

Is it possible to optimize it more?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by mericon** [comment]
Sorry ... had an config issue on my side

**Comment by badgerwithagun** [comment]
@mericon what was the issue on your side? Seeing the same thing here.

**Comment by danielvdbosch** [comment]
> @mericon what was the issue on your side? Seeing the same thing here.

Have you ever figured it out? I also have high cpu usage :)
