### ISSUE TITLE
AUTO_RECEIVE_SCHEDULE: Couldn't call receive for number +gBe4....

### ISSUE THREAD

**Issue by AbdulkadirAtAnb** [bbernhard/signal-cli-rest-api#296]
### The problem

When the container runs the AUTO_RECEIVE_SCHEDULE it uses not a phone number but what looks like an encrypted version of it. This leads to the receive call failing. I have redacted part of the encryption in case it is something sensitive.

```
[GIN] 2022/10/17 - 22:00:02 | 400 |  2.035521857s |       127.0.0.1 | GET      "/v1/receive/+gBe4_XXXXXXXX="
time="2022-10-17T22:00:02Z" level=error msg="AUTO_RECEIVE_SCHEDULE: Couldn't call receive for number +gBe4_XXXXXXX=: {Invalid account (phone number), make sure you include the country code.\n}"
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by AbdulkadirAtAnb** [comment]
Yes, when we perform the receive call manually it works. And sending messages also works.

**Comment by bbernhard** [comment]
Could you please give this docker image a try: `bbernhard/signal-cli-rest-api:0.114-dev`

If there's no specific reason, I'd suggest to use the `json-rpc` mode instead of the `normal` mode. It is much faster and the `AUTO_RECEIVE_SCHEDULE` is not required anymore, as the messages are fetched automatically.

**Comment by guus461** [comment]
Hi @bbernhard,
I had the same problem as the OP and followed your advice. 
Indeed, much faster but also a new error/warning:

`time="2023-01-27T18:54:50+01:00" level=info msg="Started Signal Messenger REST API"
time="2023-01-27T18:54:58+01:00" level=error msg="Couldn't read data for number +31620929166: EOF. Is the number properly registered?"`

Any advice please?

**Comment by AbdulkadirAtAnb** [comment]
I had completely forgotten I had logged this issue 😄 
I jus tried with `bbernhard/signal-cli-rest-api:0.114-dev` but sadly it didn't change anything. However I've found out what is being used instead of the phone number. It is a groupID, except the forward slash has been replaced with an underscore.

Haven't had the chance to try out json-rpc mode yet.

**Comment by bbernhard** [comment]
please try with the latest version and open another issue if the problem still exists.
