### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by voskuh** [bbernhard/signal-cli-rest-api#30]
Hi,

I'm using this rest api as a hassio-addon. It's really easy to use it for sending messages with home assistant. 
Unfortunately sending a message is taken (too) long, approximately 10 seconds per message. When sending multiple messages after each other, things are throttling up. 

Reading https://github.com/AsamK/signal-cli/issues/351, there a two common causes for signal-cli's long response times: a long java virtual machine startup time, and the lack of cryptographic entropy. To avoid the JVM startup time, run signal-cli as a daemon and use dbus to interact with it; see https://github.com/AsamK/signal-cli/wiki/DBus-service.

By using the DBUS service another user got a really big improvement in performance. I already read [another issue](https://github.com/bbernhard/signal-cli-rest-api/issues/24) about implementing DBUS service. Is this really needed or can I do other thing to improve performance?

Thanks in advance

**Comment by bbernhard** [comment]
Just to understand your use case better: How many messages are you sending? 

If you are sending the same message to multiple recipients you could consider creating a Signal group. That way you only need to send a message once. 

Apart from that, I think the only way to really speed it up would be using the DBUS implementation. Unfortunately, support for DBUS is not yet implemented. I can have a look, but I am not sure how long it will take (it requires some changes to the Dockerfile and the REST API implementation...so it could take a bit until we have a working prototype).

**Comment by voskuh** [comment]
I'm sending messages to a group. I'm sending notifications from home assistant via signal. For example, when there is motion detection on the driveway every 5 seconds a snapshot is send. The logs show what happened. 
`[GIN] 2020/10/06 - 17:34:40 | 200 |      60.944µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:34:45 | 200 |      60.037µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:34:50 | 200 |      48.537µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:34:51 | 201 | 11.079009864s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:34:59 | 201 | 14.229681436s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:35:06 | 200 |      28.574µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:35:07 | 201 | 17.071123379s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:35:11 | 200 |      45.778µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:35:23 | 201 | 16.409366194s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:35:26 | 200 |      42.463µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:35:28 | 200 |     222.574µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:35:29 | 200 |      47.352µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:35:32 | 201 | 21.186302765s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:35:33 | 200 |       56.37µs |     172.30.32.1 | GET      "/v1/about"
[GIN] 2020/10/06 - 17:35:41 | 201 |  15.06295512s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:35:49 | 201 | 20.903031673s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:35:57 | 201 | 27.627167706s |     172.30.32.1 | POST     "/v2/send"
[GIN] 2020/10/06 - 17:36:04 | 201 | 31.314794593s |     172.30.32.1 | POST     "/v2/send"`

Also other notifications are being send, but that's not that frequently. 
Eventually I'm planning to connect my doorbell as well. But waiting 10-12 seconds before a notification is send, is a bit too long. The delivery guy is not waiting that long, lol

**Comment by bbernhard** [comment]
I see.

The problem with the DBUS implementation is, that only a subset of commands is implemented (see https://github.com/bbernhard/signal-cli-rest-api/issues/24#issuecomment-701265555 for details). And while the signal-cli DBUS daemon is running it's not possible to spawn another signal-cli process. So, by switching to the DBUS implementation we can't


 * register a phone number
 * verify a phone number
 * delete a group
 * link device via QR code

anymore. The only really ugly & hackish workaround (apart from adding the missing functionality to the upstream signal-cli) I see at the moment is to create two docker images. One image uses the DBUS interface while the other one just invokes the signal-cli binary. But as the docker image with the DBUS interface has a pretty limited functionality it would be pretty cumbersome to use. It basically means that the docker image with the DBUS implementation can just send (and maybe receive) signal messages. In case you want to do something else (e.g delete a signal group) you would need to stop the DBUS container and start the other container.

**Comment by f45tb00t** [comment]
> The only (really ugly & hackish) workaround (apart from adding the missing functionality to the upstream signal-cli, of course) I see at the moment is to create two docker images. One image uses the DBUS interface while the other one just invokes the signal-cli binary. But as the docker image with the DBUS interface has a pretty limited functionality it would be pretty cumbersome to use.

Hello Bernhard,

first of all I would like to thank you for your outstanding work. This is pretty much appreciated.
I would like to jump into that topic. Because for my understanding I don't need that functionality after I've registered the number, created a channel or configued another number where to send the details. This is done in one shot at first configuration. And for my case that's it. I don't want nor need to add additional Channels and so on.

Whats absolutelly more important to me is: Get the messages just in time and not with a delay of 10+ seconds. Example: If you want to realize that someone is in your home who does not belong there, 10 seconds can be 5 seconds too much to take action. 

So I would be very pleased if you could create an additional docker image just for sending with no delay. 

Kind Regards

fastboot

**Comment by bbernhard** [comment]
After thinking about it a bit more, I don't think that the DBUS goes well together will a REST API interface. Unfortunately, those two technologies are totally different. The DBUS is a messagebus, so basically a continuous stream of bytes whereas the REST API is more like a polling mechanism. So, I think it would make way more sense to either use websockets or MQTT for that. 

> EDIT: Would it also be possible to add the new groups? Newer versions of signal allow now group admins for example.

Could you please create a new issue for that. That way it's easier to track.

**Comment by Atomic-Bean** [comment]
> After thinking about it a bit more, I don't think that the DBUS goes well together will a REST API interface. Unfortunately, those two technologies are totally different. The DBUS is a messagebus, so basically a continuous stream of bytes whereas the REST API is more like a polling mechanism. So, I think it would make way more sense to either use websockets or MQTT for that.
> 
> > EDIT: Would it also be possible to add the new groups? Newer versions of signal allow now group admins for example.
> 
> Could you please create a new issue for that. That way it's easier to track.

To be sure, are you saying dbus is the issue, or daemons in general regarding building a REST api on that?

**Comment by bbernhard** [comment]
> > After thinking about it a bit more, I don't think that the DBUS goes well together will a REST API interface. Unfortunately, those two technologies are totally different. The DBUS is a messagebus, so basically a continuous stream of bytes whereas the REST API is more like a polling mechanism. So, I think it would make way more sense to either use websockets or MQTT for that.
> > > EDIT: Would it also be possible to add the new groups? Newer versions of signal allow now group admins for example.
> > 
> > 
> > Could you please create a new issue for that. That way it's easier to track.
> 
> To be sure, are you saying dbus is the issue, or daemons in general regarding building a REST api on that?

I think DBUS is a perfectly fine IPC mechanism, but in my opinion it doesn't map that well to a REST API interface. Don't get me wrong, it's definitely possible to write a REST API wrapper around DBUS, but in that case I would need to add some local storage to cache the received messages via DBUS. As this adds quite some complexity (e.g I need to take care to properly remove already received messages from the cache when a message was deleted), I would like to avoid that at all costs (for now). So the issue is neither DBUS nor daemons in general, it's just that I don't want to cache data on the disk as I think this will add some unnecessary complexity to the application which might not be needed (with the native binary). 

At the moment calling the `signal-cli` binary is quite slow, resulting in REST API calls that take ~20 seconds (on ARM based machines). Hopefully, that's mostly due to the slow JVM startup time and improves with the native binary.

**Comment by mightym** [comment]
@bbernhard By the way, I just tested your approach:
> The only (really ugly & hackish) workaround (apart from adding the missing functionality to the upstream signal-cli, of course) I see at the moment is to create two docker images. One image uses the DBUS interface while the other one just invokes the signal-cli binary. 

It felt like a good compromise. But I just realized that it is sadly not possible. It seems like to be some kind of security protection.  You can't run multiple `signal-cli`s sharing the same config. You could use for the DBUS service another "linked device". But I'n my case this would be overcomplicating things. 
https://github.com/AsamK/signal-cli/discussions/527

**Comment by bbernhard** [comment]
> @bbernhard I just tested your approach:
> 
> > The only (really ugly & hackish) workaround (apart from adding the missing functionality to the upstream signal-cli, of course) I see at the moment is to create two docker images. One image uses the DBUS interface while the other one just invokes the signal-cli binary.
> 
> It felt like a good compromise. But I just realized that it is sadly not possible. It seems like to be some kind of security protection. You can't run multiple `signal-cli`s sharing the same config. You could use for the DBUS service another "linked device". But I'n my case this would be overcomplicating things.
> [AsamK/signal-cli#527](https://github.com/AsamK/signal-cli/discussions/527)

Yeah, I tried that a while ago too and came to the same conclusion. But I think with the native mode (https://github.com/bbernhard/signal-cli-rest-api#native-image-experimental) it's not that big of a problem anymore.

**Comment by mightym** [comment]
@bbernhard you mean not relying on the DBUS service anymore and just using the native mode for everything?

**Comment by bbernhard** [comment]
> @bbernhard you mean not relying on the DBUS service anymore and just using the native mode for everything?

jep, right. On my x86-64 system it takes about 2-4 seconds to send/receive messages. Other users who run the docker container on a amd64 system (e.g on a Raspberry Pi 4 with a Raspbian 64bit OS) have reported similar numbers. Of course, that's not blazingly fast (and the DBUS mode is probably still faster), but I think it's not that bad anymore.

**Comment by bbernhard** [comment]
Please use the `json-rpc` mode for better performance.

**Comment by mightym** [comment]
@bbernhard but for receiving messages without relying on a periodical fetch of messages you would still recommend using DBUS?

**Comment by bbernhard** [comment]
@mightym I've never implemented the DBUS interface (and probably never will). Currently, three modes are supported: `normal`, `native` and `json-rpc`. The first two modes require you to periodically call `receive`. The last one doesn't (it is btw. also the fastest). In `json-rpc` mode a websocket connection is used for receiving messages. So it is not necessary anymore to poll the REST API.
