### ISSUE TITLE
not work Auto Receive Schedule

### ISSUE THREAD

**Issue by tischenkoa** [bbernhard/signal-cli-rest-api#300]
### The problem

Not work Auto Receive Schedule, condition not met: `strings.HasPrefix(filename, "+")`
Number registered and send message.

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
If there's no specific reason, I would suggest switching to the `json-rpc` mode. The `json-rpc` mode is usually much faster and doesn't need the Auto Receive Schedule.

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
