### ISSUE TITLE
new phone: not receiving message any more (other recipients work fine)

### ISSUE THREAD

**Issue by prankousky** [bbernhard/signal-cli-rest-api#308]
### The problem

Hi everybody,

I recently had to set up my (recipient) signal on a new phone; actually, it was even the same phone, but I had to factory-reset it. Not anything about the (sender) signal-cli number has changed, though.

Now, my "new" (=reset) phone does not receive message from the signal-cli number any longer! **However**, _other recipients_ still do receive message from it (the signa-cli number), so I assume that signal-cli is still working 99% correctly - only I don't receive messages from it any longer.

What can I do to fix this? Is there any way this can be done without having to re-install signal-cli (which would mean re-linking the singal-cli number, getting the group IDs, etc.)? 

I read the [troubleshooting page](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/TROUBLESHOOTING.md#sending-a-message-suceeds-but-no-message-is-sent) and ran `curl -X GET -H "Content-Type: application/json" 'http://...:.../v1/receive/+49171...'` and got `{"error":"Failed to send message due to untrusted identities"}%
`.

Finally, I tried `curl -X POST -H "Content-Type: application/json" 'http://...:.../v2/send' -d '{"message":"test", "number": "+sender", "recipients":["+mynr"]}'` and got  `{"error":"Failed to send message due to untrusted identities"}%`.

Thank you in advance for your help :)

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
> Failed to send message due to untrusted identities

You need to trust the identity (see the `trust` endpoint here: https://bbernhard.github.io/signal-cli-rest-api/#/Identities/put_v1_identities__number__trust__numberToTrust_).

Alternatively you can always re-register the device. But in that case it is advised to delete the `signal-cli-config`  folder before doing that (which makes sure that you start from scratch)

**Comment by prankousky** [comment]
Thank you, this worked.
