### ISSUE TITLE
Use non-root user in Dockerfile

### ISSUE THREAD

**Issue by ryanjdillon** [bbernhard/signal-cli-rest-api#31]
It would be nice if the Dockerfile was configured to use a [non-root user](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user) to improve security.

**Comment by bbernhard** [comment]
I've reverted the change for now, as it created backwards compatibility issues with existing bind mounts: https://github.com/bbernhard/signal-cli-rest-api/commit/136fa6269815b1155a1fa5804dcfd4701f15e651

**Comment by bbernhard** [comment]
Thanks to @fl42 there's now a proposal to run `signal-cli-rest-api` without a root user. The way it is implemented, it should work transparently without breaking existing setups. I've already tested the image on my x86-64 and armv7 machines without any issues. 

But it would be great if some more people could give the image a try. The docker image has the tag `bbernhard/signal-cli-rest-api:0.31-dev`. The changes can be found here: https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.29

I am notifying everybody that has contributed something to this project. If you have time and want to give the image a quick try, it would be highly appreciated. If no issues are raised, the image will become public in the next days :) 


@danijelst @funkybunch @stayradiated @haberda

**Comment by haberda** [comment]
After a little testing this seems to work fine in terms of the HassIO add-on. Thanks!

**Comment by bbernhard** [comment]
> After a little testing this seems to work fine in terms of the HassIO add-on. Thanks!

Many thanks for testing! 

As Christmas and New Year's Eve is probably a busy time for most people, I'll wait another 2-3 days in case someone wants to give it a try. If no issues are raised by then I'll push the new image to dockerhub.

**Comment by bbernhard** [comment]
The image on dockerhub is now updated :tada:. Thanks to @fl42 for implementing the feature and @haberda for testing!
