### ISSUE TITLE
Cannot Register Number: Error "This endpoint is not supported in JSON-RCP mode. and Timeouts"

### ISSUE THREAD

**Issue by RJ-Make** [bbernhard/signal-cli-rest-api#312]
### The problem

In an attempt to get Signal working in Home Assistant using the Add-On, I'm running into this error trying to register the phone number. 

in Gitbash console
`"This endpoint is not supported in JSON-RCP mode."`
in Add-On Logs
`[GIN] 2022/12/18 - 10:01:13 | 400 |     193.695µs |    192.168.1.26 | POST     "/v1/register/+1XXXXXXXXXX"`

I've tried the other 2 modes and I receive a timeout error. 
`Failed to register: Connect timed out\n`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

Running the latest version of all Home Assistant parts. (HAOS in VMWare on Windows 10)

**Comment by RJ-Make** [comment]
EDIT: 
  I also notice the addon is hit the CPU pretty hard.

![image](https://user-images.githubusercontent.com/8496835/208306285-303aadd4-5732-4694-8584-e97b9fc9ff16.png)

**Comment by RJ-Make** [comment]
What is an "endpoint"?

**Comment by bbernhard** [comment]
The ` register` endpoint can only be used  in ` nomal` or `native` mode. So, before switching to the `json-rpc` mode, please make sure to register your phone number. 

> Failed to register: Connect timed out

This looks like a Signal Server error or a network issue in your network to me. Do you maybe have a firewall that could block the traffic?

**Comment by RJ-Make** [comment]
Thank You @bbernhard for your help. 

You nailed it, After switching to normal mode and trying again just now it registered. The time out had to be a Signal issue.

**Comment by RJ-Make** [comment]
I'm re-opening for the Timeout errors. I had to start all over, after ~6 hours of it working due to an unresolved `{"error":"write tcp 127.0.0.1:58396-\u003e127.0.0.1:6000: write: broken pipe"}` error.

So now I'm back to not being able to register or verify my number, due to "timeout issues" (setting is 240 sec) but that is being ignored at 60sec

I don't think these timeout issues are related to Signal, and while it could be my network all other HA service are working as expected. 

Where do I go from here?

**Comment by bbernhard** [comment]
I've updated the software to the latest signal-cli version. Could you please give the docker image tag `bbernhard/signal-cli-rest-api:0.115-dev` a try to see whether this fixes your issue.

**Comment by RJ-Make** [comment]
> I've updated the software to the latest signal-cli version. Could you please give the docker image tag `bbernhard/signal-cli-rest-api:0.115-dev` a try to see whether this fixes your issue.

I'm using the HA add-on, is there a way I can update in HA?

Thanks for your help.

**Comment by bbernhard** [comment]
Unfortunately, I do not know much about the internals of the HA addon (it is maintained by a different person) and whether this is possible. But I'll release the dev version in the next days anyhow, so it should be picked up by addon maintainer :)

**Comment by RJ-Make** [comment]
Thank you @bbernhard, I'll let you know the outcome.

**Comment by RJ-Make** [comment]
@haberda released an update based on .65 and unfortunately the results are the same.

**Comment by RJ-Make** [comment]
I'm closing this, as the problem seems to be with my system and the HA Addon.  I spun up docker version and I don't have any problems with registering and using the service.
