### ISSUE TITLE
support go-get

### ISSUE THREAD

**Issue by urandom2** [bbernhard/signal-cli-rest-api#316]
your go module does use `github.com/bbernhard/signal-cli-rest-api` as the import path, but because it lives in `github.com/bbernhard/signal-cli-rest-api/src`, it is not possible to import or use the code without a replace directive:

```go.mod
replace github.com/bbernhard/signal-cli-rest-api => github.com/bbernhard/signal-cli-rest-api/src 0.64
```

I know that releases and builds leverage docker, but it would be nice to have this code exist such that it can be shared with the greater go ecosystem.

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
