### ISSUE TITLE
InvalidObjectException

### ISSUE THREAD

**Issue by ChrisLoiz** [bbernhard/signal-cli-rest-api#318]
### The problem

Hello,
after having registered my device a directory with a key number and a json are created
but when I try to send a message I get this message : 
    "error": "Error loading state file for user +123456456456: Incorrect file format: expected parameter username not found  (InvalidObjectException)\n"
I've try to delete the directory and recreate it with a new QRCode but I've still have the same error
thanks 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

### Additional information

it's running into docker on a Mac

**Comment by bbernhard** [comment]
Do you also get the same error when registering the number in the `normal` mode? (please again start from scratch by deleting the config folder first)

**Comment by ChrisLoiz** [comment]
Hello
You’re right in normal mode the registration looks a bit different and now
the message goes

I ve after the good test reinstalled it in native mode but  I’ve a fail to
load native library now

Can I stay in normal mode or do I have to test something else ?

Thanks anyway for your first reply

Le lun. 2 janv. 2023 à 17:11, Bernhard B. ***@***.***> a
écrit :

**Comment by bbernhard** [comment]
The `normal` mode is the slowest one. I recommend switching to the `json-rpc` mode, if speed matters to you. Regarding the issue with the library load: you are probably running into this issue now: https://github.com/bbernhard/signal-cli-rest-api/issues/319

**Comment by ChrisLoiz** [comment]
Right again

I’ve installed json-rpc it goes faster indeed

But when I want to receive I get now a bad request

{"error":"websocket: the client is not using the websocket protocol:
'upgrade' token not found in 'Connection' header"}



Le lun. 2 janv. 2023 à 17:30, Bernhard B. ***@***.***> a
écrit :

**Comment by bbernhard** [comment]
In `json-rpc` mode you need to establish a websocket connection. A HTTP GET request doesn't work anymore.

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
