### ISSUE TITLE
0.65: Failed to load native library:sqlite-3

### ISSUE THREAD

**Issue by hulmgulm** [bbernhard/signal-cli-rest-api#319]
### The problem

I just switched from 0.64 to 0.65 docker image. All requests which worked fine in the 0.64 image are resulting now in a 400 Bad Request response:
`{
  "error": "Failed to load native library:sqlite-3.40.0.0-add5fb17-bcf9-41ec-9666-1f926ece56bd-libsqlitejdbc.so. osinfo: Linux/x86_64\njava.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-3.40.0.0-add5fb17-bcf9-41ec-9666-1f926ece56bd-libsqlitejdbc.so\n\tat com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:104)\n\tat java.lang.ClassLoader.loadLibrary(ClassLoader.java:54)\n\tat java.lang.Runtime.load0(Runtime.java:755)\n\tat java.lang.System.load(System.java:1953)\n\tat org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)\n\tat org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)\n\tat org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)\n\tat org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)\n\tat org.sqlite.core.NativeDB.load(NativeDB.java:63)\n\tat org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)\n\tat org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)\n\tat org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)\n\tat org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)\n\tat org.sqlite.JDBC.createConnection(JDBC.java:104)\n\tat org.sqlite.JDBC.connect(JDBC.java:77)\n\tat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)\n\tat com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)\n\tat com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n\tat com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)\n\tat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)\n\tat com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)\n\tat com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)\n\tat org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)\n\tat org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)\n\tat org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)\n\tat org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)\n\tat org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)\n\tat org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)\n\tat org.asamk.signal.App.loadManager(App.java:355)\n\tat org.asamk.signal.App.handleLocalCommand(App.java:288)\n\tat org.asamk.signal.App.init(App.java:229)\n\tat org.asamk.signal.Main.main(Main.java:60)\nERROR HikariPool - HikariPool-1 - Exception during pool initialization.\njava.sql.SQLException: Error opening connection\n\tat org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)\n\tat org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)\n\tat org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)\n\tat org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)\n\tat org.sqlite.JDBC.createConnection(JDBC.java:104)\n\tat org.sqlite.JDBC.connect(JDBC.java:77)\n\tat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)\n\tat com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)\n\tat com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n\tat com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)\n\tat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)\n\tat com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)\n\tat com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)\n\tat org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)\n\tat org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)\n\tat org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)\n\tat org.asamk.signal.manager.storage.recipients.RecipientTrustedResolver$RecipientTrustedResolverWrapper.resolveSelfRecipientTrusted(RecipientTrustedResolver.java:28)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:639)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)\n\tat org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:92)\n\tat org.asamk.signal.manager.SignalAccountFiles.initManager(SignalAccountFiles.java:79)\n\tat org.asamk.signal.App.loadManager(App.java:355)\n\tat org.asamk.signal.App.handleLocalCommand(App.java:288)\n\tat org.asamk.signal.App.init(App.java:229)\n\tat org.asamk.signal.Main.main(Main.java:60)\nCaused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/lib64:/lib64:/lib:/usr/lib]\n\tat org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)\n\tat org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)\n\tat org.sqlite.core.NativeDB.load(NativeDB.java:63)\n\tat org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)\n\t... 30 common frames omitted\nError loading state file for user +497xxxxxxx: Failed to initialize pool: Error opening connection (PoolInitializationException)\n"
}`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Looks like this issue here: https://github.com/AsamK/signal-cli/issues/1129

Do you need the mode to be `native`? Otherwise you could try to switch to a different mode (e.g `json-rpc`) in the meantime.

**Comment by hulmgulm** [comment]
Thank you, it works with normal mode. Why is `v1/receive` not a GET in `json-rpc` anymore? It's hard to do a get with curl and websockets.

**Comment by WeldFire** [comment]
I have the same issue with `native` mode
![image](https://user-images.githubusercontent.com/293969/210670447-95628424-80a9-4053-901b-7d16eefb9028.png)

`normal` and 'bbernhard/signal-cli-rest-api:0.64` with `native` mode still works for me

Please let me know if I can provide any further info to fix `native` mode in future versions

**Comment by jarrah31** [comment]
I have the same problem since the update to 0.65 - can't remember why I was using native mode over json-rpc at the moment. :)

**Comment by bbernhard** [comment]
> Thank you, it works with normal mode. Why is `v1/receive` not a GET in `json-rpc` anymore? It's hard to do a get with curl and websockets.

The `json-rpc` mode behaves like the signal client on every other platform, so you can't poll the service for updates, but get a notification via websocket.

The issue with the native mode is something that needs to be fixed upstream - there's nothing I can do. So hopefully with the next upstream release, the native mode works again

**Comment by marvinruder** [comment]
@bbernhard This issue appears to be fixed in signal-cli v0.11.7 now.

**Comment by stth1998** [comment]
@bbernhard i ran into this issue after updating  docker and containers on raspbian
* native is not supported
* normal brings up the sqlite error on first rest api call
* json-rpc cannot connect

i tried to go back until 0.62 but the issue persists. Seems to be that the docker update breaks all used signal-cli versions.

also tried the tmpfs fix with no success
```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
[...]
    tmpfs:
      - /tmp:exec,mode=777

```

Is there a release with fixed signal-cli? Do you plan to update the lib?

Thanks btw. for this awesome container.

**Comment by stth1998** [comment]
oh. i see 0.66 is using signal-cli 0.11.7. well, this does not fix the issue for me.

raspbian up to date with these repos:

http://archive.raspberrypi.org/debian bullseye InRelease                                                                                                                                       
http://raspbian.raspberrypi.org/raspbian bullseye InRelease                                                                                                                                
https://download.docker.com/linux/raspbian bullseye InRelease
http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages

docker --version
> Docker version 24.0.1, build 6802122

**Comment by stth1998** [comment]
Seems to be due to an automatic update from 32 to 64 bit kernel on raspbian

https://github.com/raspberrypi/firmware/issues/1795

The 'fix' to go back to 32 bit kernel and armv7l worked. That means that the signal-cli is required as aarch64 library to work on latest raspbian.

What needs to be done to achieve that? The rest of the system (home assistant, esp-home, etc. works fine with the newest kernel so i am not really happy with that step backwards...

**Comment by stth1998** [comment]
@bbernhard thanks for looking after this issue. sadly, this is still not working with the settings proposed by the raspian maintainers. when i reboot with the 64 setting and fully upgraded raspian, signal-cli (newest stable package) is still not working.

Did you close because there is a solution for 64 bit kernels or because there is a workaround?

BR

**Comment by stth1998** [comment]
hm. forgot to pull the signal-cli image. on it.
