### ISSUE TITLE
Error loading state file for user +49xxxxxxxxx

### ISSUE THREAD

**Issue by chefschaffner** [bbernhard/signal-cli-rest-api#320]
### The problem

Hi,
after registering my number, I tried to send a message:

`curl -X POST -H "Content-Type: application/json" 'http://localhost:85/v2/send' -d '{"message": "Test via Signal API!", "number": "+49xxxxxxxxx", "recipients": [ "+49xxxxxxxxx" ]}'`

Got that error:
`Error loading state file for user +49xxxxxxxxx: Incorrect file format: expected parameter username not found  (InvalidObjectException)\n"}`

I guess, the file ment is accounts.json:
`{
  "accounts" : [ {
    "path" : "823104",
    "environment" : "LIVE",
    "number" : "+49xxxxxxxxx",
    "uuid" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
  } ],
  "version" : 2
}`

Version is:
`curl -X GET -H "Content-Type: application/json" 'http://localhost:85/v1/about' `
`{"versions":["v1","v2"],"build":2,"mode":"native","version":"0.65","capabilities":{"v2/send":["quotes","mentions"]}}`

Any idea?

Thanks for providing your software!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by markhaur** [comment]
Also experiencing the same issue

**Comment by CubicDE** [comment]
I'm also experiencing this issue on the v0.65, the v0.64 works for me

**Comment by bbernhard** [comment]
Please remove the signal-cli-config folder and try to register the number in `normal` mode. The `native` mode doesn't work well with the latest release.

**Comment by markhaur** [comment]
hello, @bbernhard thanks for mentioning it. It is working awesome with `normal` mode.

**Comment by chefschaffner** [comment]
Yes, I can confirm. Works perfectly in normal mode.
Thank you - have a nice day :-)
