### ISSUE TITLE
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received. Failed to send message

### ISSUE THREAD

**Issue by s3luX** [bbernhard/signal-cli-rest-api#322]
### The problem

Hi,

I`ve setup the container with the MODE=normal, as I was experiencing issues with the native mode (there is an issue open for that case as well already by another user where it was suggested to setup the container in normal mode.

After the setup via the normal mode I am encountering a different issue:

`curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "Test via Signal API!", "number": "+38xxxxxxxxx", "recipients": [ "+38xxxxxxxxx" ]}'`
`{"error":"INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.\nFailed to send message\n"}`

The installation was performed as the readme dictates (except the change from native to normal). Number successfully registered as well, I can see the accounts.json file and my number in it.

Anyone has an idea what might be the cause of the issue?

Thanks!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Have you tried to call the `receive` endpoint? In `normal` mode you have to call the endpoint regularily in order to make it work. Alternatively, you can also switch to the `json-rpc` mode, which behaves more like the Signal Client on any other device (e.g Android) - in that mode messages are automatically fetched from the Signal Server

**Comment by s3luX** [comment]
I have tried to install the container in json-rpc mode, but it gets stuck in a restarting loop:
```
CONTAINER ID   IMAGE                           COMMAND                  CREATED              STATUS                         PORTS                                       NAMES
883c8002adf7   bbernhard/signal-cli-rest-api   "/entrypoint.sh"         About a minute ago   Restarting (1) 3 seconds ago                                               signal-api
```

Normal and Native modes install and run without issues (from docker perspective), only the json-rpc one is restarting. tried it a couple of times, but no avail.

I`m quite new to the signal-api, so not sure how can I call the receiver endpoint, if I understood correctly, that would be call my phone via the docker/signal-api or vice versa?
If so (signal-api -> my phone), what would be the process to call the receiver? I`m guessing we are not talking about a voice call, but a different call, correct? (also checked the documentation but couldnt find any references to voice calls) :)

If I try with the native mode, it gives me the below error:
 `curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "Test via Signal API!", "number": "+38xxxxxxxxx", "recipients": [ "+38xxxxxxxxxx" ]}'`
`{"error":"Error loading state file for user +38xxxxxxxx7: Incorrect file format: expected parameter username not found  (InvalidObjectException)`

Which is mentioned in the ticket #320 .

Thanks!

**Comment by s3luX** [comment]
I have found the issue, and I'm pretty embarrassed to say that it was down to a typo... I mistyped a number in the recipient number...
For the others who might encounter the issue like I did:

The container works fine in MODE=normal, install it as per the instructions in the readme:
`sudo docker run -d --name signal-api --restart=always -p 8080:8080 -v $HOME/.local/share/signal-cli:/home/.local/share signal-cli -e 'MODE=normal' bbernhard/signal-cli-rest-api`

Once installed, register your signal number with via the link:
`http://localhost:8080/v1/qrcodelink?device_name=signal-api`

And finally send messages via:
`curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "MESSAGE CONTENT", "number": "+38xxxSENDING NUMBERxxx", "recipients": [ "+38xxxRECEIVING NUMBERxxx" ]}'`

Thanks for your support! closing the issue.
