### ISSUE TITLE
QUESTIONS: How to change the MODE in Docker

### ISSUE THREAD

**Issue by RJ-Make** [bbernhard/signal-cli-rest-api#323]
### The problem

Since I could not get the HomeAssistant Add-on to work, I muddled my way through installing docker and installing the listed .yml file. 

This allowed me to easily get my number registered, verified and created a group (I've not tried any communication yet). 

QUESTIONS:

1) How do I change the Mode to rpc? I stopped docker, changed the .yml file, and restarted but it appears that's not how it's done. 

2) How do I auto start the container in Docker?

I know nothing about docker, so I'm quite lost with which is probably very simple functions. 

Thank You. 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
You can use `docker-compose down` to shutdown the docker container, change the mode to `json-rpc` and then start the container again with `docker-compose up -d`.

**Comment by RJ-Make** [comment]
Thank You! Worked Perfectly.
