### ISSUE TITLE
New phone causes group message not be received anymore

### ISSUE THREAD

**Issue by anotherbridge** [bbernhard/signal-cli-rest-api#324]
### The problem

The phone number registered with the signal api is used to sent out messages into a group and did not change so far. However, one of the participants in the group recently changed to a new phone and now she is not receiving any messages from the signal-api user anymore. All other messages that are send to the group from any user than the signal api user are received. 

Similar to what is described in #308 I added that user to the trusted users. After that I can send personal messages from the signal api, but still the group messages are not received. 

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

**Version info**
I am using version 0.64

**Comment by bbernhard** [comment]
Are you calling the `receive` endpoint regularily? (that is required in `normal` mode, otherwise it won't work correctly).

**Comment by anotherbridge** [comment]
Yes, I have a cron job that call the endpoint every hour.

**Comment by domdenu** [comment]
same here. please see my comment in #325

**Comment by bbernhard** [comment]
Cleaning up old issues. In case you still have questions/problems, please create another issue.
