### ISSUE TITLE
expected parameter username not found 

### ISSUE THREAD

**Issue by hxcde** [bbernhard/signal-cli-rest-api#328]
### The problem

Error: AxiosError: Request failed with status code 400 {"error":"Error loading state file for user +0000000000: Incorrect file format: expected parameter username not found  (InvalidObjectException)\n"}×

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

### Additional information

When requesting from Uptime Kuma or Home Assistant, this error is appearing.

**Comment by hxcde** [comment]
Looks like the ` /.local/share/signal-cli/data/<number>` is empty.
Tryed the docker container on debian and on alpine linux.

**Comment by tobilektri** [comment]
Worked in my case also with 0.64 thank you for the issue. Helped in my case.

**Comment by bbernhard** [comment]
fyi: the `native` mode is unfortunately not working in the latest version. So, you either have to stick to version 0.64 for now, or use the `normal`/`json-rpc` mode.

**Comment by hxcde** [comment]
Thanks for the info. Then I'll wait for the new update to be released.
