### ISSUE TITLE
library error in docker container

### ISSUE THREAD

**Issue by daneb255** [bbernhard/signal-cli-rest-api#332]
### The problem

Since a few days following error occured if API is requested:

`{
    "error": "Failed to load native library:sqlite-3.40.0.0-89ef0618-ab23-4b48-98f9-7b1ac9736ffe-libsqlitejdbc.so. osinfo: Linux/x86_64\njava.lang.UnsatisfiedLinkError: Can't load library: /tmp/sqlite-3.40.0.0-89ef0618-ab23-4b48-98f9-7b1ac9736ffe-libsqlitejdbc.so\n\tat com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:104)\n\tat java.lang.ClassLoader.loadLibrary(ClassLoader.java:54)\n\tat java.lang.Runtime.load0(Runtime.java:755)\n\tat java.lang.System.load(System.java:1953)\n\tat org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:280)\n\tat org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:237)\n\tat org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:350)\n\tat org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)\n\tat org.sqlite.core.NativeDB.load(NativeDB.java:63)\n\tat org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)\n\tat org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)\n\tat org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)\n\tat org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)\n\tat org.sqlite.JDBC.createConnection(JDBC.java:104)\n\tat org.sqlite.JDBC.connect(JDBC.java:77)\n\tat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)\n\tat com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)\n\tat com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n\tat com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)\n\tat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)\n\tat com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)\n\tat com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)\n\tat org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)\n\tat org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)\n\tat org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:632)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)\n\tat org.asamk.signal.manager.SignalAccountFiles.initRegistrationManager(SignalAccountFiles.java:180)\n\tat org.asamk.signal.manager.SignalAccountFiles.initRegistrationManager(SignalAccountFiles.java:146)\n\tat org.asamk.signal.App.loadRegistrationManager(App.java:340)\n\tat org.asamk.signal.App.handleRegistrationCommand(App.java:260)\n\tat org.asamk.signal.App.init(App.java:221)\n\tat org.asamk.signal.Main.main(Main.java:60)\nERROR HikariPool - HikariPool-1 - Exception during pool initialization.\njava.sql.SQLException: Error opening connection\n\tat org.sqlite.SQLiteConnection.open(SQLiteConnection.java:281)\n\tat org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)\n\tat org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)\n\tat org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)\n\tat org.sqlite.JDBC.createConnection(JDBC.java:104)\n\tat org.sqlite.JDBC.connect(JDBC.java:77)\n\tat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)\n\tat com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)\n\tat com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)\n\tat com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)\n\tat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)\n\tat com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)\n\tat com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)\n\tat org.asamk.signal.manager.storage.Database.getHikariDataSource(Database.java:101)\n\tat org.asamk.signal.manager.storage.Database.initDatabase(Database.java:32)\n\tat org.asamk.signal.manager.storage.AccountDatabase.init(AccountDatabase.java:32)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getAccountDatabase$38(SignalAccount.java:1236)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getAccountDatabase(SignalAccount.java:1234)\n\tat org.asamk.signal.manager.storage.SignalAccount.lambda$getRecipientStore$30(SignalAccount.java:1209)\n\tat org.asamk.signal.manager.storage.SignalAccount.getOrCreate(SignalAccount.java:1649)\n\tat org.asamk.signal.manager.storage.SignalAccount.getRecipientStore(SignalAccount.java:1206)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:632)\n\tat org.asamk.signal.manager.storage.SignalAccount.load(SignalAccount.java:181)\n\tat org.asamk.signal.manager.SignalAccountFiles.initRegistrationManager(SignalAccountFiles.java:180)\n\tat org.asamk.signal.manager.SignalAccountFiles.initRegistrationManager(SignalAccountFiles.java:146)\n\tat org.asamk.signal.App.loadRegistrationManager(App.java:340)\n\tat org.asamk.signal.App.handleRegistrationCommand(App.java:260)\n\tat org.asamk.signal.App.init(App.java:221)\n\tat org.asamk.signal.Main.main(Main.java:60)\nCaused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=x86_64, paths=[/org/sqlite/native/Linux/x86_64:/usr/lib64:/lib64:/lib:/usr/lib]\n\tat org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:375)\n\tat org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:68)\n\tat org.sqlite.core.NativeDB.load(NativeDB.java:63)\n\tat org.sqlite.SQLiteConnection.open(SQLiteConnection.java:278)\n\t... 29 common frames omitted\nError loading or creating state file: Failed to initialize pool: Error opening connection (PoolInitializationException)\n"
}`

if I delete the persistent directory and register the device again following error occured:

`{"error":"Error loading state file for user +123456789: Incorrect file format: expected parameter username not found  (InvalidObjectException)\n"}`

maybe any1 could help me? :)
Thanks!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
> if I delete the persistent directory and register the device again following error occured

Are you sure that you've registered the device in `normal` mode and not `native` mode? In the latest release, the `native` mode doesn't work, so you either need to stick with the `normal` mode or switch to the `json-rpc` mode after you've registered the number.

**Comment by daneb255** [comment]
ahh looks good, thanks!! :) Switch to `normal ` mode was the solution
