### ISSUE TITLE
source number in null

### ISSUE THREAD

**Issue by vibhore-gupta** [bbernhard/signal-cli-rest-api#347]
### The problem

1. Registered number with register endpoint
2. send a message to registered number
3. call the receive endpoint on the registered number
4. below is the receive call response
[
  {
    "envelope": {
      "source": "cfd8ad65-0e1c-46a8-8f96-322ccaa73212",
      "sourceNumber": null,
      "sourceUuid": "cfd8ad65-0e1c-46a8-8f96-322ccaa73212",
      "sourceName": "sample",
      "sourceDevice": 1,
      "timestamp": 1677667247915,
      "dataMessage": {
        "timestamp": 1677667247915,
        "message": "Happy `Birthday",
        "expiresInSeconds": 0,
        "viewOnce": false
      }
    },
    "account": "*****" // number masked
  }
]

why source number is null ?

thanks

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
https://github.com/AsamK/signal-cli/issues/1156

sounds related to your issue?
