### ISSUE TITLE
Build on Mac M2 (arm)

### ISSUE THREAD

**Issue by pedromreis** [bbernhard/signal-cli-rest-api#349]
Hi

I cant build this on a M2 Mac.
I got the error below. Any help? 
Tks

#16 0.338 Cloning into 'signal-cli-0.11.7-source'...
#16 9.836 Downloading: Component catalog from www.graalvm.org
#16 10.97 Processing Component: Native Image
#16 10.99 Downloading: Component native-image: Native Image from github.com
#16 11.75 Installing new component: Native Image (org.graalvm.native-image, version 22.1.0)
#16 138.7 Note: /tmp/signal-cli-0.11.7-source/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java uses or overrides a deprecated API.
#16 138.7 Note: Recompile with -Xlint:deprecation for details.
#16 148.3 ========================================================================================================================
#16 148.3 GraalVM Native Image: Generating 'signal-cli' (executable)...
#16 148.3 ========================================================================================================================
#16 149.3
#16 149.3 [1/7] Initializing...                                                                                    (0.0s @ 0.28GB)
#16 149.3 Error: Collecting native-compiler info with '/usr/bin/gcc -v' failed
#16 149.3 Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
#16 149.3 ------------------------------------------------------------------------------------------------------------------------Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
#16 149.3
#16 149.3                          0.2s (2.6% of total time) in 8 GCs | Peak RSS: 0.77GB | CPU load: 2.59
#16 149.3 ========================================================================================================================
#16 149.3 Failed generating 'signal-cli' after 6.4s.
#16 149.5 Error: Image build request failed with exit status 1
#16 149.6
#16 149.6 FAILURE: Build failed with an exception.
#16 149.6
#16 149.6 * What went wrong:
#16 149.6 Execution failed for task ':nativeCompile'.
#16 149.6 > Process 'command '/tmp/graalvm-ce-java17-22.1.0/bin/native-image'' finished with non-zero exit value 1
#16 149.6
#16 149.6 * Try:
#16 149.6 > Run with --stacktrace option to get the stack trace.
#16 149.6 > Run with --info or --debug option to get more log output.
#16 149.6 > Run with --scan to get full insights.
#16 149.6
#16 149.6 * Get more help at https://help.gradle.org
#16 149.6
#16 149.6 BUILD FAILED in 2m 14s
------
executor failed running [/bin/sh -c if [ "$(uname -m)" = "x86_64" ]; then 		cd /tmp 		&& git clone https://github.com/AsamK/signal-cli.git signal-cli-${SIGNAL_CLI_VERSION}-source 		&& cd signal-cli-${SIGNAL_CLI_VERSION}-source 		&& git checkout -q v${SIGNAL_CLI_VERSION} 		&& cd /tmp && tar xf gvm.tar.gz 		&& export GRAALVM_HOME=/tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION} 		&& export PATH=/tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin:$PATH 		&& cd /tmp/signal-cli-${SIGNAL_CLI_VERSION}-source 		&& sed -i 's/Signal-Android\/5.22.3/Signal-Android\/5.51.7/g' src/main/java/org/asamk/signal/BaseConfig.java 		&& chmod +x /tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin/gu 		&& /tmp/graalvm-ce-java${GRAALVM_JAVA_VERSION}-${GRAALVM_VERSION}/bin/gu install native-image 		&& ./gradlew -q nativeCompile; 	elif [ "$(uname -m)" = "aarch64" ] ; then 		echo "Use native image from @morph027 (https://packaging.gitlab.io/signal-cli/) for arm64 - many thanks to @morph027" 		&& curl -fsSL https://packaging.gitlab.io/signal-cli/gpg.key | apt-key add - 		&& echo "deb https://packaging.gitlab.io/signal-cli focal main" > /etc/apt/sources.list.d/morph027-signal-cli.list 		&& mkdir -p /tmp/signal-cli-native 		&& cd /tmp/signal-cli-native 		&& apt-get -qq update 		&& apt-get -qq download signal-cli-native=${SIGNAL_CLI_NATIVE_PACKAGE_VERSION} < /dev/null > /dev/null 		&& ar x *.deb 		&& tar xf data.tar.gz 		&& mkdir -p /tmp/signal-cli-${SIGNAL_CLI_VERSION}-source/build/native/nativeCompile 		&& cp /tmp/signal-cli-native/usr/bin/signal-cli-native  /tmp/signal-cli-${SIGNAL_CLI_VERSION}-source/build/native/nativeCompile/signal-cli;     elif [ "$(uname -m)" = "armv7l" ] ; then 		echo "GRAALVM doesn't support 32bit" 		&& echo "Creating temporary file, otherwise the below copy doesn't work for armv7" 		&& mkdir -p /tmp/signal-cli-${SIGNAL_CLI_VERSION}-source/build/native/nativeCompile 		&& touch /tmp/signal-cli-${SIGNAL_CLI_VERSION}-source/build/native/nativeCompile/signal-cli;     else 		echo "Unknown architecture";     fi;]: exit code: 1

**Comment by bbernhard** [comment]
This looks like an issue with GraalVM. If you are fine without the `native` mode, you can try to comment out the GraalVM related part in the `Dockerfile`.
