### ISSUE TITLE
Issue with registering phone number.

### ISSUE THREAD

**Issue by vishnuunni910** [bbernhard/signal-cli-rest-api#357]
### The problem

I have registered phone number using captcha and verified it using otp. I'am able to send messages using the cli but message is not being received.

The logs are throwing this error. How will I be able to resolve this.

[GIN] 2023/04/14 - 04:48:07 | 200 |       38.34µs |  192.168.11.125 | GET      "/v1/about"
[GIN] 2023/04/14 - 04:48:07 | 200 |      16.716µs |  192.168.11.125 | GET      "/v1/about"
[GIN] 2023/04/14 - 04:48:17 | 200 |        37.9µs |  192.168.11.125 | GET      "/v1/about"
[GIN] 2023/04/14 - 04:48:17 | 200 |      32.707µs |  192.168.11.125 | GET      "/v1/about"
time="2023-04-14T04:48:23Z" level=error msg="Couldn't read data for number +9191480*****: EOF. Is the number properly registered?"
[GIN] 2023/04/14 - 04:48:27 | 200 |      42.172µs |  192.168.11.125 | GET      "/v1/about"
[GIN] 2023/04/14 - 04:48:27 | 200 |      17.801µs |  192.168.11.125 | GET      "/v1/about"
[GIN] 2023/04/14 - 04:48:37 | 200 |      38.371µs |  192.168.11.125 | GET      "/v1/about"

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

Running signal-cli version 0.11.4

**Comment by vishnuunni910** [comment]
edited

**Comment by bbernhard** [comment]
Sorry for the late reply! It looks like as if your number isn't properly registered. The easiest way to fix this, is to remove the `signal-cli-config` folder from the filesystem and re-register the number in `normal` mode.

**Comment by vishnuunni910** [comment]
Thanks for the reply. I updated to the latest version and registered number in normal mode. It is now working perfectly.

**Comment by vishnuunni910** [comment]
Fixed now
