### ISSUE TITLE
Allow setting tcp port other than 8080

### ISSUE THREAD

**Issue by dlonghi** [bbernhard/signal-cli-rest-api#359]
### Feature Request

Is it possible to set the tcp port to another value than `8080` (for those who use `docker run --net=host` option) ?

If not, could you please add this option ?

Note: Tried passing `--env PORT=9090` to `docker run`, but still got `8080` as listen port.

Thanks

**Comment by coolerUA** [comment]
@dlonghi 
docker run -d -p 9090:8080 --name .....

**Comment by soundstorm** [comment]
Unfortunatly docker also exposes the port through firewalld when using port-mappings, so the firewall is useless in that case. Only Solution currently would be to change the env in the Dockerfile and build it locally with a different port. Would be nice to adjust it on the fly via an env param.

**Comment by soundstorm** [comment]
Nvm, PORT=x works in the evnvironment compose.yml perfectly with network_mode: host
