### ISSUE TITLE
{"error":"Failed to register: [413] Rate limit exceeded: 413\n"}

### ISSUE THREAD

**Issue by manjotsc** [bbernhard/signal-cli-rest-api#362]
### The problem

Hi,

I am keeping getting this error while trying to register number,

```
curl -X POST -H "Content-Type: application/json" -d '{"captcha":"captchahere", "use_voice": true}' 'http://192.168.40.28:8080/v1/register/+15140000000'

{"error":"Failed to register: [413] Rate limit exceeded: 413\n"}
```

Thanks in Advance

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Looks like the Signal Server API is rate limiting your requests. Have you called the `register` API endpoint multiple times within a short time span?

**Comment by manjotsc** [comment]
I did, because I was keep getting CAPTCHA errors, since then I am keep getting the same error, I don't know if there is way to reset the limit?

**Comment by fixmeee** [comment]
Hi,

good to hear that someone has the same issue. I'm going  crazy for days now.
I'm trying to use the HA plugin, version 0.66.

`[core-ssh ~]$ curl -X POST -H "Content-Type: application/json" --data '{"captcha":"signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQPSkRM3ZybogqW13q9C8RTQ7exjn5kmZPsZxEFwPfVxzI8zGxXcrdfoETmipYqkbRFRNzpVOXWUV1aitiGD-zo4ne3-pSLGOztpWWg3NqAJEtjaWYyFLAe9LaEgetERxSIA0U_TlMmfmeSfxAIhMKB1RcyFh09QfoBwt3m-5QahweYpvjXWV3v7EoT_9qDLMhIETGRo2pzSD48eiHN8NNnBlNX36hQHBPTxkgblF_0D0opB33LTa0relMU-0QphwZxZvmZp8Sj5-XgOBdA7zQ60PrhylYtoOck2K10hO-fD8Kk_L2wWxTB666uo9IIs5kgxAokPxz7ErNoR90jM3XcxVVW9G97D8q1jgcHsEGr4oMzPSzafMdPwZc_8-kQY-1AG1CyU7dCfEBtB7eZCylgYzDU8hNiJHPEILoqS6YPzUo07jXBfOIshlyH5A10pQeJ4TmBsTBh14a3ydUkxzHuQdaDadhSdxKrAU1cM9T46gZ8C2kTxAaaIDODO8gNVQLJQJw0rRkRFXthVsGTKb5JW59JII5drgxLN56Y1m5F0YFqScniLzMmx5fa__z3s006C97C1FoNyGpREIGM3tUxpqJtoyL6e41UPNdPqOxmK7H5okjWOq9zRWVO8kIpl61VvN6GrPDeE7zOtHC2lwNYjHcSxRsx8UJD17otOsgBf3VZl8MEP4fXmf0V9nIEkjPk_tjmAkHxWMqL2Gu1M_9vSqjGoZtCHzo3HWbK5SY1oDalm-xI79wt-mZW0UKM8j_dwIAOAWDYfxBjS2PyB52Cd7C0JGdeEpnjpO2Dvw_nFuxEvfcnGOSZmuy_D9ESIHrrsjZoYXwOZu7lu5DSLV0H5W33FGBhUsZaknai45_rKKg_qIwqbf97vbEFc1kKw67kNlpUn9emmzUFTofppp_1_QMukhsD_JdrPTTTjoy5Zht9Aj4exQdtWTLOwu0ZsUryQYmIEpFj8D8RG4Y6aPB6SMVKGK-ZOy9M1qDj1QRxUmLbyB_Cs603xfx1GTxsCZv0XkVyVeMBiLM38zydQxwTRD4g88DH6nlMAB_iQsarMIW8GY7D-qJarGmZxmAKYL5pClCQ9P0MmcppY_2uitFFYpUoq-1QKF0tvEA43n7PGBlrqC2p0loyifndlVlo4scoDEAMYmqkzDSyK0uF6V_hAZRebCtlDEtXk1OsHTCczlUO4EhuRnONDMNKDxxfvP5ioMbFYz4ptsnwxqxs-o6MPnzesGw4nb7aI23NSfGovcfDSF2wX9MzanYLTuS8-M48a_c79QQQp152Qb7kUg-g8WUyAo2V4cM5kWpOlqHNoYXJkX2lkzgMxg2-icGQA.PZHn_UnJUlW7Z5BBPF3FHKyPZ9Lh6izoHNZfd4KF6qc", "use_voice": true}' 'http://172.30.33.3:8080/v1/register/+49xxxxxxxxxxxx'

{"error":"Invalid captcha given.\n"}
[core-ssh ~]$ 
[core-ssh ~]$ curl -X POST -H "Content-Type: application/json" --data '{"captcha":"signalcaptcha://signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQloniyEFqi4lIuoyN242Ku_wyNCOT7Ex_HF4boERlXoTUigzMF5Pd2E4TAEz5pGTcxky-zfYTdbtRM23ZRG9Gui_tucy4a0IC2mN30T_EUmNWjoCIWpGg8wVMZiZPmh--vLsjEMqjY1Vk6IRO3ZEoo-iILshS2k5ltmt-5D3KXz-SkS4406hwiCw6dyhOEs9bzCpQWyWFGQ1IdAbcqK5UYVc4CbF1iiB-Oj3JCoFk3-QJ-NDfJ4h6RnfWkwc0cs2_8mASftjK0nPVMHJfqe1MwIvYdB0uRht15zH-WySR-fFW5jMqxdVpXcJlVnI3fCbwwIFSOVRuMCCr_SuA_91YHZSFT-9-oaP3WF4P-nE1kZsPIwPQjxNn0T7YDi4Gr0zAZRu-JM6wachr29E7lybpeKxIwgV47BuxbyrFYrZ_LexKtSftXPmMw_GoS2erYrsU9O624iiVFDY1eAcQFEtgEBKr1KvY2aIo1hvIwgXn8uCouxaaF6E8VlaA3q6pwn9PsF-ldYNc1mNkq2sGgDwy1iWtH0p3lnflJhbgavZxFnm3CWevmTw-2mGitUAcdoAlmJfMKbRv4Vl13Tslddlb2DMZf_U_AA7N5pjeDptXpU0TZaSzzwa514qXsXfCCWq_Lif428AYwvSTEPZg_CuROKDQbO1BNRHH5He1u_ERchXt3LMchrvXUbBcJ2taVvqCMje7TpmR-XXKB3awxpLK2LKfCfozM5Hx8Z-FtsNOC14lZCXcxklR96KsOwuRc7aHLgUxGlHtDI3wX705bY-jAyNDehxHTe8Aw5AXj6R_HaoFS0_c25i-zXLO7IhrIuPq5T9_mCurb30SIDvBMAJO75GMMDPnZe7LkXxuiSyq1gYeYM5sNrLoKywS3VA6UltKbkmpkCw0lrrZQv3izxwn45CYpyUnYTYTaVAEyRbkSu3UAWGV5L0OqKKODrFi4ROTG9TVhKH6N-mBtystvvxVohpLU8hIFTYyalpIBNdTEjNADQlezK_kum0et1I9j5oyoCo2fdbld6CGRTqaJXAE0FZ_vk1cbwH1gRQquWT7ss5Ux62D-38p8NIwL1U90iXOhFEk3Siap1_oIVuxrmIFKlwoB-NItdLFxmFaZ-t3ta90TFVOS1-5qSSeRh5rymdIyHwS0HNteF0P4Fu8Lh4mL76J2r_abp_Zpp7_TIU0unOdmttE4C29RyC9HvgtG5GPQHdFkYIKDZnO3d53bv0bO_0YJNi27fItvc5pJbhfXPwUKnH8iuWnU-SApd4tpI7Q2aU5Z2x7top9MaUqdcvvguguT1Rzq_fZmzYk-Micv-wn97NtpnmN0aEdH6h9xT1pjf4sBmSYiBkzlslBp98vDAkOe-wqZMA2O_WRQNLN4C284-AQxlOpiodhNuRUQwfeeM5WLJiTVR327_q5xD6R4Fscvq3DlWu4Qj9zvS6bHMtdD8l-adHjR-qNffUPAPLRIp9pXI0PxnkB2HcVtWemjU5ViQgJfokn6aBOG4DVeUAXjJQgbwnnKDcaJ5eh_XQcZzVlYxOA2Py8CE6cYRS2WcSeeYWV7sXoT8almmHFJLkXKI1l2o8zGOfcVSawOwdtVAtkX0LvPHJFEkf_ZFNUKREnCaTwbnPbKfuXzX0c4xyGw__TyKfOn8qicuWuNnsKhm-MjLoEatZQK6gT6YWRL3Zs8sTJH1DpOoI43OAY5FpkMzeCbmw083aSsQ9HFRQpigd9DyFYmkXDjqSVuznz3rmtRUtCphkhv8IuRieXFkqf2Oe0pHjcYBJ7XkNs3uO0EkOlVHHO3mzlo4FSkYugNKxyHWH1lroMxPSdpURz6fGYge0FriyOyrqe9hoGGrHhKOE_vwp4ByDgO63hiqSktP88ELNuL2MjRsqlCYgLSMm55JBr5rEczlqYfqBqmtAtZ2yrEuQym_KAhcLVAYukWU96SlaIza3YuaOMLYQ_Cfn4evW-88oTvWBjUAkkHGP4B628xNYh4pBob161zqzSUXcNlHMrCKlNW5fVP_Q6e-0PVnl68CenAjmRmqbkDpV2l8b48Nqc5jR7ZKFEeNrMt4ioSIq_u35BrRG_RbarP_V6O7T9yKLrqJSNf60MGRm6QZUt7yUT8mqEEZFiejgBOdzosNMAkoaiJkG0mvOMv1XaAqYAdUSL1RJyxNHhdXUV4LzNXQwk-E754QD-2aNc4moZcxQZUfiL7Wl8lyJG3ylIxmEZz2EM8lLHOH7tJe287e6F0m7828GejxlUY50EQ4adhZIXjkOA6Qgl47NS6llgx1WGUJ5GbR9e-bqLMb9R2IynYltxKs_Z3ftZXsdCVWw-XpTZfduBw8HX-mukekTXrrCugovM5Shx334n-6XdVEAP0zXVzHUvywk01-4vzk1OBFe1NljeiqqRqpw2xrIpEQTZiYtjzigHzyr7bXeX78IU2slyr3d-CUtsKEyae_QaFhxkI7A6Eoaa2pb0IOumTdr19rZ2oRazMpZMlPBOoa2dFVVbN1TkCndYashsYVi99HSgyQM6Xcy3u-3FzvqZ8LiDeqNAf18NjBA_0Au3k0h-0TnpyIFFAT0-qhcq7adDpQ86hBHXJo7LKc_mQ3xW4LR6fa7ixhoCgtaAR3kZjeggKpeig77tDJmLB9d_Yv-oyEWiqEnCykaow6NQUFJkY8Xv4wZOQX3ouoWRSF_BjHO6zY_gknBAB6Hmr6qQ2uKs2wCCK-IMAL6H8te9HbDATkUoMMWOg9SHokkbmu9ebcWkoZi45Xdv4MSZTKREA1fM_uFMCyG89XhhTF7lsDZzvtum7rwYR-qax1e55dEFKtXROfOjS2G7vjJ-wfLJUQc79vFVSwo5p5AKD-o6-jcXVbX2BhS_vC-yupVtSo83xkldV1jzp7YEFuXR7eOC9wxTXNH8cOJM7SWBOgp5Hzvm2Jg5Ol_qBPFBO0iiWS0RXuDAOt1ifNyllx0KiGvwSCHx6QJBFe29vn6aeU0mIkIZPb5oPye4NEZXT7r-g9kyy-dGbU0CHzopy9G2MrnAnLZG2xKYTy0stwFMtWm02DJASrbKLFK-rQN_HXRQESB0JQzLd3v2Cv9HJffA0WmvYt4BMAQ-vL7Kk3au88gCgKBH2f7nKfJutrTZ-7RwvRv9YPB9FpGd4iP9R5DqR5PAvRwMhUPsjH3VHrAk1AQTMfyW73tMcdVVXwktcmG79IAKDamZB4ixaIKE6jZXhwzmRalLCoc2hhcmRfaWTOAzGDb6JwZAA.QTlLwaugboKgiirdoo9umw7SkFNt_7TK3pczeXY7y2w", "use_voice": true}' 'http://172.30.33.3:8080/v1/register/+49xxxxxxxxxxxx'
{"error":"Failed to register: [413] Rate limit exceeded: 413\n"}

[core-ssh ~]$ `

I also waited 24h, 48h and 72h hours to see if the rate limited gets cleared, but no success.
I tried another land-line number I own, but exactly the same error. Any idea is highly appreciated.

Thank you

**Comment by bbernhard** [comment]
Not sure how rate limiting is implemented on the Signal Server side, but have you tried from a different IP (via VPN)?

**Comment by fixmeee** [comment]
Hi Bernhard,

thanks for the quick response. I'll give it a try.
Just to double check. Documentation states:
_Everything after signalcaptcha:// is the captcha token._
But with this I got invalid captcha error, so I tried with and it was also accepted.
So is it with or without "signalcaptcha:// " prefix?

Thank you and BR

**Comment by manjotsc** [comment]
I tried VPN and then I power cycled my modem to obtain a new ip address, still the same error

**Comment by kojanovski** [comment]
> Hi Bernhard,
> 
> thanks for the quick response. I'll give it a try. Just to double check. Documentation states: _Everything after signalcaptcha:// is the captcha token._ But with this I got invalid captcha error, so I tried with and it was also accepted. So is it with or without "signalcaptcha:// " prefix?
> 
> Thank you and BR

Hello,

Copy  all without signalcaptcha://, so yo should execute the command like below. In my case I did it in Normal mode, it did not work in json-rpc mode. Also I see in your command "-- (double minus) data". It should be -data (1 x minus sign before data).
In response you get AUTMSG from signal.

curl -X POST -H "Content-Type: application/json" -d '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQmrVIBR1p8KCJOn3shtxOuqksvFG1JGOL3AJjTj1Z9z1qo0mibwp5lfV1XNIK1isanYgP0DhY-06HotVwljhKSBAkYvnxqVrhVGfHT8ZEEMYx9nTvH12zfILycXbfr7PfR4EMa8lVE3wQcjXOV23rW1N7maciIVU0JVPSgpu9OlAvY71qlv8FZaE3rx4Jk8Ng5X-glu5z-V1_i1K_o5hX_DyylRqjMYuY-hXNQc1Ry0cNo9hXIco7nnWj0XoyeROmG3FqH6oMR92mIra3I-iRDfGOrRG9kTjOfKO0sY6vjHEQh1qjBEg2GT64xHTtJy8lFlTY4KMzFCuMFI74Mm17tRHlWKRQ_WTTIvuIlHsn2i7mBRjIPI022H6xlSeewRNGqigW7wbh6Aq163J84N7TGvLT7IKQgGxG1hl06tVdFnu0C9xY-ONx2r4rIdYoZ9BrnaHhsrqAkvhQKpg_jsazwEnx0p2e3RYDV4bvlnqacbr4qaRLWj2Qofny3D8lrDz2c_y44CeDNLf9EpcA3Rvh0h7JVXiPCzhPXhmRatk-WIBwvhpUxzyjtcSeLzMo_0ZU7ETdHT9Kr6onDpww63cV6MZhK_6Ym1Iqf26ClgxF03DFCcvA0jbM1jCWy3Mm5Uh3yxaKJpqMPVUKDtm9Zbw5GJvyPBR03QcXh8M0SmdKNgBoRaRW2O3OiDm9c_v3bAtzDBzOlNhiTnxqo7g-w6ixNVqQ68rYYTB1jGyiJ8Ob6YDAioo9P2OwdcSz-PP8_R1Er_-K_dANxQq44ziCf1gz5RiYU8Lavs21K_Gt3CnoKNLeV12btDRwnQy3Yw_xKjyjapFDXqHicKBkKZrOAZP7FEaFLxzlVo37luMOJNJ6mIrBznYA60nkUYXKNH6jpm9RadTZ5i22JGF7F6is4rn_Pk67gKo7MkU6UupFtv0rAdx2jipPJdGy8AfGoHSEJSM4zyjQHXvlpoJEGzwAREzPJz268YtI99SLxgi10PGa4fHS78cD-TO2W5We4QHHd4Y1HtkKTpQV9B6CFPP-VNEaTpERMf3Lxl9UOtlv9McbSNG_NLHxcL_HJV0fVhfmZEXwYOoqTOFKbEOFDjWFJwRFUxfPVWGiHe5Q55hB9WbmObLZTe9u1SIILuij0ldjx6zb81GjKSxHKZZt5m49tt0T79SaC0KxwjI2lNShZmpXoGWBPKjfyr_CsZOKSOKjJ4sWnAzlmpg4ggTtuQCKZWpWCdUuP73hLj9EqOSeZVxjrEpJ_ojjGzXBmbvc8oLwEj-ZBN3ti1v5Wzl3wq21_Imq-gMpQv-SZJmHjb1Mj67QQyCnQ9kFAyk4o6_FJy95vXvRiw6z_cCn6T4LFWgtPpE7qiuHtvIORX9DqM7DuVCb09qNwmM_IMp8tE5GorLIglIHxZclK-7iwd4T7E251MFbb18DbrUAPvErFEVvNbQph6wctK8UZ5flgTVlvg2RYndnhNk5rP6QyWsbnNDQwA4Wb_8btT3b5UWgkUwT4P0tw_dWWBffvkIl0qedJjpISt_PZm74n-eRMKGqOWkTa8RWgRtK190ph--_SWHFfzQfsm1rIZR4p6JlZiL3a0z5ZxzmgV96mnUL213l2krx1fFIQnqpNAb3_Zt8-ihBuanzkceM_H0iHgM-WjfaRKDMYBDqDUDUHM9g5dQLVzFd9UVpAmQq7vXqPeNIODI7Ib2Rc5zIR33AeBfJdGKfIocTppBak080SiK3l98gBvKFVnGR_SHyGIRKMFuM02P-BkF_A0iGS7rwmQlWq3Dc6PkIPa1hM09kwpbnqRmozgAoR8AbuHr1Hihv4pIlX5kL_o7hcfukcdjx2jAdXynZ80GfAqrG5w22qLcmxEu1p6NJ1GjI_tqSaVLTIoG0QIeioHFtnIBQumie902IVE40ZufsZwEgLGLCE0xlG82cIW1oQ6kzkyltxgE6Ic5kLq3UlpqcMbyOkOWbWPoKHBuocArcVIoguAsPte8qKLjGGvZbIbUD5Wymm5HSbdnFbYrPQXPeC0X6E3cbELBxqivJIYop-jPQ3-U-i-uJS0_4PEmanXBHCSkUOE6DaJYULiWQJPkYsmuCDqV0FAJT8Y8_yrDJ33ibYscbh3TJB-p5NuJ19YzsUuTKk0Rwf3MTCstNk09B9ZlPYaxbzB-GLFd2boBtTEcKiZKbCFSykjoiA1ktqMM5xrpXws6c-vDIFz7l6BjLd2qaMjv73aFm_RrDsssb3FrviKu3vntsdApyRJzE_XZLY9VsA73GF3VKk4EF8GkCuhunHLdpIgBj8h_x1CsU9iWHX_ElRMX87Td-7bGuXJUwW9NeOAj76aVaKd0NLfluqYSTt3YPbDjgCYGIOpop9xP2h5IdxVHer9_zge0ivR2GgNgkHkgFYun_3icUGqF86q87ugZsYULwL9fJNB2Hj4wgKvRSYJ53LxwEDpUbetdFTAlPlMCYs4Ib--va8kAWwnI3MLhJ-JdouLflmOFu9T7KsTF280tMOO5UQaWuju2FUaBfw8okmRf0DLakXEYeTq45wJTXk9DTWmNOJI1SsbGI-vSjY10mLlDKc2us7UKiGLn43sz3X1ld84trMOChpEWWiHoB1Uo6BC_jaiS4CrEdWrRi7auedbZn1t_WCOUZO_QAtYoU4p62Ppje9ThtW6kRg_TytZPnqogCHeCQeVy9QtZw3I-nq6eYLgSzSIZbtsZ4u4VrOF0cbFuYZ6q-YT88ZmvqpiRobjBYdL1_tpjaj1VWuMoLfrHDu2cxlHBmBRwcb_sHf5Dz-P4_azCjg82CXMOrWTLjctGMv78p2FBOim7l_w8y_OHr44fqGsx35ODPBYOu9ddhGy7mll9IpymtlUtZ2wIZNqmhKf0AR8NjpFxYpYVPVv_B-Atwh3N_qiMIV_7_zbk39SHeJw4nKgaKp2ypQJvX8O3-941MaIt2nJn7CPmN333NFe7oOaV9xwpgAkWO6LwxDB7RZpskBSZZTK4OhPhJgB9LRpwkla2h1k7QkLwpspjAWLjfoPqa3EenYIXhCB4-lgKMd6sKmCfTpcF8E5zzSltQJSRbqHSZagRR-xVA2gTylXi2tpURT7BHUqOk2sAxHZNbfWLAVAYFCi_COQ8dyrwKBirHsfjxmUG9PG6j3-HBO-OqgJrrMM3lzPjTP5qnKJ1BYbMOizRWzMVm47G3iKPN1Pei-g04QcN0n6kcyfWcGXXQStko01qCDfIIIIdSij6FvHvf8CQCboXMiN53eXOANwyoE3_P4RXgFRIOsdEXoJkkJ00i8o2_9IL8CuxYCccqBdo2V4cM5kX7zNqHNoYXJkX2lkzhQ8hB-icGQA.M9eC25iavhmBQM5RKs2MEiVvL2Zf8Xhfte-ETu27IgQ", "use_voice": false}' 'http://192.168.1.131:8080/v1/register/+NUMBER'

BR

**Comment by M-Pixel** [comment]
I'm also seeing "Invalid captcha given." consistently.  Tried about 6 times now, following the instructions exactly.  Tried different browsers.  Perhaps Signal has made the captcha expiry timeout too short for human copy-paste.  I even tried doing it as quickly as I could manage, but as quick as I am with this keyboard, grabbing the link and removing the scheme and pasting it into the terminal still takes well over 400ms.

**Comment by kojanovski** [comment]
> I'm also seeing "Invalid captcha given." consistently. Tried about 6 times now, following the instructions exactly. Tried different browsers. Perhaps Signal has made the captcha expiry timeout too short for human copy-paste. I even tried doing it as quickly as I could manage, but as quick as I am with this keyboard, grabbing the link and removing the scheme and pasting it into the terminal still takes well over 400ms.

Hi,

You don't need to hurry. You have a couple of minutes to complete the registration. I left my 2nd phone with a sim card I wanted to register in another, remote  location, so I didn't have it with me. After submitting captcha I managed to access my 2nd phone remotely, make a backup of text messages, upload the backup to a location where I was, and retrieve Signal auth code from the text message from the backup and complete registration. I suggest to use any number for testing, can be any fake number until you get a proper result - the proper result means you get no error message, you simply will be returned to the prompt in the console. Obviously no auth code from Signal will be received as it is the fake number. Once it done, remove and install again the add-on to remove fake numbers permanently. Now you can register your real number. See the screenshot from my registration. BR.

![2023-05-14_17h35_05](https://github.com/bbernhard/signal-cli-rest-api/assets/80360113/1eeb11cf-550f-4f32-8d0a-6a2651d05956)

**Comment by gorman553** [comment]
Hello,

I have the same problem, and no clue what I am doing wrong.
I tried in native mode and in normal mode

I tried with:
curl -X POST -H "Content-Type: application/json" -d '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQlJWodWyJT9YS49jhUafkBN4LnFpy0M3RoeslyPFXvw3-IbnPTgTaYucBHXd9tnLYpyUlIIU1RtvAslnO4qY_L6VEdu0jU8l5WXeET911mFnvEj1AysByXdYxwR8OFVj_TUINQyQe9b8sRUO8eA1cHsKwHFrPPGeLk-KGyf1mwWH_N7mZ2UigOeWFPUUDA-gImcg3vmNjA15vys6MY_h4pADHVd8jNIwAHwTOwEJkDci5NtBHkAXPz0SC8A3HiVfge2YZFoHD_7dHj8ZnJp2tsOIp_QzGKLQcN2pT0YnTDEZLpnuglkNjL-Wy-0tZdR2aViwbHNAXeAOuRGiP_BxqsHAZ27zq-BbzrHk6AD54QtUmNJ_YMWGkQ-LGBDsxyaQEaHBtErOGmcni3ryz2KRSSMwUnDlx4eV5_4ONwpwyG4Hon0JHsYh5vgvWKNAVeUC7B50jdrPlR_Z419hjPxsAk80L2CPQSr5Fog1mmzX7KeiL36P7e0UKsDE3I0-g5LUEzh92XZxGXeS9393-n4Fo9oXoy-sPpSesj3xYp9_apjMcKCCDh-GwR3JoGeJtJW7JzYSBlm6VULlV8-x0szYDdlCODS5JAjU0hBiopkDuO2GNN2y5-Ldur9iVUlMZbjihVNLTSUMff85HEt12NEeWkmBLIgoq2KuBnprcfDA0Kq1B-ThRPlpWdw-wIH5nkGU774vBreIxpxaR3ZeliP8cyaDMLFkYLse7T6Io1mMyzqyjN4O71wH7ecXqVIgDYLpzpnstAWbgjxduj2eIHHRoNLIJbys7abtFzRxtgNG41Uq5CbbmOWQYYL8c-9yCZZvjqZU4AdTyOFtp-_zoi6ebuNP2JCtRCxBLVMeuOmHukEPrvGj7H4uIDBTvJtAqM0on_N2xzGfoyoFVqaYchpXMF0QA-ClSIZ67TosUpYQwqCLL8-sRuh29XUcOg3V8mXy1OQpsHnebYQ21fQfmskAbOfpNYKb1ttNlO9gx-cI_Pq9jYPn8yFcwXGtuZC5ShyeeE4_a2jjHT8N43u2n1sDTLLeVMkxI90QBEOnLCHLScyPy_kEc5gkAGpWQ0ArZx4QJztuGlQakzC6X6DFIoGjxYFWjfJicgwim1zgECKD2RMFw-FCIsWalULIQk49ESnp-MbGK68V0eBxQmF3VqriNGyzdolZtUviHJFlX7glXyKkwzCGkCo3tJNBTcDIo75l3FR60-gGiZSBDsxnSZRkaXv8dWPhdO0SBCUF4ZlSJStwUJuvTLC2g_69uyJ7fOT4OJ602IYnxAaACVogsdub9_GaOvty0S-C4az87x7RnkVcyu5lmwJtPwWOnHtQarwtPUcQZfg74NfX_JHNtPQwqJZr0BrOsPH50wZPI_YBzgNX0hqmimKH6U2T1eNVa_Rmt3N_6TBUpzPZaK498gkOhBxfE2sx6DZBSdj-2L8PgNhmfCBazRmwKT8dg1biGjRBr2yBPSAyGeJdLbMmH6lnSM1SIRbxplhFWBDfmXlNlcWV6WfzdN1xOFYyaryqoNoF0K8PUiMD8lyPNTVgKrfPgzhqUPfaHDoByrfjniXWq30g8awo7lj2QyEwDsZjH_wIaATy8Dtitx3mOwAnfgpr7p5Yti_C6eGTpiJl57t2uVbkQV_vm6E4oQ2xkirGn3VDlMt3tCQIJud49D7-zCOhBnrSaCSESaBgbym9zr9Svrxl2EeWEhtq_Jo-9PiAWUZO3Bi1V9g_sGlr039jEDEWBBdj5Zws9CrGz6cENLaS1hA2fHF9pVf5pnxd1F56huzV-FSwPjVLMEzl40ZnxkGOrvk9lJqtN2PbkcI0H4YjWqM-dRV-HnbQsAVzDm9mucDxp56AxPIXf0MYfopIzIxnVMUj1NvK9yPyrn8OcSWYoi88SbXudUtJQlVCvXoCXypYNQ7qiaG6hq_wZKyEKabSBxP0ZvowWEQN_cqHDJxZDBnwEw5HXzaZO0-fR9T7IR20T4L6KYG0Pcxz-qkNYKpmC5whGunRk7MolUKW2NU5SJP9WhT-akRDGXMwCKhPYRM_rc2wve4vk63tVJM0mPEx8oaVlaAauZzqwS_MHhlqBQNFfyBLLhDEGuBAWjQOUtUkO9C_tUlpa1nqv9VUyW1nFGi9N0DX-S6x8FrydtjiCvZakNnUYBz9yvx7qBiCppUZ_niytlfvp-90nUkT-NS5vjzJ3HfRxMWx3dv5GbENxAhLiP5pQYPc6U7tlHpCaiDr0RzDKM961swE4qOLguqRwUO2PPlbjR4gSfxNf2CKmtX3WugjM8zIDBDvbSsigu1jS7D--cIybpp9V1HMU9vYuexLVv7DLGEpFrp43_WJVyGXyExDpY-gCZPRla6YGuP04Oo7ORWnFIF-eIwL4npYcpbGjjapdGSEk0QhpjKa-1u6Csl6Blv9OpMZo90-l4EUtjoAN_2rLmMN73A3goBpfwc2wHPZjmV8ECaMqJxFY1Dj9USkxvYv--D4bMeGhhAPICshxOaid6UqRXGZv-tXGz1Gitw4rHe575WkvW4yOHIkwfnfm4u2IUGM3QeIywG86tGfdDfnbC8BE525u3ouPWdSyiBuzfMYF3ZSAG4zki8PQ7kTy8K7VniU71IqWSAjbu2z5Ln02SPQQpDF1pDq8EQn1PByWI0OVwvolDdfhqd_ZYlK68j3rFI-G8Hz5tsOQ-ITgKNWFQMybht_YYlTZATC_BaPAjovoFuczlXMuNDtTGY-h57HMtdgWnhf9isQxQIes5EiKddesl-oOtsenSkEvBe4VwRBeS9KyfM7Llo8p0aRbAdHFQnH8R7JVRKV8K-zRYXUc-ctMGw5JTsFt57chKs5442mMAoXRwuDWCc_BJ8cUmsKdzDElleT-eJr-BtKs1EB5y734DS1F0ncV5g9dgKDeKSuI93yaozmjh5g8Xs_gFFSZ8Ifq9zSe9f91MQ0d74YCFykYWRUOS6fH00fLycvClBniOOtIIEysO2gh4JF6fTAiwDDQj92oKuPW1to6h2mm70IAsvY3fj37w2POHTzUywbtpyvk-RZOJFZCabJyVtC6cbxqgLPCleWNhpXZ-NlElFlRyZZEwMSsLFf-WhCaNo1QP7GwEI0ZQwRme03k-pAy6dg5VjNcwve4iiNddO8fY1pKKQYew2H1zh1g6g2a91HUP28qNleHDOZGijJahzaGFyZF9pZM4UPIQfonBkAA.N0Ooh1JnXRmMxIrG0HioK9dyH4Wx74vopW3PWepQBNQ", "use_voice": true}' 'http://192.168.X.Y:8080/v1/register/+49123456789'

and I got
{"error":"Failed to register: [413] Rate limit exceeded: 413\n"}root@jarvis

I tried to wait 24hours or 48hours. I changed my IP. But nothing.

What is wrong? Thanks for any hint on it.

I used to PCs (one with the hassio docker image) and one with the browser. But they have the same external IP.

Thanks for any help on it

gorman

**Comment by dufguix** [comment]
Hello.
Same problem here.

MODE=normal

First try without captcha.
Second with captcha --> {"error":"Failed to register: [413] Rate limit exceeded: 413\n"}

**Comment by gorman553** [comment]
Hello,
I found a solution for the problem.  I tried with the dev-version from signal-cli https://github.com/AsamK/signal-cli/actions/runs/4582714390 

as described in

https://github.com/AsamK/signal-cli/issues/1202

and after successfull registration I copied the key and other signal files to the container of the rest-api. No it works with HA as expected

gorman

**Comment by Fossy777** [comment]
solved... Re-installed the whole add-on (and I guess thus also pulled latest version of the container) and tried it again after some days, plus I waited for not only 1 but rather 2-3 minutes between the voice:false and voice:true commands, then it worked first attempt, like a charm. All fine now.

**Comment by dufguix** [comment]
> solved... Re-installed the whole add-on (and I guess thus also pulled latest version of the container) and tried it again after some days, plus I waited for not only 1 but rather 2-3 minutes between the voice:false and voice:true commands, then it worked first attempt, like a charm. All fine now.

Do you use the same captcha between the voice:false and voice:true commands ?

**Comment by Fossy777** [comment]
No, a new one

**Comment by fixmeee** [comment]
Hi all,

thank you for the great feedback. I can also confirm the workaround described in [AsamK/signal-cli#1202](https://github.com/AsamK/signal-cli/issues/1202) is working now.

BR
