### ISSUE TITLE
`AUTO_RECEIVE_SCHEDULE` seems to be broken

### ISSUE THREAD

**Issue by xSAVIKx** [bbernhard/signal-cli-rest-api#363]
### The problem

So I'm trying to make the `AUTO_RECEIVE_SCHEDULE` work, but it feels like either smth has changed in the CLI config structure or the code for the CRON is outdated, or smth else :-( 

I've tried using 2 schedules that should just be calling the `receive` very frequently. The `* * * * *` - just to call it every minute and the `*/2 * * * *` - to call it once every 2 minutes. Both seem to do nothing.

The container I'm running is the [v64](https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.64) and runs in `native` mode.

I've tried enabling debug mode and see no debug logs from the CRON. I also don't see any logs with any errors. Just no CRON task logs whatsoever.

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

### Additional information

Also, I see the health checks and `send` works fine and getting groups, etc.
![image](https://user-images.githubusercontent.com/5675689/236333830-4235e095-94ed-4af9-a8ba-763c341b7c1a.png)

I'm not sure I fully understand the CRON file scanning logic, but it seems like there must be a file with a phone number format name in it (starts with `+`) in the signal CLI config (https://github.com/bbernhard/signal-cli-rest-api/blob/11da8f867d9b9931fbd4da6dded9c041c4d80236/src/main.go#L272) and I don't think there's anything like that in the config folder. I'm using the default config folder and it's content looks like this:
![image](https://user-images.githubusercontent.com/5675689/236334406-e73fb30b-c025-47f2-b7cf-c6be6894ee6a.png)
(the JSON RPC is from the previous runs, I'm positive that I'm running in Native mode now).
Also the `data` looks like this:
![image](https://user-images.githubusercontent.com/5675689/236334517-f54247f7-ef59-4199-a61d-b87d0372cdb7.png)

**Comment by bbernhard** [comment]
Do you have a dedicated phone number that you use or have you linked your phone number to the docker container? From the screenshots you've posted, it looks like as if you are running a setup with a linked phone number, right? (at least that would explain why you don't have a file starting with `+` in your data folder). I _think_ I've never tried the `AUTO_RECEIVE_SCHEDULE` with a linked number, so it is likely that it was never with that and you've discovered a bug :see_no_evil:

**Comment by xSAVIKx** [comment]
> Do you have a dedicated phone number that you use or have you linked your phone number to the docker container? From the screenshots you've posted, it looks like as if you are running a setup with a linked phone number, right? (at least that would explain why you don't have a file starting with `+` in your data folder). I _think_ I've never tried the `AUTO_RECEIVE_SCHEDULE` with a linked number, so it is likely that it was never with that and you've discovered a bug :see_no_evil: 

Yeah, I basically have a number of linked numbers and I need to just discard their messages from time to time. I believe this is a required call to do a receive before I can get the groups. Getting the groups and working with them is the end goal.

**Comment by bbernhard** [comment]
I see. Is there a specific reason why you can't use the json-rpc mode? (that's usually the mode I'd recommend, as it is the fastest mode and doesn't require the `AUTO_RECEIVE_SCHEDULE`).

**Comment by xSAVIKx** [comment]
> I see. Is there a specific reason why you can't use the json-rpc mode? (that's usually the mode I'd recommend, as it is the fastest mode and doesn't require the `AUTO_RECEIVE_SCHEDULE`).

Yes, I need to be able to register new users and JSON rpc has no support. That's one of the reasons why I was asking about multi-container mode here (#354)

**Comment by bbernhard** [comment]
Should be fixed. In case you are interested, I can provide you with a docker image for testing (the docker image would contain the latest changes from the master branch. i.e the new, updated signal-cli version and the changes from above).

**Comment by xSAVIKx** [comment]
> Should be fixed. In case you are interested, I can provide you with a docker image for testing (the docker image would contain the latest changes from the master branch. i.e the newest signal-cli version and the changes from above).

That would be great 👍

**Comment by bbernhard** [comment]
Here you go: `bbernhard/signal-cli-rest-api:0.116-dev`

**Comment by xSAVIKx** [comment]
First of all, thx for checking this quickly!

The auto-receive functionality now works. The requests are sent on a given schedule. But there's a question regarding the `-t 1` in the command CLI when calling receive. It seems that with such a small timeout it just fails to receive the messages when there are a lot of them (consider a case when receive wasn't called for a long period of time). So can you maybe let this configurable?

**Comment by xSAVIKx** [comment]
Yep, after doing the `receive` manually via the CLI with increased timeout the auto-receive then works perfectly fine

**Comment by xSAVIKx** [comment]
@bbernhard, looks like there's a constant crash loop when auto-receive can't find/access the `accounts.json` file.

**Comment by xSAVIKx** [comment]
Hey @bbernhard, I hope you're doing well. Wanted to wonder if you plan to publish another dev/prod container?

**Comment by bbernhard** [comment]
should be fixed
