### ISSUE TITLE
No matching manifest for linux/arm/v6

### ISSUE THREAD

**Issue by fr1sty** [bbernhard/signal-cli-rest-api#367]
Trying to install this on my Volumio box. Running on a Raspberry Pi Model B+. 
But getting the following error:
`volumio@volumio:~$ docker compose up -d
[+] Running 0/1
 ⠧ signal-cli-rest-api Pulling                                                                                                                               3.7s
no matching manifest for linux/arm/v6 in the manifest list entries
`
OS information:
`volumio@volumio:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
`
`volumio@volumio:~$ uname -a
Linux volumio 5.10.92+ #1514 Mon Jan 17 17:35:21 GMT 2022 armv6l GNU/Linux
`

**Comment by bbernhard** [comment]
I am sorry, but the docker image only supports `arm/v7` and `arm/64`.
