### ISSUE TITLE
Search endpoint broken with multiple accounts

### ISSUE THREAD

**Issue by MarcoBorchert** [bbernhard/signal-cli-rest-api#369]
### The problem

I have 2 Signal accounts registered on the server (version 0.66).

When trying to use `/v1/search`, the following error is returned: 
`Multiple users found, you need to specify an account (phone number) with -a\n`

Directly using signal-cli-native from within the container works when supplying one of the registered accounts with the -a parameter like suggested in the error message.

Maybe the search endpoint could be changed to to `/v1/search/{number}`?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

### Additional information

This issue was previously mentioned in a feature request: [Search for registered numbers with specific account for multiple users #253](253)

**Comment by bbernhard** [comment]
should be fixed with the next release. As suggested, the endpoint now let's you specify a number. i.e: `/v1/search/{number}`.
In order to stay backwards comptatible and not break any existing setups, the number parameter is optional. So, if someone uses the endpoint without the number parameter and has only one account registered, it works like before.

**Comment by MarcoBorchert** [comment]
I can confirm the change in release 0.67 fixes our usecase.
Thank you for the quick fix as well as for the overall quality of the API @bbernhard

**Comment by bbernhard** [comment]
Thanks for the kind words! I am glad it is working :)
