### ISSUE TITLE
Cannot create new group

### ISSUE THREAD

**Issue by DigitalTuna** [bbernhard/signal-cli-rest-api#370]
### The problem

Hi 

**trying create a group or send a message to an already created group on my device (via group link) fails.**

1. I ran docker with signal-cli
2. I registered my acc on: 
`http://192.168.10.140:3002/v1/qrcodelink?device_name=signal-api` -> that worked fine
3. I can send messages to a number with no problem using:
`curl -X POST -H "Content-Type: application/json" 'http://192.168.10.140:3002/v2/send' -d '{"message": "Test via Signal API!", "number": "+4917580626662", "recipients": [ "+4917580624545" ]}'`
4. Sending Messages to numbers works fine
`curl -X POST -H "Content-Type: application/json" 'http://192.168.10.140:3002/v2/send' -d '{"message": "Test via Signal API!", "number": "+4917580626662", "recipients": [ "+4917580624545" ]}'`

5. On my mobile device I created a new group which has the group-link
`https://signal.group/#CjDKIC2_KNpPL730K_y6SwFcfqg1UC1yFuP1BvNWpnruQEOREhBskQKvqQwQnph1FDMx5DRq`

6. Trying to get group list gives empty array. The number : +4917580626662 is memeber of several groups
`curl -X GET -H "Content-Type: application/json" http://192.168.10.140:3002/v1/groups/+4917580626662`
-> result: `[]`

7. If I try to send to create a group like this, it does not work:
`curl -X POST -H "Content-Type: application/json" -d "{'name': 'My_new_group', 'members': ['+4917580624545']}" 'http://192.168.10.140:3002/v1/groups/+4917580626662'`
-> `{"error":"Couldn't process request - invalid request"}`

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

My account has a name and avatar set!

**Comment by bbernhard** [comment]
After you've created your group, have you called the `/v1/receive` endpoint? This is necessary in `normal`/`native` mode, but not in `json-rpc` mode. (btw: if there's no specific reason for you to run your docker container in normal mode, I'd suggest to switch it to `json-rpc`).

**Comment by DigitalTuna** [comment]
Yes, calling /v1/receive endpoint worked. 
Just a wohlmeinende suggestion: maybe this call should be described more prominently in the docu on the front page. I missed it. Btw, I also ask myself if the receive call stores some private information in the docker file? If yes, that might be a security issue.

**Comment by DigitalTuna** [comment]
Yes, calling /v1/receive endpoint worked. 
Just a wohlmeinende suggestion: maybe this call should be described more prominently in the docu on the front page. I missed it. Btw, I also ask myself if the receive call stores some private information in the docker file? If yes, that might be a security issue.
