### ISSUE TITLE
Linking not working

### ISSUE THREAD

**Issue by karlmagi** [bbernhard/signal-cli-rest-api#371]
### The problem

Might be related to  #330.

Just installed a fresh add-on in HA. Tried normal and native mode.
When trying to link a device nothing happens.
Tried with a Android phone and a Iphone SE (different signal accounts).
When trying in Android i get the little message "no device found".

I am generating my qr code using Firefox on linux: "http://HA_IP:8080/v1/qrcodelink?device_name=homeassistant"

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by kalbfuss** [comment]
I am having the same problem. Using Signal REST API as Home Assistant add-on. When I try to link the API with my Android device I receive the error message "No device found" on my phone. The API is not linked afterwards. Tried with latest version of Signal (6.23.5), two different phones and two different accounts.
Version of the Home Assistant add-on is 0.66, installed from https://github.com/haberda/hassio_addons. Home Assistant and the add-on run on a Home Assistant Yellow device (Raspberry Pi CM4 based).

**Comment by RobinGiel** [comment]
It worked for me after stoping my wifi and switch to 4G
