### ISSUE TITLE
Possibility to not use array when sending to a single recipient (Synology case)

### ISSUE THREAD

**Issue by DigitalTuna** [bbernhard/signal-cli-rest-api#372]
### Feature Request

Currently the api always needs an array even if you send a message to one recipient (group or sim#). 
I would like to use this API to send notifications from my Synology NAS to my "monitoring" signal group. The problem is that I cannot configure Synology to send arrays.

What ever I put into the GUI, it never creates a request that would contain an array.

Here is an example:
![grafik](https://github.com/bbernhard/signal-cli-rest-api/assets/78354266/a413eee5-66ab-4e17-b09c-dc671f5514a2)
![grafik](https://github.com/bbernhard/signal-cli-rest-api/assets/78354266/c547140a-026a-48d2-a417-6b2af0de26c2)

**Comment by bbernhard** [comment]
This is now implemented. See https://github.com/bbernhard/signal-cli-rest-api/issues/428#issuecomment-1949056607 for details
