### ISSUE TITLE
Make first contact to API more clear for HomeAssistant users

### ISSUE THREAD

**Issue by bromosky** [bbernhard/signal-cli-rest-api#38]
Hey there,

after some initial problems this code works pretty good for me. But it wasn't that clear to me, that I need to interact with the API from another machine through CLI. I thought of some configuration in the HomeAssistant UI, but after I got the way it works, it was so easy. Found out, that I wasn't the first one with this question, so maybe you could point newbies abit in the right direction.

Something like: 

After installing the Addon, you need to go on with registering the phone number through Command Line Interface (from the same machine or another local machine) and not within the User Interface from HomeAssistant.

Maybe you/I need to change some words to make it more clear and avoid confussion.

If you are okay with it, I could also do a pull request.

(Talked about it here: [https://github.com/haberda/hassio_addons/issues/8](url) )

Max :)

**Comment by bbernhard** [comment]
yeah, sure. I think the documentation is also structured a bit unfortunate at the moment. I imagine that it might not immediately be clear, that there are actually two slightly different ways to interact with signal-cli-rest-api from Home Assistant (one being the Home Assistant Addon and the other one being a simple docker container). Any documentation improvements are highly appreciated! Feel free to create a PR :)

**Comment by KamelStrike** [comment]
Hello, 
Maybe you can help me with my interogations?
When i register the phone number with the curl commands on the signal-contener --> My signal-phone ask for register the number with token.
So signal can't work on Hassio + on my phone at the same time ?

Thanks a lot for your time.

**Comment by bbernhard** [comment]
> So signal can't work on Hassio + on my phone at the same time ?

The REST API is just a small wrapper around [signal-cli](https://github.com/AsamK/signal-cli). So everything that's possible with signal-cli is theoretically also possible via the REST API wrapper. But, at the moment only a subset of the functionality is exposed via the REST API.

That being said, there's a functionality called "linking a device" which is most probably what you are looking for. I do not have any experience with linked devices, but there are some users who run such a setup (see https://github.com/bbernhard/signal-cli-rest-api/issues/35).
