### ISSUE TITLE
support of new text-style option

### ISSUE THREAD

**Issue by andreasbrett** [bbernhard/signal-cli-rest-api#382]
### Feature Request

Signal-cli v0.11.11 introduced [text styles](https://github.com/exquo/signal-cli/blob/master/man/signal-cli.1.adoc) and I would love to use that via signal-cli-rest-api as well. Are there plans to implement this already? I know that it currently is not fully implemented in signal-cli ([missing in DBUS](https://github.com/AsamK/signal-cli/issues/1271)). That might be a blocker for now but I'm just curious if styling text messages will be implemented through the REST API as well. Would greatly help me in formatting notifications.

**Comment by bbernhard** [comment]
That looks interesting. I am not really sure whether signal-cli allows multiple text-style statements, but if it does, I could imagine a Markdown like Syntax for the REST API. 

e.g:

```
curl -X POST -H "Content-Type: application/json" -d '{"mode": "smart", "message": "**This is a bold text**, *this is a italic text*", "number": "<number>", "recipients": ["<recipient1>", "<recipient2>"]}' 'http://127.0.0.1:8080/v2/send'
```

What do you think about that? Would that work for you?

**Comment by andreasbrett** [comment]
> I am not really sure whether signal-cli allows multiple text-style statements

signal-cli takes multiple text-style statements as the man page suggests:
![image](https://github.com/bbernhard/signal-cli-rest-api/assets/6610451/cebddfab-8b6f-4140-8287-58e00fe8e1e7)

The markdown-style example would work very well for me.

**Comment by berofa** [comment]
I would love to have these formatting options. Any news about it?

**Comment by bbernhard** [comment]
First draft is implemented. If you want to give it a try, I'll try to upload a test version in the next days.

**Comment by ostasevych** [comment]
> First draft is implemented. If you want to give it a try, I'll try to upload a test version in the next days.

Yes, please. Will it cover SPOILER as well?

**Comment by andreasbrett** [comment]
> First draft is implemented. If you want to give it a try, I'll try to upload a test version in the next days.

@bbernhard Did you upload it somewhere already? Couldn't find it but am eager to test it.

**Comment by bbernhard** [comment]
Here's the docker image for testing: `bbernhard/signal-cli-rest-api:0.118-dev`

Currently only the **bold** and *italic* style options are available.

Example:

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "This is a **bold** text and this a *italic* text", "text_mode": "styled", "number": "<+number>", "recipients": ["<+recipient>"]}' 'http://127.0.0.1:8080/v2/send'
```

**Comment by andreasbrett** [comment]
> "text_mode": "styled"

Works for me. Have changed a lot of my Signal-Cli-Rest-API notifications to use formatting now. Will let you know of any quirks experienced in the coming days.

**Comment by andreasbrett** [comment]
Found a bug. Only the first instance of a bold text element is sent as bold. For italics this works just fine, all instances are formatted correctly.

Example message: `This should be **bold** and this should be *italic*. This is something **bold** again and this *italic* once more. And another **bold** text followed by an *italic* one.`

Renders like this: This should be **bold** and this should be *italic*. This is something bold again and this *italic* once more. And another bold text followed by an *italic* one.

**Comment by bbernhard** [comment]
> Found a bug. Only the first instance of a bold text element is sent as bold. For italics this works just fine, all instances are formatted correctly.
> 
> Example message: `This should be **bold** and this should be *italic*. This is something **bold** again and this *italic* once more. And another **bold** text followed by an *italic* one.`
> 
> Renders like this: This should be **bold** and this should be _italic_. This is something bold again and this _italic_ once more. And another bold text followed by an _italic_ one.

Thanks! Should be fixed. New build is running: https://github.com/bbernhard/signal-cli-rest-api/actions/runs/6124896610

When it finishes successfully, the following image should be on dockerhub: `bbernhard/signal-cli-rest-api:0.119-dev`

**Comment by ostasevych** [comment]
> > Found a bug. Only the first instance of a bold text element is sent as bold. For italics this works just fine, all instances are formatted correctly.
> > Example message: `This should be **bold** and this should be *italic*. This is something **bold** again and this *italic* once more. And another **bold** text followed by an *italic* one.`
> > Renders like this: This should be **bold** and this should be _italic_. This is something bold again and this _italic_ once more. And another bold text followed by an _italic_ one.
> 
> Thanks! Should be fixed. New build is running: https://github.com/bbernhard/signal-cli-rest-api/actions/runs/6124896610
> 
> When it finishes successfully, the following image should be on dockerhub: `bbernhard/signal-cli-rest-api:0.119-dev`

Hi! Would that be possible to add SPOILER styling as well, which is quite helpful for sending passwords or other sensitive data. Thanks.

**Comment by shalak** [comment]
There's also the MONOSPACE and STRICKE-THROUGH styles. They could be achieved via gravis and tilde, e.g.:

```
This should be **bold**, this should be *italic*, is something `monospaced` and this should be ~stricken-through~
```

Would result in:

This should be **bold**, this should be *italic*, is something `monospaced` and this should be ~stricken-through~

Unfortunately, AFAIK, there's no Markdown standard for SPOILER style, but reddit supports inline spoilers with `>!` as opening tag and and `!<` as closing, e.g.
```
This should be >!hidden in spoiler!<
```

**Comment by bbernhard** [comment]
`strikethrough` and `monospace` is now also implemented (as suggested by @shalak). In case you want to give it a try, use this docker image: `bbernhard/signal-cli-rest-api:0.120-dev`

**Comment by shalak** [comment]
Is there a simple way to install this within the custom hassio addon? Or better yet - migrate the HassOS-based Home Assistant addon to my regular docker-host? For the next few weeks, I don't have access to the SIM card I registered the signal account for, and I'd like to test some corner cases for this.

**Comment by ostasevych** [comment]
I've found that the dev version has slower response, so there's certain delay in processing the send request, around 14 seconds. Is it normal?

**Comment by andreasbrett** [comment]
> I've found that the dev version has slower response, so there's certain delay in processing the send request, around 14 seconds. Is it normal?

I have not noticed that. Messages arrive just like before without delay (have not measured, but it's still roughly 1sec).

**Comment by bbernhard** [comment]
> > `strikethrough` and `monospace` is now also implemented (as suggested by @shalak). In case you want to give it a try, use this docker image: `bbernhard/signal-cli-rest-api:0.120-dev`
> 
> Strikethrough works for me but monospaced does not. This is the payload I send via POST request to `/v2/send`:
> 
> `` {"recipients":["+xxxxxxxx"],"message":"this is a *test* with `mono-spaced` and ~striked~ text","text_mode":"styled","number":"+xxxxxxxx"} ``
> 
> I first thought the nginx reverse proxy I have put in front of signal-cli-rest-api messes with the backtick but issuing the command directly within the docker container via CURL gives the same results. The backticks get removed from the text but the text is not styled in mono-space.

strange. it works for me :thinking: 

That's the curl command I am using:

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "This is a `monospace` and another `monospace` message", "text_mode": "styled", "number": "<number>", "recipients": ["<number>"]}' 'http://127.0.0.1:8080/v2/send'
```

**Comment by andreasbrett** [comment]
Never mind, it's a known issue with the font on my Android phone that doesn't show monospace variants (same issues with WhatsApp and other messengers). If I switch system fonts then the monospace shows up correctly.

**Comment by Xmonpl** [comment]
I am also asking, like the guy above, to add spoilers.

**Comment by bbernhard** [comment]
With the next release spoilers should be supported. The syntax is: `||this is a spoiler||`

**Comment by bbernhard** [comment]
everything should be supported now

**Comment by ll3141** [comment]
should the actual 0.80 support this feature?
I'm trying to use it via the Homeassistant Signal-Messenger-Add-on.

     curl -X GET -H "Content-Type: application/jason" 'http://...../v1/about
returns 
    {"versions":["v1","v2"],"build":2,"mode":"normal","version":"0.80","capabilities":{"v2/send":["quotes","mentions"]}}

but the following command results in a Message containing the plain markdown characters
    curl -X POST -H "Content-Type: application/jason" "http://...../v2/send -d '("message": "Test **via** *Signal* API", .....}'

am I missing something?

**Comment by ll3141** [comment]
ah, yes, I was missing something: the "text_mode": "styled" part.

now I only have to convince the maintainer of the Signal-Messenger-Add-In to fix this in the add-in
