### ISSUE TITLE
Send some attach Microsoft Excel (OpenXML)

### ISSUE THREAD

**Issue by StanisGit** [bbernhard/signal-cli-rest-api#386]
### The problem

Why can't I send multiple xlsx files? But at the same time I can send some pictures. I can also send one xlsx file. I can also send one xlsx file. If I send pictures and xlsx file together, only the first picture arrives

`curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "some files", "base64_attachments": ["data:application/vndopenxmlformats-officedocumentspreadsheetmlsheet;filename=С названием.png;base64,iVB...ggg==","data:application/vndopenxmlformats-officedocumentspreadsheetmlsheet;filename=С названием.png;base64,iVB...ggg=="], "number": "+123456789012", "recipients": [ "+123456789012" ]}'`

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by StanisGit** [comment]
It turns out that this also cannot be done and Signal

**Comment by bbernhard** [comment]
this unfortunately is a general Signal Messenger limitation.
