### ISSUE TITLE
Trying to register a Google Voice number, received text but keep getting auth error

### ISSUE THREAD

**Issue by Austin1** [bbernhard/signal-cli-rest-api#388]
### The problem

I cannot figure out why I can't get this number registered. It's a Google Voice number, if that matters. I get the text with the verification number after doing the captcha but still get authorization failed. I've tried using a dash like the example in the verify code and without the dash. So the text says 

`SIGNAL: Your code is: 493704`
I've tried entering the endpoint as /verify/493704 and /verify/493-704

```
➜  EufySecurity curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://192.168.1.4:8080/v1/register/+1<number>'
{"error":"Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"}%
                                                                      
➜  EufySecurity curl -X POST -H "Content-Type: application/json" -d '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_...-M31o2V4cM5kwwJ8qHNoYXJkX2lkzjGtTIGicGQA.5cm2_BGOzXzwirBVbKAmpb_KSrlKppk2MMop4Gyse4A", "use_voice": false}' 'http://192.168.1.4:8080/v1/register/+1<number>'

➜  EufySecurity curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://192.168.1.4:8080/v1/register/+1<number>/verify/493-704'
{"error":"Verify error: [401] Authorization failed!\n"}%        
                                                        
➜  EufySecurity curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://192.168.1.4:8080/v1/register/+1<number>/verify/493704' 
{"error":"Verify error: [401] Authorization failed!\n"}%           
```                                                     

What am I missing? Hosted on an Unraid virtualization layer using a HomeAssistant VM and the default "normal" mode.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by Austin1** [comment]
I don't know what I've done, but now I can't even get a response. I run command with captcha and it returns nothing and no text comes through. If I run without captcha,it does respond, but says I need a captcha.

Is it possible to verbose log using CURL? It's almost like I've gotten my number banned trying to register it. Does that happen?

**Comment by bbernhard** [comment]
Please remove the whole `signal-cli-config` folder and start from scratch. In case you've tried too much, it can be that you are temporarily blocked and need to wait a few days.

Regarding the verbosity/debug logging: Please have a look [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md)
