### ISSUE TITLE
Send Message seemes successful but no message comes

### ISSUE THREAD

**Issue by markmghali** [bbernhard/signal-cli-rest-api#394]
### The problem

trying to send messages to a group ID via Home Assistant Integration.  I believe I am on the latest version.  Home Assistant says it sends and here are the logs from Signal-cli-rest-api:
![signal logs](https://github.com/bbernhard/signal-cli-rest-api/assets/17356528/8b116cc4-e18d-4863-bf43-4a51505ba0c7)

But I never receive a message. I read the troubleshooting to call the Receive API Endpoint but I don't' understand how I guess. Sorry for lack of understanding on my side. 

Signal-cli version 0.11.11
### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by markmghali** [comment]
EDIT:

I figured it out with this command 

curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/receive/phone_number

then tested sending a message with the cli and it worked!

Thank you again

**Comment by markmghali** [comment]
Okay I am running it in docker on unRAID. How do I change the mode?

Thank you for all your work on this

**Comment by bbernhard** [comment]
If you are running the docker container with docker-compose you can set the mode in the docker-compose.yml file

**Comment by markmghali** [comment]
It's docker in unRAID. So it uses unRAID templates. Can we update the
template?

**Comment by bbernhard** [comment]
Sorry, no idea about unRAID templates, you have to look up that works there (or ask in a forum)
