### ISSUE TITLE
Please add stickers features

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [bbernhard/signal-cli-rest-api#398]
### Feature Request
Hey there, first off, thank you for this rest API! It’s amazing <3 !!!
Now what I’m missing is being able to list the installed stickers and to install new stickers.
It is possible via the CLI so I’m asking to add it to the API. See: https://github.com/AsamK/signal-cli/discussions/1306
I could give it a try if you have no time but am also short on time

Thank you!

**Comment by bbernhard** [comment]
I can have a look once this feature is released.

**Comment by bbernhard** [comment]
will be part of the next release
