### ISSUE TITLE
Swagger BASE_URL and SWAGGER_JSON

### ISSUE THREAD

**Issue by tj57** [bbernhard/signal-cli-rest-api#406]
### The problem

The BASE_URL and SWAGGER_JSON variables for configuring embedded Swagger do not work in docker-compose, I cannot change the URL. The /swagger/index.html page shows local ip addresses from the container, so swagger in the container is not usable.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
It works for me. How does the docker-compose.yml file look like?

**Comment by tj57** [comment]
Here is my docker-compose config, swagger issue and container env result.
![image](https://github.com/bbernhard/signal-cli-rest-api/assets/20434907/c3694042-f64d-4e96-a0ee-b27654f161d1)

![image](https://github.com/bbernhard/signal-cli-rest-api/assets/20434907/0afe6625-7e06-4766-8bf8-311ceef1c7dc)

![image](https://github.com/bbernhard/signal-cli-rest-api/assets/20434907/bdd59080-8a7b-4100-9f37-31e411271ceb)

**Comment by bbernhard** [comment]
Have you tried setting the `SWAGGER_IP` env variable (see https://github.com/bbernhard/signal-cli-rest-api#advanced-settings)?

**Comment by tj57** [comment]
Now it working correctly with SWAGGER_IP and PORT env variables
