### ISSUE TITLE
can't install docker

### ISSUE THREAD

**Issue by maciejbrylewicz** [bbernhard/signal-cli-rest-api#408]
### The problem

Trying to run:

sudo docker run -d --name signal-api --restart=always -p 8080:8080 \
>       -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli \
>       -e 'MODE=native' bbernhard/signal-cli-rest-api

I get:

Unable to find image 'bbernhard/signal-cli-rest-api:latest' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/bbernhard/signal-cli-rest-api/manifests/latest": unauthorized: incorrect username or password.

Am I missing something?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by ostasevych** [comment]
run `sudo docker pull bbernhard/signal-cli-rest-api:latest` on your server/laptop/whatever.
