### ISSUE TITLE
Fail to return message timestamp on error

### ISSUE THREAD

**Issue by Xethron** [bbernhard/signal-cli-rest-api#409]
### The problem

Hello,

I recenlty had someone in my group reinstall Signal, and that broke my bot. The reason seems to be that, when one person in the group is untrusted, the signal-cli returns an error message first, followed by the messageid/timestamp at the end.

```
{"error":"strconv.ParseInt: parsing \"Failed to send (some) messages:\\nr+VOP.....Xg=: Untrusted Identity for \\\"+3162.....00\\\"\\n1695021300000\": invalid syntax"}
```

The message still goes through for all other recipients, only this one person does not receive the message.

I would like to suggest that in the above example, we could return both an error and a timestamp. Something like:

```
{
    "timestamp": 1695021300000,
    "error": "Failed to send (some) messages:\nr+VOP.....Xg=: Untrusted Identity for \"+3162.....00\""
}
```

I am happy to try my hand at implementing this if we can decide on a solution.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
That definitely makes sense. But I think this will probably break at some point (again), in case signal-cli changes the structure of the error message. But I guess that's probably our only option...

btw: Have you tried the ` json-rpc` mode in that condition? As signal-cli returns a json blob, I think the output should be better formatted. Just curious if this is also a problem there.

**Comment by bbernhard** [comment]
should be fixed
