### ISSUE TITLE
Couldn't send message to golang channel, as there's no receiver

### ISSUE THREAD

**Issue by toni-h** [bbernhard/signal-cli-rest-api#411]
### The problem

i get this error message when running in aws Couldn't send message to golang channel, as there's no receiver
this error pops up every second.

im using json rpc mode.

also got problems when trying to send messages to some groups. sometimes they work and sometimes not and getting error 400

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Are you sure that the number is properly registered?

**Comment by toni-h** [comment]
yes i think so. everything works great when i use it locally. 
i do the registeration locally with normal mode enabled, after that i change mode to json-rpc and push account info etc to aws.
is this the rightway to register in json-rpc mode?

**Comment by bbernhard** [comment]
Did you also copy the ` signal-cli-config` folder to aws?

**Comment by toni-h** [comment]
yea everything go's to aws. 
currently i try to delete bot account and try to redo it. lets hope it helps

**Comment by toni-h** [comment]
its odd that sometimes messages are delivered correctly, even in aws, but sometimes one of groups i try to send messages will fail for bad request error. i even checked that messages was correct. no anything odd in there

**Comment by toni-h** [comment]
i got it sorted out, i just needed to remove bot from groups and delete it's account after that i reregistered it and everything started to work. It also now sends messages to all groups everytime
