### ISSUE TITLE
Couldn't create QR code: no data to encode

### ISSUE THREAD

**Issue by henry-delaruelle** [bbernhard/signal-cli-rest-api#415]
### The problem

After installing on docker, and going to http://localhost:8080/v1/qrcodelink?device_name=signalapi i get the message Couldn't create QR code: no data to encode

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

I tested both x86-64 and Arm64

**Comment by Kuhkaefer** [comment]
May I ask what `http://localhost:8080/v1/about` yields?
And which command did you use to start the docker?
I had a similar problem…

**Comment by henry-delaruelle** [comment]
I used the procedure mentioned on github to start the docker

About states :

{"versions":["v1","v2"],"build":2,"mode":"normal","version":"0.67","capabilities":{"v2/send":["quotes","mentions"]}}

**Comment by Kuhkaefer** [comment]
Hm okay, I only had that problem with version 0.68 in native mode.
For me, version 0.67 (or also 0.68) in normal mode worked:

`docker run -p 8080:8080 --name signal-api-normal-0.67 -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli -e 'MODE=normal' bbernhard/signal-cli-rest-api:0.67`

**Comment by bbernhard** [comment]
@henry-delaruelle please try again with the latest version

**Comment by villovil** [comment]
@henry-delaruelle did you get it resolved?
@bbernhard I have version 0.69 and got the same error message. any other ideas about what I could try?

 About output:
{"versions":["v1","v2"],"build":2,"mode":"native","version":"0.69","capabilities":{"v2/send":["quotes","mentions"]}}

**Comment by villovil** [comment]
> > @henry-delaruelle did you get it resolved? @bbernhard I have version 0.69 and got the same error message. any other ideas about what I could try?
> > About output: {"versions":["v1","v2"],"build":2,"mode":"native","version":"0.69","capabilities":{"v2/send":["quotes","mentions"]}}
> 
> Please try in `normal` mode, there is an issue with the native mode in the latest version.

Worked like a charm!

**Comment by bbernhard** [comment]
should be fixed with the latest version

**Comment by kallewoof** [comment]
I am seeing this after running instructions on main github page FYI @bbernhard.

**Comment by xsquared** [comment]
@bbernhard - just an FYI that I'm also seeing this using the main page instructions:
`http://localhost:8080/v1/qrcodelink?device_name=signal-api` returns: `{"error":"Couldn't create QR code: no data to encode"}`

`http://localhost:8080/v1/about` returns `{"versions":["v1","v2"],"build":2,"mode":"native","version":"0.81","capabilities":{"v2/send":["quotes","mentions"]}}`
Switching from `native` to `normal` fixes the issue and it works beautifully (thank you!).
