### ISSUE TITLE
Link to the Swagger API documentation broken?

### ISSUE THREAD

**Issue by ChrWieg** [bbernhard/signal-cli-rest-api#418]
First of all, thanks for the great project, I love it!
Unfortunately the link to the Swagger API documentation in the readme seems to be broken: https://bbernhard.github.io/signal-cli-rest-api/
![2023-10-01 10_26_34-signal-cli-rest-api API documentation - Brave](https://github.com/bbernhard/signal-cli-rest-api/assets/39028994/f7500e42-13c6-454a-b7b7-26ed4a32a9cc)

**Comment by bbernhard** [comment]
Works for me. Do you have anything in your network that blocks the requests?

**Comment by ChrWieg** [comment]
Oh, you are right. Seems the CDN unpkg.com was on the blocklist of my pihole. It's working now, Thanks a lot!
