### ISSUE TITLE
JSON-RPC: not every message is being sent through websocket

### ISSUE THREAD

**Issue by yolanv** [bbernhard/signal-cli-rest-api#419]
### The problem

Currently using the Docker image in jsonrpc mode.
Subscribed to the websocket server with wscat and started sending messages to that number on Signal.
Sadly I notice that not every message is coming through. Sometimes I get the STARTED event, sometimes the actual message, but this is not consistent. Sometimes I simply do not get them through.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
should be fixed now with version 0.80
