### ISSUE TITLE
Regular autoreceive functionality

### ISSUE THREAD

**Issue by ostasevych** [bbernhard/signal-cli-rest-api#421]
Hi. Signal has started to warn that the account should receive the messages on a frequent basis:
```
{"error":"strconv.ParseInt: parsing \"WARN  AccountHelper - Messages have been last received 10 days ago. The Signal protocol expects that incoming messages are regularly received. ... }
```
After that I see that the messages are stuck in queue until I do manual receiving:
```
curl -X 'GET' 'http://127.0.0.1:8080/v1/receive/+*************?timeout=1' -H 'accept: application/json'
```
![image](https://github.com/bbernhard/signal-cli-rest-api/assets/5199030/30a11873-97a1-49dc-8ce6-3f096ea8162f)

Would that be possible to implement something like autoreceiving messages on some regular basis to solve this issue?

**Comment by bbernhard** [comment]
see https://github.com/bbernhard/signal-cli-rest-api#auto-receive-schedule
