### ISSUE TITLE
Set Profilname

### ISSUE THREAD

**Issue by erbse83** [bbernhard/signal-cli-rest-api#424]
Ich### The problem

On Home Assistant every Automation stopps with Error Message- i have to Set a Profile Name. I dont know how. 

The Message: 
strconv.ParseInt: parsing "WARN ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name with the updateProfile command. This may become mandatory in the future.\n1696987927031": invalid syntax

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

Home Assistant newest Version (OS und Core)

**Comment by bbernhard** [comment]
see https://bbernhard.github.io/signal-cli-rest-api/#/Profiles/put_v1_profiles__number_

**Comment by erbse83** [comment]
Can you please make an example with the command? I try much Versions but nothing works... The Error is 405. 
I insert my Number an then Copy the curl and put it into terminal at Home Assistant. Error in HA and in the linked Site is 405...

**Comment by erbse83** [comment]
Got it. Thanks!
