### ISSUE TITLE
Read receipt for messages possible?

### ISSUE THREAD

**Issue by Kuhkaefer** [bbernhard/signal-cli-rest-api#431]
### Feature Request

In order for the user to know that the bot successfully read the message, it would be helpful to see the white check marks as a confirmation.

Would that be possible?

**Comment by kxait** [comment]
hey, you get that from `/v1/receive`

**Comment by Kuhkaefer** [comment]
@kxait sorry, could you elaborate please? I am using 'v1/receive' but the white check marks are not shown. And in the docs I don't see an option to activate read confirmation.

**Comment by jneidel** [comment]
You only get the "delivered to" status from `/v1/receive`.

The underlying cli has a `--send-read-receipts` that is not available through the endpoint.
