### ISSUE TITLE
getting 'Is the number properly registered?' error in json-rpc mode

### ISSUE THREAD

**Issue by joopdo** [bbernhard/signal-cli-rest-api#435]
### The problem

Thanks for this wonderful solution! Creating an issue as I am debugging. I'm using signal-cli-rest-api for a year or so, and suddenly started to have a new issue, **'Couldn't read data for number : EOF. Is the number properly registered'?**. Switching from  json-rpc to native solves the issue. I think the next logic step is to remove the config completely and re-register to see if that resolves the issue.

docker-compose:
````version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    network_mode: host
    environment:
      - MODE=json-rpc
      # - MODE=native
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" 
      
````
Log messages (which happen in json-rpc mode):
````signal-cli-rest-api   | time="2023-10-31T06:24:52Z" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
signal-cli-rest-api   | time="2023-10-31T06:29:52Z" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
signal-cli-rest-api   | time="2023-10-31T06:34:52Z" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
````

Then I change the config to use native mode, and it signal-cli-rest-api works again:
````ignal-api-lowcpu-signal-cli-rest-api-1  | time="2023-10-31T06:37:15Z" level=info msg="Started Signal Messenger REST API"
signal-cli-rest-api   | [GIN] 2023/10/31 - 06:37:20 | 200 |   11.438782ms |       127.0.0.1 | GET      "/v1/about"
signal-cli-rest-api   | time="2023-10-31T06:37:30Z" level=warning msg="WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name with the updateProfile command. This may become mandatory in the future."
signal-cli-rest-api   | [GIN] 2023/10/31 - 06:37:30 | 201 | 10.104682961s |       127.0.0.1 | POST     "/v2/send"
```

Just to confirm, when I switch back to json-rpc, it's broken again:
signal-cli-rest-api   | time="2023-10-31T06:41:55Z" level=info msg="Started Signal Messenger REST API"
signal-cli-rest-api   | time="2023-10-31T06:42:00Z" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"


### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

arm64

### Additional information

_No response_

**Comment by bbernhard** [comment]
Have you tried setting the username? Although it is not an error, I would do it anyway. If that doesn't help, I would try to re-register.

**Comment by joopdo** [comment]
Ended up resetting the config, but to be sure set a username this time. Thanks!

**Comment by Kuhkaefer** [comment]
sorry to bring this back up. I'm having the same issue. How do I set the username?

**Comment by joopdo** [comment]
@Kuhkaefer `curl -X PUT -H "Content-Type: application/json" -d '{"name": "Kuhkaefer"}' 'http://192.168.1.1:8080/v1/profiles/+1234567890'`

**Comment by Kuhkaefer** [comment]
@joopdo Thanks!

Unfortunately, it is still not working for me with v0.70, although it works with v0.96:

clear folder:
`rm -r ~/.local/share/signal-cli/*`

start docker in native mode
`docker run -p 8080:8080 --name signal-docker-native-v0.70 -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli -e 'MODE=native' bbernhard/signal-cli-rest-api:0.70`

register device on
http://localhost:8080/v1/qrcodelink?device_name=my-api-0.70

set username
`curl -X PUT -H "Content-Type: application/json" -d '{"name": "Kuhkaefer"}' 'http://127.0.0.1:8080/v1/profile/MYNUMBER`

restart docker in json-rpc mode:
`docker run -p 8080:8080 --restart=always --name signal-docker-json-v0.70 -v $HOME/.local/share/signal-cli:/home/.local/share/signal-cli -e 'MODE=json-rpc' bbernhard/signal-cli-rest-api:0.70`

gives me:
`level=info msg="Found number  and added it to jsonrpc2.yml"`
`level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"`

Am I missing something?
