### ISSUE TITLE
API KEY auth

### ISSUE THREAD

**Issue by kratosok** [bbernhard/signal-cli-rest-api#438]
Please implement at least a API key auth mechanism so just any random request cant trigger a signal event.

**Comment by bbernhard** [comment]
If you want to have authentication, please use a nginx reverse proxy in front of your setup.

**Comment by CodeShellDev** [comment]
Hey, there I developed a secured Proxy for Signal API: Secured Signal API, it implements Query, Bearer and Basic Auth (+ Body and Path Auth). Aswell as per token defined allowed/blocked endpoints.
Here is the [Repo](https://github.com/CODeshelldev/secured-signal-api).
