### ISSUE TITLE
Unable to create a group - no versioned profile

### ISSUE THREAD

**Issue by playlix42** [bbernhard/signal-cli-rest-api#448]
### The problem

If I try to create a group via the `POST /v1/groups/{number}` URL, I don't get an error as an error response from the API; but looking into the docker logs reveals a warning message `WARN GroupV2Helper - Cannot create a V2 group as self does not have a versioned profile`.
The group doesn't appear in the signal clients of group members.
But the request response gave me a group ID, which is identical to the group ID i get via `GET /v1/groups/{number}`.
When I use this ID to send a message to the group, every member of the group gets the message as a direct message instead of a message in a group.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
Please try to update your profile (see https://bbernhard.github.io/signal-cli-rest-api/#/Profiles/put_v1_profiles__number_) and then call the `receive` endpoint afterwards. Then, please try again to create the group.

**Comment by playlix42** [comment]
Checked that out, works like a charm!
Thanks, I thought I already tried that but obviously I didn't.
I will close this as solved.
