### ISSUE TITLE
[Feature Requests] Verbose or debug mode

### ISSUE THREAD

**Issue by gadric** [bbernhard/signal-cli-rest-api#45]
Hi, 

I am just thinking if a verbose or debug mode with much more detailled logs would make sense?

I am currently have a issue that some messages from OMV are not sent via signal but I cannot debug.

**Comment by bbernhard** [comment]
I guess you are talking about [this](https://github.com/AsamK/signal-cli/issues/379) here, right? Unfortunately, there's nothing I can do right now, as it first needs to be implemented upstream. This project here is just a simple wrapper around signal-cli - all the heavy lifting is done by signal-cli. Once it is implemented upstream, we can also expose that via API :)

**Comment by gadric** [comment]
Ah I see.
