### ISSUE TITLE
Subject: Issue with signal-cli-rest-api: CAPTCHA proof required error

### ISSUE THREAD

**Issue by johe123qwe** [bbernhard/signal-cli-rest-api#456]
### The problem

I am encountering an issue while using the signal-cli-rest-api to send messages. The error message is as follows:

```text
{"error":"Failed to send (some) messages:\n+19291043005: CAPTCHA proof required for sending to \"+19291043005\", available options \"RECAPTCHA, PUSH_CHALLENGE\" with challenge token \"26ccfae6-4fc1-4df0-a27c-084a8191704c\", or wait \"86400\" seconds.\nTo get the captcha token, go to https://signalcaptchas.org/challenge/generate.html\nAfter solving the captcha, right-click on the \"Open Signal\" link and copy the link.\nUse the following command to submit the captcha token:\nsignal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN\n1700812896656\nFailed to send message due to rate limiting\n"}
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

Currently, the problem is resolved by executing the following command on the server: 
```bash
signal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN
```
However, I am exploring a way to achieve the same result programmatically using curl.

**Request for Assistance:**
I am reaching out to the community for guidance on using curl or a similar command-line tool to automate the resolution of the CAPTCHA challenge in the signal-cli-rest-api.

**Comment by eschaubert** [comment]
I got the same issue. It happened right after I switched on VPN or it could have been a coincidence and it was triggered by my frequent testing.

**Comment by bbernhard** [comment]
is now available
