### ISSUE TITLE
Can't link with QR code

### ISSUE THREAD

**Issue by bwirt** [bbernhard/signal-cli-rest-api#458]
### The problem

I've installed the latest version (0.70) and Signal will no longer accept my device when scanning the QR code.  There are no errors in the debug log as the failure seems to happen on the Signal side.  No errors are displayed  when I scan the code -- the linking seems to fail on their end after I scan the code.  

This is a fresh container built from scratch.  Used to work in previous versions.

Any tips on troubleshooting this?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by Kuhkaefer** [comment]
Seems to be a signal-cli thing (https://github.com/AsamK/signal-cli/issues/1386). So we need to wait for a fix :)

**Comment by reddwarf666** [comment]
I might face the same issue so I do not want to create a new ticket.

Running the latest Docker image
Running Signal on mobile (ios)
Generated the QR code and scanned with Signal
Goes through the process, no messages or errors
No device is listed in Signal after scanning QR Code
In the Data folder on the Docker Host I can see entries and the accounts.json file has the number of mu phone
Tried the curl command to send a test message:
curl -X POST -H "Content-Type: application/json" 'http://192.168.2.183:8087/v2/send' \
     -d '{"message": "Test via Signal API!", "number": "+316xxxxxxxx", "recipients": [ "+316xxxxxxxx" ]}'
Got a response like this:
{"error":"User +316xxxxxxxx is not registered.\n"}%  

I see no errors in the logs of the container, just references that the QR code was asked for (to register) and the Send command API call was made:
    [GIN] 2023/12/03 - 14:01:17 | 200 | 11.220054756s |   192.168.2.183 | GET      "/v1/qrcodelink?device_name=signal-api"
    03/12/2023 15:02:39
    [GIN] 2023/12/03 - 14:02:39 | 400 |  7.082493188s |   192.168.2.183 | POST     "/v2/send"

Should the device name be related to my Docker container name perhaps?
Curl has:
  /v1/qrcodelink?device_name=signal-api
Docker compose has:
services:
  signal-cli-rest-api:
    container_name: signal-cli-rest-api
    image: bbernhard/signal-cli-rest-api:latest

As you can imagine, this stops me right at the gate and I am lost on how to resolve this error.

**Comment by hvdort** [comment]
same problem here. Any news?

**Comment by martinleo** [comment]
In my case I'm just building my docker compose file and ran into the same thing. I was able to link my device on the first docker compose up, then I needed to re-build my compose file, so I unlinked the device on the Android app and ran up again. This time linking didn't work (network error).
The solution for me was just cleaning up the volume mapping (on the host). I guess running docker compose up with an empty signal-cli-config folder recreated files that allowed me to link my devices again.

**Comment by steeeeev0** [comment]
I have the same issue, I cannot link to Signal using the app on my iPhone. Tried a brand new container/volume, no luck. Only thing I can see in the terminal is the GET request:
` [GIN] 2023/12/09 - 17:46:16 | 200 |  1.374746847s |     10.0.30.197 | GET      "/v1/qrcodelink?device_name=SIGNAL-API" `

**Comment by paulkitt** [comment]
Seems to be fixed in the signal-project and we just need to wait for the next signal-cli-rest-api release including the latest version of signal-cli.

**Comment by bbernhard** [comment]
just released it

**Comment by paulkitt** [comment]
Amazing thank you so much! Just solved my problems of my services with the update :)

**Comment by paulkitt** [comment]
Thanks for all the effort with the project. Appreciate it a lot

**Comment by reddwarf666** [comment]
Thanks!

**Comment by bbernhard** [comment]
Thanks for the kind words! Glad it is working for all of you now :)

**Comment by asyslinux** [comment]
Latest version. When try link via scan `/v1/qrcodelink?device_name=signal-api` QR code on phone, then java detached as zombie process. Tried in normal and native modes. 

```
signal-+       1  0.0  0.8 1545616 34172 ?       Ssl  20:20   0:00 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
signal-+      24  6.7  0.0      0     0 ?        Z    20:20   0:05 [java] <defunct>
```

**Comment by rarephill** [comment]
FWIW for anyone else bumping into this, I had do change the device name for the generated QR code before it would work. QR codes generated for 'signal-api' were just resulting in silent failure

The docs say to do
`http://localhost:8080/v1/qrcodelink?device_name=signal-api`

Instead I did
'http://localhost:8080/v1/qrcodelink?device_name=mysignalbot'
