### ISSUE TITLE
/v1/accounts - 404 not found

### ISSUE THREAD

**Issue by starcheek** [bbernhard/signal-cli-rest-api#460]
### The problem

Hi,

I am able to register, verify, send message, but checking registered accounts throws 404.

```
$ curl -X 'GET'   'http://127.0.0.1:8080/v1/accounts'   -H 'accept: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    18  100    18    0     0   2763      0 --:--:-- --:--:-- --:--:--  3000404 page not found
```

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by starcheek** [comment]
Is there reason why path is missing `/` at the start?

```go
accounts := v1.Group("accounts")
		{
			accounts.GET("", api.GetAccounts)
		}

```

**Comment by bbernhard** [comment]
Please enable the debug mode (https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and post the obfuscated output here.
