### ISSUE TITLE
HoAss Addon: Can only connect from remote

### ISSUE THREAD

**Issue by bobbolous** [bbernhard/signal-cli-rest-api#463]
### The problem

For me the rest-api does only work with an IP from the outside. The local IP or localhost as suggested in the examples do not work. So right now the API is exposed to everyone in my local network, instead of restricted to the local machine.
The following works:
`curl -X GET -H "Content-Type: application/json" '192.168.0.123:8080/v1/groups/<number>'`

The following returns `curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server`:
`curl -X GET -H "Content-Type: application/json" '127.0.0.1:8080/v1/groups/<number>'`
`curl -X GET -H "Content-Type: application/json" 'localhost:8080/v1/groups/<number>'`

Is this expected behaviour?
Any chance I can change this behaviour to expose the API only on the local machine?

I am running HoAss on a Raspberry Pi.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
That sounds like a issue in your network/with your docker configuration. There is unfortunately not much I can do here.
