### ISSUE TITLE
Start a call

### ISSUE THREAD

**Issue by Sn0wAlice** [bbernhard/signal-cli-rest-api#465]
### Feature Request

Hello 👋

My feature request can be a little bit crazy, but can be useful: Start a call on signal.

Like this, bots will be able to: 
- Reception voice raw data that can be interpreted in the backend.
- Send raw voice recorded audio to the user.

I don't know how can I be more specific with this feature request.

Let me know if I am a little bit TOOOO crazy or not xD

**Comment by bbernhard** [comment]
This project is just a small wrapper around https://github.com/AsamK/signal-cli/ - which does all the heavy lifting. So in order to make your suggestion work, the functionality first needs to be added to signal-cli. I just checked the docs and couldn't find any support for voice calls.

**Comment by robin-thoni** [comment]
> couldn't find any support for voice calls.

Well, now there is: https://github.com/AsamK/signal-cli/releases/tag/v0.14.2

```
$ signal-cli --help
[...]
    acceptCall           Accept an incoming voice call.
    hangupCall           Hang up an active voice call.
    listCalls            List active voice calls.
    rejectCall           Reject an incoming voice call.
    startCall            Start an outgoing voice call.
```

But still, I'm not sure how this would work in this API :/
