### ISSUE TITLE
/v1/contacts and /v1/contacts{number}/sync don't seem to work

### ISSUE THREAD

**Issue by mjw3428** [bbernhard/signal-cli-rest-api#466]
### The problem

I am running the latest 0.80 version and cannot seem to get the api endpoints for /v1/contacts and /v1/contacts{number}/sync to work. I just get an error 404 returned everytime. 

Would you be able to provide some sample curl commands and confirm if these endpoints do in fact work in the latest version?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Please enable the [debug](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) mode and post the obfuscated(!) output here.

**Comment by mattw-hatake** [comment]
I have enabled debug mode. There doesn't appear to be any additional information provided in the logs

The commands run were:

curl -X 'PUT'   'http://localhost:8090/v1/contacts%2B<number removed>'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
  "expiration_in_seconds": 0,
  "name": "matt",
  "recipient": "<number removed>"
}'

The response was: 404 page not found and the logs just show: 

[GIN] 2024/01/08 - 17:18:59 | 404 |       2.482µs |   192.168.122.1 | PUT      "/v1/contacts+<number removed>"

For the sync request the command was:

curl -X 'POST'   'http://localhost:8090/v1/contacts%2B<number removed>/sync'   -H 'accept: application/json'   -d ''

The response is: 404 page not found

Within the logs you get:

[GIN] 2024/01/08 - 17:25:43 | 404 |         641ns |   192.168.122.1 | POST     "/v1/contacts+<number removed>/sync"

I have confirmed with a get requrst that debug logging is on. There just dosn't seem to be much to go on in there.

**Comment by mjw3428** [comment]
I've confirmed that debug mode is on and run the two queries:

curl -X 'PUT'   'http://localhost:8090/v1/contacts%2B<number removed>'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '{
  "expiration_in_seconds": 0,
  "name": "<name removed>",
  "recipient": "<number removed>"
}'

You get '404 page not found' as the response and

 [GIN] 2024/01/08 - 17:33:43 | 404 |         644ns |   192.168.122.1 | PUT      "/v1/contacts+<number removed>"

in the logs. 

For the sync, when I run:

curl -X 'POST'   'http://localhost:8090/v1/contacts%2B<number removed>/sync'   -H 'accept: application/json'   -d ''

Again, I am just getting a '404 page not found' and in the logs:

[GIN] 2024/01/08 - 17:36:35 | 404 |         673ns |   192.168.122.1 | POST     "/v1/contacts+<number removed>/sync

There doesn't seem to be much to go on.

**Comment by bbernhard** [comment]
Oh, there was an issue in the swagger documentation. The URL for the PUT request is: `/v1/contacts/{number}`  and the URL for the sync endpoint is: `/v1/contacts/{number}/sync`

**Comment by mjw3428** [comment]
Yep that was it. Thanks for your fast response. It is all working now.
