### ISSUE TITLE
Cant' registered a new Phonenumber...

### ISSUE THREAD

**Issue by AndiRued** [bbernhard/signal-cli-rest-api#469]
### The problem

 Hello, I can add Homeassistant as another device with the Signal addon, that works. But if I want to use a new phone number exclusively to use Signal from Homeassistant, I get as far as the captcha. But how do I enter the CaptchaCode in Homeassistant (via the terminal) and how do I proceed to make it work?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
You need to add the captcha to the REST API call that is requiring the captcha. See https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md#trouble-shooting-a-captcha-is-required

**Comment by AndiRued** [comment]
> You need to add the captcha to the REST API call that is requiring the captcha. See https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md#trouble-shooting-a-captcha-is-required

Hi Bernhard. Thank you. It dosn't work. I do it right now but i see a error Message like this in the terminal: 'Couldn't process request - invalid request'

How long ist the captha from signal? I see a lot of numbers and a text like this: signalcaptcha://signal-hcaptcha....

**Comment by bbernhard** [comment]
> > You need to add the captcha to the REST API call that is requiring the captcha. See https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md#trouble-shooting-a-captcha-is-required
> 
> Hi Bernhard. Thank you. It dosn't work. I do it right now but i see a error Message like this in the terminal: 'Couldn't process request - invalid request'
> 
> How long ist the captha from signal? I see a lot of numbers and a text like this: signalcaptcha://signal-hcaptcha....

The captcha is quite long. Please post the REST API request here (make sure to obfuscate your number when doing so). Please also make a screenshot of the captcha from the developer console. It looks like that your REST API request is somehow ill formatted.

**Comment by AndiRued** [comment]
> > > You need to add the captcha to the REST API call that is requiring the captcha. See https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md#trouble-shooting-a-captcha-is-required
> > 
> > 
> > Hi Bernhard. Thank you. It dosn't work. I do it right now but i see a error Message like this in the terminal: 'Couldn't process request - invalid request'
> > How long ist the captha from signal? I see a lot of numbers and a text like this: signalcaptcha://signal-hcaptcha....
> 
> The captcha is quite long. Please post the REST API request here (make sure to obfuscate your number when doing so). Please also make a screenshot of the captcha from the developer console. It looks like that your REST API request is somehow ill formatted.

OK, i try it in this way:

curl -X POST -H "Content-Type: application/json" -- data '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQSuIB9zeQJ11A5T1-YxXeVp8b14EWlEmt5nDMHQmskwBotnvqN16ajVfVJJ64DmNDbrK75QhtUhdkrQsaEtLmNuF4Kj-5pMhriasjtaoRXGaEvMSbA3YXE8i0G5YFPP6pLVcoLEf1F7FcwyGc_guZgww-PxoWKQjG9V-kPZCkNRzmGyd8F9QdQgCovKsd3BWdUob8o-fWztmft4Y_1McBH52m_sOt90zDrxLULfu9CVsXlzQSKTCiL2PWDdaMwyMl2OQVNAxoE3LOGaEdSksaTSDSIf9taYrl0OHduB7ox5cAiF8vLtBg4o6q6fTpl3jyo7_UXeZ9-ecOrnFKDljJUp6pphY5KrRsXCy6vcWcEu33kNH18JykTweg04A-2qXYvD8Y_geoQ0EUqmumEbcx77Y6xxEXG-5BQvh6LkZuAWgtufiIHxnHKey_fKjhmSGiHgw0uXz9aOjaCW93hwvdHFwyvMrAUzx9pezVOw8IJNUkNLVSVLbMFRsktS_0bcfV95Ds-VDqMkjM1sT7Vv2nQcKH8S2VfQt3GtERbqyE8RUzDk9rZ6Uacgz_sxMLre7cyGrP7l31Tw400pZ2DXkqPOiTWA3f7TpLYjuqux-G0whXTSNj72nIMG6n5iiRyoUNqsxHKs8WR7_KgYvK5CxedQr2-CzyIh7TAzp-quJSKeu7PjSi063puOxcQtBylvRh6Aw9_s5_wTb7cAGnVWMlfCcGZ1PP9AC-3TkK85lGKiQNlh7m9iIQMtYYD1QyVhLZd_Kiz320M9INsmPo-KQT_tNUrIQ1ka0NaHdJq0OLRlZhF8sx7EiLHPPWT39EW-c_C09LHFnZ9I1bdgQht38xFSsfP7iWTceiBudx9s74m4QC9vNJDt1ea3inPv9bsCzioRxdkKD1VTgH-zcVOXo__c5BbzIlEhA8ACWwPeNiba23mjr8GINUaJUCDeYnaYvlyZvSiF3AARXF1Hc7dWqyeB1AAmiJd83ZzSvIFluomtt88ETLhFIVq50R2rwr8gQA7pKw5DCxfndgjE4UCMDbmPIekkznfj86Xh1e9B2wQKBTu0lujU5Mhl1oTLzF6TB81mHR4uM5duREBycbezOtz5DM0hHWVVebbQgStYId3bEKG06LmMXZ0-nK7SLT0cb3by8wpna7pN7dJhV-RtAweyM8cozCEy-d5f5NljbrXQdlsjE27imz5_AdUFioIKfZ_4yEPudJdVfIGrlk7wxGfnObIIzZJ4NHxKv2Bi8M4tn0VS4iIXDPv8Q0fWlSHFxVOOZ4OWRX55mb3vxle6MgEQReupjDdaXR3XLg81efCV4b3eV-MDNcGsBEBzwLEphr9n0LTU8NDuc48sXqQJWvR4qRd3DnW-0mo0n0XI0wEthScWqKpHM9ARa-2O2ozz-WrVQHzsYk6RU3Xopi81ydzQ5JM7vFTDezov1IgAWkW7-253kYC8fr-YN0SjWaIuZlr9h8_f8DbPcw5Gs61Bu3pTStFjI_bZH9CzR_6J1lkiosWuicnHL4faAV1RAQtH4sG7wD8iPaAhh2H9bVyDoAtCURu9ulDbrc6WTAZ5qr8RD8O_W0nkfSNSXFJNWBXkPaNleHDOZbgaTKhzaGFyZF9pZM4UPIQfonBkAA.kAvOscU3opvheSa4bnDE9x_DwRQOPzuY3To5icHVUc4", “use_voice“: false}' 'http://127.0.0.1:8080/v1/register/+49xxxxxxxxxx‘

<img width="1336" alt="Bildschirmfoto 2024-01-29 um 22 41 03" src="https://github.com/bbernhard/signal-cli-rest-api/assets/129784508/0f8896a2-0eea-419c-b893-1fe89ee90263">

**Comment by bbernhard** [comment]
Does the above curl command really work for you?

I just tried it out here, and it looks like that you used the `“` character instead of `"` in the `"use_voice"`. And `‘` instead of `'`. 

Here is a cleaned up version:

```
curl -X POST -H "Content-Type: application/json" --data '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQSuIB9zeQJ11A5T1-YxXeVp8b14EWlEmt5nDMHQmskwBotnvqN16ajVfVJJ64DmNDbrK75QhtUhdkrQsaEtLmNuF4Kj-5pMhriasjtaoRXGaEvMSbA3YXE8i0G5YFPP6pLVcoLEf1F7FcwyGc_guZgww-PxoWKQjG9V-kPZCkNRzmGyd8F9QdQgCovKsd3BWdUob8o-fWztmft4Y_1McBH52m_sOt90zDrxLULfu9CVsXlzQSKTCiL2PWDdaMwyMl2OQVNAxoE3LOGaEdSksaTSDSIf9taYrl0OHduB7ox5cAiF8vLtBg4o6q6fTpl3jyo7_UXeZ9-ecOrnFKDljJUp6pphY5KrRsXCy6vcWcEu33kNH18JykTweg04A-2qXYvD8Y_geoQ0EUqmumEbcx77Y6xxEXG-5BQvh6LkZuAWgtufiIHxnHKey_fKjhmSGiHgw0uXz9aOjaCW93hwvdHFwyvMrAUzx9pezVOw8IJNUkNLVSVLbMFRsktS_0bcfV95Ds-VDqMkjM1sT7Vv2nQcKH8S2VfQt3GtERbqyE8RUzDk9rZ6Uacgz_sxMLre7cyGrP7l31Tw400pZ2DXkqPOiTWA3f7TpLYjuqux-G0whXTSNj72nIMG6n5iiRyoUNqsxHKs8WR7_KgYvK5CxedQr2-CzyIh7TAzp-quJSKeu7PjSi063puOxcQtBylvRh6Aw9_s5_wTb7cAGnVWMlfCcGZ1PP9AC-3TkK85lGKiQNlh7m9iIQMtYYD1QyVhLZd_Kiz320M9INsmPo-KQT_tNUrIQ1ka0NaHdJq0OLRlZhF8sx7EiLHPPWT39EW-c_C09LHFnZ9I1bdgQht38xFSsfP7iWTceiBudx9s74m4QC9vNJDt1ea3inPv9bsCzioRxdkKD1VTgH-zcVOXo__c5BbzIlEhA8ACWwPeNiba23mjr8GINUaJUCDeYnaYvlyZvSiF3AARXF1Hc7dWqyeB1AAmiJd83ZzSvIFluomtt88ETLhFIVq50R2rwr8gQA7pKw5DCxfndgjE4UCMDbmPIekkznfj86Xh1e9B2wQKBTu0lujU5Mhl1oTLzF6TB81mHR4uM5duREBycbezOtz5DM0hHWVVebbQgStYId3bEKG06LmMXZ0-nK7SLT0cb3by8wpna7pN7dJhV-RtAweyM8cozCEy-d5f5NljbrXQdlsjE27imz5_AdUFioIKfZ_4yEPudJdVfIGrlk7wxGfnObIIzZJ4NHxKv2Bi8M4tn0VS4iIXDPv8Q0fWlSHFxVOOZ4OWRX55mb3vxle6MgEQReupjDdaXR3XLg81efCV4b3eV-MDNcGsBEBzwLEphr9n0LTU8NDuc48sXqQJWvR4qRd3DnW-0mo0n0XI0wEthScWqKpHM9ARa-2O2ozz-WrVQHzsYk6RU3Xopi81ydzQ5JM7vFTDezov1IgAWkW7-253kYC8fr-YN0SjWaIuZlr9h8_f8DbPcw5Gs61Bu3pTStFjI_bZH9CzR_6J1lkiosWuicnHL4faAV1RAQtH4sG7wD8iPaAhh2H9bVyDoAtCURu9ulDbrc6WTAZ5qr8RD8O_W0nkfSNSXFJNWBXkPaNleHDOZbgaTKhzaGFyZF9pZM4UPIQfonBkAA.kAvOscU3opvheSa4bnDE9x_DwRQOPzuY3To5icHVUc4", "use_voice": false}' 'http://127.0.0.1:8080/v1/register/+49xxxxxxxxxx'
```

**Comment by AndiRued** [comment]
> Does the above curl command really work for you?
> 
> I just tried it out here, and it looks like that you used the `“` character instead of `"` in the `"use_voice"`. And `‘` instead of `'`.
> 
> Here is a cleaned up version:
> 
> ```
> curl -X POST -H "Content-Type: application/json" --data '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQSuIB9zeQJ11A5T1-YxXeVp8b14EWlEmt5nDMHQmskwBotnvqN16ajVfVJJ64DmNDbrK75QhtUhdkrQsaEtLmNuF4Kj-5pMhriasjtaoRXGaEvMSbA3YXE8i0G5YFPP6pLVcoLEf1F7FcwyGc_guZgww-PxoWKQjG9V-kPZCkNRzmGyd8F9QdQgCovKsd3BWdUob8o-fWztmft4Y_1McBH52m_sOt90zDrxLULfu9CVsXlzQSKTCiL2PWDdaMwyMl2OQVNAxoE3LOGaEdSksaTSDSIf9taYrl0OHduB7ox5cAiF8vLtBg4o6q6fTpl3jyo7_UXeZ9-ecOrnFKDljJUp6pphY5KrRsXCy6vcWcEu33kNH18JykTweg04A-2qXYvD8Y_geoQ0EUqmumEbcx77Y6xxEXG-5BQvh6LkZuAWgtufiIHxnHKey_fKjhmSGiHgw0uXz9aOjaCW93hwvdHFwyvMrAUzx9pezVOw8IJNUkNLVSVLbMFRsktS_0bcfV95Ds-VDqMkjM1sT7Vv2nQcKH8S2VfQt3GtERbqyE8RUzDk9rZ6Uacgz_sxMLre7cyGrP7l31Tw400pZ2DXkqPOiTWA3f7TpLYjuqux-G0whXTSNj72nIMG6n5iiRyoUNqsxHKs8WR7_KgYvK5CxedQr2-CzyIh7TAzp-quJSKeu7PjSi063puOxcQtBylvRh6Aw9_s5_wTb7cAGnVWMlfCcGZ1PP9AC-3TkK85lGKiQNlh7m9iIQMtYYD1QyVhLZd_Kiz320M9INsmPo-KQT_tNUrIQ1ka0NaHdJq0OLRlZhF8sx7EiLHPPWT39EW-c_C09LHFnZ9I1bdgQht38xFSsfP7iWTceiBudx9s74m4QC9vNJDt1ea3inPv9bsCzioRxdkKD1VTgH-zcVOXo__c5BbzIlEhA8ACWwPeNiba23mjr8GINUaJUCDeYnaYvlyZvSiF3AARXF1Hc7dWqyeB1AAmiJd83ZzSvIFluomtt88ETLhFIVq50R2rwr8gQA7pKw5DCxfndgjE4UCMDbmPIekkznfj86Xh1e9B2wQKBTu0lujU5Mhl1oTLzF6TB81mHR4uM5duREBycbezOtz5DM0hHWVVebbQgStYId3bEKG06LmMXZ0-nK7SLT0cb3by8wpna7pN7dJhV-RtAweyM8cozCEy-d5f5NljbrXQdlsjE27imz5_AdUFioIKfZ_4yEPudJdVfIGrlk7wxGfnObIIzZJ4NHxKv2Bi8M4tn0VS4iIXDPv8Q0fWlSHFxVOOZ4OWRX55mb3vxle6MgEQReupjDdaXR3XLg81efCV4b3eV-MDNcGsBEBzwLEphr9n0LTU8NDuc48sXqQJWvR4qRd3DnW-0mo0n0XI0wEthScWqKpHM9ARa-2O2ozz-WrVQHzsYk6RU3Xopi81ydzQ5JM7vFTDezov1IgAWkW7-253kYC8fr-YN0SjWaIuZlr9h8_f8DbPcw5Gs61Bu3pTStFjI_bZH9CzR_6J1lkiosWuicnHL4faAV1RAQtH4sG7wD8iPaAhh2H9bVyDoAtCURu9ulDbrc6WTAZ5qr8RD8O_W0nkfSNSXFJNWBXkPaNleHDOZbgaTKhzaGFyZF9pZM4UPIQfonBkAA.kAvOscU3opvheSa4bnDE9x_DwRQOPzuY3To5icHVUc4", "use_voice": false}' 'http://127.0.0.1:8080/v1/register/+49xxxxxxxxxx'
> ```

In this way as you explained it works. the error was between --- and data (no space are right)
Thanks a lot. Danke Dir :-)
Andreas

**Comment by bbernhard** [comment]
> > Does the above curl command really work for you?
> > I just tried it out here, and it looks like that you used the `“` character instead of `"` in the `"use_voice"`. And `‘` instead of `'`.
> > Here is a cleaned up version:
> > ```
> > curl -X POST -H "Content-Type: application/json" --data '{"captcha":"signal-hcaptcha.5fad97ac-7d06-4e44-b18a-b950b20148ff.registration.P1_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.hKdwYXNza2V5xQSuIB9zeQJ11A5T1-YxXeVp8b14EWlEmt5nDMHQmskwBotnvqN16ajVfVJJ64DmNDbrK75QhtUhdkrQsaEtLmNuF4Kj-5pMhriasjtaoRXGaEvMSbA3YXE8i0G5YFPP6pLVcoLEf1F7FcwyGc_guZgww-PxoWKQjG9V-kPZCkNRzmGyd8F9QdQgCovKsd3BWdUob8o-fWztmft4Y_1McBH52m_sOt90zDrxLULfu9CVsXlzQSKTCiL2PWDdaMwyMl2OQVNAxoE3LOGaEdSksaTSDSIf9taYrl0OHduB7ox5cAiF8vLtBg4o6q6fTpl3jyo7_UXeZ9-ecOrnFKDljJUp6pphY5KrRsXCy6vcWcEu33kNH18JykTweg04A-2qXYvD8Y_geoQ0EUqmumEbcx77Y6xxEXG-5BQvh6LkZuAWgtufiIHxnHKey_fKjhmSGiHgw0uXz9aOjaCW93hwvdHFwyvMrAUzx9pezVOw8IJNUkNLVSVLbMFRsktS_0bcfV95Ds-VDqMkjM1sT7Vv2nQcKH8S2VfQt3GtERbqyE8RUzDk9rZ6Uacgz_sxMLre7cyGrP7l31Tw400pZ2DXkqPOiTWA3f7TpLYjuqux-G0whXTSNj72nIMG6n5iiRyoUNqsxHKs8WR7_KgYvK5CxedQr2-CzyIh7TAzp-quJSKeu7PjSi063puOxcQtBylvRh6Aw9_s5_wTb7cAGnVWMlfCcGZ1PP9AC-3TkK85lGKiQNlh7m9iIQMtYYD1QyVhLZd_Kiz320M9INsmPo-KQT_tNUrIQ1ka0NaHdJq0OLRlZhF8sx7EiLHPPWT39EW-c_C09LHFnZ9I1bdgQht38xFSsfP7iWTceiBudx9s74m4QC9vNJDt1ea3inPv9bsCzioRxdkKD1VTgH-zcVOXo__c5BbzIlEhA8ACWwPeNiba23mjr8GINUaJUCDeYnaYvlyZvSiF3AARXF1Hc7dWqyeB1AAmiJd83ZzSvIFluomtt88ETLhFIVq50R2rwr8gQA7pKw5DCxfndgjE4UCMDbmPIekkznfj86Xh1e9B2wQKBTu0lujU5Mhl1oTLzF6TB81mHR4uM5duREBycbezOtz5DM0hHWVVebbQgStYId3bEKG06LmMXZ0-nK7SLT0cb3by8wpna7pN7dJhV-RtAweyM8cozCEy-d5f5NljbrXQdlsjE27imz5_AdUFioIKfZ_4yEPudJdVfIGrlk7wxGfnObIIzZJ4NHxKv2Bi8M4tn0VS4iIXDPv8Q0fWlSHFxVOOZ4OWRX55mb3vxle6MgEQReupjDdaXR3XLg81efCV4b3eV-MDNcGsBEBzwLEphr9n0LTU8NDuc48sXqQJWvR4qRd3DnW-0mo0n0XI0wEthScWqKpHM9ARa-2O2ozz-WrVQHzsYk6RU3Xopi81ydzQ5JM7vFTDezov1IgAWkW7-253kYC8fr-YN0SjWaIuZlr9h8_f8DbPcw5Gs61Bu3pTStFjI_bZH9CzR_6J1lkiosWuicnHL4faAV1RAQtH4sG7wD8iPaAhh2H9bVyDoAtCURu9ulDbrc6WTAZ5qr8RD8O_W0nkfSNSXFJNWBXkPaNleHDOZbgaTKhzaGFyZF9pZM4UPIQfonBkAA.kAvOscU3opvheSa4bnDE9x_DwRQOPzuY3To5icHVUc4", "use_voice": false}' 'http://127.0.0.1:8080/v1/register/+49xxxxxxxxxx'
> > ```
> 
> In this way as you explained it works. the error was between --- and data (no space are right) Thanks a lot. Danke Dir :-) Andreas

Das freut mich, gerne!
