### ISSUE TITLE
Is there an API call that can tell me which version is running?

### ISSUE THREAD

**Issue by redwoodtree** [bbernhard/signal-cli-rest-api#47]
I'm running the latest tag but without comparing dates it can get confusing to know which version I've pulled down and am running. I was thinking an API call could give me that info (which version of the docker container and maybe which version of the Signal CLI as well)? Maybe there's another way to get the info?

**Comment by bbernhard** [comment]
Unfortunately there's no possibility yet to query that information. Up to now, there's only the `/about` endpoint which returns some (internal) meta information. I guess it could make sense to add the version number and the signal-cli version there as well.

**Comment by redwoodtree** [comment]
Thanks for the speedy reply. I can submit a pull request if it seems worthwhile.

**Comment by bbernhard** [comment]
That would be very much appreciated! 

The signal-cli version is already set as `ARG` in the [Dockerfile](https://github.com/bbernhard/signal-cli-rest-api/blob/master/Dockerfile#L3). So I think the easiest would probably be to set an ENV variable inside the docker container to this value. And then expose that via the `/about` endpoint. 

For the build version I think it's probably a bit more complicated. At the moment I am using [this](https://github.com/bbernhard/signal-cli-rest-api/blob/master/publish.sh) script here to publish a new release. e.g: `./publish.sh -v 0.30 -t stable` would build + upload the version `0.30` to dockerhub. Ideally we can find a way to somehow pass this version inside the docker container.

**Comment by bbernhard** [comment]
With the next release it's possible to query the version with `curl -X GET http://127.0.0.1:8080/v1/about`
