### ISSUE TITLE
Doesn't return groups when I send a request /v1/groups/{number}

### ISSUE THREAD

**Issue by dxbit** [bbernhard/signal-cli-rest-api#471]
### The problem

Why are groups created via phone not returned by the server? Those created by the POST request are returned: /v1/groups/{number}.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Do you call the `receive` endpoint before calling the `groups` endpoint?

**Comment by dxbit** [comment]
No. I don't call `receive.`

**Comment by bbernhard** [comment]
Then please do it

**Comment by dxbit** [comment]
Thank you.

**Comment by Reasel** [comment]
I am also having issues. You mention calling `receive` before calling `groups` I have received many messages but I am still not seeing and response from the groups calls.

I was able to see messages in specific groups with specific `groupId` listed but making a request to get info on that group using the /groups/{number}/{groupId} just tells me `{"error":"No group with that id found"}`
