### ISSUE TITLE
JAVA_OPTS are ignored when using json-rpc mode

### ISSUE THREAD

**Issue by kleptog** [bbernhard/signal-cli-rest-api#473]
### The problem

To get the signal-cli to work behind a proxy you can using the JAVA_OPTS environment variable to configure them like so:
```
JAVA_OPTS=-Dhttp.proxyHost=proxy.server -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.server -Dhttps.proxyPort=3128
```
However, this fails in json-rpc mode. (It also fails in native mode but I don't know how to fix that.)

It happens because in java-rpc mode signal-cli is run under supervisor as a service, which clears the environment.

The fix is to copy the variable through. Will post patch shortly.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by funxiun** [comment]
Hi

I ran into the same problem but with another issue.
Maybe this will work for you too:  #https://github.com/bbernhard/signal-cli-rest-api/issues/231#issuecomment-1908386800

**Comment by kleptog** [comment]
> I ran into the same problem but with another issue. Maybe this will work for you too: [#231 (comment)](https://github.com/bbernhard/signal-cli-rest-api/issues/231#issuecomment-1908386800)

Yes, switching the MODE=normal will work too, but is stupidly slow. This little patch makes it usable for us in production, so I figured I'd submit it here for other people.
