### ISSUE TITLE
signal-cli version is too old for the Signal-Server, please update.

### ISSUE THREAD

**Issue by k-bx** [bbernhard/signal-cli-rest-api#475]
### The problem

About 30 mins ago I started getting this error on multiple instances:

```
signal-cli version is too old for the Signal-Server, please update.
```

Docker image is latest (`sha256:f2708ded8a2adebf76ce9c217a791b2c824bd25789fb39f48956b47cc059bda3`) and signal-cli is 0.12.7

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
There already exists a upstream issue: https://github.com/AsamK/signal-cli/issues/1439

**Comment by k-bx** [comment]
@bbernhard apologies for pinging you on this, quite an important subsystem is dependant on the engine.

Is it possible to build against the `master` version of signal-cli? If yes, can you help with it? (Trying myself meanwhile)

Thank you!

**Comment by deoxykev** [comment]
Me too, does anyone have a fix for this yet?

**Comment by richtier** [comment]
> There already exists a upstream issue: [AsamK/signal-cli#1439](https://github.com/AsamK/signal-cli/issues/1439)

is it not controllable via 

https://github.com/bbernhard/signal-cli-rest-api/blob/master/Dockerfile#L3
```yml
ARG SIGNAL_CLI_NATIVE_PACKAGE_VERSION=0.12.7+3
```

**Comment by richtier** [comment]
oh lord I spent 5 hours debugging haha

**Comment by richtier** [comment]
I've am trying this workaround:

cloned `signal-cli-rest-api/` then edited Dockerfile thusly to pointing it at [this absolute King's](https://github.com/AsamK/signal-cli/issues/1439#issuecomment-1927924917) fork

```diff
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-ARG SIGNAL_CLI_VERSION=0.12.7
+ARG SIGNAL_CLI_VERSION=0.12.7_patch2
 ARG LIBSIGNAL_CLIENT_VERSION=0.36.1
 ARG SIGNAL_CLI_NATIVE_PACKAGE_VERSION=0.12.7+3
 
@@ -54,7 +54,7 @@ RUN cd /tmp/ \
        && rm -r /tmp/swag-${SWAG_VERSION}
 
 RUN cd /tmp/ \
-       && wget -nv https://github.com/AsamK/signal-cli/releases/download/v${SIGNAL_CLI_VERSION}/signal-cli-${SIGNAL_CLI_VERSION}.tar.gz -O /tmp/signal-cli.tar.gz \
+       && wget -nv https://github.com/key-lime-box/signal-cli/releases/download/v${SIGNAL_CLI_VERSION}/signal-cli-${SIGNAL_CLI_VERSION}.tar.gz -O /tmp/signal-cli.tar.gz \
        && tar xf signal-cli.tar.gz
 
 # build native image with graalvm
@@ -69,7 +69,7 @@ RUN arch="$(uname -m)"; \
 
 RUN if [ "$(uname -m)" = "x86_64" ]; then \
                cd /tmp \
-               && git clone https://github.com/AsamK/signal-cli.git signal-cli-${SIGNAL_CLI_VERSION}-source \
+               && git clone https://github.com/key-lime-box/signal-cli.git signal-cli-${SIGNAL_CLI_VERSION}-source \

```

will report back if that works

**Comment by k-bx** [comment]
What I did was to just compile this via `go build` and launch manually on server with native build provided in the linked thread. Put it under `/usr/bin/signal-cli-native`. Run as (put your dirs):

```
MODE=native sudo /usr/bin/signal-cli-rest-api -signal-cli-config /home/ubuntu/storage/signal-cli/ -attachment-tmp-dir /home/ubuntu/storage/signal-cli/attachments/
```

**Comment by richtier** [comment]
Fixed https://github.com/bbernhard/signal-cli-rest-api/pull/477

it works!

**Comment by MStrecke** [comment]
Thank you for the fast resolution
