### ISSUE TITLE
Update needed from v0.12.7 to v0.12.8

### ISSUE THREAD

**Issue by Lurikbolding** [bbernhard/signal-cli-rest-api#480]
### The problem

Hello

With the version 0.12.7, we got the error "signal-cli version is too old for the Signal-Server, please update.".

This issue has just been fix with the version 0.12.8.

Is it possible to update the docker image ton include this new version?

Thank you

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

the release is here : https://github.com/AsamK/signal-cli/releases/tag/v0.12.8

**Comment by Lurikbolding** [comment]
Same issue  : https://github.com/bbernhard/signal-cli-rest-api/issues/475

**Comment by Lurikbolding** [comment]
close duplicate issue

**Comment by richtier** [comment]
this has been done 

https://github.com/bbernhard/signal-cli-rest-api/pull/477

use tag [0.81](https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.81)

**Comment by Lurikbolding** [comment]
Update successful, 
thank you for the job.
