### ISSUE TITLE
Healthcheck should not return 204 when signal-cli fails

### ISSUE THREAD

**Issue by bwirt** [bbernhard/signal-cli-rest-api#481]
### The problem

In my system I didn't notice I was affected by #475 for days because my monitor didn't catch it.  /v1/health was still reporting 204 when the underlying cli was not working.

### Are you using the latest released version?

- [x] Yes

### Have you read the troubleshooting page?

- [x] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
I think that is not really doable - at least not in normal mode. In normal mode, the signal-cli java app (which talks to the Signal Server) is only called when there is any activity via REST. So, what you can do, is periodically call the `receive` endpoint as a poor man's healthcheck.
