### ISSUE TITLE
why do I get this when trying to do the qr code things with my phone

### ISSUE THREAD

**Issue by cthompstone** [bbernhard/signal-cli-rest-api#484]
### The problem

Couldn't create QR code: Link request error: Connection closed!

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Please enable the debug mode (https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md) and post the obfuscated output here.

**Comment by cthompstone** [comment]
Thanks, I actually deleted the docker and cleaned up.  Re-installed completely and it's all good, so will see what happens

**Comment by kSzajo** [comment]
I'm having the same issue, enabled debug mode but there are no extra logs 

```
signal-signal-1  | time="2024-02-17T17:53:49Z" level=debug msg="full command: {\"jsonrpc\":\"2.0\",\"method\":\"startLink\",\"id\":\"db7e0040-3123-4925-b866-c2cb56ab3f2d\",\"params\":{}}"
signal-signal-1  | [GIN] 2024/02/17 - 17:53:50 | 400 |  450.922184ms |    10.10.10.230 | GET      "/v1/qrcodelink?device_name=signal-omicron"
```

I recreated docker but it did not help

**Comment by kSzajo** [comment]
forgot to use `docker compose pull` to ensure that latest image is actually fetched
