### ISSUE TITLE
Handle message edit

### ISSUE THREAD

**Issue by D0han** [bbernhard/signal-cli-rest-api#485]
### Feature Request

It would be awesome to have support for message editing, seems that [signal-cli](https://github.com/AsamK/signal-cli/) have this since [[0.11.10] 2023-05-11](https://github.com/AsamK/signal-cli/blob/e78146eb67da3e011028c9df6a23df114306ec1b/CHANGELOG.md?plain=1#L153) with `--edit-timestamp`.

I already have use case for it (that's why i was searching trough API how to do that, sadly no joy):  
My automation has a need for asynchronous message handling, i want to send first message with audio as soon as possible, and then update it adding text with more info after a while.

**Comment by bbernhard** [comment]
will be in the next release
