### ISSUE TITLE
New major release v0.13.0 of the signal-cli tool with critical bugfixes

### ISSUE THREAD

**Issue by goshi** [bbernhard/signal-cli-rest-api#486]
### The problem

Hi!
Sebastian Scheibner has released the new [major release](https://github.com/AsamK/signal-cli/milestone/27) with some [critical fixes](https://github.com/AsamK/signal-cli/issues/1450#issuecomment-1951434367).
Please, implement it to your containers.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
There is a pre-release available. If you want to give it a try, use this docker image tag: `bbernhard/signal-cli-rest-api:0.142-dev`
