### ISSUE TITLE
Sending message to Group not working

### ISSUE THREAD

**Issue by bijuabraham** [bbernhard/signal-cli-rest-api#49]
I was able to install, register a phone, create a group and test it through curl and Home Assistant.
Everything works well when i send it to a phone number or list of numbers.
But sending it to a group is giving the following error.
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}%

Here's the output from the group listing
`
MacBook-Pro ~ % curl -X GET -H "Content-Type: application/json" 'http://homeassistant.local:8080/v1/groups/+14087824585'
[{"name":"Home Alerts","id":"group.ZkFERWhRTDMxV01wbm53ZDRhaG1Sdz09","internal_id":"fADEhQL31WMpnnwd4ahmRw==","members":["+14082421927","+14087824585"],"active":true,"blocked":false}]%                                                                                                                      MacBook-Pro ~ % 
'

Then I am not sure what exactly is the ID that I should pass in for the group, but I tried all 3 options
'
MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+14087824585", "recipients": ["group.ZkFERWhRTDMxV01wbm53ZDRhaG1Sdz08"]}' 'http://homeassistant.local:8080/v1/send'
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}%                               MacBook-Pro ~ % 
'
I also tried passing in ZkFERWhRTDMxV01wbm53ZDRhaG1Sdz08 as well as the internal ID. But all give the same error.

On the phone, I can see that the group is created as a "Legacy Group"

Any help appreciated.

**Comment by bijuabraham** [comment]
I just created a new group and tried again with no luck. Full sequence of instructions.. Can you find any issue in the below that I am overlooking ?
`
MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"name": "Home Alerts", "members": ["+1510946AAAA", "+1408242BBBB"]}' 'http://homeassistant.local:8080/v1/groups/+1408782XXXX'
{"id":"group.Q25yWDlVQll4NlF4YmVnSWlQMUJodz09"}%

MacBook-Pro ~ % curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+1408782XXXX", "recipients": ["group.Q25yWDlVQll4NlF4YmVnSWlQMUJodz09"]}' 'http://homeassistant.local:8080/v1/send'
{"error":"Failed to send message: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found\n"}% MacBook-Pro ~ %

I have only obfuscated the phone numbers above.

**Comment by bbernhard** [comment]
Please try to use `http://homeassistant.local:8080/v2/send` instead of `http://homeassistant.local:8080/v1/send`. The former one is deprecated (and limited in function). 

Regarding the legacy group: In signal-cli version [0.7.0](https://github.com/AsamK/signal-cli/releases/tag/v0.7.0) there's now support for the new groups. Unfortunately signal-cli-rest-api still uses the latest 0.6.x version..but this will hopefully change in the next days.

**Comment by CorruptOffset** [comment]
Hi,
firstly -> thanks for your support and easy to use dockerimage.

tried to send to a group with todays source without any luck. 
 curl -X POST -H "Content-Type: application/json" -d '{"message": "HELLO FROM AUTOMATED JAMES" , "number": "SENDER", "recipients": ["group.id"]}' 'http://192.168.178.36:1313/v2/send

Using this code to message one  number direclty works like a charm.

**Comment by bbernhard** [comment]
> Hi,
> firstly -> thanks for your support and easy to use dockerimage.
> 
> tried to send to a group with todays source without any luck.
> curl -X POST -H "Content-Type: application/json" -d '{"message": "HELLO FROM AUTOMATED JAMES" , "number": "SENDER", "recipients": ["group.id"]}' 'http://192.168.178.36:1313/v2/send
> 
> Using this code to message one number direclty works like a charm.

I think that might be related to an outdated signal-cli version. See this thread here for details: https://github.com/bbernhard/signal-cli-rest-api/issues/54

**Comment by bbernhard** [comment]
Should now be fixed with the latest image. See https://github.com/bbernhard/signal-cli-rest-api/issues/54 for details
