### ISSUE TITLE
Registration does not work for me

### ISSUE THREAD

**Issue by skynan22** [bbernhard/signal-cli-rest-api#497]
### The problem

I tried both alternatives for setting up signal-cli, as HA Add on and as docker container, and both do not work for me actually.
After setting up HA add-on and running the add-on everything look fine, see log lines below:

+ set -e
+ [ -z /config ]
+ usermod -u 1000 signal-api
usermod: no changes
+ groupmod -g 1000 signal-api
+ chown 1000:1000 -R /config
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ [ native = json-rpc ]
+ hostname -I
+ awk {print $1}
+ export HOST_IP=172.30.33.5
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/config

Next step is to register or rink my signal number, an already existing one, opening this page:
http://homeassistant:8090/v1/qrcodelink?device_name=signal-api

Port is 8090 because 8080 was already in use! QR code shows up in browser, but after scanning the QR code within signal app (iOS), to add an additional device, nothing happens. The following GET - request is incoming on the server (look ok for me):

time="2024-03-01T20:11:09+01:00" level=info msg="Started Signal Messenger REST API"
[GIN] 2024/03/01 - 20:11:55 | 200 |  706.858936ms |    192.168.2.83 | GET      "/v1/qrcodelink?device_name=signal-api"

When I try to create the QR code via curl cmd and save the QR code as an image - the same issue occurs.
I tried to add my signal app on a Mac mini as additional device, worked for me. I was asked for a name and voila I see the messages on. both iOS & macOS. 

How can I solve that issue and how can I set up a log level that tells me more about what is going wrong when trying to add HA add-on as additional device? 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by JonathanSaudhof** [comment]
Same for me

**Comment by bbernhard** [comment]
Please try this version here: `bbernhard/signal-cli-rest-api:0.145-dev`. Please also make sure to remove the signal-cli config folder from your filesystem before you attempt to register again with the new version.

**Comment by skynan22** [comment]
> Please try this version here: `bbernhard/signal-cli-rest-api:0.145-dev`. Please also make sure to remove the signal-cli config folder from your filesystem before you attempt to register again with the new version.

Thanks for the reply but it is still the same for me:
I deleted previous container & stack with signal-cli  in portainer and set it up from scratch via the following editor lines:

```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:0.145-dev
    environment:
      - MODE=json-rpc #supported modes: json-rpc, native, normal. json-prc is recommended for speed
    ports:
      - "8080:8080" # map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal_cli" # map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
```

After successfully starting all over and opening the qr - code site (http://192.168.2.40:8080/v1/qrcodelink?device_name=signal-api) + scanning the QR code from within Signal App (for adding additional device) just a flickering appears in the Signal App and the following log output has been written in container log:


```
+ set -e
+ [ -z /home/.local/share/signal-cli ]
+ usermod -u 1000 signal-api
usermod: no changes
+ groupmod -g 1000 signal-api
+ chown 1000:1000 -R /home/.local/share/signal-cli
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ [ json-rpc = json-rpc ]
+ /usr/bin/jsonrpc2-helper
time="2024-03-07T14:10:47Z" level=info msg="Updated jsonrpc2.yml"

]
+ service supervisor start
Starting supervisor: supervisord.
+ supervisorctl start all
+ awk {print $1}
+ hostname -I
+ export HOST_IP=172.20.0.2
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/home/.local/share/signal-cli
time="2024-03-07T14:10:48Z" level=info msg="Started Signal Messenger REST API"
[GIN] 2024/03/07 - 14:11:50 | 404 |         568ns |    192.168.2.83 | GET      "/"
[GIN] 2024/03/07 - 14:11:50 | 404 |         324ns |    192.168.2.83 | GET      "/favicon.ico"
[GIN] 2024/03/07 - 14:12:15 | 200 |  673.134455ms |    192.168.2.83 | GET      "/v1/qrcodelink?device_name=signal-api"
```

Thats it. What can I do now? Container IPv4  is 172.20.0.2 within, host has 192.168.2.40, port 8080 from signal-cli is being forwarded ...

**Comment by skynan22** [comment]
As it works for me, I close the issue.

**Comment by jrdwiz** [comment]
FYI - I was having the same issue and this also corrected it for me.
