### ISSUE TITLE
Home Assistant signal_messenger integration improvement

### ISSUE THREAD

**Issue by nagyrobi** [bbernhard/signal-cli-rest-api#5]
bbernhard, do you think it's possible to implement the following in Home Assistant's signal_messenger integration?
- specify attachment as an URL to a picture
- specify multiple attachments per message

Reasons:
- security cameras often natively offer a direct access to a snapsot on a simple http URL, no need to download the picture to the filesystem first and attach from there (it's possible in the Telegram integration btw)
- one would like to send a series of images from multiple cameras in a single notification event - could it be supported as a single message?

**Comment by bbernhard** [comment]
Multiple Attachments are now working for a while. Attachment as an URL will be implemented with this PR: https://github.com/home-assistant/core/pull/62311

So I guess we can close that issue now :)
