### ISSUE TITLE
API to check if number exist on signal???

### ISSUE THREAD

**Issue by rupali-mishra** [bbernhard/signal-cli-rest-api#50]
Can anyone help me to check if there is any API to just check if the phone number exist on signal or not????

**Comment by bbernhard** [comment]
What do you exactly mean by that?

**Comment by rupali-mishra** [comment]
I need an API of Signal app which can show that which numbers of my contact list exist on it. Basically I just want to check if the uploaded number has existing signal account or not. it will be helpful while handling multiple contacts.

**Comment by Atomic-Bean** [comment]
Not sure about this rest api, but I can confirm signal-cli itself does have a command to check if a bunch of numbers are registered on Signal Servers or not.

**Comment by bbernhard** [comment]
@Atomic-Bean thanks for the info! Well, in that case I'll close the ticket for now. If that feature is implemented upstream we can also expose that via REST API :)

**Comment by Atomic-Bean** [comment]
np. Also I forgot to say, the signal-cli command is called `getUserStatus`

**Comment by bbernhard** [comment]
> np. Also I forgot to say, the signal-cli command is called `getUserStatus`

oh sorry, I accidentally misread your comment. I thought you were saying that it is not implemented in signal-cli. Oops..I'll reopen it again. :) Thanks for the command - I'll have a look!

**Comment by bbernhard** [comment]
will be available with the next release

**Comment by morph027** [comment]
Are you sure about the API model?

You're specifying `numbers` as a list of strings, but the response is just one dictionary. Shouldn't it be a list of dictionaries?

```json
[
  {
    "number": "string",
    "registered": true
  }
]
```

Also, not sure if GET allows to pass a list properly.

**Comment by morph027** [comment]
Also, the answer is 204 - No Content, which does not has a body, only headers.

**Comment by bbernhard** [comment]
You are completely right, there were some errors in the swagger documentation. Should be fixed now. Many thanks!

**Comment by morph027** [comment]
Great! Just stumbled upon it as i were trying to add the endpoint to my pythonic clone in https://gitlab.com/morph027/signal-cli-dbus-rest-api as well ;)
