### ISSUE TITLE
Does api support username?

### ISSUE THREAD

**Issue by kentliuqiao** [bbernhard/signal-cli-rest-api#503]
I want to use my username as a user id when sending message out. I've trie to replace the number field in the v2/send api with my username, but it responded "Specified account does not exist".

Is there any other field in the request that I can use to specify mu username?

**Comment by bbernhard** [comment]
Do you want to send a message to others where you only have the username or do you want to set a username (to hide your phone number)?

**Comment by bbernhard** [comment]
> I want to hide my phone number

This will be in the next release

**Comment by bbernhard** [comment]
There is a pre-release now available. If you want to give it a try, please use the docker image tag: `bbernhard/signal-cli-rest-api:0.154-dev`. A new release should follow soon.
