### ISSUE TITLE
Join goup error

### ISSUE THREAD

**Issue by OwenJobs** [bbernhard/signal-cli-rest-api#505]
### The problem

when I use the API:  https://bbernhard.github.io/v1/groups/{number}/{group_id}/join
like this :  http://localhot:8080/v1/groups/+xxxx/VmVQdUhrVGEvUlYrQUZVays2cytFdXUyVFhYdWFZaXN4VHVWclBSemZnND0=/join
Got the error:
{
    "error": "User is not a member in group: temp (VePuHkTa/RV+AFUk+6s+Euu2TXXuaYisxTuVrPRzfg4=)\n"
}

I read the signal-cli , need the invate-link ，so this API is not working?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
You can only join a group that you've been invited to. So, either create a group via the REST API (then you are automatically a member of this group) or create a group in the Signal App and invite yourself to that group. As soon as there is an invitation pending, you can join the group via the join endpoint.
