### ISSUE TITLE
[Accounts] Cannot update or create a username

### ISSUE THREAD

**Issue by LunarN0v4** [bbernhard/signal-cli-rest-api#509]
### The problem

When trying to update my registered accounts username, the server installed in Docker Desktop 4.28.0 (port 8080 is routed to 4446, this setup does work as I could register my account just fine)  

This is what I do:  
curl -X POST -H "Content-Type: application/json" 'http://localhost:4446/v1/accounts/[REDACTED]/username' -d '{"username":"ausername"}'  

This is how the server responds:  
404 page not found

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Those changes are not released yet. You have to use the dev image tags for that. e.g: `bbernhard/signal-cli-rest-api:0.152-dev`
