### ISSUE TITLE
help on getting started

### ISSUE THREAD

**Issue by mariomare22** [bbernhard/signal-cli-rest-api#51]
Hello,
I have installed the CLI via repository on my home assistant installation.
I already have a signal account on my phone and my macbook is linked as well

I am trying to register the container with the same account but maybe I am doing something wrong?
What are the correct steps for having:
Phone
Laptop
API-Container?

Thanks

M.

**Comment by bbernhard** [comment]
Please have a look here: https://github.com/bbernhard/signal-cli-rest-api/issues/35

**Comment by mariomare22** [comment]
I have read all the issue but still I don't understand how to make the API and my phone work with the same account.
should I remove the configuration i have currently in place and start from scratch?
What if I register the account with my phone, then I link a new device (my hassio) generating a QR code, will they be synced in that case?

Thanks for the answer

**Comment by mariomare22** [comment]
Ok I think I have got them linked now I can see the folder into `/data/`
sending message is working but listing groups it returning [] (I have created a group from the phone)

`curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/groups/<number>'`

Also group creation is not working

`curl -X POST -H "Content-Type: application/json" -d '{"name": "MarioTest", "members": ["+mynumber"]}' 'http://IP:PORT/v1/groups/+mynumber'`

getting this error 
`{"error":"Failed to send message: Unable to parse entity\n"}%`

**Comment by olisei** [comment]
Here to... group creation is not working

**Comment by mariomare22** [comment]
nor getting groups is

**Comment by raskitoma** [comment]
Hi guys, what's the correct route for the swagger documentation?

I tried:
localhost:8080/swagger
localhost:8080/swagger/docs
localhost:8080/docs
localhost:8080/api
localhost:8080/v1/docs
localhost:8080/v1/swagger

with no luck...

Any ideas?

Thanks!

**Comment by bbernhard** [comment]
> Hi guys, what's the correct route for the swagger documentation?
> 
> I tried:
> localhost:8080/swagger
> localhost:8080/swagger/docs
> localhost:8080/docs
> localhost:8080/api
> localhost:8080/v1/docs
> localhost:8080/v1/swagger
> 
> with no luck...
> 
> Any ideas?
> 
> Thanks!

It's `http://127.0.0.1:8080/swagger/index.html` :)
