### ISSUE TITLE
arm64 image complains of missing cpu feature

### ISSUE THREAD

**Issue by jodab** [bbernhard/signal-cli-rest-api#510]
### The problem

Been using signal-cli-rest-api for a long time on an aarch64 vps without any issues but after updating the image today I'm seeing the following:

>"/v1/receive/(redacted number)?ignore_attachments=false&ignore_stories=false&timeout=10"
>time="2024-04-03T04:00:00+03:00" level=error msg="AUTO_RECEIVE_SCHEDULE: Couldn't call receive for number >(redacted number): {The current machine does not support all of the following CPU features that are required by the >image: [FP, ASIMD, AES, PMULL, SHA1, SHA2, CRC32, LSE, DCPOP, SHA3, SHA512, SVE, PACA, SVEBITPERM, SVE2].\nPlease >rebuild the executable with an appropriate setting of the -march option.}"

The CPU in the VPS claims to be an ARM Neoverse-N1 with the following cpu flags: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

arm64

**Comment by ajdelgado** [comment]
Same issue with x86_64 (podman container) in latest, falling back to 0.81 worked.

**Comment by bbernhard** [comment]
> Same issue with x86_64 (podman container) in latest, falling back to 0.81 worked.

Please give `bbernhard/signal-cli-rest-api:0.155-dev` a try. For testing purposes I am now building the native image with `-march=compatibility` which should (according to the GraalVM documentation) result in the best compatibility. Hope that helps (and doesn't have a severe performance impact on other, newer, machines). 

regarding the arm64 image: the arm64 image is kindly provided by @morph027 and his project https://gitlab.com/packaging/signal-cli, so there is not that much I can do here.

**Comment by morph027** [comment]
Thanks for pinging me, created an issue over there and will fix it with a new build soon

https://gitlab.com/packaging/signal-cli/-/issues/22

**Comment by bbernhard** [comment]
> Thanks for pinging me, created an issue over there and will fix it with a new build soon
> 
> https://gitlab.com/packaging/signal-cli/-/issues/22

Thank you very much - that is greatly appreciated!

**Comment by morph027** [comment]
Created v0.13.2+3 with the fix and build pipeline is running right now. Should be ready for testing soon.

**Comment by JaCoLJcL** [comment]
For me works go to **mode: json-rpc** in settings but waiting for fix

**Comment by bbernhard** [comment]
> Created v0.13.2+3 with the fix and build [pipeline](https://gitlab.com/packaging/signal-cli/-/pipelines/1240691326) is running right now. Should be ready for testing soon.

Many thanks!

I've updated the version and triggered a [build](https://github.com/bbernhard/signal-cli-rest-api/actions/runs/8561329519).

When the job finishes successfully, there should be this docker image tag available for testing: `bbernhard/signal-cli-rest-api:0.157-dev`

**Comment by Joelius300** [comment]
> > Created v0.13.2+3 with the fix and build [pipeline](https://gitlab.com/packaging/signal-cli/-/pipelines/1240691326) is running right now. Should be ready for testing soon.
> 
> Many thanks!
> 
> I've updated the version and triggered a [build](https://github.com/bbernhard/signal-cli-rest-api/actions/runs/8561329519).
> 
> When the job finishes successfully, there should be this docker image tag available for testing: `bbernhard/signal-cli-rest-api:0.157-dev`

Works on Raspberry Pi 4, thanks :)

**Comment by jodab** [comment]
Working fine for me too now with 0.157-dev :)

Many thanks!

**Comment by mike4001** [comment]
Hi, sorry to bother but do you know when the next version will be released?

Since I cannot download easily in Home Assistant I would need Version 0.83 for the Addon to start working again.

Thank you

**Comment by bbernhard** [comment]
> Hi, sorry to bother but do you know when the next version will be released?
> 
> Since I cannot download easily in Home Assistant I would need Version 0.83 for the Addon to start working again on my Raspberry Pi 4.
> 
> Thank you

should be released now :)

**Comment by RaceAap** [comment]
Just updated to 0.83 and can confirm that it works again on my Synology.

**Comment by bbernhard** [comment]
great, then I'll close this issue here. Thanks to everybody - especially @morph027!
