### ISSUE TITLE
Notifications on "Note to Self" stopped working

### ISSUE THREAD

**Issue by LordShadowen** [bbernhard/signal-cli-rest-api#511]
### The problem

When sending a message to self (same number on "from" and "to"), both Android and Desktop clients would trigger a standard notification.
After upgrading to 0.82, that is no longer the case - the message is delivered fine, but silently, without notifications.
Reverting to 0.81 restores the previous functionality.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
That's an [upstream change](https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0130---2024-02-18). But I guess we could make the behavior configureable.

**Comment by LordShadowen** [comment]
Yes, please 👍 
At least for me, getting notifications is the the main reason to use this project :)

Is there any workaround I could use in the meantime if I upgrade back to 0.82? 
Or is it better to just stick with 0.81 and wait?

In any case, thanks for the quick answer

**Comment by bbernhard** [comment]
I've thought about it a bit more and actually the upstream change is a breaking change. And as I do want the REST API wrapper to be as stable as possible I am considering this now a bug and I've reinstated the original behavior.

If you want to give it a try, please use `bbernhard/signal-cli-rest-api:0.156-dev`

**Comment by LordShadowen** [comment]
Worked on first try :)
