### ISSUE TITLE
"Please set the JAVA_HOME variable" since update

### ISSUE THREAD

**Issue by rowie** [bbernhard/signal-cli-rest-api#513]
### The problem

Since update to the lattest docker version i got this:

{"error":"ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk
Please set the JAVA_HOME variable in your environment to match the location of your Java installation

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
When do you get that error? I do not see that issue here.

**Comment by viaregio** [comment]
I'm not the issue owner, but I get the same error whiel calling `signal-cli` from within the container.

I called `signal-cli` from within the container to understand why all endpoints give me a status of 400.

**Comment by bbernhard** [comment]
> I'm not the issue owner, but I get the same error whiel calling `signal-cli` from within the container.
> 
> I called `signal-cli` from within the container to understand why all endpoints give me a status of 400.

Which mode do you use?

**Comment by viaregio** [comment]
I use the native mode.

**Comment by viaregio** [comment]
Setting JAVA_HOME=/lib/jvm/java-21-openjdk-amd64 and modifying the path accordingly fixed the problem for me.

**Comment by jounathaen** [comment]
Same issue and @viaregio's solution fixes it. (until Java 22 is used in the container :sweat_smile: )

**Comment by eelcohn** [comment]
I have the same problem. I'm on v0.13.7 and I've tried 3 different solutions that didn't work:

1. setting the `JAVA_HOME` variable in Docker to `/lib/jvm/java-21-openjdk-amd64`
2. `export JAVA_HOME=/lib/jvm/java-21-openjdk-amd64`
3. `ln -s /usr/lib/jvm/java-21-openjdk-amd64 jvm`.

Can some sort of permanent solution be implemented in the next release? Thank you!

**Comment by bbernhard** [comment]
Can't reproduce the issue.
