### ISSUE TITLE
Attachments download api

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#52]
We have registered a number using "register" api and we are able to sent message using "send" api.

Also we could fetch messages/attachments using "receive" api and we are getting the response as below.

For eg: [{"envelope":{"source":"+919xxxx","sourceDevice":1,"relay":null,"timestamp":1610517721588,"dataMessage":{"timestamp":1610517721588,"message":null,"expiresInSeconds":0,"attachments":[{"contentType":"image/jpeg","filename":null,"id":"**pwtcq-xxxx**","size":366267}],"groupInfo":null},"syncMessage":null,"callMessage":null,"receiptMessage":null}}]

But we would like to know how to get/download the image by using attachments id "**pwtcq-xxxx**".

Is there an api to fetch the attachments (image/video/pdf)?

**Comment by bbernhard** [comment]
will be part of the next release

**Comment by jyothisjose** [comment]
Can you please let us know when can we expect the next release with attachment downloading API.
Also can you please let us know if there is a way to receive the incoming messages in a webhook url.

**Comment by bbernhard** [comment]
The API endpoints are now available in the latest release: https://bbernhard.github.io/signal-cli-rest-api/

**Comment by jyothisjose** [comment]
Also can you please let us know if there is a way to receive the incoming messages in a webhook url.

**Comment by jyothisjose** [comment]
```
#!/bin/perl

use Modern::Perl;

use Net::DBus;
use Net::DBus::Reactor;

sub msgRcv {
    my ($timestamp, $sender, $groupID, $message, $attachments) = @_;
    print "Message: $message\nSender: $sender\nTimestamp: $timestamp\nAttachments: $attachments\n";
    return;
}

my $bus = Net::DBus->system();
my $sig = $bus->get_service("org.asamk.Signal");
my $obj = $sig->get_object("/org/asamk/Signal","org.asamk.Signal");
my $sigid = $obj->connect_to_signal('MessageReceived', \&msgRcv);

my $reactor=Net::DBus::Reactor->main();
$reactor->run();

exit 0;
```
https://github.com/AsamK/signal-cli/wiki/DBus-service


How to get the contentType of the attachment in the notification (msgRcv)?
Is there any way for that?

**Comment by bbernhard** [comment]
> ```
> #!/bin/perl
> 
> use Modern::Perl;
> 
> use Net::DBus;
> use Net::DBus::Reactor;
> 
> sub msgRcv {
>     my ($timestamp, $sender, $groupID, $message, $attachments) = @_;
>     print "Message: $message\nSender: $sender\nTimestamp: $timestamp\nAttachments: $attachments\n";
>     return;
> }
> 
> my $bus = Net::DBus->system();
> my $sig = $bus->get_service("org.asamk.Signal");
> my $obj = $sig->get_object("/org/asamk/Signal","org.asamk.Signal");
> my $sigid = $obj->connect_to_signal('MessageReceived', \&msgRcv);
> 
> my $reactor=Net::DBus::Reactor->main();
> $reactor->run();
> 
> exit 0;
> ```
> 
> https://github.com/AsamK/signal-cli/wiki/DBus-service
> 
> How to get the contentType of the attachment in the notification (msgRcv)?
> Is there any way for that?

If you want to use the above script you have to use [signal-cli](https://github.com/AsamK/signal-cli) directly. The REST API wrapper doesn't use the DBUS interface.

**Comment by jyothisjose** [comment]
We are able to fetch (retrieve) messages using dbus perl code.
But now the rest apis for sending messages are not working.

curl -X POST "http://IP:PORT/v2/send" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{ \"message\": \"test message\",  \"number\": \"+xxxxxxxxxx\",  \"recipients\": [    \"xxxxxxxxxx\"  ]}"

we are getting timeout error as given below

_**{"error":"process killed as timeout reached"}**_

Can you please let us know what could be the issue here?

**Comment by bbernhard** [comment]
As mentioned above: The DBUS interface doesn't work with the docker container.

**Comment by jyothisjose** [comment]
How to send message after using DBUS interface?

**Comment by bbernhard** [comment]
If you want to use the DBUS interface you have to drop the docker container and use [signal-cli](https://github.com/AsamK/signal-cli) directly. The DBUS mode isn't supported by the docker container.

**Comment by jyothisjose** [comment]
Can you please let us know if there is a webhook/notification to get the read/delivery receipt for a message sent via api (we are DBUS inteface using Perl code to fetch messages)?

**Comment by bbernhard** [comment]
There is no webhook mechanism. You have to poll the `receive` API endpoint periodically.

**Comment by jyothisjose** [comment]
We are using signal-rest-api for sending the messages with " --dbus " option
Internally signal-rest-api calling the signal-cli command, we are getting a delay  of 3 - 8 sec while  sending the messages.
Can you please let us know how can we reduce the send delay time to less than 1 sec.

**Comment by Atomic-Bean** [comment]
> We are using signal-rest-api for sending the messages with " --dbus " option
> Internally signal-rest-api calling the signal-cli command, we are getting a delay of 3 - 8 sec while sending the messages.
> Can you please let us know how can we reduce the send delay time to less than 1 sec.

He's considering using signal-cli's new GraalVM binary option. It hasn't been added yet, but do be aware that it is experimental and GraalVM is a fork of an old JVM so it might have compatibility issues.

**Comment by jyothisjose** [comment]
Can you please let us know how can we set profile name and display picture?
We are using dbus interface.

**Comment by bbernhard** [comment]
The attachments API is now implemented, so I'll close the issue now :)
