### ISSUE TITLE
How to send to an accout which has only a user name?

### ISSUE THREAD

**Issue by MilamberValheru** [bbernhard/signal-cli-rest-api#529]
(Maybe this is not a feature and I just missed the documentation.)

Within signal You can hide your phone number and make only a user name public, something like 
"thatsme.123".
How can I send a message to such an address? Is there a special syntax for this recipent field?

Using
`    "recipients": [ "thatsme.108" ]`
in http://localhost:8080/v2/send Post responds with
`  "error": "Failed to send (some) messages:\n+49123: Unregistered user \"+49123\"\n1714855949363\nFailed to send message\n"`

**Comment by bbernhard** [comment]
Although that is already supported by the upstream `signal-cli`, there is no support yet in the REST API wrapper. But it is on my todo list.

**Comment by MilamberValheru** [comment]
👍

**Comment by bbernhard** [comment]
In case someone wants to give it a try, there's now a docker image for testing here: `bbernhard/signal-cli-rest-api:0.159-dev`

**Comment by GergelyGombai** [comment]
@bbernhard I suggest closing this issue.

**Comment by MilamberValheru** [comment]
Ok, seems to work now 😄🙏
