### ISSUE TITLE
Moving HomeAssistant to other Hardware 

### ISSUE THREAD

**Issue by olisei** [bbernhard/signal-cli-rest-api#53]
How to unregister the Phone-Number from the old HomeAssistant? 
Error on the new HomeAssistant: Authorization failed, was the number registered elsewhere? 

curl -X POST -H "Content-Type: application/json" 'http://192.168.x.x:8080/v1/register/+41xxxxxxxxx' for registration.

Unregister?
curl -X POST -H "Content-Type: application/json" 'http://192.168.x.x:8080/v1/unregister/+41xxxxxxxxx' for registration.

**Comment by bbernhard** [comment]
I'll close this issue for now. In case you have still issues with that, please open another ticket.
