### ISSUE TITLE
how to send a message to a group?

### ISSUE THREAD

**Issue by mgx0** [bbernhard/signal-cli-rest-api#538]
### The problem

how to send a message to a group please?

can anyone provide a json where it is more clear?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

here is what I have tried:

{
  "message": "hello",
  "number": "+0000000000000",
  "text_mode": "normal",
  "recipients":[{"groupId":"YwZkqf+JZCWQcU3BC65qmJKucNeqv+IiwQWUc+9rXeA="}]
  } 

{
  "message": "hello",
  "number": "+0000000000000",
  "text_mode": "normal",
  "recipients":["group.YwZkqf+JZCWQcU3BC65qmJKucNeqv+IiwQWUc+9rXeA="]
  } 

{
  "message": "hello",
  "number": "+0000000000000",
  "text_mode": "normal",
  "recipients":["YwZkqf+JZCWQcU3BC65qmJKucNeqv+IiwQWUc+9rXeA="]
  } 

nothing from above works

**Comment by bbernhard** [comment]
there's an example here: https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/EXAMPLES.md

**Comment by mgx0** [comment]
> there's an example here: https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/EXAMPLES.md

Stupid me, thanks man!
