### ISSUE TITLE
Warning: No profile name set

### ISSUE THREAD

**Issue by Dirk-Ingenieur** [bbernhard/signal-cli-rest-api#539]
So far it is only a warning, but it may become an error in the future:

Sending a message I noticed the warning:
"No profile name set. When sending a message it's recommended to set a profile name with the updateProfile command. This may become mandatory in the future."

Any hints, what I need to do?

**Comment by Dirk-Ingenieur** [comment]
To be more precise: I am looking for the curl syntax I need to update my profile name.

**Comment by bbernhard** [comment]
This is the request: https://bbernhard.github.io/signal-cli-rest-api/#/Profiles/put_v1_profiles__number_

If you click on "Try it out" in the swagger documentation, it will generate you the curl command

**Comment by Dirk-Ingenieur** [comment]
Hi, 
thanks. It still took me some time trying, put finally I managed. Here is the result to all who struggle at the same stuff:
curl -X PUT -H "Content-Type: application/json" 'http://<myIP>:8080/v1/profiles/<+49mynumber>' -d '{"name":"<profilename>"}'
