### ISSUE TITLE
Unable to create groups

### ISSUE THREAD

**Issue by linderbo** [bbernhard/signal-cli-rest-api#54]
Im running latest stable home assistant on latest homeassistant os, installed this addon from the repository.

I was able to register a phone number, fetching messages and sending messages to numbers via automations works just fine. However, when i try to create a group using (numbers obfuscated):

curl -X POST -H "Content-Type: application/json" -d '{"name": "HAMP", "members": ["+358XXXXXXX", "+358YYYYYYY"]}' 'http://192.168.10.119:8080/v1/groups/+358ZZZZZZZZZ'

i get {"error":"Failed to send message: Unable to parse entity\n"}

Am i doing something wrong?

**Comment by sandersdc** [comment]
I'm getting the same error when trying to create a group using the instructions given in this link: https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md

curl -X POST -H "Content-Type: application/json" -d '{"name": "Group1", "members": ["+61400000002", "+61400000003"]}' 'http://172.30.20.10:8080/v1/groups/+61400000001'

If you run the command without the "members" part then a group is created but with only one member in it being the number which you registered.

**Example:** 
curl -X POST -H "Content-Type: application/json" -d '{"name": "Group1"}' 'http://172.30.20.10:8080/v1/groups/+61400000001'

When this is run a group is created with one member (+61400000001).  Does the creation of a group need to be processed in stages - i.e. first create the group and then add members to it?

**Comment by bbernhard** [comment]
It should work like it is described in the documentation, so there's no need to do that in stages. At the moment, Signal is experiencing some problems (see https://status.signal.org/), so I guess it could be related to that. In case the error persists, even after Signal service issues are resolved, it could be related to the signal-cli version. Currently, signal-cli-rest-api uses the latest v0.6.x signal-cli version, although there's already v0.7.2 out. I am already working on the update.

**Comment by sandersdc** [comment]
Thanks @bbernhard

**Comment by andreasbrett** [comment]
> Currently, signal-cli-rest-api uses the latest v0.6.x signal-cli version, although there's already v0.7.2 out. I am already working on the update.

That has to be it - not the signal outage. When I try to create a group with the account I registered through signal-cli-rest-api I get a message within the Signal app that this user is still on an old version and thus only a "old group" can be created with that account. Once the account is on the new type, a "new group" can be opened with that account.

Do you have a time frame for when 0.7.2 is supported for signal-rest-api.

PS: This project is awesome! Finally a secure way to send notifications from servers.

**Comment by bbernhard** [comment]
> Do you have a time frame for when 0.7.2 is supported for signal-rest-api.

I think I've finally fixed the issue with the docker image and it hopefully should wok now for all supported architectures (x86-64, arm64, armv7) - at least it seems that the zkgroup linking error is now gone :crossed_fingers: As the Signal Service is experiencing some problems at the moment, I cannot really test the image. 

My usual release practice is to build the release candidate, push the image with the `dev`-tag to dockerhub and test the image for a few days on my test machine. If no issues occur, the productive image on dockerhub will be updated. 

But maybe I'll shorten the test phase this time a bit, as it's affecting many users. Of course, if anyone wants to help with testing let me know. I'll then post the dockerhub tag for the release candidate here as soon as it is built and alpha tested.

> PS: This project is awesome!

Thanks, glad you like it :)

**Comment by andreasbrett** [comment]
> Of course, if anyone wants to help with testing let me know. I'll then post the dockerhub tag for the release candidate here as soon as it is built and alpha tested.

Sure, just hit me up. I'm still in the testing phase so no production setup.

**Comment by renini** [comment]
Just came here looking for solution on this issue. You want me to test the new version as well?

**Comment by bbernhard** [comment]
There's now a new docker image for testing: `bbernhard/signal-cli-rest-api:0.47-dev`

Please don't forget to change the docker image back to `bbernhard/signal-cli-rest-api:latest` as soon as the new productive image is released, otherwise you won't receive any new updates.

**Comment by andreasbrett** [comment]
I tried it and it partially works. Before creating a group the profile needs to be updated (with a name) using the updateProfile command like so:

`signal-cli -u "+49xxxxxx" updateProfile --name "WhatsMyName?!" --remove-avatar`
(note: you can of course provide an avatar instead if you wanted to)

Once that is done, a group can be created through the REST API. Otherwise this error comes up:
`{"error":"Cannot create group - please first update your profile."}`

I haven't checked if there's an endpoint for *updateProfile* so I simply bash'ed into the docker container an ran the command manually.

**Comment by bbernhard** [comment]
Thanks for testing!

Unfortunately there isn't much I can do to make that more user friendly. `signal-ci` returns the following error: `Cannot join a V2 group as self does not have a versioned profile`. I tried to make it a bit more user friendly by re-phrasing the error message a bit.

But there's an update profile REST API call which can be used to update the profile: https://bbernhard.github.io/signal-cli-rest-api/

**Comment by andreasbrett** [comment]
> But there's an update profile REST API call which can be used to update the profile: https://bbernhard.github.io/signal-cli-rest-api/

Well then everything's fine I guess! Please let us know when this is live so I can switch back the docker-compose tag to latest.

Do you also plan on implementing a REST API call for trusting safety numbers? That's the only thing I had to run within the docker container to establish trust between my server and all the receiving parties.

**Comment by bbernhard** [comment]
> Well then everything's fine I guess! Please let us know when this is live so I can switch back the docker-compose tag to latest.

I'll start a new build in a minute. I'll let you know as soon as it's finished.

> Do you also plan on implementing a REST API call for trusting safety numbers? That's the only thing I had to run within the docker container to establish trust between my server and all the receiving parties.

Yeah, I think that shouldn't be too hard to implement. Could you maybe create a ticket for that? I am pretty sure I'll forget about it otherwise ;)

**Comment by bbernhard** [comment]
The new image should be available :tada:

**Comment by sandersdc** [comment]
Thanks @bbernhard for the fix and @andreasbrett for testing.

I was able to create a group using the REST API and accepted the message on the two phones which I added to the group.  I then tried to send a message to the group but nothing came through.

I then went and listed the groups and the group which I created was listed but it showed that the two numbers which I added to my group were "pending members" even though I had accepted the group invite on the two phones.  I assume that is why the group message was not sent.  Did you also have pending members when you added your group?  Is there a way to refresh it so that it registers that those members have accepted the invite?

Below is the response I receive when listing the groups:

{"name":"Group1","id":"group.M5Fgq3BLHH68MMaed21sJTGG34=","internal_id":"3VgOLD34GG7AL11aaq5BN/jEZ2Uyc3fMMDR5hOFhmSHg=","members":["+61400000001] Pending members: [+61400000002","+61400000003] Requesting members: [] Link: -"],"active":true,"blocked":false}]

**Comment by bbernhard** [comment]
This issue looks similar to the one here: https://github.com/bbernhard/signal-cli-rest-api/issues/67

Unfortunately I can't reproduce the issue. But I'll try to release a new in the next few days which will (among other things) also upgrade `signal-cli` to version 0.7.3. Maybe this fixes your issue. 

`signal-cli` v 0.7.3 also introduced a global verbosity flag which provides some additional debug output. I'll try to expose that flag via the REST API as well, maybe that helps to track the issue down.

**Comment by sandersdc** [comment]
Thanks @bbernhard
