### ISSUE TITLE
How to show all received messages form one number?

### ISSUE THREAD

**Issue by trybula** [bbernhard/signal-cli-rest-api#541]
### The problem

I want to show all received (new and old) messages from one phoen number. From what i see the `http://127.0.0.1:8080/v1/receive/+48000000000` shows only newly received messages, and once shown the same message wont be shown again. I understand that feature and yes in may applications its good, but i need to be able to pull all messages.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Messages aren't stored anywhere - that is also something that isn't planned for the near future. So, if you need access to older messages, you have to store them yourself.

**Comment by trybula** [comment]
Ok, so what's stored in db?

**Comment by bbernhard** [comment]
> Ok, so what's stored in db?

What do you mean?

**Comment by trybula** [comment]
In signal api config / data / 37728.d is an database

**Comment by bbernhard** [comment]
That is an artifact created by [signal-cli](https://github.com/AsamK/signal-cli)

**Comment by trybula** [comment]
Ok, thanks
