### ISSUE TITLE
/v1/receipts/ 404 page not found

### ISSUE THREAD

**Issue by Kuhkaefer** [bbernhard/signal-cli-rest-api#543]
### The problem

While all other services work, sending a receipt does not work for me:

`curl -X POST -H 'accept: application/json' -H "Content-Type: application/json" 'http://localhost:8080/v1/receipts/+49XXXXXXX'  -d '{"receipt_type": "read", "recipient": "+49XXXXXXX", "timestamp": 1}'`

leads to 

`404 page not found`

And the docker logs (debug mode) just show:

`[GIN] 2024/06/05 - 18:28:58 | 404 |       4.166µs |      172.17.0.1 | POST     "/v1/receipts/+49XXXXXX"`

Is there anything I can do to trace it down?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
The version which contains that endpoint is not yet released. But you can give this test version a try: ` bbernhard/signal-cli-rest-api:0.160-dev`

**Comment by Kuhkaefer** [comment]
Thank you!

It now doesn't return anything, but the docker logs show:

`time="2024-06-06T23:35:01Z" level=debug msg="json-rpc command: {\"jsonrpc\":\"2.0\",\"method\":\"sendReceipt\",\"id\":\"a8604ea3-2db5-4a67-aeec-a5a5f4313731\",\"params\":{\"recipient\":\"+49XXXXXXX\",\"receipt-type\":\"read\",\"target-timestamp\":1717716743897,\"account\":\"+44XXXXXXX\"}}"
time="2024-06-06T23:35:02Z" level=debug msg="json-rpc received data: {\"jsonrpc\":\"2.0\",\"result\":{\"timestamp\":1717716901690,\"results\":[{\"recipientAddress\":{\"uuid\":\"0c607c60-c7a6-4d52-8fad-93d8105c83fa\",\"number\":\"+49XXXXXXX\"},\"type\":\"SUCCESS\"}]},\"id\":\"a8604ea3-2db5-4a67-aeec-a5a5f4313731\"}\n"
[GIN] 2024/06/06 - 23:35:02 | 204 |  363.468628ms |      172.17.0.1 | POST     "/v1/receipts/+44XXXXXXX"
time="2024-06-06T23:35:02Z" level=debug msg="json-rpc command response message: {\"timestamp\":1717716901690,\"results\":[{\"recipientAddress\":{\"uuid\":\"0c607c60-c7a6-4d52-8fad-93d8105c83fa\",\"number\":\"+49XXXXXXXX\"},\"type\":\"SUCCESS\"}]}"
time="2024-06-06T23:35:02Z" level=debug msg="json-rpc response error: "`

**Comment by bbernhard** [comment]
Looks good to me, no? Or is there some data you would it expect to return?

**Comment by Kuhkaefer** [comment]
Ah sorry, I forgot to say that it didn't seem to have any effect on the signal app. 

When sending "read" it's supposed to show the two grey check marks and with "viewed" they should turn white, right? It doesn't happen. 

And does the timestamp need to be exactly the one of the sent message?

**Comment by bbernhard** [comment]
Yes, right. Just tried it with "read" and it is working fine for me.

> And does the timestamp need to be exactly the one of the sent message?

I'd suggest to use the `/receive` endpoint and use the timestamp of the received message.

**Comment by Kuhkaefer** [comment]
ok perfect, thank you so much, it works!!

**Comment by bbernhard** [comment]
glad it works now!
