### ISSUE TITLE
Multicharacter emojis shift formatting

### ISSUE THREAD

**Issue by Kuhkaefer** [bbernhard/signal-cli-rest-api#544]
### The problem

When using text_mode="styled", the formatting gets shifted if multicharacter emojis are in the text.

Example: 
- "Test via \*\*signal\*\* API!" works fine
- "Test 👦🏿 via \*\*signal\*\* API!" results in "signal" and the "A" being bold

On iPhone and Linux Signal App:

![image](https://github.com/bbernhard/signal-cli-rest-api/assets/33182214/b2692f12-8a6a-4004-8eaa-86559192756c)

Version: v0.84, 0.83 & dev0.160

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.161-dev`

**Comment by Kuhkaefer** [comment]
Thank you, works great!
