### ISSUE TITLE
getting this : Request verify error: Bad response: 502

### ISSUE THREAD

**Issue by Zixim** [bbernhard/signal-cli-rest-api#55]
I'm following the Register phone number instructions but I keep getting this error in response :
```
➜  ~ curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/register/+32479033400'
{"error":"Request verify error: Bad response: 502 \n"}#
```
What am I doing wrong ?
PS: in case you're wondering : it ain't my real phone nr...

**Comment by bbernhard** [comment]
Signal is experiencing some technical difficulties at the moment. I guess it could be related to that: https://status.signal.org/

**Comment by Zixim** [comment]
must be...can we keep this open until Signal re-surfaces ?
