### ISSUE TITLE
Want to use in HA, cannot trust my device.

### ISSUE THREAD

**Issue by DcFamas** [bbernhard/signal-cli-rest-api#554]
### The problem

Hey there,
unfortunately I cannot trust my recipient:

`curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' \-d '{"message": "Test via Signal API!", "number": "+sender", "recipients": [ "+recipient" ]}'`

I get this error:

`{"error":"Failed to send message due to untrusted identities"}root@1315902c-signal-messenger:/#`

So I saw this issue:

https://github.com/bbernhard/signal-cli-rest-api/issues/56

But signal just give me this for the --config. :/

`signal-cli --config /data/ -u +sender listIdentities`
`Failed to read local accounts list`

So I guess the path to the config is wrong. How do I get the right one?

![grafik](https://github.com/bbernhard/signal-cli-rest-api/assets/35306967/d1e4905b-987b-44f1-b005-fe87b81899e2)

Best regards and thank for the upcoming help. :)

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
There are already endpoints for listing/trusting identities, see https://bbernhard.github.io/signal-cli-rest-api/

So you don't need to call signal-cli directly

**Comment by bbernhard** [comment]
Doesn't look that bad on first glance ;-). Did you replace the `string` with the actual safety number?

**Comment by DcFamas** [comment]
Oh I'm stupid. The "string" stands for the string which is the safety number. Sorry to annoy you with something like that. Now it works like a charme. Also for somebody who see's this topic, here my conclusion:

`curl -X 'GET' \      
'http://localhost:8080/v1/identities/SENDER' \
-H 'accept: application/json'`

`curl -X 'PUT' \
  'http://localhost:8080/v1/identities/SENDER/trust/RECIPIENT' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "trust_all_known_keys": false,
  "verified_safety_number": "THESAFETYNUMBERofRECIPIENT"
}'`

SENDER = your sender number like +49111111111
RECIPIENT = the person you want to send, like +231111111111
THESAFETYNUMBERofRECIPIENT = the string is shown in the first command like 49424 46754 81606 03014 47112 96921 824327 91222 76213 34383 57434 54246

@bbernhard  thank you for your help! :)

**Comment by bbernhard** [comment]
you're welcome - glad it worked :)

**Comment by cklinkbeil** [comment]
When typing in the command I get this error:


Entered Command: 

curl -X PUT -H 'Content-Type: application/json' -d '{"trust_all_known_keys": false, "49424 46754 81606 03014 47112 96921 824327 91222 76213 34383 57434 54246": "11111 11111 11111 03014 47112 96921 824327 91222 76213 34383 57434 54246"}' 'http://1.1.1.1:8080/v1/identities/+14444444444/trust/+15555555555'

{"error":"Couldn't process request - please either provide a safety number (preferred \u0026 more secure) or set 'trust_all_known_keys' to true"}
