### ISSUE TITLE
Can't send to 1 specific recipient, others OK.

### ISSUE THREAD

**Issue by Zixim** [bbernhard/signal-cli-rest-api#56]
I'm trying to send to one of my phone numbers : 
```
➜  /config curl -X POST -H "Content-Type: application/json" -d '{"message": "Hello World!", "number": "+32123456789", "recipients": ["+32987654321"]}' 'http://127.0.0.1:8080/v2/send'
{"error":"Failed to send message: 1610795206942\nFailed to send (some) messages:\nUntrusted Identity for \"+32987654321\"\n\n"}#
```
That recipient number has no problems receiving messages in the Signal app for Android. (Tested by sending msg to it from other Signal apps/ numbers)
Sending from `signal-cli-rest-api` with the same registered number to my other recipients works just fine.
Any thoughts why that specific recipient gets marked as `Untrusted` when using the api ?

**Comment by bbernhard** [comment]
I guess the key of that number has changed, so you need to trust it manually.
Have a look at the `signal-cli` API [here](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc)

The functionality is not yet exposed via the REST API so you have to fix that on the commandline

* run `docker ps` to find out the container id of the `signal-cli-rest-api` docker container
* run `docker exec -it <container id> /bin/bash` to connect to your running docker container
* run `su signal-api`
* run `signal-cli --config /home/.local/share/signal-cli/ -u <registered number> listIdentities` to list all identities and their trust status
* run `signal-cli --config /home/.local/share/signal-cli/ -u <registered number> trust <number to trust> -v <verified safety number>` to trust the new key.

**Comment by Zixim** [comment]
```
signal-api@1315902c-signal-messenger:/data/data$ signal-cli --config /home/.local/share/signal-cli/ -u "+32123456789" listIdentities
Error loading state file: /home/.local/share/signal-cli/data
```

by the way , this is on HA-OS

**Comment by bbernhard** [comment]
I think for the HASSIO Addon the config location is different. I think it's  `--config /data/data` instead of `--config /home/.local/share/signal-cli/`

**Comment by Zixim** [comment]
just discovered i need to `$ signal-cli --config /data/ -u .... `
The untrusted rcpt number appears 3x in the list of Identities...should I remove the older ones, and then `trust` the most recent one ?

**Comment by bbernhard** [comment]
> just discovered i need to `$ signal-cli --config /data/ -u .... `
> The untrusted rcpt number appears 3x in the list of Identities...should/can I remove the older ones, and then `trust` the most recent one ?

that should work.

**Comment by Zixim** [comment]
it does indeed work(except for removing an identity, can't find that in the signal-cli docs.
Many thanks.

**Comment by guusnijssen** [comment]
Awesome, this did the trick for me. Many thanks
