### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by vincentdev15** [bbernhard/signal-cli-rest-api#560]
### The problem

Hello,

I don't know if it's an issue or if it's just that I don't know how to do.

I have followed all the steps to install and run the dockerized API on my computer, all works perfect until I scan the QR code from within Signal with my smartphone.

After having scenned the QR code, I get an error message : network error.

What can be the problem ?

Thanks for your help.

V

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by mfuhrmann** [comment]
I have exactly the same issue. I've used to use this image
```
bbernhard/signal-cli-rest-api                        <none>    17304636c3e1   5 months ago   522MB
```

But since it didn't work anymore, I am going with the latest right now which seems to be 300MB larger :thinking: 
```
bbernhard/signal-cli-rest-api                        latest    d58565ea1725   2 weeks ago    849MB
```
But didn't help. I also get the `network error` message. But linking the desktop client works perfectly.

Maybe important: I am in the beta Signal app group. My Signal version is `7.11.1`.

**Comment by bobsiboo** [comment]
I get also get a network error, however i did notice a pop up on my phone asking to finish the setup on my other device, Since i am scanning the qr code via Rest in my browser i am not sure how to proceed.

**Comment by bbernhard** [comment]
Unfortunately this is an upstream error, see https://github.com/AsamK/signal-cli/issues/1556.

I'll close this issue, as there already exists a similar issue: https://github.com/bbernhard/signal-cli-rest-api/issues/564
