### ISSUE TITLE
"Finish linking on your other device"

### ISSUE THREAD

**Issue by Hellmo-Luciferrari** [bbernhard/signal-cli-rest-api#564]
### The problem

When trying to link via QR code from Signal on my mobile device, the QR Code is accepted; however when it is scanned I get a message telling me to "Finish linking on your other device"

Signal on Android version: 7.11.3

6c86af7a75c5 is the version for Signal-cli-rest-api

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

arm64

### Additional information

Running via Docker Compose on a Pi 4 8gb

**Comment by bohart** [comment]
Got the same issue.
Once QR code is scanned, the mobile app shows "Finish linking on your other device".

Additional details:
- an account details has been appeared at ./signal-cli-config/data/accounts.json
- but API request to `/v1/accounts` return nothing;
- API request to `/v2/send` return an error "User %mynumber% is not registered.";

**Comment by bobsiboo** [comment]
Got the same issue, When scanning the qr code a second time i just get a message Network error. I noticed there is an issue from last week with the same error. Maybe related?

**Comment by bbernhard** [comment]
unfortunately this is an upstream issue: https://github.com/AsamK/signal-cli/issues/1556

**Comment by ender-the-xenocide** [comment]
do you have any info as to why previous versions don't work then? I tried with 0.82 which uses signal-cli v 0.13.2 with the same issue. Where there backwards-incompatible changes on Signal's backend?

**Comment by bobbolous** [comment]
Upstream master has fixed the issue, although it is still marked as open

**Comment by k-bx** [comment]
As mentioned in https://github.com/AsamK/signal-cli/issues/1556 , this is fixed in latest master. In my case, I'm using signal-cli-rest-api and signal-cli-native without docker, so fixing is simple, just put the linked binary in your `/usr/bin/signal-cli-native`

**Comment by xalik111** [comment]
any chance if i use docker?

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.164-dev`

**Comment by ender-the-xenocide** [comment]
I confirm linking now works. thanks for the quick fix!

**Comment by ValentinFreelancer** [comment]
thank you sir

**Comment by HeyVern** [comment]
@bbernhard much appreciated!  Looking forward to next release.  Quick question for group.  Do you think it would have been possible to use docker to remap the path in the container to an external folder and place the updated v013.5 binary there?  I was considering trying this when I saw that a fix is incoming.

**Comment by ender-the-xenocide** [comment]
I imagine so - the last 2 commits are for taking the newer upstream lib, so in this particular case it might've worked.
https://github.com/bbernhard/signal-cli-rest-api/commit/30615592b32bddec506868929aa21f45b9eafdda
https://github.com/bbernhard/signal-cli-rest-api/commit/bb246cf3f7e786822a910194ba6f62cc2015e78c

**Comment by HeyVern** [comment]
Any ideas when we are going to se an updated release that includes this fix?

**Comment by ahatius** [comment]
Using the latest version (0.86, released yesterday) I was able to link my device again.

**Comment by pavacs** [comment]
A question for those who managed to connect their device.
What needs to be done in hassio addons after the message Finish linking on your other device ?

**Comment by rzemykers** [comment]
at 0.88 in HA same issue.

**Comment by DBendit** [comment]
Seeing this with 0.86 and 0.88 today. No report upstream as far as I can tell.

**Comment by DBendit** [comment]
I was able to get past the issue by downloading https://github.com/AsamK/signal-cli/releases/tag/v0.13.6 and pointing it at the config dir and linking my device using the generated code.

**Comment by ge8020** [comment]
I am also stuck at "finish linking on your other device" with 0.88

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.167-dev`

**Comment by ge8020** [comment]
> Please give this version a try: `bbernhard/signal-cli-rest-api:0.167-dev`

Thx, but sorry, i have no clue, how to try this?I´m not using the docker installation, but the home assistant add on from https://github.com/haberda/hassio_addons. And sorry, i just recognized that this is something different...

**Comment by Joly0** [comment]
i am seeing the same issue with "bbernhard/signal-cli-rest-api:latest-dev", i cant link my device

**Comment by thalesmaoa** [comment]
> Please give this version a try: `bbernhard/signal-cli-rest-api:0.167-dev`

I confirm. It is working now.

**Comment by ge8020** [comment]
But how do you get this to work with the home assistant addon version?

**Comment by thalesmaoa** [comment]
@ge8020 , the main problem was that, latest version, it is not possible to add a new device. With the `0.167-dev` that is working. Nothing changes after that.

**Comment by p-roman** [comment]
> Problem still existing with latest Home Assistant Add On that I installed today. After several "network error" messages, now stuck at "finish linking on other device" in the Signal app. Registering the number purely via API (instead of Signal App) did not work either: Getting around the captcha does not work, following the instructions eventually returns a "wrong captcha value" error message.

I know this is a closed issue, but I'm seeing the same thing with the Home Asssistant Add On, version 0.93.0. I was able to register it through the API, but I'd rather link it as a device...let me know if I should create a new issue instead. I tried enabling debugging logging, but don't think I can do that through the add-on version.

Edit: Nevermind, was able to set the debug level via the API and it turns out I had already tried registering the number, so once I got that cleared out, was able to link successfully.

**Comment by kuduacz** [comment]
Can we open it on e again?
I Just add it as 3rd device to my signal account so i cant use api, and when try to pair device via qr code ask me to aprrove it on device and cant do it. Signal cli as HA addon. Anyone can help me?
