### ISSUE TITLE
Add account number to challenge token log output

### ISSUE THREAD

**Issue by benjy3gg** [bbernhard/signal-cli-rest-api#566]
### Feature Request
I have a multi-number signal setup. When i get a rate-limit-challenge the logging works and i get the token id and the phonenumber of the recipient.

To lift the rate-limit i need to call http://localhost:8888/v1/accounts/{number}/rate-limit-challenge with the number of the registered account in signal-cli.
This number is not in the log output.

Can you please add it?

**Comment by bbernhard** [comment]
Just to be clear: By log output you mean the JSON response, right?

**Comment by benjy3gg** [comment]
`{"jsonrpc":"2.0","error":{"code":-5,"message":"Failed to send message due to rate limiting","data":{"response":{"timestamp":1721686852997,"results":[{"recipientAddress":{"uuid":"xxxx-xxxx","number":"+0123456789"},"type":"RATE_LIMIT_FAILURE","token":"xxxx-xxxx-xxxxxyy","retryAfterSeconds":86400}]}}},"id":"xxxxxx-xxyxyyyy"}`
Yes I meant this json response.

**Comment by bbernhard** [comment]
With the next release the number should now be returned in normal and native mode. But in json-rpc mode the output comes directly from [signal-cli](https://github.com/AsamK/signal-cli). I guess I could manually extend the output with the information, but maybe it would be better to create an upstream feature request. Sounds cleaner to me :)
