### ISSUE TITLE
Linking device leads to MissingCapabilitiesException

### ISSUE THREAD

**Issue by benjy3gg** [bbernhard/signal-cli-rest-api#567]
### The problem

When i try to link a new device, i get the MissingCapabilitiesException.
Seems to be already tracked in signal-cli https://github.com/AsamK/signal-cli/issues/1556

can you create a new release once this is fixed?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
already tracked in https://github.com/bbernhard/signal-cli-rest-api/issues/564
