### ISSUE TITLE
Phone Registration & Signal Windows Desktop Client

### ISSUE THREAD

**Issue by fnordson** [bbernhard/signal-cli-rest-api#576]
### Feature Request
Could you please add to the documentation that you should try the registration process on a PC that hasn't the Signal Desktop Client installed? 

It took me far too much time to realize why I didn't get the code in the developer console...

Thank you.

**Comment by frekuz** [comment]
another option is to right klick on the link (open signal) and copy it.

**Comment by fnordson** [comment]
This is even better.  
It was late at night here...didn't get the idea.
