### ISSUE TITLE
Unable to link, callback from API required

### ISSUE THREAD

**Issue by bboybboy** [bbernhard/signal-cli-rest-api#579]
### The problem

Unable to link, callback from API required

I'm trying to link new device, after scanning QR code on phone I see message - now proceed on machine you are linking. 
How to accept link request from API side?

version used 0.88

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bboybboy** [comment]
I also tried 0.164.dev and latest.... Same issue :(

**Comment by bboybboy** [comment]
from 1053 try I logged in

**Comment by bbernhard** [comment]
> @bboybboy so you've just tried 1000 times and it worked? :) any guess why it worked? I've tried 10x times and don't really want to try more

might be worth a try: https://github.com/bbernhard/signal-cli-rest-api/issues/564#issuecomment-2350962463
