### ISSUE TITLE
signal-cli config does not default to /home/.local/share/signal-cli/ so account information does not persist

### ISSUE THREAD

**Issue by eric72777** [bbernhard/signal-cli-rest-api#582]
### The problem

The container does not default to having the signal-cli config default to `/home/.local/share/signal-cli/` so if the user sets up the system per the documentation, the signal account registration information won't persist after a `docker compose down`. 

### Temporary Fix for Users
To temporarily fix this, I explicitly added the env variable `- SIGNAL_CLI_CONFIG_DIR=/home/.local/share/signal-cli/` and it works fine. However, this isn't the fix for the bug since the container should default to this location per the documentation.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Can't reproduce that issue. Have you maybe set the `SIGNAL_CLI_CONFIG_DIR` environment variable before (to some other value)?
