### ISSUE TITLE
{"error":"invalid character 'S' after top-level value"}

### ISSUE THREAD

**Issue by Joly0** [bbernhard/signal-cli-rest-api#585]
### The problem

When i try to fetch the groups using this command `curl -X GET -H "Content-Type: application/json" 'http://OBFUSCATED/v1/groups/+OBFUSCATED'` i only get the error message: `{"error":"invalid character 'S' after top-level value"}`
 I am btw using the latest-dev docker version

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by Joly0** [comment]
Also, for additional information here is the command for the signal-cli directly `signal-cli-native --config /home/.local/share/signal-cli --output json -a +4REDACTED listGroups -d`
and the output:
```
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
REDACTED
```

**Comment by Joly0** [comment]
I think this line `SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]` might be the reason?

**Comment by bbernhard** [comment]
This seems to be an upstream issue, see https://github.com/AsamK/signal-cli/issues/1584

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.168-dev`

**Comment by Joly0** [comment]
Yes, works with that version

**Comment by bbernhard** [comment]
Should be fixed with the latest release.
