### ISSUE TITLE
Error 400 when sending message (message is still sent)

### ISSUE THREAD

**Issue by Joly0** [bbernhard/signal-cli-rest-api#586]
### The problem

I tried setting up this project alongside with apprise and noticed, that when using apprise to send notifications to my signal number, apprise would always complain about it with error code 400. Also saw this in the signal-cli logs.

When i tried to run the recommended command for testing `$ curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' \
     -d '{"message": "Test via Signal API!", "number": "+4412345", "recipients": [ "+44987654" ]}'` i noticed this behaviour aswell. The logs also state error 400

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Native Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
This seems to be an upstream issue, see https://github.com/AsamK/signal-cli/issues/1584

**Comment by Joly0** [comment]
Ok, good to know. But it seems to ve fixed in upstream already 4 days ago.

**Comment by bbernhard** [comment]
yes, but there is no release yet.

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.168-dev`

**Comment by Joly0** [comment]
Yep, works correctly with this version

**Comment by bbernhard** [comment]
Should be fixed with the latest release.
