### ISSUE TITLE
Disappearing / expiring group chat messages

### ISSUE THREAD

**Issue by travelvice** [bbernhard/signal-cli-rest-api#587]
### The problem

My Signal CLI device was not respecting the message expiration timer in group chats. The secondary CLI device is sending alerts to a group channel, and while the other members of the channel have their messages disappear as expected the untouched message history is made visible when logged into Signal Android with the primary device.

I found references that this was touched on a few years ago, but didn't see any matching documentation in this project's API:

https://github.com/AsamK/signal-cli/issues/620
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc

> **updateGroup**
> `-e EXPIRATION_SECONDS, --expiration EXPIRATION_SECONDS`
>     _Set expiration time of messages (seconds). To disable expiration set expiration time to 0._

Although undocumented I passed the following body to the `PUT /v1/groups/{number}/{groupid}` endpoint and I _believe_ it's having the correct impact (but needs more testing).
```
{
  "EXPIRATION_SECONDS": "86400"
}
```

Hoping to both confirm this was correct and the setting will remain sticky and respected for the secondary CLI device and if so hopefully get it documented. Thanks!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
There's no option yet, but it should be pretty easy to add. I'll have a look

**Comment by bbernhard** [comment]
It's now possible to set the expiration time with the `expiration_time` parameter.

**Comment by oleua** [comment]
> It's now possible to set the expiration time with the `expiration_time` parameter.

Hi! Is this configuration value is in seconds or miliseconds?
