### ISSUE TITLE
Use JRE for runtime container

### ISSUE THREAD

**Issue by x-jokay** [bbernhard/signal-cli-rest-api#59]
Is there any reason why you use the JDK container instead of the JRE, see [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/Dockerfile#L75)?

I would switch to [adoptopenjdk:11-jre-hotspot-bionic](https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/11-jre-hotspot-bionic/images/sha256-403072dcaabacb010ba3cddbeaef233de7f083b8e223f87940b006da4905d3f5?context=explore) if possible.

- 11-**jdk**-hotspot-bionic - compressed size: **223.97 MB**
- 11-**jre**-hotspot-bionic - compressed size: **80.3 MB**

**Comment by bbernhard** [comment]
good point, thanks for the PR!
