### ISSUE TITLE
Can't link device with QR-code. Error 409

### ISSUE THREAD

**Issue by AntonKun** [bbernhard/signal-cli-rest-api#591]
### The problem

I can't pair devices using a QR code (`/v1/qrcodelink`). I see the following in the logs:

```
signal-api@ea76a0ba1ea8:/$ signal-cli --config /home/.local/share/signal-cli link -n signal-api
sgnl://linkdevice?uuid=e2BgZS2gJ2KU-iflYyBq4Q&pub_key=BVguwLasm3wpY6CcTaGSDxgiYQ0CAHNdDRn%2BI6BePt5q
INFO  ProvisioningManagerImpl - Received link information from +<my_number>, linking in progress ...
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
Link request error: StatusCode: 409
```

I use latest version (0.88) and new clean docker container

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by mpekatsoula** [comment]
I had the same issue and it looks like we need signal-cli v0.13.6, while the latest image has v0.13.5. I tested with bbernhard/signal-cli-rest-api:0.167-dev and it works fine

**Comment by AntonKun** [comment]
@bbernhard should we expect a new release in the near future?

**Comment by bbernhard** [comment]
I am waiting for another signal-cli release. While signal-cli v0.13.6 (which is used in `bbernhard/signal-cli-rest-api:0.167-dev`) fixes the registration bug, it introduced another issue during normal operation. I'd suggest to use the above dev version for now to get the device registered and afterwards switch back to the release version.

**Comment by mpekatsoula** [comment]
@bbernhard Works fine (managed to sync and send messages), but I think you have changed the HOST_IP to 172.18.0.8 so I had to access this IP to get the qrcodelink instead of localhost. Not sure if it's intentional.

**Comment by bbernhard** [comment]
> @bbernhard Works fine (managed to sync and send messages), but I think you have changed the HOST_IP to 172.18.0.8 so I had to access this IP to get the qrcodelink instead of localhost. Not sure if it's intentional.

Thanks for the feedback!

I haven't changed anything regarding the HOST_IP - that one must come from your docker setup.

**Comment by AntonKun** [comment]
Everything seems to be in order.
I have tested most of the methods on 0.168-dev and they work properly.

Thanks!

**Comment by bbernhard** [comment]
Thanks for the feedback! As there is now also an official release, I'll close this one here.

**Comment by andrew-belyi** [comment]
> Thanks for the feedback! As there is now also an official release, I'll close this one here.

Can I use `bbernhard/signal-cli-rest-api:latest` now?

**Comment by bbernhard** [comment]
> > Thanks for the feedback! As there is now also an official release, I'll close this one here.
> 
> Can I use `bbernhard/signal-cli-rest-api:latest` now?

yes
