### ISSUE TITLE
 Can't link device with QR-code. No Error Code

### ISSUE THREAD

**Issue by lmaddox** [bbernhard/signal-cli-rest-api#593]
### The problem

after scanning the qr code, the phone app says to continue linking signal on the browser. after a few attempts, the phone app now says network error.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

attempted with all modes.

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.168-dev`

**Comment by evgeny-l** [comment]
@bbernhard 
Had the same problem around 3 hours ago.
In the mobile app the message was "Complete setup on Signal Desktop". The config folder was populated, but no active accounts appeared in API. Errors were "User not registered".

Tested now with the your image `bbernhard/signal-cli-rest-api:0.168-dev` - everything worked well now.
The device was linked successfully.

Thanks a lot for the great lib! :)

**Comment by bbernhard** [comment]
> @bbernhard Had the same problem around 3 hours ago. In the mobile app the message was "Complete setup on Signal Desktop". The config folder was populated, but no active accounts appeared in API. Errors were "User not registered".
> 
> Tested now with the your image `bbernhard/signal-cli-rest-api:0.168-dev` - everything worked well now. The device was linked successfully.
> 
> Thanks a lot for the great lib! :)

Thanks for the kind words - glad it is working now! :)
