### ISSUE TITLE
"Specified account does not exist" when using REST, can only send via Signal-CLI

### ISSUE THREAD

**Issue by Nautilus52** [bbernhard/signal-cli-rest-api#596]
### The problem

Anytime I send a request with the REST protocol, I get this error message:

{"error":"Specified account does not exist"}

It works perfectly if I use the container terminal and send the message through signal-cli.  I have successfully registered my number with Signal using both methods, REST and signal-cli, but as soon as the container restarts, REST will no longer function and just says the account doesn't exist.  It is a dedicated number, not linked.

In the past, I remember needing to add my number in place of a null value in the username field of a file located in signal-cli-config/data/<some random id>, but I think that may no longer be necessary and that signal-cli folder doesn't have a random id number file in it, just a folder named data and jsonrpc2.yml

I started fresh with a new container and clean volume, same result in both normal and JSON-RPC modes.  What am I doing wrong?  Thanks for any help!

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

JSON-RPC Mode

### What's the architecture of your host system?

x86-64

### Additional information

I have verified the volume mapping is correct   "./signal-cli-config:/home/.local/share/signal-cli"

I have not used the SIGNAL_CLI_CONFIG_DIR environmental variable.

Contents of jsonrpc2.yml

config:
  <multi-account>:
    tcp_port: 6001
    fifo_pathname: /tmp/sigsocket1

**Comment by bbernhard** [comment]
How did you call signal-cli? Did you use the same commands that the REST API wrapper is using?

If you switch to the normal mode and enable debug logging you can see the actual signal-cli commands the REST API wrapper is executing(see https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md)

**Comment by Nautilus52** [comment]
> How did you call signal-cli? Did you use the same commands that the REST API wrapper is using?
> 
> If you switch to the normal mode and enable debug logging you can see the actual signal-cli commands the REST API wrapper is executing(see https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md)

I used the container's CLI in Portainer, and ran signal-cli commands following the instructions in the signal-cli manual.  I will enable debug logging and see if I can glean any additional information.

**Comment by Nautilus52** [comment]
Never mind, everything works as it should.  For some reason, I had it in my head that registering the number needed to be done directly via signal-cli.  I started fresh and used only REST to configure everything, and now it is working perfectly.  Thank you for all the time you have spent on this wonderful project!
