### ISSUE TITLE
Better documentation for endpoint /v2/send

### ISSUE THREAD

**Issue by Quiwy** [bbernhard/signal-cli-rest-api#602]
### The problem

Going on the [swagger page](https://bbernhard.github.io/signal-cli-rest-api/#/Messages/post_v2_send) of the api, the /v2/send endpoint seems not documented with all.

It would help to explain somewhere how to pass all parameters. If I'm not mistaken, they are [a lot](https://github.com/bbernhard/signal-cli-rest-api/blob/master/src/api/api.go). For example, I'm really not sure how to send a message to a group, mentionning someone in the message. Or what other option thant `text_mode` are available.

I read the example page too and didn't find information about them.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

Home Assistant Signal Addon

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
Thanks for the info! Unfortunately a commit last week broke the swagger documentation. Should be fixed now.

**Comment by Quiwy** [comment]
Thank you very much 😀
