### ISSUE TITLE
GetGroups should display member UUID if there is no number

### ISSUE THREAD

**Issue by uriinf** [bbernhard/signal-cli-rest-api#611]
### Feature Request
In latest Signal versions it's possible to add group members without phone number. In this case member is added as UUID. But `/v1/groups/<NUMBER>` shows empty string for such members:

```json
{
  "name": "Group Name",
  "id": "group.SomeHashHere",
  "internal_id": "someHashHer",
  "members": [
    "+XXXXX",
    "",
    "+YYYYYYY",
    ""
  ],
  "blocked": false,
...
}
```

`signal-cli` responses with [member UUID](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/commands/ListGroupsCommand.java#L47) in such cases. It would be useful if `signal-cli-rest-api` could return these UUIDs instead of empty strings.

Thanks.

**Comment by uriinf** [comment]
It seems may require to update `/v1/groups/{number}/{groupid}/members [delete]` and `/v1/groups/{number}/{groupid}/members [post]` with member UUID as parameter.

**Comment by bbernhard** [comment]
I've fixed something, but unfortunately it's hard for me to test, as I do not have group members without a phone number set. But I could provide you a test version in case you want to give it a try.

**Comment by EnriqCG** [comment]
I manage a few groups without phone numbers. I'm willing to give it a try and see if it works.

**Comment by bbernhard** [comment]
please give this version a try: `bbernhard/signal-cli-rest-api:0.171-dev`

**Comment by uriinf** [comment]
> please give this version a try: bbernhard/signal-cli-rest-api:0.171-dev

it works:

```
  "members": [
    "+************",
    "2b6cb1eb-df3c-4f4b-9bd4-175642b877a9",
    "+************",
    "+************",
    "+************",
    "1fba9429-7082-4ad4-be61-6b5f1fbbf46f",
    "+************",
    "+************",
    "f37c38ce-b1dc-428f-a01c-032e60c986dc",
    "+************",
    "+************",
    "+************",
    "+************",
    "a4ee2636-a834-4003-8348-e6cd3558dd3b",
    "de43a0a3-d9b3-48a2-a83b-b3e1d70ce55b",
    "+************",
    "+************",
    "+************",
    "677c5fb7-90f8-4c8b-8f32-b5363b0586ea"
  ],
```

**Comment by EnriqCG** [comment]
I can confirm it works too.
