### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by bleh666** [bbernhard/signal-cli-rest-api#615]
### The problem

When trying to access http://localhost:8080/v1/qrcodelink?device_name=signal-api, all I get is "Unable to connect". According to the logs everything seems to be running fine.

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bleh666** [comment]
Nevermind, redeployed it about 600 times and suddenly it worked. No idea why.

**Comment by bleh666** [comment]
Well, that worked for a good 10 minutes, now it's more of the same issue.

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.169-dev`

**Comment by bleh666** [comment]
@bbernhard There must be some error at my end. I tried it via Portainer through TrueNas and that worked fined. First try was via Proxmox/Portainer.

**Comment by bleh666** [comment]
@bbernhard There must be some error at my end. I tried it via Portainer through TrueNas and that worked fined. First try was via Proxmox/Portainer.
