### ISSUE TITLE
Groupmod: GID 101 already exists

### ISSUE THREAD

**Issue by Sn4kez** [bbernhard/signal-cli-rest-api#620]
### The problem

The API was running fine since the last update. I didn't change any users, groups, or anything. Suddenly I cannot start the container because of the following message:

`<html><body>

date | stream | content
-- | -- | --
2024/11/23 13:29:19 | stdout | groupmod: GID '101' already exists
2024/11/23 13:29:19 | stdout | + groupmod -g 101 signal-api
2024/11/23 13:29:19 | stdout | usermod: no changes
2024/11/23 13:29:19 | stdout | + usermod -u 1026 signal-api
2024/11/23 13:29:19 | stdout | + [ -z /home/.local/share/signal-cli ]
2024/11/23 13:29:19 | stdout | + set -e
2024/11/23 13:23:43 | stdout | groupmod: GID '101' already exists
2024/11/23 13:23:43 | stdout | + groupmod -g 101 signal-api
2024/11/23 13:23:43 | stdout | + usermod -u 1026 signal-api
2024/11/23 13:23:43 | stdout | + [ -z /home/.local/share/signal-cli ]
2024/11/23 13:23:43 | stdout | + set -e

</body>
</html>` 

Is it now necessary to have an own user for the container?

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

### Additional information

- Running on Synology Container Manager

**Comment by bbernhard** [comment]
Please give this version a try: `bbernhard/signal-cli-rest-api:0.173-dev`

**Comment by Sn4kez** [comment]
> Please give this version a try: `bbernhard/signal-cli-rest-api:0.173-dev`

Thanks for the quick response. I solved it by changing the UID and GID to the default settings (both 1000), like described in your docs. It don't really know why it works right now but it does.
