### ISSUE TITLE
400 Bad Request // USer not registered -- Linked Device!

### ISSUE THREAD

**Issue by dmindfuse** [bbernhard/signal-cli-rest-api#621]
### The problem

Hi
Until yesterday, I was perfectly happy using a linked Signal device to send notifications from changedetection.io. However, Signal on my phone reminded me that my linked device needed to login or it would expire. So I thought I should delete and re-link the device and that'd fix it for a while. And so I did. Unfortunately, since then, apprise in the changedetection.io container is unable to send notifications. It doesn't matter how often I delete and re-link my phone in the signal-cli container (and successfully send notifications from CLI in this container), it always responds stating my number is not registered. And in a sense that is correct, because it's "linked". However, this worked until I deleted and re-linked the device. I cannot work out, why for api calls on the 8080 port the signal-cli container insists on a registered phone number and ignores the one I linked.

Go to Docker Console of the container you run apprise in (in my case changedetection.io)
Using a signal URL, enter:
apprise -D -b "This is a test" signal://signal-cli-signal-cli-1:8080/123456789012
(123456789012 is the phone number of the signal user, beginning with the country code, eg.: 155500555 for a US number)
(signal-cli-signal-cli-1 is the name of the docker signal-cli container)

This reports in my case
root@changedetection:/app# apprise -D -b "This is a test" signal://signal-cli-signal-cli-1:8080/123456789012
2024-11-21 16:23:01,503 - DEBUG - Language set to en
2024-11-21 16:23:01,846 - DEBUG - Notification Plugin 109(s) and 155 Schema(s) loaded in 0.3394s
2024-11-21 16:23:01,847 - DEBUG - Loaded Signal API URL: signal://signal-cli-signal-cli-1:8080/+123456789012/?batch=no&status=no&format=text&overflow=upstream
2024-11-21 16:23:01,847 - DEBUG - Signal API POST URL: http://signal-cli-signal-cli-1:8080/v2/send (cert_verify=True)
2024-11-21 16:23:01,847 - DEBUG - Signal API Payload: {'message': 'This is a test', 'number': '+123456789012', 'recipients': ['+123456789012']}
2024-11-21 16:23:04,296 - WARNING - Failed to send 1 Signal API notification to +123456789012: Bad Request - Unsupported Parameters., error=400.
2024-11-21 16:23:04,297 - DEBUG - Response Details:
**b'{"error":"User +123456789012 is not registered.\n"}'**

To verify Signal Cli works, switch to the Docker Console of the signal-cli container, in my case signal-cli-signal-cli-1
run: signal-cli receive # This successfully retrieves messages for the registered number +123456789012
run: signal-cli send +123456789012 --note-to-self -m "Test message" +123456789012 # This sends a test message successfully.
Additional context
Port 8080 in the signal URL is the internal docker port number that signal-cli container listens on. This is correct, because if I choose a different port I get a SocketException.
Both signal-cli-signal-cli-1 and changedetection.io share the same docker network bridge so they can see each other, and anyway, I'd see a SocketException if that weren't the case.

Any help greatly appreciated with this issue. What am I missing? Why is a linked device ignored from external calls?

Thanks all.

### Are you using the latest released version?

- [ ] Yes

### Have you read the troubleshooting page?

- [ ] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

x86-64

**Comment by bbernhard** [comment]
Since you haven't ticked the checkbox: Do you use the latest version?

**Comment by dmindfuse** [comment]
Hi @bbernhard , thanks. The container runs with :latest and I removed and recreated it. 

When I checked just now:
- ENV shows "BUILD_VERSION=0.89",
- CLI says
root@a87f9172258e:/# signal-cli --version
signal-cli 0.13.7

Any ideas as to what I need to check/set?
Thanks

**Comment by bbernhard** [comment]
Do other endpoints work? e.g the `receive` endpoint?

**Comment by dmindfuse** [comment]
@bbernhard , good idea. Sadly, the response is the same. I tried from the docker host to the container:

`~$ curl -X GET http://172.19.0.4:8080/v1/receive/+1234567890
{"error":"User +1234567890 is not registered.\n"}`

**Comment by bbernhard** [comment]
Please try the [Debug Mode](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/DEBUG.md), which logs out the exact signal-cli commands that are executed. Since you mentioned that it works via the docker console, there must be a difference between the command you executed and the one the REST API wrapper is executing.

**Comment by dmindfuse** [comment]
@bbernhard ... Actually, both the API from host to docker container as well as the apprise test call from changedetection.io web-gui to docker container generate the same debug response in compose log. Before I did these, I took down compose and up-started it with output to stdout.

1. API from host -> docker container:

```
...
user@dock:~/signal-cli$ curl -X POST -H "Content-Type: application/json" -d '{"logging": {"level": "debug"}}' 
'http://172.19.0.4:8080/v1/configuration'
signal-cli-1  | [GIN] 2024/11/27 - 08:04:03 | 204 |      91.962µs |      172.19.0.1 | POST     "/v1/configuration"
user@dock:~/signal-cli$ curl -X POST -H "Content-Type: application/json"  --verbose -d '{"message": "Hello World!", "number": "+12345678901", "recipients": ["+12345678901"]}' 'http://172.19.0.4:8080/v2/send'
signal-cli-1  | time="2024-11-27T08:04:08Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
signal-cli-1  | time="2024-11-27T08:04:08Z" level=debug msg="*) docker exec -it / /bin/bash"
signal-cli-1  | time="2024-11-27T08:04:08Z" level=debug msg="*) su signal-api"
signal-cli-1  | time="2024-11-27T08:04:08Z" level=debug msg="*) echo 'Hello World!' | signal-cli --config /home/.local/share/signal-cli -a +12345678901 send --message-from-stdin +12345678901 --notify-self"
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=utf-8
< Date: Wed, 27 Nov 2024 08:27:24 GMT
< Content-Length: 51
< 
* Connection #0 to host 172.19.0.4 left intact
{"error":"User +12345678901 is not registered.\n"}signal-cli-1  | time="2024-11-27T08:04:10Z" level=debug msg="signal-cli output (stdout): "
signal-cli-1  | time="2024-11-27T08:04:10Z" level=debug msg="signal-cli output (stderr): User +12345678901 is not registered.\n"
signal-cli-1  | [GIN] 2024/11/27 - 08:04:10 | 400 |  2.453843018s |      172.19.0.1 | POST     "/v2/send"
```

2. changedetection.io web GUI "test notification" -> docker container (verbose not possible):

```
signal-cli-1  | time="2024-11-27T08:14:26Z" level=debug msg="If you want to run this command manually, run the following steps on your host system:"
signal-cli-1  | time="2024-11-27T08:14:26Z" level=debug msg="*) docker exec -it / /bin/bash"
signal-cli-1  | time="2024-11-27T08:14:26Z" level=debug msg="*) su signal-api"
signal-cli-1  | time="2024-11-27T08:14:26Z" level=debug msg="*) echo '<--cut a lot of text--> Example text: a lot more examples\n---' | signal-cli --config /home/.local/share/signal-cli -a +12345678901 send --message-from-stdin +12345678901 --notify-self"
signal-cli-1  | time="2024-11-27T08:14:28Z" level=debug msg="signal-cli output (stdout): "
signal-cli-1  | time="2024-11-27T08:14:28Z" level=debug msg="signal-cli output (stderr): User +12345678901 is not registered.\n"
signal-cli-1  | [GIN] 2024/11/27 - 08:14:28 | 400 |  2.592585289s |      172.19.0.5 | POST     "/v2/send"
```

On a side note, after docker down and docker up I had to relink my phone manually again. 
Not sure if that is normal behavior either.

For the record, inside the docker container command shell, things operate just fine, I received:

```
signal-cli -a +12345678901 send --note-to-self -m "Test" 
1732695252174
```

Hope this helps, I can't work out why this would not work. Thanks.

**Comment by tau-ri** [comment]
I have a similar issue where the directory for signal-cli-config is empty and I can not sent messages after some time as cli reply tells me my device is not registered.

this is my docker compose file:

```
version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      - MEM_LIMIT=128
      - MEM_STARTUP=1024
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8099:8080" #map docker port 8080 to host port 8080
    restart: always
    volumes:
      - "./signal-cli-config:/opt/dcc/signalcli/signal-cli-config/"

```

I think the volume mount is correct as just used from main repo page howto.

**Comment by bbernhard** [comment]
> I have a similar issue where the directory for signal-cli-config is empty and I can not sent messages after some time as cli reply tells me my device is not registered.
> 
> this is my docker compose file:
> 
> ```
> version: "3"
> services:
>   signal-cli-rest-api:
>     image: bbernhard/signal-cli-rest-api:latest
>     environment:
>       - MODE=normal #supported modes: json-rpc, native, normal
>       - MEM_LIMIT=128
>       - MEM_STARTUP=1024
>       #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
>     ports:
>       - "8099:8080" #map docker port 8080 to host port 8080
>     restart: always
>     volumes:
>       - "./signal-cli-config:/opt/dcc/signalcli/signal-cli-config/"
> ```
> 
> I think the volume mount is correct as just used from main repo page howto.

Your bind mount is wrong, see https://github.com/bbernhard/signal-cli-rest-api?tab=readme-ov-file#example for reference

**Comment by tau-ri** [comment]
Thanks @bbernhard, sometimes you can not see the forest because of all these trees there

**Comment by dmindfuse** [comment]
> > Not sure if that is normal behavior either.
> 
> That's definitely not normal. Are you sure that the signal-cli config is stored persistently on the filesystem and not just inside the docker container?
Depends, the sub-directory to the docker-compose.yml shows 
~/signal-cli$ ll signal-cli-config/
total 16
drwxr-xr-x 4 rto rto 4096 Sep  7 16:24 ./
drwxr-xr-x 8 rto rto 4096 Nov 30 15:02 ../
drwx------ 2 rto rto 4096 Sep  7 16:24 avatars/
drwx------ 2 rto rto 4096 Nov 21 16:05 data/

Nov 21 is not the last time I had to relink the phone.... But I don't know if a relink is re-writing accounts.json. Last time was 3 days ago.

> It looks like the main difference is, that you are invoking `signal-cli` without the `--config` parameter (the `--config` parameter specifies the path to the signal-cli config directory). So, I guess `signal-cli` then implicitly uses a different config directory and stores the linked device data there, instead of `/home/.local/share/signal-cli` (this is where the REST API wrapper looks for the configuration)

Well, I have no control over how changedetection.io submits the call using apprise. IMO, the default should ensure functionality and --config could be offered to those that have special needs, right?

Maybe I should just delete the directory and reclone, redo.. I'll try that.

**Comment by bbernhard** [comment]
The REST API container uses the `--config` parameter correctly - you don't have to change anything there. You only have to take care of that in case you directly invoke `signal-cli` directly from within the container (as you did). In that case you have to manually set the `--config` parameter accordingly.

**Comment by dmindfuse** [comment]
I see., But I get the same bad request response on API... so.. I'll just delete the project and redeploy it. Who knows what docker does wrong... ;)

**Comment by dmindfuse** [comment]
@bbernhard , actually the answer is simple: https://github.com/caronc/apprise/issues/1246#issuecomment-2526157628
But it was not immediately clear to me that API usage requires an API linked device. A link via CLI will not also work for the API methods. ;) It's operational now.
