### ISSUE TITLE
Dockerfile fails to build => Bump libsignal-client version to 0.62

### ISSUE THREAD

**Issue by mrmattwright** [bbernhard/signal-cli-rest-api#629]
### The problem

When running a `docker build .` (which I need to do to deploy to Fly.io) you get an error : 

```
90.17 ls: cannot access 'build/install/signal-cli/lib/libsignal-client-0.58.2.jar': No such file or directory
90.17 
90.17 
90.17 signal-client jar file with version 0.58.2 not found. Maybe the version needs to be bumped in the signal-cli-rest-api Dockerfile?
90.17 
90.17 
90.17 Available version: 
90.17 
90.17 build/install/signal-cli/lib/libsignal-client-0.62.0.jar
```

Which makes sense. So the binaries from ext/libraries/libsignal-client need to include 0.62.0

I actually tried to do that as per the readme : https://github.com/bbernhard/signal-cli-rest-api/blob/master/ext/libraries/libsignal-client/README.md

but got bogged down in rust errors - dunno how happy `cross` is running on an M1? Just a guess - but ran into issues there.

Just for interests sake here's the error 
```
  thread 'main' panicked at rust/protocol/build.rs:18:10:
  Protobufs in src are valid: Custom { kind: Other, error: "protoc failed: " }
```

I guess the ask is here for a bump to include the libsignal-client version v0.62.0 (note: not the latest) 
 

### Are you using the latest released version?

- [X] Yes

### Have you read the troubleshooting page?

- [X] Yes

### What type of installation are you running?

signal-cli-rest-api Docker Container

### In which mode are you using the docker container?

Normal Mode

### What's the architecture of your host system?

arm64

**Comment by bbernhard** [comment]
should build again

**Comment by mrmattwright** [comment]
Thank you sir! I had hoped to provide you a PR for that - in any case thanks for the turn around!
