### ISSUE TITLE
Addon: use of cli from console requires --config ..

### ISSUE THREAD

**Issue by ed-holland** [bbernhard/signal-cli-rest-api#64]
Used: AddOn 0.31

When using the the CLI from docker shell (as user signal-cli) one needs to set the config parameter. If not, you get this error:
`Error loading state file: /home/.local/share/signal-cli/data`

Providing the parameter `--option ..` will correctly use the \data\data directory.

Note: CLI commands get this message also
```
OpenJDK Server VM warning: You have loaded library /tmp/resource3526462944586254940.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

**Comment by bbernhard** [comment]
There's now some additional output on the cli which lets you know which `--config` directory you need to specify.
