### ISSUE TITLE
AddOn: Can not create group Failed to send message: Unable to parse entity

### ISSUE THREAD

**Issue by ed-holland** [bbernhard/signal-cli-rest-api#65]
AddOn: v 0.31

Trying to register a new group using the below curl (numbers redacted):
```
curl -X POST -H "Content-Type: application/json" -d '{"name": "Home Assistant Alerts", "members": ["+49<...>"]}' 'http://pi-hassio:8080/v1/groups/+49<...>'
```

Error:
`{"error":"OpenJDK Server VM warning: You have loaded library /tmp/resource10076316106301360679.so which might have disabled stack guard. The VM will try to fix the stack guard now.\nIt's highly recommended that you fix the library with 'execstack -c \u003clibfile\u003e', or link it with '-z noexecstack'.\nFailed to send message: Unable to parse entity\n"}`

Tried also with a name without blanks but that does not seem to be the problem. Any idea why this is happening?

Extra:
Tried to create the group directly using the command shell (docker) and received the same result.

**Comment by bbernhard** [comment]
Have a look here: https://github.com/bbernhard/signal-cli-rest-api/issues/54

**Comment by ed-holland** [comment]
Thx, did not see that one. Will switch to the bbernhard/signal-cli-rest-api:0.47-dev and try again.

**Comment by ed-holland** [comment]
With the bbernhard/signal-cli-rest-api:0.47-dev i was able to create the group (after updating name). 

Thanks again and keep up the good work.
