### ISSUE TITLE
group invite

### ISSUE THREAD

**Issue by joseftsch** [bbernhard/signal-cli-rest-api#68]
Hey!

I create a new group on my mobile (android) and invited my "signal cli rest api"-phone/contact.
Signal just tells me that the contact can not automatically be added to the group but receives an invite to join the group.
Running `curl -X GET -H "Content-Type: application/json" 'http://signal.signalhost.lan/v1/groups/+43xxxxxxx'` just returns an empty json.

What am I doing wrong? How can Signal-cli accept an invite?
Thanks!

**Comment by joseftsch** [comment]
Addition, I update the profile (at least with a description) and I just found that this might be related to "updateGroup" flag of signal-cli.
`updateGroup
Create or update a group. If the user is a pending member, this command will accept the group invitation. To be able to join or create a v2 group the account needs to have a profile (can be created with the updateProfile command)`
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc

**Comment by bbernhard** [comment]
Confirming a group invitation is unfortunately not yet exposed via the REST API. However, it's possible to manually run `signal-cli` inside the docker container. If you do so, don't forget to explicitly set the config directory before executing any command. If you are using the normal docker image it's `signal-cli --config /home/.local/share/signal-cli/ ...` or in case you are running the HASSIO addon it's `signal-cli --config /data/data ...`.

**Comment by joseftsch** [comment]
Thank you @bbernhard this solved my issue :)
Would be great if you could expose this option via api as well sometime in the future.
