### ISSUE TITLE
Docker  signal-cli-rest-api on windows 10

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [bbernhard/signal-cli-rest-api#69]
is it possible to run with windows client and docker? I am trying more without success

**Comment by x-jokay** [comment]
There is currently no container for for Windows on Docker Hub available, see [here](https://hub.docker.com/search?q=signal-cli&type=image&operating_system=windows).

**Comment by DiegoLimeiradaSilva** [comment]
ok. obrigado
