### ISSUE TITLE
Add support for voice registration

### ISSUE THREAD

**Issue by Export33** [bbernhard/signal-cli-rest-api#7]
The [signal-cli](https://github.com/AsamK/signal-cli) supports voice registration for landline numbers. Can you add the `--voice` command? 

When i register myself in the shell
`docker exec -it signal-cli-rest-api sh`
`signal-cli -u +49xxxxxx register --voice`

i get an authorization error during the verification using the rest service:
[{"error":"Authorization failed, was the number registered elsewhere?\nError loading state file: Authorization failed!\n"}](url)

**Comment by bbernhard** [comment]
latest version should be capable of voice registration.

**Comment by Export33** [comment]
Thanks this worked.

I still had the authorization error. Deleting the data folder helped.
