### ISSUE TITLE
Registering to signal-cli log me out from my phone/desktop

### ISSUE THREAD

**Issue by pumbaa666** [bbernhard/signal-cli-rest-api#70]
When I register to signal-cli it logs my account out from the app on my phone, and therefore from the desktop application too.
No more message are retrieved.
Is it the expected behavior ?

```
# register
myPhoneNumber=+41769998877
header="Content-Type: application/json"
url="http://127.0.0.1:8080/v1/register/$myPhoneNumber"
curl -X POST -H "$header" $url

# send verification code
code=123-456
url="http://127.0.0.1:8080/v1/register/$myPhoneNumber/verify/$code"
curl -X POST -H "$header" $url

# send message to a contact
url="http://127.0.0.1:8080/v2/send"
writeToNumber=+41762223344
curl -X POST -H "$header" -d '{"message": "'"$message"'", "number": "'"$myPhoneNumber"'", "recipients": ["'"$writeToNumber"'"]}' $url
```

Message is sent, but now I'm logged out from the app and get this message : "Device no longer registered. This is likely because you registered your phone number with Signal on a different device. Tap to re-register"

And when I re-register and try to send a message again 
```
# send message to a contact
url="http://127.0.0.1:8080/v2/send"
writeToNumber=+41762223344
curl -X POST -H "$header" -d '{"message": "'"$message"'", "number": "'"$myPhoneNumber"'", "recipients": ["'"$writeToNumber"'"]}' $url
```

I get this : "Authorization failed, was the number registered elsewhere"

Can I not use my main (and only) phone number to send message from the cli ?

**Comment by bbernhard** [comment]
Per default it is assumed that you will use a dedicated phone number for the API. In case you don't want to do this, you can try linking your device. I have no experience with that, but others have sucessfully done that. see here: https://github.com/bbernhard/signal-cli-rest-api/issues/35

and here: https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)

There's the `qrcodelink` REST API endpoint which generates a QR code for linking with the Android Signal app.

**Comment by pumbaa666** [comment]
Ok thanks.
I also tested directly from the signal-cli api and the behavior is the same.
I'll use a dedicated phone.
