### ISSUE TITLE
Signal send sticker

### ISSUE THREAD

**Issue by giggslam** [bbernhard/signal-cli-rest-api#72]
Is it possible to send a Sticker? thanks.

**Comment by bbernhard** [comment]
Sending stickers is unfortunately not possible. I am not sure if `signal-cli` even supports that right now (see [man page](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc)). In case you find the functionality somewhere in `signal-cli` it's also possible to make it accessible via the API.

**Comment by giggslam** [comment]
noted.
thanks a lot.
