### ISSUE TITLE
using joinGroup from signal-cli

### ISSUE THREAD

**Issue by soleous** [bbernhard/signal-cli-rest-api#76]
Hi Guys,

I've probably caused myself a whole heap of mess with this but!  I've using HA with Node Red.  I have flows setup, which are working to send messages to individual users using the home assistant entities.

I am wanting to join my signal account for HA to already created groups.  I've dipped into the docker container and ran commands to updateProfile and joinGroup.  It all works fine from cli, I can send messages to the group.  When I move over HA and configure a recipient using the group id (group.), I get the following error:

Call-service API error.  Error Message: Failed to send message: User is not a member in group: null (Internal_ID).

I assume this is a difference between the siginal-cli and REST API because of the ID group.

Is there another way to joinGroup using the rest API and the URI's?

Thanks,

**Comment by VooPoc** [comment]
I restarted the container and it started working...

**Comment by bbernhard** [comment]
The latest version (0.34) now contains API endpoints to join/block/quit Signal Groups.

**Comment by VooPoc** [comment]
oh wow, thanks dude. I'll check it out
