### ISSUE TITLE
Not able to create groups

### ISSUE THREAD

**Issue by kaizersoje** [bbernhard/signal-cli-rest-api#77]
I'm running latest stable home assistant on latest homeassistant os, installed this addon from the repository.

I was able to register a phone number. However, when i try to create a group using (numbers obfuscated):

`curl -X POST -H "Content-Type: application/json" -d '{"name": "Hassio", "members": ["+61XXXXXXXX"]}' 'http://127.0.0.1:8080/v1/groups/<my_number>'`

I get the following error: `{"error":"Cannot create group - please first update your profile."}`

Am I doing something wrong?

**Comment by sandersdc** [comment]
Hi @kaizersoje ,

Before creating your group you will need to update your profile by running the following:

curl -X PUT -H "Content-Type: application/json" -d '{"name": "your name"}' 'http://127.0.0.1:8080/v1/profiles/+61XXXXXXXXX'

**Comment by kaizersoje** [comment]
Thanks, it worked. I reckon this should be mentioned in the Readme section.
