### ISSUE TITLE
trusting number returns 

### ISSUE THREAD

**Issue by ed-holland** [bbernhard/signal-cli-rest-api#81]
Was able to retrieve a list of identities. It stated that one number was TRUSTED_UNVERIFIED.

Used the curl PUT with /v1/identities/+49.../+49176... and received '404 page not found'

Image used: 2021-01-29 17:00:15

**Comment by bbernhard** [comment]
there was an error in the swagger documentation. The API call should be: 

`curl -X PUT -H "Content-Type: application/json" -d '{"verified_safety_number": "<safety-number>"}' 'http://127.0.0.1:8080/v1/identities/<your-signal-number>/trust/<number-to-trust>'`
