### ISSUE TITLE
Update profile does not allow for blanks in the name

### ISSUE THREAD

**Issue by ed-holland** [bbernhard/signal-cli-rest-api#82]
Wanted to update the name of the sender using

curl: PUT and data `'{"name": "Home Assistant", "base64_avatar": ""}'`

In debug mode the command was issued in this way:
`signal-cli --config /data/ -u +49*** updateProfile --name Home Assistant --remove-avatar`
resulting in an error message

The following was successful:
`signal-cli --config /data/ -u +49*** updateProfile --name 'Home Assistant' --remove-avatar`

small issue ;-)

**Comment by bbernhard** [comment]
Should be working - please re-open in case the issue still exists.
