### ISSUE TITLE
Delay on sending messages

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#83]
We are using signal-rest-api for sending the messages with " --dbus " option
Internally signal-rest-api calling the signal-cli command, we are getting a delay of 3 - 8 sec while sending the messages.
Can you please let us know how can we reduce the send delay time to less than 1 sec.

**Comment by bbernhard** [comment]
This project doesn't support DBUS. If you want to use the DBUS interface, please use https://github.com/AsamK/signal-cli directly.
