### ISSUE TITLE
curl: failed to connect ... connection refused

### ISSUE THREAD

**Issue by dTrimon** [bbernhard/signal-cli-rest-api#85]
Hello.
First I'm pretty new to home assistant, so apologize If I made a mistake here.
I've installed your add-on through Install Home Assistant Add-on.
And tried different Port . But I always get this curl message  "FAiled to connect  connection refused"

I installed a ssh add on and issued a netstat:

no listening on the configured port

```
here is the add on log:
+ set -e
+ export SIGNAL_CLI_CONFIG_DIR=/data/data
+ chown 1000:1000 -R /data/data
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 37
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37 signal-cli-rest-api -signal-cli-config /data/
time="2021-02-06T00:35:07+01:00" level=info msg="Started Signal Messenger REST API"
```
thansk for your help

**Comment by bbernhard** [comment]
According to the log snippet you posted, the docker container seems to be running fine. 

> I installed a ssh add on and issued a netstat:

so, if you do something like `netstat -tulpen | grep 8080` it shows that no service is running listening on that port?

Are you sure you are running the curl command with the correct IP? (If you are using `127.0.0.1` as IP, you need to run the command on the same machine the docker container is running on)

**Comment by dTrimon** [comment]
Sorry for the late reply. Indeed nothing come out the netstat command on port 8080
I tried to change the port but nothing happen.
I'm not familiar with home assistant . i've donladed an ISO and burn my SD card, put it in a raspberry pi!
After I don't really know how it works!
Maybe the docker is runing elswhere. How can I know?

**Comment by bbernhard** [comment]
Unfortunately I am not familiar with Home Assistant addons - so I do not how Home Assistant manages those under the hoods. I am using the docker container directly, instead of using the Home Assistant addon. But the HA addon is really well maintained by @haberda and used by quite a few people already - so I guess it's most probably something on your end. Are you sure that the addon is running?

**Comment by haberda** [comment]
Under the configuration tab you should see Network settings which allow you to expose the desired port. By default the exposed port is 8080 on both the container and the add-on. So unless you changed it is should work. I try and test on both an x86 setup and a Pi. Works fine on both for me. 

I tried that netstat command on my production machine and got this result:

`tcp6       0      0 :::8080                 :::*                    LISTEN      0          26088895   -`

**Comment by chrugel** [comment]
Hi,
I seem to have the exact same issue as @ dTrimon.
The log from the addon:
```
Native mode
0
AUTO RECEIVE SCHEDULE
0 22 * * *
+ set -e
+ [ -z /data ]
+ chown 1000:1000 -R /data
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/data
time="2021-06-12T23:45:42+02:00" level=info msg="Started Signal Messenger REST API"
```
Netstat in Hassio ssh shell:

```
~ $ netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 core-ssh.local.hass.io:8099 hassio:50338            ESTABLISHED 
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node Path
unix  3      [ ]         STREAM     CONNECTED     260639 /tmp//tmux-0/default
unix  3      [ ]         STREAM     CONNECTED     258622 
~ $ 
```

And i then get this error:

```
~ $ curl -X POST -H "Content-Type: application/json" '127.0.0.1:8080/v1/register/+4795522083'
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
~ $ 
```

**Comment by haberda** [comment]
The Hassio ssh shell does not necessarily translate 127.0.0.1 to your machine loopback, The loopback stays in the shell container. I would suggest using the actual machine ip address in place of the loopback.

**Comment by chrugel** [comment]
Thank you so much, that worked!

**Comment by nicolas-sora** [comment]
Hi guys. Can I humbly suggest this specific issue is added to the original documentation for future users :)
