### ISSUE TITLE
Unable to save config as a configmap in kubernetes

### ISSUE THREAD

**Issue by vavallee** [bbernhard/signal-cli-rest-api#86]
Looking for some suggestions.

I loaded your container in k3s/kubernetes and it works lovely! Of course, I am not using persistent volumes, and don't want to. I was hoping to load the configs into a configmap or secret, but because the configs are stored in a file with the phone number and a "+" symbol, the name is not valid. Any suggestions how I can load the configs into a configmap/secret so that I can mount them into the container?

```
kubectl create configmap signal-data --from-file=signal-restapi/+12000000000
error: "+12000000000" is not a valid key name for a ConfigMap: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

**Comment by bbernhard** [comment]
Unfortunately, I do not know anything about kubernetes. I've read up a bit on kubernetes' configmap and if I understood it correctly, that's just some key/value pairs? Not sure if it's a particularily good idea (or even possible), but could you maybe encode the key somehow? 

At first I thought about base64 here, but as it contains `=` it probably won't work here. But there seem to be other encodings out there which only use alpha numeric characters (like the `z-base-32` encoding). If you can encode the key before writing it to the configmap and then decode it again when reading the value again from the configmap, I _think_ it could work. But as I said, I do not know anything about kubernetes, so not sure if this is even a viable approach ;)

**Comment by vavallee** [comment]
Thanks for your comment. I haven't found a solution unfortunately, I may just go ahead and use a persistent volume for the time being.

**Comment by mfw78** [comment]
@vavallee From what I've seen so far with my limited experience around `signal-cli`, the configuration file is often written to and updated, therefore this is likely to necessitate the requirement of a `PersistentVolume`. 

I think likely if you wanted to go down this route, the best option would be to have the maintainer of `signal-cli` abstract out the cryptographic components from the user configuration, such that these were loaded from a subdirectory (like +1234567890.secrets). The keys within there could then be abstracted away in Kubernetes secrets, no problems.

An alternative may be a PodLifecycle control on the pod such that when the pod shuts down it fires a script (Python for example would be able to do this, relatively easily) that would then take the latest user configuration file and override the `ConfigMap` that is stored on the K8S master. I'm unsure of how the pod lifecycle would affect things like rolling updates etc, which may cause you some issues as it rolls.
