### ISSUE TITLE
Captcha  error while registering a number

### ISSUE THREAD

**Issue by jyothisjose** [bbernhard/signal-cli-rest-api#89]
On registering a phone number with signal, we are getting following error

**{"error":"Captcha invalid or required for verification (null)\n"}.**

We are using **curl -X POST -H "Content-Type: application/json" 'https://127.0.0.1:8080/v1/register/v1/register/+PHONE_NUMBER_COUNTRY_CODE'**

**Comment by horizonchasers** [comment]
I have this same issue currently.  I installed it using Home Assistant and I also installed it on a dedicated container in my docker environment.  Same response {"error":"Captcha invalid or required for verification (null)\n"}. both times.

**Comment by bbernhard** [comment]
> I have this same issue currently. I installed it using Home Assistant and I also installed it on a dedicated container in my docker environment. Same response {"error":"Captcha invalid or required for verification (null)\n"}. both times.

Looks like that you need to provide a `captcha` (see details here: https://github.com/bbernhard/signal-cli-rest-api/issues/19)

**Comment by Cempakers87** [comment]
That's true. You must provide captcha
`curl -X POST -H "Content-Type: application/json" --data '{"captcha": "<captcha>"}' 'http://127.0.0.1:8080/v1/register/+1234567890'`

**Comment by jyothisjose** [comment]
We have used captcha from https://signalcaptchas.org/registration/generate.html and
executed following command.

_curl -X POST -H "Content-Type: application/json" --data '{"captcha": "03AGdBq263LoI21mz7kUvZRp_WuzeIDjG-zo2v7QF_R4-GeJEYUtq1OqlKuBqNVONxe3-Kxt8E4v12TuiIkylLCzPBba6GUm-bpTqWVbfJ97ecjBg_52iZ9Q9XrOMBXdO0ORuFSL-vNS9Z57e9xM6RMXFxLTHEcJiXoROlVvnrw1TxX-punYMpivgy-naQrNE3LjmOj1vKgMiRtN1aNFEwSaJ_zPLcAX8sZtKfMpnjtq5Wr1rGp9DIBB0xGir7AyyfnFZmiGAW5TIfI5etMKmpg6V1or3ekF4Ft3lLEy77uyPuLD3wHd59FyfJAFFHFqnYJV5Y8jnU0jIY8C_LgzQImh6HqGIav8kNK6V1140XuGCdkLNASS_gU8AFQtzrEGM2RW3tilxDm6vKlvHnI9r8Sc6O6iDSXbSqhX8bhPKSUxMGiekPFqAqmD3KyAjSoKCCOyzmiEvV1OIIwkZsehCvKu7P2nINBy4Tjw"}' 'http://127.0.0.1:8080/v1/register/+91xxxxxxx'_

Still we are getting same error
**{"error":"Captcha invalid or required for verification (null)\n"}j**

Can you please help us to solve registration issue?

**Comment by Cempakers87** [comment]
@jyothisjose how many times have you tried your command above? just once or more? mentioned here https://github.com/bbernhard/signal-cli-rest-api/issues/19#issuecomment-772827785 that he tried 4-5 times. Hope that helps.

For me, I try with succes on my first time.

**Comment by EJansenMSFT** [comment]
This is the closest that I've been thus far:

I just don't know what syntax I'm messing up.  Here's the latest Captcha:

![image](https://user-images.githubusercontent.com/72317762/110259176-63aabd80-7f74-11eb-888e-06d2712f95df.png)

Here's the latest attempt, which says that the captcha is invalid trying it with and without the //:

![image](https://user-images.githubusercontent.com/72317762/110259210-82a94f80-7f74-11eb-89c2-6ccfa8347806.png)

![image](https://user-images.githubusercontent.com/72317762/110259865-cd789680-7f77-11eb-8b6d-565dcd05c3ea.png)

Thanks for any guidance that anyone has!

**Comment by fanuch** [comment]
I've been hopping around from project to project but I do not think any of them require `signalcaptcha://` 

Try only the character after `signalcaptcha://` that is `"signalcaptcha://<this only>"`

Make sure you are using a recent captcha too.

On mobile so I can check later in practice

**Comment by EJansenMSFT** [comment]
Awesome, I'll try it out in about an hour and post back.  Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EJansenMSFT** [comment]
Unfortunately, if I do it without the prefix, it fails with the following error:

![image](https://user-images.githubusercontent.com/72317762/110262532-0453aa00-7f82-11eb-89df-c1e765d3bddd.png)

In looking at the error on the container, it shows the following:

![image](https://user-images.githubusercontent.com/72317762/110262586-2b11e080-7f82-11eb-9f4f-ae9d88bc343e.png)

So it at least sees it as a key.  I tried a few things after that, based on the error, but nothing seemed to work.  Closer at least.  Any suggestions?

Thanks,
Eric

**Comment by fanuch** [comment]
> That's true. You must provide captcha
> `curl -X POST -H "Content-Type: application/json" --data '{"captcha": "<captcha>"}' 'http://127.0.0.1:8080/v1/register/+1234567890'`

@EJansenMSFT mate... You didn't follow the JSON structure as per this....

The "value" in "key:value" pair is the captcha. You are missing `"captcha":`

Also, if you are using single quotes (`'`) pretty sure you do not need to escape the double quotes (`"`) i.e. don't so `/"`

But definitely wrong with out the key`"captcha":` before your captcha

**Comment by EJansenMSFT** [comment]
I had '{"captcha": "<captcha>"}'  a few posts up and I my understanding of what you said was to not use the key.  I really don't know because yesterday was literally the first time I've ever used curl before.  If I don't escape the double quotes, I get this error:

![image](https://user-images.githubusercontent.com/72317762/110286149-6e844300-7fb2-11eb-84f3-f6a1dd792ff1.png)

![image](https://user-images.githubusercontent.com/72317762/110286194-822fa980-7fb2-11eb-8bb2-152132d38e91.png)

If you were to modify the following, what would you change?

curl -X POST -H  "accept: application/json" -H "Content-Type: application/json" --data '{"captcha":"03AGdBq25uKao8EWXvnhILvYnRf4hGQPI7-FBdF8iIZ_ChgkesTMt2iuzqxgZHjEfv_gGerR6WlaWCQlep48Mforf-zB1NjTPR3KaSOejI0q5imeD0qkc-DuU6nLWqticD_orvyVvWBWWprevHGJ336gcqzjETBKM1xsvF6AnL3lrjVC0pbcgUX_ycwWUAZ4PB7yt2YJ-ZG53Ja6h5KA8oHNfZk2gED3WBtY1lOXcutVwrUA1VG24l-YooV3aM6hrzsARD9Iw6O7ciKaDUOo_Vy3YQOX6RsFnnRInT1Jz1L0PJcT3Nhu_kYKPdJN8rur_ivj5iezwwpkYM6llRd53XVC12uQwW7-F6vCllGep4R-7OI9FLSkjiEIj-kwbr1hve4a6CRXYPpbH6szdPd9Fe-UsLR-PilE1bpVcT0MheJipV5rW2lp42-6NzRdZ6ztPSgXIOrL_XEjyH5F9d8EOeWxpdw5RpbICBrA"}' 'http://127.0.0.1:8080/v1/register/+1...........'

Cheers,
Eric

**Comment by fanuch** [comment]
@EJansenMSFT I copy and pasted what you have above with nothing more than my number and a new captcha and it worked.

___

It's making a bit more sense to me. You are on PowerShell making the request. I have to  assume it is not as standard as *nix CuRL.

Recommendation for you to make this less error prone and more repeatable:

1. Download [Postman](https://www.postman.com/downloads/)
2. Click on "**Import**" on the top
3. Click on "**Raw text**" at the top
4. Paste in the following:
5. ```curl -X POST -H "Content-Type: application/json" --data '{"captcha": "<captcha>"}' 'http://127.0.0.1:8080/v1/register/+1234567890'```
6. Click "**Import**" again to accept
7. In the top bar, edit your number to replace the `+1234567890`
8. Directly under that click the tab that says "**Body**"
9. Go get a new Captcha from https://signalcaptchas.org/registration/generate.html 
10. Look at the Debug Tools (console) and copy `<captcha>` from `"signalcaptcha://<captcha>"` (do not copy the quotes or beginning of the URI!!)
11. Paste it in to replace the `<captcha>` in the body `{"captcha": "<captcha>"}` (make sure you leave the double quotes!!!)
12. Click "**Send**" in the top right
13. If successful, you should see nothing returned and "**Status 201 Created**"

<img width="666" alt="image" src="https://user-images.githubusercontent.com/4865267/110297217-59a5bf00-8047-11eb-992f-025006f29632.png">

**Comment by EJansenMSFT** [comment]
Thanks for the detailed write up.  Definitely appreciate you!

I tried it a few times, but it doesn't want to play nice.  Here's the latest captcha and screenshots from Postman and the Container:

![image](https://user-images.githubusercontent.com/72317762/110360062-3dd0f780-800c-11eb-839a-84b74f2cf33f.png)

![image](https://user-images.githubusercontent.com/72317762/110359953-1e39cf00-800c-11eb-8ad7-53bda86dbad1.png)

![image](https://user-images.githubusercontent.com/72317762/110360223-7375e080-800c-11eb-8a5e-562167fd653f.png)

I'll keep playing with it.

Thanks again!

**Comment by bbernhard** [comment]
Do you see any output in Postman after executing the API call? Besides the `400` status code, there should also be an error message returned from the REST API.

**Comment by EJansenMSFT** [comment]
Hmm, I tried it a few more time, and generated a new captcha, and now it worked.  No further changes. 

![image](https://user-images.githubusercontent.com/72317762/110362641-8342f400-800f-11eb-8cfc-d2046427fe3e.png)

Have no idea why it all of the sudden worked.

**Comment by EJansenMSFT** [comment]
If the attempt fails using a captcha one time, should I have been generating a new captcha every single time?  If so, maybe that's part of it.

**Comment by bbernhard** [comment]
> If the attempt fails using a captcha one time, should I have been generating a new captcha every single time? If so, maybe that's part of it.

Creating a new captcha is definitely recommended!

I don't know the details about the captcha handling mechanism on the server side, but if I would implement something like this, I would probably set a pretty short expiration date to prevent abuse by scripts. So, one problem could have been that you just were too slow.

**Comment by EJansenMSFT** [comment]
> .

![image](https://user-images.githubusercontent.com/72317762/110364353-a79fd000-8011-11eb-9fe1-cd64ba10a9e7.png)

No errors that I could see.

**Comment by bbernhard** [comment]
> No errors that I could see in Postman or on the Container.

That's strange. I've checked again in the sourcecode: The error isn't logged (so you won't see it in the container log file), but should be reported back via the REST API. But as it has worked now for you, I guess it was just some error from the Signal Server telling you that the captcha was wrong.

**Comment by EJansenMSFT** [comment]
I did get a text message to my phone with the six digit pin, but the pin fails :(  

How many times can I attempt to use the pin before I have to try to re-register my phone to get a new pin?

Is the syntax correct?



Thanks!

**Comment by bbernhard** [comment]
> I did get a text message to my phone with the six digit pin, but the pin fails :(
> 
> How many times can I attempt to use the pin before I have to try to re-register my phone to get a new pin?
> 
> Is the syntax correct?
> 
> Thanks!

I've removed your screenshot, as you've accidentally leaked your phone number.

Are you sure that you need to set the `pin`? Or in other words: Are you using a new SIM card or was it already in use with Signal?

**Comment by EJansenMSFT** [comment]
Ah whoops, preciate that.   Yeah the phone is already registered with Signal.

**Comment by bbernhard** [comment]
> Yeah the phone is already registered with Signal.

Is the number still in use? Signal doesn't allow the number to be registered on multiple devices. So, if there's already a client (e.g your smartphone) using the number, you either have to use a dedicated SIM card for the REST API (personally I find that the better option) or link your device (there's a dedicated REST API endpoint for linking devices).

In case the number was previously used by another client, but is not anymore you are good to go.

**Comment by EJansenMSFT** [comment]
Yeah the number is still in use.  Right now I'm just testing the functionality, so I'd have to go buy another sim.  Hmm, so how can I register container / device?  Essentially what I want to do is write PowerShell wrappers around everything so I can send secure notifications for something like a network outage etc.

**Comment by bbernhard** [comment]
> Yeah the number is still in use. Right now I'm just testing the functionality, so I'd have to go buy another sim. Hmm, so how can I register container / device? Essentially what I want to do is write PowerShell wrappers around everything so I can send secure notifications for so mething like a network outage etc.

I do not have any experience with linking devices, so I most probably can't help you troubleshoot in case you are running into problems. But there are some people out there that have successfully linked their devices.

It basically works like this:
* Open the following URL in the browser: `http://127.0.0.1:8080/v1/qrcodelink?device_name=mydevice`
* Scan the generated QR code in the Signal Android App

See also this thread here: https://github.com/bbernhard/signal-cli-rest-api/issues/35

**Comment by EJansenMSFT** [comment]
That goes back to my original issue, where though I can use curl, I can't actually connect using the browser for some reason:

![image](https://user-images.githubusercontent.com/72317762/110371529-1a617900-801b-11eb-952b-0f9567f7982c.png)

**Comment by EJansenMSFT** [comment]
Disregard, got the curl equivalent working and it generated a QR code.

**Comment by EJansenMSFT** [comment]
Unfortunately when I try to link the device in Signal from my cell phone, it just gives a network error.

**Comment by EJansenMSFT** [comment]
I found another phone to use though that's not registered with Signal :)

**Comment by EJansenMSFT** [comment]
So i registered the new number just fine and I added the number as a contact to my phone, and invited the new number to join a group, but how can I programmatically accept the invite?  I guess the better question is how do I know what the group ID is?

**Comment by poudenes** [comment]
after last update I must reregister my number:

```
root@ha:/var/log# curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/register/+MY NUMBER'  
{"error":"Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"}root@ha:/var/log#
```

```
root@ha:/var/log# curl -X POST -H "Content-Type: application/json" -d '{"captcha":"03AGdBq25HWvcvFF1FfyR8ukURWy94H73t1Y_Phwj54wPWpF5hCyK3LTaTSptn5r2c3obXWNXfGvCDCg5hZe6gssDURFaKtZlLYIb9OLoE6ifoD657mSUdpA0xw7cvKjgAd5-VnRL-fbkXHOW28Rypoc-9Q49QjxRL7AMPENTFRbj-TBBzKahfvlHu2WEphZPiUj3FW7tlGSTVn6JNHMC9_K5nFednZMHqdW72OzyHcE3gueMc_SiTinvUYrVVUtnRpX0Zj9_PRCiSRY-lyJjq41LeEXRldjtZIgNwLPySOOz8bQs15VVGAFhHS82Ry71ilrwdLurB2pP3WBwkEDFJiHZKZbOCIcrHZjSlKsZgtDmfrbYqAJJtFMrj8aPVPsqkKW6I56zUhvue2Qt2rsBSMI0_mznU8yjtX9To-wgPgfB3DrKlY46jfXvJ2DoRZz-qCD-y1wGwTfstTTBSRRZ_J0yjdEhcPyrEIA"}'  'http://127.0.0.1:8080/v1/register/+MY NUMBER'
root@ha:/var/log# 
```

No errors.
But when I want send a message in log I see this:

`2021-03-14 21:07:18 ERROR (SyncWorker_28) [homeassistant.components.signal_messenger.notify] ERROR App - User +MY NUMBER is not registered.`

**Comment by bbernhard** [comment]
Have you verified the registration with the verification code you received via SMS?

**Comment by poudenes** [comment]
> Have you verified the registration with the verification code you received via SMS?

ahh that was last part I forgot! Thanks

**Comment by bbernhard** [comment]
Should be fixed. Please re-open in case it's still an issue.
