### ISSUE TITLE
Feature link devices 

### ISSUE THREAD

**Issue by FabioPinheiro** [bbernhard/signal-cli-rest-api#9]
It would be great to support the feature of linking devices so we can use my number.

The signal-cli already supports this. So I enter on the docker container instance.
`docker exec -it -u 0 NameOfContainer bash`
and generate the link code `signal-cli link -n "signal-laptop"`
It generate +- a String like this `tsdevice:/\?uuid=asdfghjkl\&pub_key=qwertyuiop`

Then I generate a picture (QR-Code) with https://linux.die.net/man/1/qrencode
`qrencode -o linkqr.png tsdevice:/\?uuid=asdfghjkl\&pub_key=qwertyuiop`
Which I scan with my Android device

After that, I was able to send messages via `signal-cli` from inside of the container instance. (Too good to be true.) When I call the API (`signal-cli-rest-api`) it did not work as I wanted, it gave some errors.

I never tried to write in go. So I don't know if I'm going to try to do this.
Also, I don't really need it. Was just playing around here.

This API makes really easy to integrate other stuff.
Thanks @bbernhard

**Comment by bbernhard** [comment]
Many thanks for the kind words :)  

I'll definitely have a look at this - thanks for bringing this up. Also thanks for the detailed ticket, very much appreciated! 

I am not sure when I'll find time to have a look at this. If you/anyone else needs this feature urgent, please bump the thread, then I'll try to prioritize this feature higher :)

**Comment by Loki321** [comment]
Would really like this too, I have linked my number with signal-cli and can send using the command line from within the container but when using the REST API it returns:
{"error":"User is not registered.\n"}

**Comment by redoules** [comment]
Hi. I had the same problem with the docker image. I solved it by copying the /root/.local/share/signal-cli/data/ directory to  /home/.local/share/signal-cli/data

**Comment by Loki321** [comment]
> 
> 
> Hi. I had the same problem with the docker image. I solved it by copying the /root/.local/share/signal-cli/data/ directory to /home/.local/share/signal-cli/data

Thanks for that. I hadn't realised it was storing the config elsewhere, makes sense as I was logged in as root.

**Comment by danijelst** [comment]
Thanks @FabioPinheiro 
I have successfully linked my device without any further problems by just removing the -u 0 from your script and also pass the config path like the signal-cli-rest-api does:

```
docker exec -ti <your_container_name> bash

signal-cli --config "/home/.local/share/signal-cli/" link -n "<name_of_device_to_be_linked>"
```
as you wrote, copy the provided `tsdevice:` URI and converted it with qrencode and scanned it with my Signal App.

**Comment by FabioPinheiro** [comment]
@danijelst  Are you able to call the signal-cli-rest-api we no problem?

**Comment by danijelst** [comment]
@FabioPinheiro yes, after the linking, the rest calls are working like expected.

**Comment by binarylimited** [comment]
Linked to my Signal fine... but when i input http://127.0.0.1:8080/v1/groups/+78123546987 

the output is : []

**Comment by bbernhard** [comment]
> Linked to my Signal fine... but when i input http://127.0.0.1:8080/v1/groups/+78123546987
> 
> the output is : []

Have you tried calling the `receive` endpoint first?
