### ISSUE TITLE
Unable to send message to group I am a member of

### ISSUE THREAD

**Issue by vavallee** [bbernhard/signal-cli-rest-api#91]
Hi,

My account became deregistered and I went ahead and reregistered it without issue.
However now I am unable to send to the group I was a member of.

I can list the group fine with

`curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/groups/+10000000000'`

returns

`[{"name":"group1 Notifications","id":"group.77777777777777777777777777777777","internal_id":"11111111111111==","members":["+10000000000","+11111111111","+12222222222","+13333333333"],"blocked":false,"pending_invites":[],"pending_requests":[],"invite_link":""}]`

When I use the group id above, the call always returns "null"

```
curl -X POST -H "Content-Type: application/json" -d '{"message": "Ignore test", "number": "+10000000000", "recipients": ["group.77777777777777777777777777777777"]}' 'http://127.0.0.1:8080/v2/send'
```
`null`

In the logs it looks like both the GET and POST calls are getting 20x response

```
[GIN] 2021/02/12 - 03:03:48 | 200 |     160.107µs |       10.42.1.1 | GET      "/v1/about"
[GIN] 2021/02/12 - 03:03:56 | 201 |  7.721459399s |       10.42.1.1 | POST     "/v2/send"
```

**Comment by vavallee** [comment]
I also created a new group, that was successful. But sending a message to it also returns null.

**Comment by bbernhard** [comment]
> I also created a new group, that was successful. But sending a message to it also returns null.

That "null" return message is unfortunately a bug which will be fixed with the next release. As long as you get a response with a 2xx status code, everything is fine.

**Comment by vavallee** [comment]
I am not sure what was causing this. When I sent messages, the logs reported 20x but the messages were not sending. In the end I gave up and just created a new group and it's working fine now.

This was all because I hadn't setup a persistent volume for the pod, which I've now remedied. thanks!
