### ISSUE TITLE
super slow sending?

### ISSUE THREAD

**Issue by malfino** [bbernhard/signal-cli-rest-api#94]
Hi, I just installed your api and got everything working. 
But what makes me very unhappy is the time, it takes to send a message.

On a raspberry pi4 with 8gb ram it looks like that:

```
$ time curl -X POST "http://127.0.0.1:8080/v2/send" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{   \"message\": \"string\",  \"number\": \"+xxxxxxxxxxx\",  \"recipients\": [    \"+xxxxxxxxxxxx\"  ]}"
null
real	0m8.747s
user	0m0.013s
sys	0m0.018s
```

on my old system with the cli from here https://github.com/aebruno/textsecure

it is roughly 10 times faster and the message arrives almost in realtime, even though it's a much older hardware (banana pi)

```
$ time /opt/textsecure/bin/textsecure -to="+xxxxxxxxxxxxxx"  -message="test"
real	0m0.825s
user	0m0.220s
sys	0m0.030s

```
Is there anything, that I can do, to make it faster with the signal-cli-rest-api?

**Comment by bbernhard** [comment]
I guess part (or even most?) of that is probably related to the JVM startup time. This project is just a small wrapper around [signal-cli](https://github.com/AsamK/signal-cli) - which is a Java application - and does all the heavy lifting. In order to speed up operations, signal-cli added the DBUS mode, where the java application gets started once and then the communication happens via DBUS. This significantly improves the performance. But if you want to use the DBUS mode, you have to use signal-cli directly - that's not supported via the REST API wrapper. 

But with the next signal-cli release there's a new experimental feature which makes it possible to compile signal-cli to a native binary.  (see https://github.com/AsamK/signal-cli/issues/446 for details). I haven't tested it yet on a Raspberry Pi, but it has the potential to improve most operations quite a bit.

**Comment by lawrencegripper** [comment]
I was taking a look at this and wondered if [nailgun](http://www.martiansoftware.com/nailgun/index.html) would work here. From reading it look like it keeps a running instance of the JVM which is then reused by each execution so the startup time is removed. 

https://github.com/facebook/nailgun

Anyone more familiar with Java able to give me some pointers as to whether this would work?

**Comment by lawrencegripper** [comment]
So had a play and think there is another easier way to half the time required for sending. By tweaking the JAVA_TOOL_OPTIONS.

I found a [doc here on speeding up tools startup](https://phauer.com/2017/increase-jvm-development-productivity/) by setting `export JAVA_TOOL_OPTIONS="-Xverify:none -XX:TieredStopAtLevel=1"` and it seems to speed things up.

Before:

```
signal-api@signal-cli-rest-api-56c879cf4c-8njdl:/$ export JAVA_TOOL_OPTIONS=""signal-api@signal-cli-rest-api-56c879cf4c-8njdl:/$ time signal-cli
Picked up JAVA_TOOL_OPTIONS: 
usage: signal-cli [-h] [-v] [--verbose] [--config CONFIG] [-u USERNAME]
                  [-o {plain-text,json}] [--dbus | --dbus-system]

real	0m4.535s
user	0m2.167s
sys	0m0.111s
```

After:

```
signal-api@signal-cli-rest-api-56c879cf4c-8njdl:/$ export JAVA_TOOL_OPTIONS="-Xverify:none -XX:TieredStopAtLevel=1"
signal-api@signal-cli-rest-api-56c879cf4c-8njdl:/$ time signal-cliPicked up JAVA_TOOL_OPTIONS: -Xverify:none -XX:TieredStopAtLevel=1
usage: signal-cli [-h] [-v] [--verbose] [--config CONFIG] [-u USERNAME]
                  [-o {plain-text,json}] [--dbus | --dbus-system]

real	0m2.157s
user	0m1.009s
sys	0m0.090s
signal-api@signal-cli-rest-api-56c879cf4c-8njdl:/$ time signal-cli
Picked up JAVA_TOOL_OPTIONS: -Xverify:none -XX:TieredStopAtLevel=1
usage: signal-cli [-h] [-v] [--verbose] [--config CONFIG] [-u USERNAME]
                  [-o {plain-text,json}] [--dbus | --dbus-system]
                  
signal-cli: error: too few arguments

real	0m1.951s
user	0m0.959s
sys	0m0.055s
```

**Comment by bbernhard** [comment]
I also stumbled across nailgun and also mentioned it in this signal-cli issue [here](https://github.com/AsamK/signal-cli/issues/446), but graalvm seemed to be the better solution for the job. But I've to admit that I am not a Java dev, so I do not know much about Java at all. If someone wants to give nailgun a try, I would be happy to assist with the REST API integration!

Regarding the `JAVA_TOOL_OPTIONS`: I think that disables quite a few sanity/security checks. The author also briefly mentions that in the article: 

> During development, we usually restart our application multiple times. This takes time and delays our feedback cycles. Fortunately, there are the following VM arguments boosting our application startup speed:

>    -noverify or -Xverify:none: Disables the bytecode verification. So the classloader won’t check the bytecode for dangerous or disallowed behavior.

>    -XX:TieredStopAtLevel=1: Limits the optimizations of the HotSpot compiler and its runtime overhead.

> Needless to say, that we should never use those VM arguments in production as they will reduce our application’s security and long-term performance.

**Comment by lawrencegripper** [comment]
Yup agree `noverify` turns off some safeguards. I believe the tiered compilation changes don't affect any checks and just reduce the optimisation done at first run but I didn't test these independently - also not super up to speed on Java dev so in a similar boat.

**Comment by bbernhard** [comment]
Should be fixed now. Please use either the `json-rpc` mode (recommended) or the `native` mode.
