### ISSUE TITLE
Invalid captcha given

### ISSUE THREAD

**Issue by CheeseySandal** [bbernhard/signal-cli-rest-api#98]
I would really appreciate any help to show where I am going wrong.  I've installed as a docker container (on a remote RP3) and can make a successful call telling me I need to provide a captcha.

I open the webpage, solve the captcha and see the token within the dev console.

I then try

`curl -X POST -H "Content-Type:application/json" -d '{"captcha":"{as87FAdfahjdfadf...................}"}' 'http://192.168.0.80:8008/v1/register/+447123456789' `

but always get `Invalid captcha given` as a response.

Have tried SSHing into the RP3 and calling via 127.0.0.1, with the same results.

Any ideas?

Thanks.

**Comment by bbernhard** [comment]
You have a pair of `{` too much. 

It should be:

```curl -X POST -H "Content-Type:application/json" -d '{"captcha":"as87FAdfahjdfadf..................."}' 'http://192.168.0.80:8008/v1/register/+447123456789
```

**Comment by CheeseySandal** [comment]
Thanks, the homeassistant README has 

`curl -X POST -H "Content-Type: application/json" -d '{"captcha":"{captcha value}"}' 'http://127.0.0.1:8080/v1/register/<number>`

which confused me.

I've had no errors, just waiting for the text message now .......

**Comment by yousaf465** [comment]
@bbernhard I entered this command as this 
```
curl -X POST -H "Content-Type:application/json" -d '{"captcha":"as87FAdfahjdfadf...................","use_voice": false}' 'http://127.0.0.1:8081/v1/register/+xxxxxxxxxxxxxxxxx
```
got no error but instead got this 
```
quote>
```
still waiting for the SMS
