### ISSUE TITLE
native image mode not working on arm64

### ISSUE THREAD

**Issue by andreasbrett** [bbernhard/signal-cli-rest-api#99]
I'm running on latest docker image v0.36 and tried using the native image mode (have activated USE_NATIVE=1) but get an error:

`{
    "error": "WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup\nERROR App - Missing required native library dependency: libsignal-client\n"
}`

I saw this issue on v0.35 over here https://github.com/bbernhard/signal-cli-rest-api/issues/96#issuecomment-785647593 and also that v0.36 had bug fixes for arm64. There might still be bugs. Let me know if I can help debugging this (as I read that you don't arm64 hardware to test against).

**Comment by bbernhard** [comment]
That's only happening with the native image, right?

I've just had a quick look and I can reproduce the issue on my x86-64 machine by emulating arm64. But I have to admit, that I do not have much experience with GraalVM (GraalVM is used to compile the Java application to a native binary), so I don't know yet how GraalVM compiles the application and how the linking is done. 

My impression after reading the GraalVM documentation was, that per default all the libraries are dynamically linked. But even after placing the arm64 shared objects in the library search path, the native binary doesn't seem to be loading them.

Not sure yet what I am doing wrong here. I'll definitely have a look at it again, but it will probably take a bit until I figure it out.

**Comment by andreasbrett** [comment]
> Is this because GraalVM only supports native images on AMD64/Java 11?
> 
> https://www.graalvm.org/reference-manual/native-image/StaticImages/
> 
> > Right now, this only works on Linux AMD64 on Java 11.

I think this is an outdated documentation. As in the release of 19.3.0 from November 2019 they mention

`We provide a preview of GraalVM Community Edition on JDK 11 for ARM64 architecture. It includes the support for all JVM languages. The support for the other languages should follow soon after. This distribution includes GraalVM Native Image off the shelf to build instantly starting applications which consume less memory in ARM64 environments.`

https://www.graalvm.org/docs/release-notes/19_3/#graalvm-jdk-11-on-arm64

**Comment by bbernhard** [comment]
@andreasbrett @Chepainais the native mode should now also work on arm64 - the newly released Version 0.39 contains the fix. credit goes to @webzit who found & fixed the issue.

**Comment by andreasbrett** [comment]
> @andreasbrett @Chepainais the native mode should now also work on arm64 - the newly released Version 0.39 contains the fix. credit goes to @webzit who found & fixed the issue.

Works like a charm right from the start. Thanks to you and @webzit for fixing this. Messages come in after 3-4seconds instead of 20-25 seconds now.

**Comment by Chepainais** [comment]
Thank you guys! Soo much better now! Instead of 20-30 sec delay from message sent till received response from server - it`s now ~ 6-7 sec.
RPi 4B 8GB

**Comment by webzit** [comment]
For me, it even takes less than 2 seconds for the message to arrive on my smartphone.
Ubuntu 21.04 @ Raspberry Pi 4B 4GB
